# Build the ACE whitepaper in the docs container, via the Qualcomm registry.
#
# SPDX-License-Identifier: CC-BY-SA-4.0

DOCS      := ace-whitepaper.adoc
VERSION   ?= v0.2.0
PDF_THEME := src/wp.yml
REQUIRES  := --require=asciidoctor-lists \
             --require=asciidoctor-bibtex

DOCKER_IMG := docker-registry.qualcomm.com/proxy-cache-qcom/riscvintl/riscv-docs-base-container-image:latest

include Makefile.common
