# Build the ACE whitepaper in the RISC-V docs container.
#
# SPDX-License-Identifier: CC-BY-SA-4.0

DOCS      := ace-whitepaper.adoc
VERSION   ?= v0.2.0
PDF_THEME := src/wp.yml
REQUIRES  := --require=asciidoctor-lists \
             --require=asciidoctor-bibtex

DOCKER_IMG := ghcr.io/riscv/riscv-docs-base-container-image:latest

include Makefile.common
