= Atomic Cryptography Extension (ACE)

The Atomic Cryptography Extension (ACE) is being developed by the RISC-V High Assurance Cryptography (HAC) Task Group.

ACE is an Instruction Set Architecture (ISA) extension that provides atomic (i.e., full-round) cryptographic operations using *Cryptographic Contexts*.
A Cryptographic Context is an indivisible data structure comprising metadata and a content section that holds secrets such as keys.
The metadata binds the secrets to a specific cryptographic algorithm and defines usage and access policies, thereby preventing the secrets from being used for other algorithms or, optionally, by unauthorized processes, security states, or other entities.

Cryptographic Contexts reside in one of two forms:

. Within protected architectural containers called *Cryptographic Registers*, which conceal their contents once provisioned. A Cryptographic Context is created by writing secrets and their metadata into a Cryptographic Register.
. As *Sealed Cryptographic Contexts* in untrusted memory, where they are stored encrypted using an Authenticated Encryption with Associated Data (AEAD) mode. Sealed Cryptographic Contexts can be reimported into Cryptographic Registers.

ACE can only utilize keys for cryptographic operations when they reside in a Cryptographic Register.
The architecture protects these registers by providing no means to export the key or its metadata as plaintext,
and it ensures keys are used strictly according to the policies in their metadata.
When a Cryptographic Context is stored in memory as a Sealed Cryptographic Context, the binding of the key and its metadata relies on the
cryptographic strength of the AEAD encryption.

Sealed Cryptographic Contexts can be produced by trusted software or hardware and supplied to applications. Software can also create its own Cryptographic Contexts by writing a key and metadata into a Cryptographic Register. The original key can then be erased from system memory to limit exposure, while ACE continues to perform cryptographic operations using the key secured within the register.

The algorithm specified in the metadata can range from a basic cipher like AES-128 or AES-256 to a more complex mode of operation such as SM4-GCM-SIV. A key advantage of ACE is that a small set of algorithm-agnostic instructions can support numerous cryptographic algorithms, as the metadata alone determines the algorithm to be executed. Consequently, the same binary code can support any 128-bit cipher in a given mode—for example, AES-GCM-SIV, SM4-GCM-SIV, Kalyna-GCM-SIV, or Kuznyechik-GCM-SIV—with only the metadata differing; the instruction sequence remains identical.

The current ACE interface supports only symmetric cryptographic primitives. However, the ISA can readily be extended to accommodate asymmetric cryptography.

== License

This work is licensed under a Creative Commons Attribution 4.0 International License (CC-BY-4.0). For details, see the link:LICENSE[LICENSE] file.

== Contributors

The list of contributors to this specification is maintained in the link:src/contributors.adoc[contributors] file.

For guidelines on how to contribute, refer to the link:CONTRIBUTING.md[CONTRIBUTING] file.

== Building the Document

=== Directory Structure

The following directories are used to organize the contents of this repo:

* `dependencies/`: software dependencies needed to build the specification
* `docs-resources/`: resources for all specifications sourced from link:.gitmodules[git submodule]
* `src/`: source files for the specification
* `build/`: default directory where the build artifacts are generated

=== Prerequisites

To build the document, you'll need the following tools installed on your system:

* Make
* asciiDoctor-pdf, asciidoctor-bibtex, asciidoctor-diagram, and asciidoctor-mathematical
* Docker

=== Cloning the Repository

```shell
git clone --recurse-submodules https://github.com/riscv/riscv-hac.git
```

=== Building the Documentation

To start the build process, run:

```shell
cd ./riscv-hac && make build
```

The link:Makefile[] script will check the availability of Docker on your system:

* If Docker is available, the documentation will be built inside a Docker container using the image riscvintl/riscv-docs-base-container-image:latest. This ensures a consistent build environment across different systems.
* If Docker is not available, the documentation will be built directly on your system using the installed tools.

The documentation is generated from the AsciiDoctor source files in your project. The primary source file is specified by the `HEADER_SOURCE` variable in the Makefile.

The build process utilizes several options, including theming and font settings, and generates a PDF document as output.

=== Cleaning up

To clean up the generated files, run:

```shell
make clean
```


== Enabling pre-commit checks locally
The repository has some basic commit checks set up with https://pre-commit.com/[pre-commit] that will be enforced by the GitHub CI.
To ensure these checks are also run in the local repository while making changes the following command can be run:
[source,shell]
----
pip3 install pre-commit && pre-commit install
----

When enabling additional checks https://pre-commit.com/#plugins[by editing .pre-commit-config.yaml], it is recommended to run to newly added check on all files in the repository. This can be done with the following command:
[source,shell]
----
pre-commit run --all-files
----
