[[ACE-Locales]]
=== Locales

Internally, ACE has a table of 128-bit Locale Secrets (LS), the Locale Secrets Table (LST).
Some of these entries are fixed, other values may be configurable only using an implementation-specific authenticated hardware procedure, and the remaining may be programmed by Machine Mode (*Note:* _we need to define the corresponding CSRs_).
The LST is a global table shared across all ACE units with some fields which can be MM-programmed and are architectural (i.e., per hart).
//Currently, the only two values that may be overridden by architectural values, in order to support multiple VMs/Supervisor Domains/Worlds are System_Secret and Boot_Session.

If the Locale Field of a context (CC/SCC) is -1 (all ones), then the CTK is used.
Otherwise, this value is used as an index _i_ in the HST, and a derived key computed from CTK and LST[_i_] is used for import/export in place of the CTK.
The encryption and authentication keys are then derived from the Locale CTK.

In <<ACE-binding-indices>>, we list the mandatory entries and their meaning.
In the column "MM-Configurable" we indicate whether the architecture may allow MM to configure the corresponding Locale Token.

[[ACE-binding-indices]]
.Mandatory Locale Values
[width="100%",cols="19%,52%,^12%,^7%",options="header"]
|===
.>| Name .>| Description .>| MM-Configurable .>| Value
| No locale binding         | | | -1 (15)
| Chip Manufacturer         | Identifies the manufacturer of the SoC. Permanent. | N | 0
| Chip Model                | Identifies specific chip model/family. Permanent. | N | 1
| OEM Secret                | Provisioned by OEM to differentiate their products from the competition.
                              Can be permanent in a device — re-generations can be optionally triggered using impdef HW authenticated mechanisms. | N | 2
| Product                   | Identifies device/system type/model (product). Not necessarily permanent. Reconfigurable like OEM_Secret. | N | 3
| Device                    | Unique device (entire system) secret (not the device ID such as a serial number, but it can be derived from it, for instance by hashing).
                               Shared across all harts in a Soc and shareable across multiple SoCs in a single device. Sharing mechanism impdef, i.e., not architected.
                               Reconfigurable like OEM_Secret. | N | 4
| OS Secret                 | Identifies Operating System (or System Stack). +
                              Not permanent, must be configured during (virtual) boot. | Allowed | 5
| Boot Session              | Regenerated at each (virtual) boot. | Allowed | 6
| Reserved                  | Reserved for future use. | N/A | 7-14
|===

// [[ACE-virtual-reboot,Remark {counter:remark}]]
// *Remark {counter:remark}.* _We need to mention what to do in case there is a reboot of a VM.
NOTE: Machine Mode has the responsibility to "virtualize" the boot session locale secret, i.e., the sixth entry in the LST.

// , since some VMs may reboot while others may not.
// Also, do we want to allow a VM to have a different virtual hardware? Or does it always declare the same configuration as the underlying hardware?_
// In principle, all this can be done by calling into MM. MM would need to keep track of the locale binding values and ensure that they are updated correctly when necessary.

*Example*: _If a key's metadata specifies a Locale field value of "2", the key for import/export operations is derived from the CTK and the "OEM Secret".
Consequently, while `ace.export` remains functional on the same device to support context switching, an `ace.import` of the resulting SCC on a device from a different OEM will trigger an authentication failure (provided that the OEM Secrets are, in fact, different)._

[[ACE-careful-with-internal-keys,Remark {counter:remark}]]
*Remark {counter:remark}.* _In a CC, a key may be referred to using an index into an internal, system defined key table, the System Key Table (STK). If some of these keys are device specific, they will not work as intended on a second device.
If the Locale of this CC is not restricted, the internal key index may be interpreted as an internal key on a different device, with unpredictable consequences.
Hence the implementation of the STK must also provide the proper Locale metadata to the ACE implementation to configure a CC._
