[[ACE-unpriv]]
== Book 1: Unprivileged Architecture, Instructions and Architectural States

// Good judgment comes from experience.
// Experience comes from bad judgment.
// —MULLAH NASRUDIN, 1200s AD

=== Introduction

ACE relies on certain fundamental concepts, which are introduced here.
While this leads to some repetitions, it also brings better clarity to the presentation.

[[ACE-concepts]]
==== Fundamental Concepts and Definitions

Cryptographic Context:::
(((Cryptographic Context)))
The *Cryptographic Context* (CC) is the foundation of ACE. A CC is an indivisible structure consisting of a *Metadata Header* and *Content*; all cryptographic operations performed by ACE execute within the constraints defined by a CC.
The Metadata Header has a fixed format and specifies the cryptographic algorithm and various optional policies associated with the CC.
(((Cryptographic Context, Metadata Header)))
The Content has an algorithm-specific format and holds sensitive material such as keys and algorithm state.
(((Cryptographic Context, Content)))
The Metadata requires integrity; the Content requires both integrity and confidentiality.
These requirements are architecturally enforced by ACE and by the cryptographic algorithms it implements.

Context Register:::
(((Context Register)))
To create CCs, ACE uses *Context Registers* (CRs), per-hart architectural containers that safeguard their contents.
A CR is *provisioned* by writing Metadata and Content into it; this operation binds the latter to form a CC.
There is no store-like instruction to extract the Content of the CR in a manner that compromises its confidentiality.
A CC may be used for cryptographic operations only while resident in a CR.
Only the ACE unit may access or modify a CC residing in a CR, in accordance with architectural rules and the algorithm bound to the CC.

Sealed Cryptographic Context:::
(((Cryptographic Context, sealed)))
To support context switching while protecting CCs outside architectural state, a CC may be *exported* from a CR as a *Sealed Cryptographic Context* (SCC)—an encrypted and authenticated representation of a CC that can later be *imported* into a CR. Export and import use a _Context Sealing Key_ (CSK), which may be programmable by M-mode. An SCC sealed under one CSK cannot be imported under a different CSK, providing cryptographic domain separation across spatial and temporal domains.

Object-Orientation:::
(((Cryptographic Context, object-oriented)))
CCs act as *objects* exposing a uniform interface across algorithms.
A CC encapsulates algorithm-specific behavior, enabling interchangeable use of different primitives (e.g., AES-128, AES-256, SM4) in identical modes (e.g., ECB, GCM-SIV, XTS) without requiring changes to compiled code.
Side-channel attack (SCA) resistant variants are supported transparently.

Usage Control Policy:::
(((Cryptographic Context, usage control)))
(((Cryptographic Context, management operations)))
(((Cryptographic Context, usage operations)))
ACE distinguishes between CC/CR *management* and *usage* operations.
(((Cryptographic Context, export)))
Management operations include *configuration* (e.g., CR provisioning, SCC import, and cloning) and *export* of a CR as an SCC. Usage operations include cryptographic operations and state changes.
To prevent denial-of-service scenarios, management operations, in particular configuration operations, are far less restricted than usage operations. _Usage Control_ policies restrict only certain CC/CR usage operations.

Localities:::
(((Cryptographic Context, Locality)))
ACE can bind CCs to a *Localities*, i.e., restrict usage to specific devices or device classes, hardware configurations, physical or virtual boot cycles, and process domains at various privilege modes. This binding is achieved by using the Localities as _tweaks_ in the encryption and decryption of SCCs.

// ////////////////////////////////////////////////////////////////////

[[ACE-architectural-model]]
==== Architectural Model

ACE is architected as an _attached_ unit, meaning that ACE instructions act as messages across a tightly coupled coprocessor interface.
The ACE unit receives the operations from the hart, executes them independently of the issuing hart, and returns results.

Beside implementations of ACE within a CPU core, this model also allows a single hardware instance of the ACE unit to be shared by multiple cores, with separate architectural states for each client hart.  The specification mandates only behavior, not implementation.

The ACE unit may lock certain architectural states—e.g., Vector Registers, CRs, and CSRs.
The hart stalls when attempting to read them until the ACE operation using those resources completes.

This design allows a certain level of concurrency.
Long-running ACE operations may proceed even if the hart is preempted.
In this case, when the context‑switch handler accesses an output of the operation register, different behaviors are allowed:
the hart may wait for the operation to finish;
the implementation may adopt a precise exception model, whereby the ACE unit is halted and sets a value in a CSR called `acestart` to allow later resumption;
or the system may impose a timeout before halting.
The architecture permits all these approaches: It only specifies the allowed interruption points for its instructions and algorithms.

For the purpose of describing the behavior of the architecture, the CRs can be considered as strings of bits, such as other architectural registers.
In particular,

// ////////////////////////////////////////////////////////////////////

[[ACE-extensions-overview-unpriv]]
=== Extensions Overview

[%header,cols="15%,47%,18%,10%,10%"]
|===
| Extension       | Features                                                                                                            | Defined in:                                    | Minimum version | Lifecycle state
| `Zlv`           | ACE with support for vector registers.^1^                                                                           | <<ACE-instructions-detailed>>                  | v0.0.0          | --
| `Zlio`          | ACE with support for `ace.input` and `ace.output`.^2^                                                               | <<ACE-usage-input-output>>                     | v0.0.0          | --
| `Zlaes128p`     | AES-128 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes192p`     | AES-192 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes256p`     | AES-256 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlsm4p`        | ShangMi 4 encryption/decryption.^3^                                                                                 | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlctrm`        | CTR and CTR with set initial counter.^4^                                                                            | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxctrm`       | XCTR and XCTR with set initial counter.^4^                                                                          | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxexm`        | XEX construction.^5^                                                                                                | <<ACE-XEX-XTS-modes>>                          | v0.0.0          | --
| `Zlgcmm`        | GCM and GCM with set IV.^4^                                                                                         | <<ACE-GCM-mode>>                               | v0.0.0          | --
| `Zlgcmsivm`     | GCM-SIV.^4^                                                                                                         | <<ACE-GCM-SIV-mode>>                           | v0.0.0          | --
| `Zlocbm`        | OCB3 and OCB3 with set IV.^5^                                                                                       | <<ACE-OCB-mode>>                               | v0.0.0          | --
| `Zlcmacm`       | CMAC.^4^                                                                                                            | <<ACE-CMAC-mode>>                              | v0.0.0          | --
| `Zlesha2h`      | SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, and SHA-512/256.                                                   | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlesha3h`      | SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128, and SHAKE256.                                                     | <<ACE-SHA-3>>                                  | v0.0.0          | --
| `Zlsm3h`        | ShangMi 3 (SM3) hash function.                                                                                      | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlhmacm`       | HMAC function with hidden key (with SHA2 when `Zlesha2h` is supported, and with SHA3 when `Zlesha3h` is supported). | TBD                                            | v0.0.0          | --
| `Zlkmacm`       | KMAC function with hidden key. Depends on `Zlesha3h`, since KMAC is only defined with SHA3.                         | TBD                                            | v0.0.0          | --
| `Zlascon`       | Ascon-AEAD128 (base, with set Nonce, or with Nonce Masking), Ascon-Hash256, Ascon-XOF128 and Ascon-CXOF128.         | <<ACE-Ascon-AEAD128>> to <<ACE-Ascon-CXOF128>> | v0.0.0          | --
4+| _Point arithmetic and signature generation and verification algorithms for curves in various standards:_                      | {empty}
| `Zlsecp256r1c`  | -- NIST curve secp256r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp384r1c`  | -- NIST curve secp384r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp521r1c`  | -- NIST curve secp521r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled25519c`    | -- Edwards curve ed25519.                                                                                           | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled448c`      | -- Edwards curve ed448.                                                                                             | <<ACE-ECC>>                                    | v0.0.0          | --
| `ZlbpP256r1c`   | -- Brainpool curve brainpoolP256r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlbpP384r1c`   | -- Brainpool curve brainpoolP384r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlbpP512r1c`   | -- Brainpool curve brainpoolP512r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlSM2c`        | -- Chinese 256-bit SM2 curve.                                                                                       | TBD                                            | v0.0.0          | --
| `Zlkn`        2+| NIST Symmetric Suite. Depends on `Zlaes128`, `Zlaes256`, `Zlesha2`, `Zlgcmm`, `Zlxexm`, and `Zlgcmsivm`.            | v0.0.0                                         | --
5+| ^1^ Requires V (or a suitable subset thereof). Must support the following CSRs: `acestart` (this is a dependency for Zicsr); must support the following instructions: `ace.prov`, all four forms of `ace.exec`, all Forms of `ace.setst`,
`ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size` (and thus `ace.avail`), `ace.getmd`/`ace.getmdh`, and `ace.restrictl`/`ace.restricth`; must support `Zlkn`.
5+| ^2^ Must support the following CSRs: `acestart` (this is a dependency for Zicsr), `aceiobuflen` and `aceiobuftop`; must support the following instructions: `ace.prov`, Form D of `ace.exec`, Forms A and B of `ace.setst`, `ace.input` and `ace.output`, `ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size` (and thus `ace.avail`), `ace.getmd`/`ace.getmdh`, and `ace.restrictl`/`ace.restricth`; must support `Zlkn`.
5+| ^3^ Beside defining the basic encryption and decryption operations, these extensions also select which ciphers can be used with the various modes of operations that follow.
5+| ^4^ The mode is applicable to all versions of AES and to SM4.
5+| ^5^ The mode is applicable to all versions of AES.
|===

At least one of `Zlv` or `Zlio` must be implemented.

// ////////////////////////////////////////////////////////////////////

=== Programmer-Visible Architectural State

[[ACE-cryptographic-registers]]
==== Context Registers

{empty}
(((Cryptographic Context)))
ACE defines 32 Context Registers (CRs), numbered 0 to 31 and denoted `K0`–`K31`.

CRs are architectural state, i.e., per-hart, like the GPRs or the vector registers.
They are a common set for a hart, that is, they are not separated per Mode.

Unlike a conventional register, a CR can be _unconfigured_, meaning it does not contain a CC.

A CR is addressed directly, as a 5-bit immediate, or indirectly, via a GPR value.
An additional instruction-encoding bit is used to select how the CR is addressed.
Accessing a CR with an indirect index outside [0..31] raises an illegal instruction exception.

An implementation must wait before performing any operation on a CR that is still being written to asynchronously
by the ACE unit.

[NOTE]
====
Indirect CR addressing has an important microarchitectural implication: Supporting CR renaming is still possible but it would significantly increase microarchitectural complexity.
However, CRs are redefined far less frequently than GPRs or FP registers (excluding implicit internal state changes), so omitting CR renaming is not expected to significantly affect performance.
====

(((Context Register File)))
CRs reside in a dedicated, per-hart _CR file_ (CRF) accessible only to the ACE implementation.
This memory shall guarantee confidentiality and integrity of its contents, including the inability for an attacker to roll-back the latter to a previous state.
We do not require that accesses to this memory are hardened against physical side-channel attacks at the hardware level.
However, the implementation of side-channel protected algorithms in the ACE unit shall provide resistance to such attacks as well.

The amount of CRF capacity consumed by each CR depends on the algorithm encoded in the metadata, and it may differ from one CR to another.

Insufficient residual CRF capacity may prevent execution of a configuration instruction (`ace.prov`, `ace.import`, `ace.clone`):
Capacity is freed by unconfiguring other CRs.

The CRF capacity is implementation-defined. Implementations shall provide sufficient
capacity for all supported operations. At a minimum, the CRF must hold the
largest possible single CR, or the largest CR pair used in cloning operations.
An optional, implementation-specific mechanism for estimating required capacity
is described in <<ACE-instruction-size>>.

Any corruption of the CRF associated with a hart shall cause an unrecoverable error condition.
The entire architectural state of the ACE unit associated with the hart is reset, and exception `ace_guru_meditation` is raised (cf. <<ACE-exceptions>>).

We list the most important operations on CRs, so we can refer to them before they are fully defined.

* Provisioning (<<ACE-management-operations>>) loads metadata and plaintext Content into a CR, binding them together.
* Exporting (<<ACE-management-operations>>) exports a CR to memory as an SCC.
* Importing (<<ACE-management-operations>>) imports a SCC into a CR.
* `ace.clear` (<<ACE-instruction-clear>>) unconfigures and clears a CR.
* `ace.exec` (<<ACE-instruction-exec>>) performs cryptographic operations as specified by the algorithm configured in a CR and according to the state of the CR.
* `ace.setst` (<<ACE-instruction-setst>>) transitions between states of a cryptographic algorithm or of a CR.
* `ace.clone` (<<ACE-instruction-clone>>) creates a copy of a CR into a second CR.

// ////////////////////////////////////////////////////////////////////

==== Inputs and Outputs: RVV-mini and ACEIOBUF

ACE inputs and outputs may use vector registers or an architectural input/output buffer (ACEIOBUF)
that can be loaded from and stored to external memory. Both mechanisms may be supported simultaneously.

When vector registers are used, the full V extension is not required. ACE depends only on a minimal subset, termed _RVV-mini_.
(((RVV-mini)))
RVV-mini must be fully opcode-compatible with RVV: code written for RVV-mini must execute with identical behavior under RVV.
The current set of features is:

* Vector registers wide enough to support the inputs and outputs of the implemented algorithms, that is, currently, 128 bits.
* Configuration-setting instructions (`vsetvli`/`vsetivli`/`vsetvl`):
 ** Since all ACE operations ignore masks while accessing vector registers, RVV-mini only needs tail and mask agnostic configurations;
 ** Since ACE operations do not depend on a concept of element (from a logical point of view, they are not performed in the vector unit),
    they view the vector/vector group as bit strings of length `VL` * `SEW` with `VL` = min(`AVL`,`VLMAX`),
    in groups of `LMUL` processing in each operation `VL` * `SEW` bits in a vector group.
 ** Support for `LMUL` integer values of 1, 2, 4, and 8;
 ** Unsupported configurations shall raise an illegal instruction exception.
* Unit-strided vector loads and stores; and
* Vector bitwise logical operations: `vxor`, `vand`, and `vor`.

// VLEN = vector register len in BITS
// VLEN is a constant parameter chosen by the implementor and must be a power of two
//
// VL = how many elements of the vector (starting from the element zero) we are going to operate on
// 0 ≤ VL ≤ vlmax(SEW, LMUL)
// vlmax(SEW, LMUL) = (VLEN / SEW) × LMUL
//
// in vsetvl and variants: AVL = application vector length which
// represents the vector length the program wants to use
// for the purposes of ACE operations, AVL ≤ vlmax(SEW, LMUL) (do not allow AVL < 2 * vlmax(SEW, LMUL) ?)
// Maybe even keep it equal AVL = vlmax(SEW, LMUL)

ACE instructions do not use vector masking and do not define masked versions of `ace.exec`.
Therefore, RVV-mini does not need support for masked operations.
We are not using bit 25 of the instruction encodings, though, for potential future adoption of masked operations, should a compelling use case arise.

Floating-point, fixed-point, and general arithmetic vector operations are not required.
Complex operations for certain cryptographic algorithms may be performed in GPRs, with data inserted into vector registers and result extracted from them via `vins`/`vext`.

[WARNING]
[.red]#RVV-mini need not be finalized before ACE ratification begins; it
may be defined later, and the ACE specification amended accordingly.
This allows additional requirements to be collected, for example, whether to mandate
`vclmul.v[vx]` and `vclmulh.v[vx]` from `Zvbc`.#

The optional per-hart input/output buffer (ACEIOBUF) may be used in place of vector registers.
The ACEIOBUF is not part of the CRF.
Instructions `ace.input` and `ace.output` are used to write inputs to the ACEIOBUF and read outputs from it.
When the ACEIOBUF is used in place of vector registers, instructions `ace.exec` and `ace.setst` that use vector registers are replaced by instruction sequences  as described in <<ACE-usage-input-output>>.

To determine the lengths of the inputs and outputs of its operations when the vector registers are used, ACE uses `VL*SEW`.
The actual choice of `VL` and `SEW` is not significant. For instance, both `VL`=2, `SEW`=64 and `VL`=4, `SEW`=32 define a 128-bit input.
The CPU instruction-decoding side of ACE uses `VL` and `SEW` to determine the amount of data to send to the ACE unit proper.
The ACE unit itself only needs the product `VL*SEW` (or `aceiobuftop`) for its functionality.

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata]]
==== Metadata Header Format

The ACE architecture recognizes two types of metadata that may be contained in a CC or associated with it.

. A 128-bit _Metadata Header_ that determines the algorithm, the type of key, and various usage policies associated with the key.
 This information is always present in a CC.
 The fields are arranged so that the first 64 bits suffice to determine the length of a PI or SCC.

. An optional 128-bit _Implementation Metadata_ block that contains copies of the values of three architectural registers which are the ACE analogues
of `mvendorid`, `marchid`, and `mimpid` CSRs for the hart implementation (see <<ACE-CSR-impl-ids>>).
 The latter may be only present in an SCC and only if the SCC has been extended by the implementation with an implementation-specific content block.
 This block is used by an implementation to determine whether it can be use the aforementioned implementation-specific content block, even if generated by another implementation.

In this section we only deal with the 128-bit Metadata Header.
Its fields are summarized in <<ACE-metadata-header>>.
// Of its 128 bits, 106 are currently defined and 22 are reserved for future use.
// Most algorithms use only 82 bits, as _StateExtension_ and _AlgorithmUse_ are currently used only by the Elliptic Curve Algorithms (<<ACE-ECC>>).
All Reserved bits, as well as bits unused by a given algorithm, must be zero.

[[ACE-metadata-header]]
.Format of the 128-bit Metadata Header
[width="100%",cols="^9%,^6%,14%,71%",options="header"]
|===
|    Field  | Size | Name              | Description
|    [11:0] |  12  | _Algorithm_       | Cryptographic algorithm (primitive, mode, or protocol). See <<ACE-Algorithm-field>>.
|   [13:12] |   2  | _AlgorithmPolicy_ | Allowed algorithm variants(s) _or_ extension of the _Algorithm_ field. See <<ACE-Algorithm-field>>.
|   [15:14] |   2  | Reserved          | Reserved for future expansion of _AlgorithmPolicy_ field.
|   [18:16] |   3  | _SCProtection_    | Side-channel protection level. See <<ACE-SCProtection-field>>.
|   [20:19] |   2  | _KeyType_         | 0: The key is given by an explicit value. 1: The key is given by a system-specific System Key Identifier, i.e., a 64-bit value to identify implementation-specific keys, or randomly generated by the implementation.  Values 2 and 3 are currently reserved. See <<ACE-system-keys>>.
|   [25:21] |   5  | _State_           | Current state of the CR/algorithm, encoded as an integer. For instance, whether the CR/algorithm is _Off_ (unconfigured), encrypting or decrypting data, absorbing data in a hash/mac/tag, computing elliptic curve point multiples, generating or verifying signatures, or in an error state. It can be modified by the user to advance through various phases of an algorithm. See <<ACE-State-field>>.
|   [29:26] |   4  | _StateExtension_  | May be used by the algorithm to extend the _State_ field with additional information. See <<ACE-State-field>>.
|   [31:30] |   2  | _ConfigStatus_   | Used to indicate whether the CR is fully configured and ready to operate, or is being provisioned, imported, or exported. See <<ACE-ConfigStatus>>.
|   [47:32] |  16  | _ImpDataLen_      | If non-zero, indicates that an additional, variable-length, implementation-dependent data section appended to Content. The length of this additional data section is _ImpDataLen_ * 128 bits (up to 1024 KiB).
|   [62:48] |  15  | Reserved          | Reserved for future use.
|   [63:63] |   1  | _SystemFormat_    | Value is 0 if an input is in the ACE architected format 1 if it is in a system-defined Format.
|   [68:64] |   5  | _UsagePolicy_     | Usage (Control) Policy. Bits 0, 1, 2, 4 and 4 of the field, when set, disallow CC usage in U-mode, (V)S-mode, H-mode, M-Mode, and Debug mode, respectively. Any bit of this field is ignored if the corresponding mode is not supported or not enabled.
|   [77:69] |   9  | _Locality_        | Zero, or a value determining one or more Locality Secrets, used in the export/import encryption and decryption algorithm to bind the CR to specific environments. See <<ACE-Localities>>.
|   [79:78] |   2  | Reserved          | Reserved for expansion of the _Locality_ field.
|   [95:80] |  16  | _AlgorithmUse_    | Reserved for algorithms and implementations to store additional state information.
|  [121:96] |  26  | _ExpirationDate_  | If non-zero, the expiration date of this CC. See <<ACE-Metadata-expiration-date>>. Expressed in minutes since 00:00, January 1, 2027 (about 127 years).
| [127:122] |   6  | Reserved          | Reserved for future use.
|===

In the following subsections we describe the fields of the Metadata Header.

// ////////////////////////////////////////////////////////////////////

[[ACE-system-format-field]]
===== _SystemFormat_ Bit

The use of a system-defined format is signalled by the _SystemFormat_ bit of the (low 64 bits of the) Metadata Header, which in this case may be just 64 bits.
The format of the other 63 bits is also entirely implementation-dependent.

// ////////////////////////////////////////////////////////////////////

[[ACE-Algorithm-field]]
===== _Algorithm_ and _AlgorithmPolicy_ Fields

Algorithms are encoded in a 12-bit field. Values 0–3071 and 4095 are architecture-defined.
The list of encodings is maintained by RVI (see <<ACE-algorithms>>).
The remaining values are available for custom algorithms.

For encryption/decryption primitives and modes, the _AlgorithmPolicy_ field indicates whether the CC may be used for encryption (lower bit set), decryption (upper bit set), or both. At least one of the bits must be set.

For asymmetric primitives supporting signatures, the lower bit permits signature generation and the upper bit permits verification.
Such an asymmetric primitive can be configured to support primitives such as key agreement or key encapsulation but _not_ signatures, and in this case both bits are zero.

For other primitives, the _AlgorithmPolicy_ field may encode additional algorithm identifiers to expand the effective encoding space of the _Algorithm_ field.

// ////////////////////////////////////////////////////////////////////

[[ACE-SCProtection-field]]
===== _SCProtection_ Field

The architecture defines the following side-channel protection levels.

[[ACE-SC-protection-levels]]
.Encoding of Side-Channel Protection levels
[%autowidth,float="center",align="center",cols="^,<"options="header"]
|===
| Value   | Description
|   0     | Data-independent execution latency (DIEL) for cryptographic operations.
|   1     | First-order threshold implementation.
|   2     | DIEL; first-order threshold, fault-tolerant implementation.
|  {ge} 3 | Reserved/Currently not defined.
|===

Implementations offering additional levels of protection may set _SCProtection_ to a value greater than 2:

* Values 3-5 are reserved for future use by the architecture.
* Values 6-7 are reserved for implementation-custom protection levels.
  In this case, the generating environment must use localities that prevent the use of the SCC on different architectures.

// ////////////////////////////////////////////////////////////////////

[[ACE-State-field]]
===== _State_ and _StateExtension_ Fields

The _State_ field is used to track the currently state of an algorithm, including certain types of errors.

The architected values of _State_ common to all algorithms are defined in the following three tables.

[[ACE-state-off]]
.Global CC State Numbers: Off State
[float="center",align="center",width="100%",cols="^7%,<27,<15%,<51%",options="header"]
|===
| Value | Mnemonic                  | State Name     | Description
|   0   | `ace_state_off`           | _Off_          | The CR is not configured.
|===

[[ACE-states-valid]]
.Global CC State Numbers: Valid States
[float="center",align="center",width="100%",cols="^7%,<27,<15%,<51%",options="header"]
|===
| Value | Mnemonic                  | State Name     | Description
|   1   | `ace_state_initial`       | _Initial_      | The state of a just provisioned CC; ready for operation.
| 2-21  3+| Defined by the specification of the Algorithm encoded in the _Algorithm_ field.
|  22   | `ace_state_success`       | _Success_      | Algorithm completed successfully. No further cryptographic operations may be performed until the CC is reset or, if allowed, transitioned to _Initial_.
|  23   | `ace_state_failure`       | _Failure_      | Failure in an algorithm, usually an authentication failure in AE(AD) algorithms or a signature verification failure. No further cryptographic operations may be performed until the CC is reset or, if allowed, transitioned to _Initial_.
|===

[[ACE-states-error]]
.Global CC State Numbers: Error States
[float="center",align="center",width="100%",cols="^7%,<27,<15%,<51%"]
|===
|  24    | `ace_state_not_impl`        | _Not_Impl_        | Not implemented algorithm. It is set by the hardware upon an attempt to provision or import a CR that is not supported by the implementation.
|  25    | `ace_state_invalid`         | _Invalid_         | Invalid/invalidated state, for instance because of the use of an invalid value (argument, state, or metadata).
|  26    | `ace_state_out_of_mem`      | _Out_of_Memory_   | Insufficient CRF memory for configuration instruction. This may be set by privileged code in case they do not handle the CR allocation.
|  27    | `ace_state_import_auth`     | _Auth_Failed_     | Authentication failure with `ace.import`.
|  28    | `ace_state_priv_viol`       | _Priv_Viol_       | Violation of Usage Control policies.
|  29    | `ace_state_expired`         | _Expired_         | The CR has expired.  This is set by the hardware even if the condition also raises an exception.
| 30, 31 | (Reserved)                  |                   | Reserved for future use.
|===

State 0 is the _Off_ state.  It denotes that the CR is unconfigured.

All states in the range 1-23 are termed _valid_. This includes both _Success_ and _Failure_ states, which must be used for
normal termination of an algorithm in the cases of its successful completion or failure.

The immediate in the `ace.setst` instruction (<<ACE-instruction-setst>>) is a 7-bit value, whereas the _State_ field is only 5 bits long.
This allows to encode additional operations related to state changes (such as stages of import, export, or provisioning code) as `ace.setst` with the two high bits of the immediate taking non-zero values.

(((ACE, algorithm, error states)))
States 24-31 are termed _Error States_, and are used to report certain specific ACE errors.
(((ACE, algorithm, invalid state)))
(((Context Register, invalidation)))
In particular, if the State is `ace_state_invalid`, we say that the CR is _invalidated_.

The Error States are currently listed in decreasing severity order, with Error State 24 being the most severe and Error State 29 the least severe.
Error States 30 and 31, if defined, will not necessarily have a lower priority than Error State 29, and may be therefore not in order.

Error conditions that lead to exceptions are treated in <<ACE-exceptions>>.

If an algorithm defines 23 or fewer valid states (including _Initial_, _Success_, and _Failure_), the current state is stored in the _State_ field.
For algorithms with more than 23 valid states, additional state information resides in the Content section.

The following rules are generic and apply to all algorithms:

. The Metadata Headers's _State_ field must reflect the current state whenever the CC is in _Initial_, _Success_, _Failure_, or any Error State.
This ensures that these states can be unambiguously determined from the _State_ field alone, without inspecting the Content.

. In States _Success_ and _Failed_, only the following ACE instructions are permitted: `ace.prov`, `ace.import`, `ace.export`, `ace.clear`, `ace.size`, `ace.setst`, and `ace.getst`.

. In States _Success_ and _Failed_, `ace.setst` can only be used permitted to transition to _Initial_ or _Off_.

. Unless an algorithm's specification explicitly states otherwise, a transition from any valid state to _Initial_ using instruction `ace.setst` is always permitted.

. Upon transitioning to an Error State, the Content of a CR is invalidated and emptied.
Internal resources associated with the Content may also be released. In that case, any additional variable-length data is released as well and the _ImpDataLen_ field is set to 0.
The CR then retains only the Metadata Header.

. Exporting a CR in an Error State exports only the Metadata Header and the authentication tag.
  Requesting the SCC's size (`ace.size` <<ACE-instruction-size>>) will return 32 (bytes).
  The resulting SCC can be reimported, allowing software to take appropriate actions even after a context switch.

. If a CR is in any Error State, it can still be reconfigured, cloned, or cleared. `ace.setst` can only be used to change the Error State (for instance by an exception handler) or transition the CR to _Off_.

. The Metadata Header of a CR in an Error State can be read (using `ace.getmd`: <<ACE-instruction-getmd>>).

. Attempts to _use_ a CR in any Error State will not perform any operation, and in particular they leave the _State_ field unchanged.

. Any _usage_ instruction that would violate the Usage Control policies will not perform its operation, and will set _State_ to `ace_state_priv_viol` instead.

We note that the State after `ace.setst` is issued may differ from the State specified by the instruction.
A common example is MAC verification: after `ace.setst` is issued with an `ace_state_hash_verify` immediate as the next state and the value to be verified as the additional parameter, the algorithm transitions to either _Success_ or _Failure_. This is done to prevent the manipulation of a CR's state and to reduce code size.
An `ace.exec` instruction may also trigger a state change.

In <<ACE-states-graph>> we display the default possible state transitions.

// //
[[ACE-states-graph]]
.Default State Transitions
[float="center",align="center"]
image::../../src/statestikz-3.svg[]
// //

////
[[ACE-states-graph]]
.Default State Transitions
[tikz,,svg,float="center",align="center",preamble=true,command=lualatex]
....
\usetikzlibrary{calc,trees,matrix,positioning,chains,fit,intersections}
\usetikzlibrary{arrows,shapes.arrows,shapes.geometric,shapes.multipart,shapes.symbols}
\tikzset{
   state/.style={ rectangle, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
   partial state/.style={trapezium, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
   error state/.style={ rectangle, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
   off state/.style={ circle, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
   branch/.style={ fill, shape=circle, minimum size=3pt, inner sep=0pt},
   cross line/.style={preaction={draw=white, -, shorten >=3pt, shorten <=3pt, line width=2pt}},
   >=latex
}
\usepackage{fontspec}
\setmainfont[UprightFont={Petrona-Light.ttf},
             BoldFont={Petrona-Medium.ttf},
             ItalicFont={Petrona-LightItalic.ttf},
             BoldItalicFont={Petrona-MediumItalic.ttf},
            ]{Petrona-Light.ttf}
~~~~
\begin{tikzpicture}[scale=1.1]

  \node[off state]   at (-1.75,0)    (off)            {Off\,\vphantom{g}};

  \node[error state, text width=1.3cm] at (2,-2)    (invalid)        {Invalid\vphantom{g}};
  \node[error state] at (2,2)                       (various errors) {\scriptsize\begin{tabular}{@{}c@{}}Privilege Violation,\\Not Implemented,\\Out of Memory\end{tabular}};
  \node[error state] at (2,3.5)                     (authfail)       {\footnotesize\begin{tabular}{@{}c@{}}Authentication\\Failure\end{tabular}};
  \node[error state, text width=1.3cm] at (2,-3.5)  (expired)        {Expired};

  \node[circle,thick,draw=black] at (4.75,2.75) (configuration hub) {};
  \node[coordinate] at ($(expired.east)+(0.5,0)$) (before expired) {};

  \node[state, thick, text width=1.3cm] at (5.5,0)    (initial)           {Initial\vphantom{g}};
  \node[state, thick, text width=2.9cm] at (8.5,-1.5) (algorithm defined) {Algorithm-Defined};
  \node[state, thick, text width=2.9cm] at (8.5,1.5)  (success failure)   {Success / Failure};

  %%%%%%%%%%%

  \node[above=0mm  of configuration hub,xshift=5mm] (ignore) {\small\textit{Configuration}};
  \node[below right=0mm and -4mm of before expired] (ignore) {\small\textit{Expiration}};

  %%%%%%%%%%%

  \draw[-,densely dashed]   (before expired) to[out=9,in=270,looseness=0.8] (initial);
  \draw[-,densely dashed]   (before expired) to[out=7,in=225,looseness=0.8] (algorithm defined);
  \draw[-,densely dashed]   (before expired) to[out=3,in=225,looseness=0.8] (success failure);
  \draw[->,densely dashed]  ($(before expired)+(-0.1,0)$) -- (expired);

  \draw[<->,densely dotted] (configuration hub) to[out=-40,in=90,looseness=0.8] (initial);
  \draw[<->,densely dotted] (configuration hub) to[out=-20,in=125] ($(algorithm defined.north)+(-0.333,0)$);
  \draw[<->,densely dotted] (configuration hub) to[out=0,in=140] ($(success failure.north)!0.5!(success failure.north west)$);
  \draw[<->,densely dotted] (configuration hub) to[out=160,in=0] (authfail);
  \draw[<->,densely dotted] (configuration hub) to[out=190,in=10] (various errors);
  \draw[<->,densely dotted] (configuration hub) -- (invalid.north east);
  \draw[<->,densely dotted] (configuration hub) to[out=270,in=10,looseness=0.6] ($(expired.east)+(0,0.1)$);

  \draw[<->] (off) to[out=-66,in=180] (invalid);
  \draw[<->] (off) to[out=78,in=180,looseness=0.7] (authfail);
  \draw[<->] (off) to[out=66,in=180] (various errors);
  \draw[<->] (off) to[out=-78,in=180,looseness=0.7] (expired);

  \draw[->] (algorithm defined) to[out=250,in=180] ($(algorithm defined)+(0,-1)$) to[out=0,in=290] (algorithm defined);
  \draw[->, cross line] (algorithm defined) -- (invalid);
  \draw[->,cross line] ($(algorithm defined.north)+(-0.667,0)$) to[out=130,in=0] (various errors);

  \draw[<->,cross line] (off) -- (initial);
  \draw[<->,cross line] (off) to[out=-33,in=180,looseness=0.3] (algorithm defined);
  \draw[<->,cross line] (off) to[out=33,in=180,looseness=0.3] (success failure);

  \draw[->,cross line]  ($(success failure.south)+(-1,0)$)   to[out=225,in=10,looseness=0.8] node[near start, above, yshift=-3pt] () {*} ($(initial.east)!0.5!(initial.north east)$);
  \draw[<->,cross line] ($(algorithm defined.north)+(-1,0)$) to[out=135,in=-10,looseness=0.8] ($(initial.east)!0.5!(initial.south east)$);
  \draw[->,cross line] (algorithm defined) -- (success failure);

\end{tikzpicture}
....
////

The legend for the graph is:

* The double circled state is the _Off_ State.
* Valid States have single rounded rectangular borders.
* Error States have double rounded rectangular borders.
* The continuous edges represent state transitions induced by both configuration and usage instructions.
* However, a transition from _Success_ or _Failure_ to _Initial_ may be forbidden by certain single-use CRs as per the _Algorithm_'s policies.
* The transitions from _Off_ to any Error State are a result of configuration instructions, whereas the corresponding transitions from these Error States to _Off_ are a result of explicitly clearing the CR.
* The dashed edges represent state transitions induced by reaching the expiration date.
* The dotted edges represent state transitions induced by configuration instructions. We note that completion of a provisioning operations can only bring to the _Initial_ state, whereas completion of an import can bring a CR to any state.
* Any transition may be caused by an performing explicit operation performed while in a given state, or be caused implicitly by reaching the latter under conditions specified in the algorithm's specification.
* The round _Configuration_ “hub” simplifies the graph to represent that it is always possible to reach any Error State, even from other Error States, by performing explicit configuration operations (or by using `ace.setst` between Error States).

The _StateExtension_ field can be used by an Algorithm to store additional state information.
This field may be used to determine the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-ConfigStatus]]
===== _ConfigStatus_ Field

The admissible values of this field are given in the table below.

[[ACE-SC-sealing-status]]
.Encoding of _ConfigStatus_ field
[float="center",align="center",cols="^7%,<21%,<72%"options="header"]
|===
| Value | Mnemonic             | Description
|   0   | _CfgStComplete_      | The CR is fully configured and ready to operate.
|   1   | _CfgStProvisioning_  | The CR is partially configured as a result of an interrupted provisioning operation.
|   2   | _CfgStImporting_     | The CR is partially configured as a result of an interrupted import operation.
|   3   | _CfgStExporting_     | The CR has been placed in exporting mode, i.e., its contents have been encrypted and authenticated for export..
|===

// ////////////////////////////////////////////////////////////////////

[[ACE-extra-content]]
===== _ImpDataLen_ Field

The _ImpDataLen_ Metadata Header field records the length of the _Additional Data Section_ of the content, which is a variable-size additional part that depends on the implementation.

The format of the _Additional Data Section_ is described in <<ACE-data-formats>>.

If _ImpDataLen_ is nonzero, the first 128-bit block of this additional section contains
a copy of the implementation qualifier

``{fournbsp}{fournbsp}IMPQUAL := zeros(32) @ aceimpid @ acearchid @ acevendorid``

(cf. <<ACE-CSR-impl-ids>>) from the originating machine. Its 16 bytes are counted within the length recorded by the _ImpDataLen_ field.
The importing implementation uses this value to determine whether any information in the Implementation-Specific Data Section can be used.

// ////////////////////////////////////////////////////////////////////

[[ACE-Localities]]
===== _Locality_ Field

ACE maintains a table of 128-bit Locality Secrets (LS), called the Locality Secrets Table (LST).
Some entries are fixed or are configurable only through an implementation-specific authenticated hardware procedure.
These are global, shared across all ACE units within the same SoC.
Other entries are per-hart architectural state, programmed by privileged modes.

<<ACE-locality-indexes>> lists the architected Localities.
Twelve LST entries are defined: the first six form the _HW Binding Group_, which binds SCCs to the hardware;
entries 6–7 form the _Boot Session Group_; and
entries 8–11 form the _SW Filter Group_.

For each Locality, the table provides: index in the LST; domain (SoC-, device-, VM-wide, or per-process); configurability; bit-field encoding; and value.

[[ACE-locality-indexes]]
.Architected Localities. Bits refer to the _Locality_ field in the Metadata Header.
[width="100%",cols="^5%,15%,50%,^9%,^9%,^6%,^6%",options="header"]
|===
|  Idx  | Locality                  | Description                                                                            | Domain | Config?|  Bits  | Value
2+|    No HW Binding                | Independent of Chip, OEM, Device                                                      ^|  --   ^|   --   | [3:0]  |  0
|   0   | _SiPScrt_                 | Identifies the designer of the SoC. Permanent.                                         |  SoC   |   No   | [1:0]  |  1
|   1   | _ChipFamScrt_             | Identifies specific chip/SoC model/family. Permanent.                                  |  SoC   |   No   | [1:0]  |  2
|   2   | _ChipScrt_                | Unique for each SoC. Permanent.                                                        |  SoC   |   No   | [1:0]  |  3
|   3   | _OEMScrt_                 | Provisioned by OEM to differentiate their products from the competition.
{empty}                               Permanent, or reconfigurable via a custom hardware authenticated mechanism.            | Device |   HW   | [3:2]  |  1
|   4   | _ProdScrt_                | Identifies device/system type/model (product).
{empty}                               Permanent or reconfigurable like OEMScrt.                                              | Device |   HW   | [3:2]  |  2
|   5   | _DevScrt_                 | Unique device (entire system) secret. Shared across all harts in a SoC and shareable
{empty}                               across multiple SoCs in a single device using an implementation-defined mechanism.
{empty}                               Reconfigurable like OEMScrt.                                                           | Device |   HW   | [3:2]  |  3
2+|   No Boot Binding               | Independent of Physical or Virtual Boot Session                                       ^|  --   ^|   --   | [5:4]  |  0
|   6   | _PhysBootScrt_            | Unique per the boot session of the host hardware and its firmware stack.
{empty}                     Configured by M-mode during the boot process of the host (see <<ACE-CSR-macePhysBootScrt>>).     | Device |   M    | [5:4]  |  1
|   7   | _VirtBootScrt_            | Unique per the boot session of the virtual hardware and its software stack.
Regenerated by H or higher at each virtual boot of a VM (see <<ACE-CSR-haceVirtBootScrt>>).                                  |   VM   |  H/M   | [5:4]  |  2
2+| No Binding to Modes             | Independent of M-, S-, or any VS-mode Localities                                      ^|  --   ^|   --   | [7:6]  |  0
|   8   | _MLocality_               | Configurable at M.  Useful to separate Supervisor Domains/Security States.             |  < M   |   M    | [7:6]  |  1
|   9   | _HLocality_               | Configurable at H.                                                                     |  < H   |   H    | [7:6]  |  2
|  10   | _SLocality_               | Configurable at (V)S.                                                                  | < (V)S |  (V)S  | [7:6]  |  3
|  11   | _Nonce_                   | Always re-configurable (out-of-band peer-to-peer nonce). Only bits [95:0] are defined. |  hart  |   U    | [8:8]  | 0/1
|===

Implementations are not required to populate every entry in the HW Binding Group, except for _ChipFamScrt_ and _DevScrt_.
If an entry is unconfigured, it is transparently replaced by the next defined entry in its chain: _SiPScrt_ {rightarrow} _ChipFamScrt_ {rightarrow} _ChipScrt_, and _OEMScrt_ {rightarrow} _ProdScrt_ {rightarrow} _DevScrt_.
If no entry is configured in these chain but one Locality is requested, the implementation must raise an authentication failure error.

_HLocality_ is active only when the H extension is enabled and V=1; otherwise, it mirrors _MLocality_.

NOTE: A system key identifier may refer to keys with unrelated purposes on different devices, leading to unspecified behavior.
Implementations shall assign usage policies at least as restrictive as the key's own native policies, and supply an appropriate _Locality_ during CR provisioning.

Up to five architected Localities may be active concurrently: two from the HW Binding Group, one of either _PhysBootScrt_ or _VirtBootScrt_, one from the SW Filter Group and the _Nonce_.
In <<ACE-provisioning-export-import>>, it is explained how the associated policies are enforced.

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata-expiration-date]]
===== _ExpirationDate_ Field

If non-zero, _ExpirationDate_ specifies the CC expiration time as a number of minutes elapsed since the base date of January 1, 2027.
The 26-bit field provides for a span of approximately 127 years (2^26^ minutes).

Checking against the _ExpirationDate_ field is the first step performed by any usage operation.
When a _usage_ instruction executes on a CR whose _ExpirationDate_ has passed, the hardware immediately sets the Metadata Header's _State_ field to `ace_state_expired` and performs all actions prescribed for Error States, including implementation-specific tasks such as releasing the CRF capacity held by the Content.
If the ACE privileged architecture is implemented, an `ace_exc_invalid` exception is raised (see <<ACE-exceptions>>).

Exporting, cloning, or configuring an expired CR is always permitted.
This includes the case when the _ExpirationDate_ has passed but no usage operation has yet been executed (so the above Error-State actions have not been triggered), in which case the _State_ field is not changed, and when the _State_ field has already been set to `ace_state_expired` and all content beyond the metadata has been cleared.
This way, when an expired CR is used, any exception will be raised in the caller code.

//Since privileged code may replace expired CRs, any user code that uses CRs that are known to potentially expire should always export the CR when it has finished using it, in case it may be needed later, instead of recovering it from a previously saved copy.

// ////////////////////////////////////////////////////////////////////

[[ACE-AlgorithmUse]]
===== _AlgorithmUse_ Field

The _AlgorithmUse_ field can be used by an Algorithm to store state information.

If not used by the Algorithm, the implementation may use this field to store state information.

This information shall _not_ be required to determine the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-Memory-Alignment]]
==== Memory Alignment Constraints

If the address accessed by an ACE memory instruction is not naturally aligned
to the effective XLEN, the context is transferred successfully or an
address-misaligned exception is raised on that address.

There are no atomicity requirements for any ACE memory instruction.

[[ACE-Memory-Model]]
==== Memory Model

ACE memory instructions appear to execute in program order on the local hart.

ACE memory instructions follow RVWMO at the instruction level. If the `Ztso`
extension is implemented, ACE memory instructions additionally follow RVTSO at
the instruction level.

ACE memory instructions may be decomposed into a set of component memory
operations of any granularity.
The ordering of these memory operations within the instructions is not specified,
and it depends on the chosen memory model and implementation,
as long as the the semantics of the configuration and export instruction and
`ace.exec` are respected.

NOTE: `Ztso` only imposes RVTSO at the instruction level; intra-instruction
ordering follows RVWMO regardless of whether Ztso is implemented.
More formal definitions required.

[[ACE-CSR-unpriv]]
==== CSRs

ACE provides a number of unprivileged CSRs.
// The privileged CSRs are documented in <<ACE-priv>>.

[[ACE-CSRs-unpriv]]
.ACE Unprivileged CSRs.
[cols="^10%,^10%,<18%,<62%"]
[float="center",options="header"]
|===
|  Address   | Privilege | Field                    | Description
|  0xXXX     |     RO    | `acevendorid`            | Used to identify manufacturer and implementation of the ACE unit. See <<ACE-CSR-impl-ids>>.
|  0xXXX     |     RO    | `acearchid`              | Used to identify manufacturer and implementation of the ACE unit. See <<ACE-CSR-impl-ids>>.
|  0xXXX     |     RO    | `aceimpid`               | Used to identify manufacturer and implementation of the ACE unit. See <<ACE-CSR-impl-ids>>.
| `vstart`   |    URW    | `acestart`               | ACE start bit index.
|  0xXXX     |    URW    | `aceiobuflen`            | ACE input/output buffer length in bits.
|  0xXXX     |     RO    | `acemaxiobuflen`         | ACE maximum input/output buffer length in bits. Read only.
|  0xXXX     |    URW    | `aceiobuftop`            | ACE input/output buffer limit for current transfers in bits.
|  0xXXX-XXX |    URW    | `acenonce0`, `acenonce1` | Nonce to be used in `ace.import` and `ace.export` (see <<ACE-provisioning-export-import>>).
|===

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-impl-ids]]
===== `acevendorid`, `acearchid`, `aceimpid`

{empty}
(((CSR, `acemvendorid`)))
(((CSR, `acemarchid`)))
(((CSR, `acemimpid`)))
`acevendorid`, `acearchid`, and `aceimpid` identify the version of the ACE unit, analogously to `mvendorid`, `marchid`, `mimpid` CSRs for the hart.

The `acemvendorid` CSR is a 32-bit read-only register providing the JEDEC manufacturer ID of the provider of the ACE unit (or 0 it is not commercial).

The `acemarchid` CSR is an 32-bit read-only register encoding the base microarchitecture of the ACE unit. Non-commercial IDs are allocated globally by RVI, while commercial IDs are specific to the acemvendorid`

The `acemimpid` CSR is a 32-bit read-only register that provides a unique encoding of the version of the ACE unit implementation. This register must be readable in any implementation, but a value of 0 can be returned to indicate that the field is not implemented. The Implementation value should reflect the design of the ACE unit itself and not any surrounding system.

These three CSRs, together, form the _Implementation Qualifier_, i.e., the zero-padded 128-bit value

``{fournbsp}{fournbsp}IMPQUAL := zeros(32) @ aceimpid @ acearchid @ acevendorid``

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acestart]]
===== `acestart`

{empty}
(((CSR, `acestart`)))
`acestart` is an alias for `vstart`. Therefore, it is an XLEN-bit RW CSR.
ACE defines it also when the V extension is not enabled.

`acestart` tracks the progress of resumable ACE instructions, such as `ace.input` and `ace.output`, but also of provisioning and import/export operations if they support resumption (for the latter, see <<ACE-provisioning-export-import>>).
It also applies to `ace.exec` when iteratively processing a multi-block operand, as `ace.exec` may be interrupted between blocks.
Only these instructions honor a nonzero `acestart`; all other instructions ignore it and are restarted, with `acestart` also being cleared.

Since ACE does not have an _intrinsic_ concept of element length, `acestart` counts the number of _bits_ processed so far nu `ace.exec`, not the number of elements, or read/written by `ace.input`/`ace.output` and `ace.prov`/`ace.import`/`ace.export` or `ace.store`/`ace.load`.

Hardware writes this register on interruption.
Software may save and restore the register across context switches.
For certain algorithms, writing zero to `acestart` to force a full restart of `ace.exec` may lead to inconsistent or unpredictable results.
Writing an invalid or non-supported nonzero value raises an illegal instruction exception.

When a vector instruction is interrupted, the CSR follows `vstart` semantics as expected, i.e., it counts the number of processed elements.
When an ACE instruction is interrupted, the CSR follows the `acestart` semantics described here.

[WARNING]
====
The reason `vstart` can be reused as `acestart` comes from the fact that the Risc-V ISA exposes a computation model in which the observable results are the same as if the instructions were executed in order.
If an implementation has executed instructions past the PC when an interrupt occurs, those instructions are discarded and must be re‑executed upon return from the handler. Only the instruction at the PC may be interrupted in a way that it saves temporary state that allows it to be resumed later.
There is no situation in which the microarchitecture of a hart can simultaneously interrupt multiple instructions allowing them to resume at the same time.
Hence, `vstart` can safely be reused by ACE as `acestart`.
====

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acemaxiobuflen]]
===== `acemaxiobuflen`

{empty}
(((CSR, `acemaxiobuflen`)))
`acemaxiobuflen` is an XLEN-bit RO CSR that reports the maximum configurable length of the ACEIOBUF.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuflen]]
===== `aceiobuflen`

{empty}
(((CSR, `aceiobuflen`)))
`aceiobuflen` is an XLEN-bit URW CSR that programs the ACEIOBUF length in bits for use by `ace.input` and `ace.output`.
Writing this register-even when re-writing the current value-also zeroes the buffer and sets `aceiobuftop` to the same length and `acestart` to zero.

When `aceiobuflen` is zero, the ACEIOBUF is _unconfigured_.
Attempting to execute an operation that expects an input or an output in the ACEIOBUF while the latter is unconfigured raises exception `ace_exc_buf_unconf`.

Writing a value larger than `acemaxiobuflen` raises exception `ace_exc_out_of_mem`.

As per the Privileged Architecture, the dirtiness of the ACEIOBUF is not tracked except as part of the entire ACE state in `*status`.
Context switching code is expected to save and restore the contents of the ACEIOBUF up to `aceiobuflen`.
We recommend software to set `aceiobuflen` to zero once the contents of the ACEIOBUF are no longer needed.
Context switching code can use this information to avoid unnecessary save and restore of ACEIOBUF contents.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuftop]]
===== `aceiobuftop`

{empty}
(((CSR, `aceiobuftop`)))
`aceiobuftop` is an XLEN-bit URW CSR that marks the upper bound in bits of the buffer range used by `ace.input` and `ace.output`.
Together with `acestart`, it defines the active transfer window.

The constraints `acestart` {le} `aceiobuftop` {le} `aceiobuflen` must hold.
Violating either bound raises an illegal instruction exception.
Modifying `aceiobuftop` does not modify buffer contents.

NOTE: `aceiobuftop` enables per-operation length adjustments without the need to reconfigure the ACEIOBUF using `aceiobuflen`, which can be expensive due to the fact that it clears the buffer and may lead to internal garbage collection.
This can be used similarly to the reconfiguration of `VL*SEW` to provide an partial “last block” or to supply a short IV/nonce to cryptographic algorithms.

Using a alternative sequence for `ace.exec` or `ace.setst` for any Form with an input or output
when `aceiobuftop` − `acestart` is zero (and `aceiobuflen` nonzero) will result in no operation being performed.

Using ACEIOBUF when `aceiobuftop` − `acestart` is an invalid length raises an illegal instruction exception.

Since context switching code saves and restores the contents of the ACEIOBUF up to `aceiobuflen`, the contents between `aceiobuftop` and `aceiobuflen` are preserved.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acenonce]]
===== `acenonce0` and `acenonce1`

{empty}
(((CSR, `acenonce`)))
`acenonce0` and `acenonce1` are XLEN-bit URW CSR that define the nonce to be used in `ace.import` and `ace.export` (see <<ACE-provisioning-export-import>>).
`acenonce0` contains bits [63:0] of the nonce, and `acenonce1` contains bits [95:64] of the nonce.
The most significant 32 bits of `acenonce1` are fixed to zero.

On RV32, 32-bit CSR `acenonce0h` shadows bits [63:32] of `acenonce0`, allowing these bits to be accessed.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

// [[ACE-CSR-aceactivecr]]
// ===== `aceactivecr`
//
// {empty}
// (((CSR, `aceactivecr`)))
// `aceactivecr` is an XLEN-bit URW CSR; only the low 5 bits are defined.
// It binds `ace.input`, `ace.output`, `ace.exec`, and `ace.setst` to a specific CR.
// The valid values are 0–31, which are used to bind to a CR, or 32, which disables any such binding.
//
// When `aceactivecr` is not 32, the CR operand in all single-CR instructions and the source CR in `ace.clone` must equal the selected value, and the
// _Sequence_ metadata field of that CR must track the operation in an instruction alternative sequence.
//
// // At any given moment, only one _Sequence_ field in the Metadata Sections of all CRs may be non-zero, and `aceactivecr` must match the number of that CR.
//
// Any deviation from these behaviors raises an illegal instruction exception.
//
// _Included in_::
// +
// --
// [%header,cols="4,2,2"]
// |===
// |Extension | Minimum version | Lifecycle state
// | `Zlio`   | v0.0.0          | --
// |===
// --
// +

// ////////////////////////////////////////////////////////////////////

[[ACE-instructions-detailed]]
=== Instructions

[WARNING]
====
The encodings presented here are preliminary.
====

ACE provides a number of unprivileged instructions.
This section specifies their semantics and encodings.

The notation `K(Xd)` denotes the CR whose index is held in GPR `Xd`.
`Kn|K(Xn)` indicates two alternative encodings: a 5-bit immediate CR index (`Kn`) or a CR number supplied by GPR `Xn`. Use of the zero register `X0` as a CR index register raises an illegal instruction exception unless explicitly indicated otherwise.

Each instruction is characterized by the following properties:

* _Modifies state_: whether the instruction may modify ACE architectural state;
* _Usage-controlled_: whether the instruction is subject to usage control policies.
// * Trappable: whether the instruction may be implemented by privileged code
//   via trap-and-emulate; and
// * _Interruptible_: whether execution may be interrupted (e.g., by a context
//   switch or page fault) and later resumed or restarted.

NOTE: Trappability refers solely to the CPU-side implementation—for example, to enable decomposition of certain ACE instructions into smaller custom operations.
This is distinct from custom algorithm implementations within the ACE unit itself (e.g., via a secure embedded CPU with updatable firmware), which are outside the scope of this specification.

NOTE: ACE does not have concepts similar to the vector crypto extension's Element Group Width (EGW), Effective Element Width (EEW), and Element Group Size (EGS).
Since the architecture decouples instructions like `ace.exec` from the actual operations, the high-level design of ACE needs only the total input and output size, denoted `ACELEN`. This is equal to either `VL * SEW` or the `aceiobuftop` length of the ACEIOBUF, as defined in <<ACE-notation>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-management-operations]]
==== Provisioning, Import and Export

Broadly speaking, and removing error handling, *Provisioning* is performed by the following three steps:

. Use `ace.setst` (<<ACE-instruction-setst>>) to prepare a CR to be provisioned, store the low 64 bits of the Metadata Header in it, check the metadata.
. Use `ace.load` (<<ACE-instruction-load>>) to load the rest of the provisioning information into the CR.
. Use `ace.setst` to make the CR available to software.

*Importing* a SCC into a CR is similar:

. Use `ace.setst` to prepare a CR to accept a SCC, store the low 64 bits of the metadata field in it, check the metadata.
. Use `ace.load` to load the rest of the SCC information into the CR.
. Use `ace.setst` to authenticate and decrypt the SCC, and make the CR available to software.

*Exporting* a CR as an SCC consists of the following steps:

. Use `ace.getmd` (<<ACE-instruction-getmd>>) to get the low 64 bits of the Metadata Header of the CR to be exported to be able to determine its size and allocate resources.
. Store the low 64 bits of the Metadata Header into memory.
. Use `ace.setst` to prepare a CR to produce a SCC, by encrypting the contents and computing the authentication tag.
. Use `ace.store` (<<ACE-instruction-store>>) to store the high 64 bits of the Metadata Header and the rest of the SCC to memory.
. Use `ace.setst` to restore the CR in a form available to software.

// NOTE: The instruction encoding of `ace.load` includes a single bit to indicate a
// system-defined format. If multiple system-defined formats are supported, the
// system is responsible for distinguishing them. These formats do not necessarily
// include the key value itself, they may contain a “recipe” for an
// implementation-defined mechanism to generate the key. Such system generated
// keys are system-specific and the “recipe” is in general not portable. After
// internal key generation, the actual key value—not the recipe—is stored in the
// CR and SCC. For all keys provisioned in this way, the _KeyType_ field
// in the Metadata is 0, denoting a key represented by value.
//
// NOTE: The export procedure does not have an export equivalent for system-defined formats.
// This means that system-specific dynamically generated keys can be imported but not exported
// in the same form: they must be exported in the format architected here for ACE CCs.

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-load]]
===== ace.load

_Encoding_::
`ace.load` is an I-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x0b, attr: ['custom-0'] },
    { bits:  5, name: 'context', attr: ['Kd','K(Xd)'] },
    { bits:  3, name: 'ace.load', attr: ['0    0    0','0    0    1'] },
    { bits:  5, name: 'Xs1' },
    { bits: 12, name: 'immed12' },
]}
....

_Mnemonics_::
`ace.load{fournbsp}{nbsp}{nbsp}{nbsp}Kd|K(Xd), %offset(Xs1)` +
`ace.sysimport{nbsp}Kd|K(Xd), %offset(Xs1)`

_Description_::
+
--
`ace.load` imports a PI or a SCC, starting with the 8th byte of the Metadata Header, at memory address `%offset(Xs1)`, into the CR `Kd` or `K(Xd)`.

Ths instruction requires that the CR is ready to import information and that the first 8 bytes of the Metadata Header have already been loaded.
Therefore, if the _ConfigStatus_ field is equal to _CfgStComplete_, an invalid instruction exception is raised.

The semantics of `ace.load` in case the key is in a system-defined format
are entirely implementation dependent and do not assume that the CR has been readied to import information and
that some metadata has already been loaded in it.
The use of a system-defined format is signalled by the _SystemFormat_ bit of the Metadata, which in this case may have a system-defined length.
--
+

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-store]]
===== ace.store

_Encoding_::
`ace.store` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 'ace.store', attr: [0x0,0x1] },
    { bits:  5, name: 'Xs1' },
    { bits:  5, name: 'context', attr: ['Ks2','K(Xs2)'] },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Mnemonic_::
`ace.store %offset(Xs1), Ks2|K(Xs2)`
(((ACE, instruction, ace.export)))

_Description_::
+
--
Exports raw data from the CR `Ks2` or `K(Xs2)` to memory at address `%offset(Xs1)`.
The operation starts with the 8th byte of the Metadata Header.
The instruction itself determines the length of the output from the Metadata Header.

If the _ConfigStatus_ field is equal to _CfgStComplete_, then an invalid instruction exception is raised.
--
+

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-exec]]
==== ace.exec

_Synopsis_::
Perform a cryptographic operation in the ACE unit.

_Mnemonic_::
The `ace.exec` instruction admits four Forms, namely
(((ACE, instruction, ace.exec)))

[upperalpha]
. `ace.exec  Vd, Kn|K(Xn), Vs2` {nbsp} takes an input vector and writes to an output vector.
. `ace.exec  {fournbsp} Kn|K(Xn), Vs2` {nbsp} takes an input vector but does not write to an output vector.
. `ace.exec  Vd, Kn|K(Xn) {fournbsp}{nbsp}` {nbsp} does not take an input but writes to an output vector.
. `ace.exec  {fournbsp} Kn|K(Xn) {fournbsp}{nbsp}` {nbsp} does not take an input vector and does not write to an output vector.

// Without this comment, the next part is not properly formatted...

_Encoding_::
`ace.exec` is an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'rd', attr: ['Vd','—','Vd','—'] },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Ks1|K(Xs1)'] },
    { bits:  5, name: 'rs2', attr: ['Vs2','Vs2','—','—'] },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 'Form', attr: ['0    0','0    1','1    0','1    1'] },
    { bits:  2, name: 0x0, attr: ['func2'] },
]}
....
+
Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an
immediate, and it takes the value 1 if a GPR (scalar integer value) is used to
reference it.
For the four Forms A–D above, the encodings are:
+
[upperalpha]
. `Form` = `0b00`.
. `Form` = `0b01` and `rs1` = `0b00000`.
. `Form` = `0b10` and `rs2` = `0b00000`.
. `Form` = `0b11` and `rs2` = `rs1` = `0b00000`.

// To make indent in next line correct

_Description_::
+
--
Performs a cryptographic operation as defined by the algorithm in CR `Ks1` or `K(Xs1)`.
The instruction may take an input and produce an output.

If the V extension register file is not implemented, only Form D `ace.exec`
is supported and `ace.input`, `ace.output` are used to provide inputs and
extract outputs from `ace.exec`, as described in <<ACE-usage-input-output>>.
--
+

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv` (Forms A-D)    | v0.0.0          | --
| `Zlio` (Form D)      | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-setst]]
==== ace.setst

_Synopsis_::
Change the state of the algorithm encoded in the CC in a CR.

_Mnemonic_::
The `ace.setst` instruction admits three Forms, namely
(((ACE, instruction, ace.setst)))

[upperalpha]
. `ace.setst Kd|K(Xd), #immed7{fournbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.setst Kd|K(Xd), #immed7, Xs{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.setst Kd|K(Xd), #immed7, Vs{nbsp}{nbsp}` with an auxiliary input in a vector register.

//

_Encoding_::
`ace.setst` is an R-type instruction.
+
[wavedrom, ,svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 'ace.setst', attr: ['0    0    1','0    1    0','0    1    1'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'rs1', attr: ['—','Xs','Vs'] },
    { bits:  7, name: 'immed7' },
]}
....
+
The encodings of the three Forms are:
[upperalpha]
. `ace.setst` = `0b001`.
. `ace.setst` = `0b010`.
. `ace.setst` = `0b011`.

// ////////////////////////////////////////////////////////////////////

_Description_::
+
--
The instruction changes the _State_ and _StateExtension_ fields of the Metadata Header of `Kd` or `K(Xd)`.

It can be used to move from one stage of an algorithm to another-for example, advancing from initialization to data absorption in a hash function, then to finalization and output of the digest.

The `#immed` operand is a constant from a set of admissible values defined for each algorithm. Optionally, `Xs` or `Vs` contain an auxiliary input.

Normally, the `#immed7` contains the _State_ value to be set.
Some states may transition to a different state automatically after completing `ace.setst`.

If the `#immed7` is zero, i.e., the value corresponding to the _Off_ state, the CR is cleared.

Certain values of the `#immed7`, depending on the Algorithm, may be used to set change _StateExtension_ instead, so that it can be used as state information that is orthogonal to the _State_ field.

The allowed state transitions are described in <<ACE-State-field>> and in the algorithms.

It is always allowed to use an Error State (see <<ACE-states-error>>) for the `#immed`.
This will also invalidate the contents of the CR and possibly release them.

Setting an Error State does _not_ trigger an exception, even if reaching that state implicitly would normally do.
Further usage of the same CR–for instance, a later `ace.exec` or `ace.state` to a valid state–will raise exceptions in that case.

[WARNING]
====
When used to affect a CR's _ConfigStatus_, `ace.setst` is _not_ considered an usage instruction because it is part of a configuration operation. It is therefore not subject to the limitations on usage instructions, and it will not cause the CR to enter any Error State, including _Expired_.
====

The special values of `#immed7` to prepare a CR for provisioning, importing, and exporting, and seal it afterwards, are

[[ACE-management-immeds]]
.Values (decimal) of `#immed7` to be used for provisioning, importing, and exporting
[float="center",align="center",width="100%",cols="^7%,<20,<73%",options="header"]
|===
| Value | Mnemonic                  |  Description
|  96   | `provision_open`          |  Prepare a CR for provisioning keys and metadata into it, set _ConfigStatus_ to _CfgStProvisioning_. Needs an auxiliary input in a GPR (or a GPR pair) with bits [63:0] of Metadata Header.
|  97   | `provision_close`         |  Make the provisioned CR available to software  (“sealing”), set _ConfigStatus_ to _CfgStComplete_. Requires no auxiliary input.
|  98   | `import_open`             |  Prepare a CR for importing a SCC into it, set _ConfigStatus_ to _CfgStimporting_. Needs an auxiliary input in a GPR (or a GPR pair) with bits [63:0] of Metadata Header.
|  99   | `import_close`            |  Decrypt and authenticate the imported SCC, make the CR available to software, set _ConfigStatus_ to a provided value.
| 100   | `export_open`             |  Prepare a CR for exporting it as a SCC (if not yet in the correct format), set _ConfigStatus_ to _CfgExporting_. Requires no auxiliary input.
| 101   | `export_close`            |  Restore the exported CR in the internal clear format (only if already complete) and make it available to software, set _ConfigStatus_ to a provided value. Uses an auxiliary input in a GPR (or a GPR pair) with bits [63:0] of Metadata Header to restore _ConfigStatus_ saved by software.
If the restored value of _ConfigStatus_ is not _CfgStComplete_, the CR is made available to software.
|===

If `ace.setst` is used to initiate provisioning:

* If the instruction fails, the target CR is unconfigured, with the same semantics as if `ace.clear` were invoked on the same CR (<<ACE-instruction-clear>>).
* If the combination of _Algorithm_, _AlgorithmPolicy_, and _SCProtection_ is not supported, exception `ace_exc_invalid` may be raised as defined in the Privileged Architecture. The handler may simply set the CR to Error State `ace_state_not_impl` and return to the original control flow.
* Exception `ace_exc_invalid` is raised in other cases here where the Metadata is invalid, such as, for instance: a nonzero _State_ or reserved field; or an unsupported _Locality_ value. The handler may simply set the CR to Error State `ace_state_invalid` and return to the original control flow.
* Exception `ace_exc_invalid` is raised also if the PI refers to a system key that the current hart or mode is not allowed to directly use.
The corresponding policies are implementation and system defined.
* The operation is described in detail in <<ACE-provisioning-export-import>>.

If `ace.setst` is used to initiate import:

* If the instruction fails, the target CR is unconfigured, with the same semantics as if `ace.clear` were invoked on the same CR (<<ACE-instruction-clear>>).
* If the combination of _Algorithm_, _AlgorithmPolicy_, and _SCProtection_ is not supported, exception `ace_exc_invalid` may be raised as defined in the Privileged Architecture. The handler may simply set the CR to Error State `ace_state_not_impl` and return to the original control flow.
* Exception `ace_exc_invalid` is raised if the Metadata is invalid (other than unimplemented algorithm), such as, for instance: nonzero bits in reserved fields;
unsupported _Locality_ value;
or a value of _State_ which is not allowed by the current _Algorithm_ and _AlgorithmPolicy_.
* The bit S takes the values 0 (false) or 1 (true). It is set to true if the key
is in a system-defined format (`ace.import.S`) and not the format defined by
the present architecture (`ace.import`).

If `ace.setst` is used to initiate export:

* There are no failure modes.
--
+

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

// The state numbers used in this specification are defined in <<ACE-states-valid>> and <<ACE-state-constants-symmetric>>.

It is allowed to issue `ace.setst` instructions to the current state.
When the algorithm needs to prevent this, it will automatically transition to a different state after completing `ace.setst`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
| Extension | Minimum version | Lifecycle state
| `Zlv`     | v0.0.0          | --
| `Zlio`    | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getmd]]
==== ace.getmd/ace.getmdh

_Synopsis_::
Export the Metadata Header of a CR.

_Mnemonic_::
`ace.getmdl  Xd, Ks|K(Xs)`
`ace.getmdh Xd, Ks|K(Xs)`
(((ACE, instruction, ace.getmd)))

_Encoding_::
`ace.getmdl`/`ace.getmdh` is an R-type instruction and its encoding shares opcode and `func3` with `ace.exec`, but `func2` is set to `0b11`.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Ks|K(Xs)'] },
    { bits:  5, name: 0x00  },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  2, name: 0x0 },
    { bits:  1, name: 'h' },
    { bits:  2, name: 0x3, attr: ['func2'] },
]}
....
+
Bit `r` (bit 26) is 0 when the context is an immediate and 1 when it is held in a GPR (scalar integer).
+
If bit `h` (bit 29) is 0, the instruction is `ace.getmdl`; if `h` is 1, it is `ace.getmdh`.

_Description_::
+
--
On RV64:

* `ace.getmdl` copies bits [63:0] of the Metadata Header of a CR `Ks` or `K(Xs)` into GPR `Xd`.
* `ace.getmdh` bits [127:64] into GPR `Xd`.

On RV32, `d` must be even, and:

* `ace.getmdl` copies bits  [31:0] of the Metadata Header of a CR `Ks` or `K(Xs)` into GPR `Xd` and bits  [63:32] into GPR `X[d+1]`, atomically.
* `ace.getmdh` copies bits [95:64] of the Metadata Header of a CR `Ks` or `K(Xs)` into GPR `Xd` and bits [127:96] into GPR `X[d+1]`, atomically.
--
+

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-restrict]]
==== ace.restrictl/ace.restricth

_Synopsis_::
Restrict the policies encoded in a CC in a CR.

_Mnemonic_::
`ace.restrict{nbsp}{nbsp}Kd|K(Xd), Xs1`
(((ACE, instruction, ace.restrict)))

// Without this comment, the next part is not properly formatted...
_Encoding_::
`ace.restrict` is an R-type instruction.
The encoding shares opcode and `func3` with `ace.exec`, but `func2` (i.e., the two msbs of `func7`) is `0b01`.
The source register field encodes a GPR and not a vector register.
If bit `h` (bit 29) is 0, the instruction is `ace.restrictl`; if `h` is 1, it is `ace.restricth`.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'Xs1' },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  2, name: 0x0 },
    { bits:  1, name: 'h' },
    { bits:  2, name: 0x1, attr: ['func2'] },
]}
....
+
Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an immediate in Bits [11:7], and it takes the value 1 if a GPR (also encoded in [11:7]) is used to reference it.

// comment

_Description_::
+
--
`ace.restrictl/ace.restricth` can only be used if the CR's state is _Initial_.
Using the instruction in any other state raises an invalid instruction exception.

`ace.restrictl` modifies the field _AlgorithmPolicy_ in bits [63:0] of the Metadata Header of the CR.

`ace.restricth` modifies fields _Locality_, _UsagePolicy_, _ExpirationDate_, and possibly _AlgorithmUse_ in bits [127:64] of the Metadata Header of the CR.

Modifying the _Locality_ field can be used to add a Locality but also to _replace_ a Locality with a stricter one, such as

 * _SiPScrt_ {rightarrow} _ChipFamScrt_, _ChipScrt_; _ChipFamScrt_ {rightarrow} _ChipScrt_;
 * _OEMScrt_ {rightarrow} _ProdScrt_, _DevScrt_; _ProdScrt_ {rightarrow} _DevScrt_.
 * _MLocality_ {rightarrow} _HLocality_, _SLocality_; and _HLocality_ {rightarrow} _SLocality_.

Generalizing Localities is not permitted: Attempting to do so raises exception `ace_exc_invalid`, but the
State is not automatically set to _ace_state_invalid_ (the exception handler may of course do that).

Once the _Locality_ field has been modified,
when the CR is exported, it will use the new Locality values to tweak the export algorithm.

Let `mh` be the Metadata Header of the CC in the destination CR.

On RV64, the semantics of the instructions are:

* For `ace.restrictl`, `Xs` follows the format of bits [63:0] of the Metadata Header,
and for `ace.restricth`,  `Xs` follows the format of bits [127:64] of the Metadata Header

Only the fields _AlgorithmPolicy_, _Locality_, _UsagePolicy_, _ExpirationDate_ and _AlgorithmUse_ of `Xs` may be defined.
All other fields must be 0, else exception `ace_exc_invalid` is raised.

* `Xs`._AlgorithmPolicy_ is used to set the new `mh`._AlgorithmPolicy_ of the
  CR, if the CC configured in the latter makes use of this field.
  No currently disabled operation may be (re)enabled, any attempt to do so raises
  exception `ace_exc_invalid`. In some cases, a zero value is not permitted, such as
  disabling both encryption and decryption. +
  If the CR is in a state only allowed while performing an operation currently
  allowed by `mh`._AlgorithmPolicy_, any change to _AlgorithmPolicy_ that would
  disable that operation will cause exception `ace_exc_invalid` to be raised at the
  next usage operation on the CR.

* If `Xs`._Locality_ is non-zero, then it is the new value of `mh`._Locality_, subject to the Locality replacement rules above.

* A zero in any of bits `Xs`._UsagePolicy_ means that the corresponding policy is _not_ changed.

* A one in any of the bits `Xs`._UsagePolicy_ means that usage by the corresponding mode is not allowed, and the corresponding bit in the Metadata of the destination CC is set to 1.

* If `Xs`._ExpirationDate_ is zero, the corresponding policy in `mh`._ExpirationDate_ is _not_ changed.

* A non-zero value in `Xs`._ExpirationDate_ will be copied to
  `mh`._ExpirationDate_, but only if that policy was not already programmed before
  or the original value of `mh`._ExpirationDate_ was equal to the new value or larger.
  Otherwise exception `ace_exc_invalid` is raised.

* Any change to `mh`._AlgorithmUse_ is subject to policies set by the Algorithm in the CR.
--
+
On RV32:

* `s` must be even, the register pair `X[s]` and `X[s+1]` is read atomically, and
  `(X[s+1] @ X[s])` replaces `Xs` in the RV64 description.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[NOTE]
====
This instruction enables several practical use cases:

*   Enabling side-channel protection when supported by the microarchitecture,
    even if the original CC was not configured with it.
*   Allowing privileged code to give a CC to several processes in a
    fine-grained manner. This can be achieved by cloning the CR and customizing
    the Localities for each clone.
*   Similarly, enabling privileged code to split a CC capable of both
    encryption and decryption into two CCs, one only capable of encryption and
    the other only capable of decryption, thereby creating a one-way channel
    between processes.

The ability to perform such customizations saves both time and computational
resources by avoiding additional round-trips to trusted environments.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clone]]
==== ace.clone

_Synopsis_::
Copy a CR into another CR.

_Mnemonic_::
`ace.clone Kd|K(Xd), Ks|K(Xs)`
(((ACE, instruction, ace.clone)))

_Encoding_::
The encoding shares opcode and `func3` with `ace.exec`, however `func2` is 2.
The instruction is thus an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks|K(Xs)' },
    { bits:  5, name: 0x0 },
    { bits:  2, name: 'R' },
    { bits:  3, name: 0x0 },
    { bits:  2, name: 0x2, attr: ['func2'] },
]}
....
+
Bits [26:25], i.e., field `R`, take the following values depending on how the
CRs are given:
+
[upperalpha]
. `00`{nbsp}{nbsp} if the source and the output CRs are both encoded as
  immediate values.
. `01`{nbsp}{nbsp} if the source CR is encoded as immediate and the output CR
  is selected using a GPR.
. `10`{nbsp}{nbsp} if the source CR is selected using a GPR and the output CR
  is encoded as an immediate value.
. `11`{nbsp}{nbsp} if the source and the output CRs are both selected using the
  values of GPRs.

// Comment to ensure proper indentation in the next Description

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
// Trappable: *YES*, it can be implemented as an export followed by an import in a handler. +
// Interruptible: *NO*. +

_Description_::
Clones source CR `Ks` (or the CR indexed by `Xs`) into destination CR `Kd` (or the CR indexed by `Xd`).

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

// //

[[ACE-instruction-derive]]
==== ace.derive

[NOTE]
====
This instruction is not yet used by any algorithm. The encoding is reserved for future use.
====

_Synopsis_::
Derive a CR from a source CR, such as a key derivation.

_Mnemonic_::
The `ace.derive` instruction admits three Forms, namely
(((ACE, instruction, ace.derive)))
[upperalpha]
. `ace.derive Kd|K(Xd), Ks1|K(Xs1) {fournbsp}{nbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.derive Kd|K(Xd), Ks1|K(Xs1), Xs2{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.derive Kd|K(Xd), Ks1|K(Xs1), Vs2{nbsp}{nbsp}` with an auxiliary input in a vector register.

_Encoding_::
The encoding differs from `ace.clone` in that bit 27 is set to 1.
The instruction is thus an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks1|K(Xs1)' },
    { bits:  5, name: 'Xs2|Vs2' },
    { bits:  2, name: 'R' },
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'Form' },
    { bits:  2, name: 0x2, attr: ['func2'] },
]}
....
+
Bits [26:25], i.e., field `R`, are encoded exactly as for `ace.clone` (<<ACE-instruction-clone>>).
+
Bits [29:28], i.e., field `Form`, deals with the optional auxiliary input:
+
[upperalpha]
. `00`{nbsp}{nbsp} the instruction admits no auxiliary input.
. `01`{nbsp}{nbsp} the instruction accepts an auxiliary input in a GPR.
. `10`{nbsp}{nbsp} the instruction accepts an auxiliary input in a vector register.
. `11`{nbsp}{nbsp} is reserved for future use.

_Description_::
Derive a new context from an existing one, with its own opaque key material, for instance using a key derivation mechanism.
The behavior of the instruction is not expected to be deterministic.
It can be used multiple times, to generate multiple derived contexts.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// //

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-size]]
==== ace.size

_Synopsis_::
Return the size of a PI or SCC in bytes, or zero in case of error.

_Mnemonics_::
There are two Forms of the `ace.size` instruction:
(((ACE, instruction, ace.size)))

[upperalpha]
. `ace.size Xd, Ks|K(Xs)` - Size from a context.
. `ace.size Xd, Xs` - Size from Metadata Header.

// Without this comment, the next part is not properly formatted...

_Encoding_::
The encoding shares opcode, `func3`, and `func2` (the two msbs of `func7`) with `ace.exec`, however with bit 27 equal to 1.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks/K(Xs)/Xs' },
    { bits:  5, name: 0x0 },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'F' },
    { bits:  2, name: 0x0, attr: ['func2'] },
]}
....
+
The `F` field and the `r` bit may assume the following values:

* `F` = `0b00`, `r` = `0` {implies} Form A: Size from a context given as `Ks`.
* `F` = `0b00`, `r` = `1` {implies} Form A: Size from a context given indirectly as `K(Xs)`.
* `F` = `0b01`, `r` = `0` {implies} Form B: Size from Metadata Header.

_Description_:: {empty}
+
--
* Form A `ace.size` returns the total size in bytes of the memory buffer that
  would be necessary to store the exported SCC, including the authentication tag and the additional variable-length data.
  Knowing this size is necessary
  for any feature that relies on `ace.export`, including context switching. The
  instruction returns 0 if the CR is unconfigured.

* On RV64, Form B `ace.size` returns the total size in bytes of an SCC having Bits [63:0]
  of the Metadata Header given in `Xs` into GPR `Xd` including the additional variable-length data,
  and `0` if the if the algorithm is not supported or the Metadata is otherwise invalid.

* On RV32, Form B `ace.size` differs from the RV64 version in that `s` must be even, and
  Bits [63:0] of the Metadata Header are passed in `X[s+1] @ Xs`,
--
+

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-input]]
==== ace.input

_Synopsis_::
Load data into the ACEIOBUF.

_Mnemonic_::
`ace.input %offset(Xs), Xl`
(((ACE, instruction, ace.input)))

_Encoding_::
`ace.input` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 0x2, attr: ['ace.input'] },
    { bits:  5, name: 'Xl' },
    { bits:  5, name: 'Xs' },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Description_::
If the vector registers are not sufficiently long, or not implemented, inputs can be read directly from memory and outputs written directly to memory.
For this reason, the architecture defines `ace.input` and `ace.output` (cf. next section).
`ace.input` loads `Xl` bytes from memory starting at address `%offset(Xs)` and copies them to the ACEIOBUF, starting at offset `acestart`.
+
If `Xl` = 0, the operation does nothing.
+
If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.
+
The intended usage of `ace.input` and `ace.output` is explained in detail in
<<ACE-usage-input-output>>.

`ace.input` may be used only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero.
Otherwise, exception `ace_exc_buf_unconf` is raised.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
// Trappable: *YES*. +
// Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-output]]
==== ace.output

_Synopsis_::
Save the contents of the ACEIOBUF to memory.

_Mnemonic_::
`ace.output %offset(Xd), Xl`
(((ACE, instruction, ace.output)))

_Encoding_::
`ace.output` is an I-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x3, attr: ['ace.output'] },
    { bits:  5, name: 'Xl' },
    { bits: 12, name: 'immed' },
]}
....

_Description_:: {empty}
+
--
This is the output operation corresponding to `ace.input`.
`ace.output` writes the contents of the input buffer, starting at offset `acestart`, to memory starting at address `%offset(Xs)`.

If `Xl` = 0, the operation does nothing.

If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.
--
+

`ace.output` may be used only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero.
Otherwise, exception `ace_exc_buf_unconf` is raised.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
// Trappable: *YES*. +
// Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-pseudo-instructions-detailed]]
=== Pseudo-Instructions

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clear]]
==== ace.clear/ace.reset

_Synopsis_::
Clears and unconfigures a CR, or the ACE state.

_Mnemonic_::
`ace.clear Kd|K(Xd)` +
(((ACE, instruction, ace.clear)))
`ace.reset`
(((ACE, instruction, ace.reset)))

_Encoding_::
Pseudo-instructions `ace.clear`/`ace.reset` are implemented as `ace.setst` (see <<ACE-instruction-setst>>) with no auxiliary operands and the immediate for _State_ set to `ace_state_off` (as defined in <<ACE-State-field>>).

_Description_::
`ace.clear` unconfigures the state of the CR `Kd` or `K(Xd)` and releases its resources in the CRF.
+
`ace.reset` unconfigures all the CRs and the ACEIOBUF.
It uses the encoding of `ace.setst` described above with indirect CR addressing and `Xd` = `X0`.

_Properties_::
Possibly modifies state: `ace.clear` only makes any status flag (global of
per-CR) Dirty if the CR was configured before. Usage-controlled: *NO*. +
// Trappable: +
// ``{fournbsp}ace.clear``: *NO*; +
// ``{fournbsp}ace.reset``: *YES* (it can be implemented as multiple `ace.clear`
// and a write to `aceiobuflen`). +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getst]]
==== ace.getst

_Synopsis_::
Returns the _State_ field of the metadata of the source CR.
This is useful to determine whether a CR is in an Error State, as defined in <<ACE-State-field>>.

_Mnemonic_::
`ace.getst Xd, Ks|K(Xs)`
(((ACE, instruction, ace.getst)))

_Encoding_::
The operations is a pseudo-instruction.

_Description_::
`ace.getst` is implemented as a read of the source CR's metadata using `ace.getmd`
followed by instructions to extract the _State_ field of the latter.
For instance, on RV64, we can use:

 . `ace.getmd Xd, Ks` or `K(Xs)`
 . `srli  Xd, Xd, 20`
 . `andi  Xd, Xd, 0x1F`

//

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-available]]
==== ace.avail

_Synopsis_::
Verify whether an algorithm is supported, or the first 64 bits of a metadata block are valid.

_Mnemonic_::
`ace.avail Xd, Xs`
(((ACE, instruction, ace.avail)))

_Encoding_::
`ace.avail` is an alias to Form B of `ace.size`, as the latter returns 0 in case of error.

_Properties_::
Same as `ace.size`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-usage-input-output]]
=== Usage of `ace.input` and `ace.output` to Replace Vector Inputs and Outputs

When the vector register file is unavailable, any _Original Instruction_ listed in <<ACE-replacement-instructions>> may be replaced by the corresponding _Alternative Sequence_.

[[ACE-replacement-instructions]]
.alternative sequences for `ace.exec`, `ace.setst`, and ```ace.derive``` using `ace.input` and `ace.output`
[float="center",align="center",width="100%",cols="<20%,<41%,<39%",options="header"]
|===
| Instruction and Form | Original Instruction          | Alternative Sequence
| `ace.exec`, Form A   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K(Xn), Vs` | `1: ace.input{nbsp}{nbsp}Xl, %offset(Xs)` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
`3: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.exec`, Form B   | `ace.exec{fournbsp}{nbsp}{nbsp}Kn\|K(Xn), Vs`     | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
| `ace.exec`, Form C   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K(Xn)`     | `1: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
`2: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.setst`, Form C  | `ace.setst{nbsp}Kd\|K(Xd), #immed, Vs` | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.setst{nbsp}{nbsp}Kd\|K(Xd), #immed` +
| `ace.derive`, Form C | `ace.derive Kd\|K(Xd), Ks1\|K(Xs1), Vs2` | `1: ace.input{nbsp}{nbsp}%offset(Xs2), Xl` +
`2: ace.derive{nbsp}Kd\|K(Xd), Ks1\|K(Xs1)` +
|===

The sole functions of `ace.input` and `ace.output` are to supply inputs to cryptographic operations and to read out their outputs. No computation is performed on the data by these instructions. All computations and internal state changes of `ace.exec`, `ace.setst`, and `ace.derive` remain within those operations.

The usage and ordering of the alternative sequences are not enforced architecturally.
Thus, the caller may omit `ace.input` or `ace.output`, meaning that the contents of the ACEIOBUF are reused, or the output is ignored.
This does not expand the attack surface, since the caller always retains full control over the data passed to ACE instructions and their outputs.
Instead, the ACE architecture defines the following rules:

. A Form D `ace.exec` can be used whenever a Form of `ace.exec` with an input and/or an output is instead expected, i.e., any of the Forms A, B, or C `ace.exec`. The implementation shall automatically use the ACEIOBUF if `Zlio` is available, and raise an invalid instruction exception otherwise.

. A Form A `ace.exec` cannot be replaced by a Form B `ace.exec`, where the input is provided by a vector register but an output vector register is not defined, expecting that the output be written to the ACEIOBUF.
Any attempt to do so raises an invalid instruction exception

. A Form A `ace.exec` cannot be replaced by a Form C `ace.exec`, where the output is provided by a vector register but an input vector register is not defined, expecting that the input be read from the ACEIOBUF.
Any attempt to do so raises an invalid instruction exception

. Similarly, for `ace.setst`, if a vector input is expected (Form C `ace.setst`) and it is not provided, the implementation shall automatically use the ACEIOBUF if `Zlio` is available, and raise an invalid instruction exception otherwise. This instruction replacement is not allowed in the case of a Form B `ace.setst`, i.e., when the auxiliary input should come from a GPR, and an invalid instruction exception is raised regardless of whether `Zlio` is available.

. A Form A `ace.derive` can be used whenever a Form C `ace.derive` is expected. The implementation shall automatically use the ACEIOBUF if `Zlio` is available, and raise an invalid instruction exception otherwise.

. Form D `ace.exec` in place of its Forms A-C, Form A `ace.setst` in place of its Form C, and Form A `ace.derive` in place of its Form C
may be issued only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero. Else, exception `ace_exc_buf_unconf` is raised. If `aceiobuflen` is non-zero but the range size `aceiobuftop - acestart` is invalid for the algorithm, exception `ace_exc_invalid` is raised and no cryptographic operation is performed.

NOTE: It is because of these rules that, in the Algorithms, we write that a certain Form of `ace.exec` or `ace.setst` is _expected_ instead of _required_ (or _only [...] allowed_). The above substitutions are implicit in all algorithms and are not restated for each occurrence.

// ////////////////////////////////////////////////////////////////////

[[ACE-resumability]]
=== Resumability of ACE instructions

`ace.clear`, `ace.reset`, `ace.setst`, `ace.getst`, `ace.restrict`, `ace.clone`, `ace.size` and `ace.avail` are uninterruptible.
`ace.prov`, `ace.import`, `ace.export`, `ace.input`, and `ace.output` may be interrupted and resumed under certain conditions.
For `ace.prov`, `ace.import`, and `ace.export`, see <<ACE-provisioning-export-import>>.
For `ace.input` and `ace.output`, `acestart` may be used to reflect the amount of data read or written before the interrupt. In this case resumption will start from that point.

The operation of `ace.exec` on a basic processing unit is uninterruptible, unless explicitly allowed by the algorithm.
Most cryptographic primitives cannot be interrupted; therefore, state information to encode round number or round key value is not needed.
For certain very long running operations, such as public key primitives, an algorithm specific interruptibility and resumability behavior is defined.

When processing multiple blocks iteratively, `ace.exec` handles each block atomically, but it may be interrupted between blocks.
On an interrupt during block processing, the implementation may either complete the current block before yielding to the handler, or discard the partial computation and restore the state from before its processing.
`acestart` is updated accordingly to point at the place of resumption.

// ////////////////////////////////////////////////////////////////////
