[[ACE-separation]]
== Structure of the ACE ISA: Separation of Architecture and Data Formats

The ACE ISA is split into three Books:

. Book 1 of the ACE Architecture is the Unprivileged Architecture. The instructions can be defined without specifying the exact data formats they consume. This is the purpose of the present chapter (<<ACE-unpriv>>).
. Book 2 is the ISA-Orthogonal Data Structures and Algorithms Architecture, which in this document is contained in <<ACE-algorithms>>.  The actual data formats of the inputs used to provision, export and import keys are meant to be interoperable across different ISAs that implement the same functionality as ACE, so they should not be limited to Risc-V.  Similarly, the algorithms implemented by ACE, shall have a well defined behavior, and produce internal states that are exported in a compatible way across different ISAs. Implementing Book 1 in Risc-V requires full adherence to Book 2 as well.
. Book 3 is the Privileged Architecture (<<ACE-priv>>).

[[ACE-unpriv]]
== Book 1: Unprivileged Architecture

// Good judgment comes from experience.
// Experience comes from bad judgment.
// вЂ”MULLAH NASRUDIN, 1200s AD

=== Introduction

ACE relies on certain fundamental concepts, which are introduced here.
While this leads to some repetitions, it also brings better clarity to the presentation.

[[ACE-concepts]]
==== Fundamental Concepts and Definitions

Cryptographic Context:::
(((Cryptographic Context)))
The *Cryptographic Context* (CC) is the foundation of ACE. A CC is an indivisible structure consisting of a *Metadata* header and a *Content* section; all cryptographic operations performed by ACE execute within the constraints defined by a CC. The Metadata has a fixed format and specifies the cryptographic algorithm and various optional policies associated with the CC.
(((Cryptographic Context, Metadata)))
The Content has an algorithm-specific format and holds sensitive material such as keys and internal algorithm state.
(((Cryptographic Context, Content)))
The Metadata requires integrity; the Content requires both integrity and confidentiality.
These requirements are architecturally enforced by ACE and by the cryptographic algorithms it implements.

Context Register:::
(((Context Register)))
To create CCs, ACE uses *Context Registers* (CRs), per-hart architectural containers that safeguard their contents.
A CR is *provisioned* by writing Metadata and Content into it; this operation binds the latter to form a CC.
There is no store-like instruction to extract the Content of the CR in a manner that compromises its confidentiality.
A CC may be used for cryptographic operations only while resident in a CR. Only the ACE unit may access or modify a CC residing in a CR, in accordance with architectural rules and the algorithm bound to the CC.

Sealed Cryptographic Context:::
(((Cryptographic Context, sealed)))
To support context switching while at the same time protecting CCs outside architectural state, a CC may be *exported* from a CR as a *Sealed Cryptographic Context* (SCC), an encrypted and authenticated representation of a CC that can later be *imported* into a CR. SCC export and import use a _Context Sealing Key_ (CSK), which may be programmable by M-mode.
A CC sealed under one CSK cannot be re-imported under a different CSK, enabling cryptographic domain separation across spatial and temporal domains.

Object-Orientation:::
(((Cryptographic Context, object-oriented)))
CCs act as *objects* exposing a uniform interface across algorithms.
A CC encapsulates algorithm-specific behavior, enabling interchangeable use of different primitives (e.g., AES-128, AES-256, SM4) in identical modes (e.g., ECB, GCM-SIV, XTS) without requiring changes to compiled code.
Side-channel attack (SCA) resistant variants are supported transparently.

Usage Control Policy:::
(((Cryptographic Context, usage control)))
(((Cryptographic Context, management operations)))
(((Cryptographic Context, usage operations)))
ACE distinguishes between CC/CR *management* and *usage* operations.
(((Cryptographic Context, export)))
Management operations include *configuration* (e.g., CR provisioning, SCC import, and cloning) and *export* of a CR as an SCC. Usage operations include cryptographic operations and state changes.
(((Cryptographic Context, access)))
All operations represent a form of *access* to CRs.
To prevent denial-of-service scenarios, management operations, in particular configuration operations, are far less restricted than usage operations. _Usage Control_ policies restrict only certain CC/CR usage operations.

Localities:::
(((Cryptographic Context, Locality)))
ACE can bind CCs to a *Localities*, i.e., restrict usage to specific devices or device classes, hardware configurations, physical or virtual boot cycles, and process domains at various privilege modes. This binding is achieved by using the Localities as _tweaks_ in the encryption and decryption of SCCs.

// ////////////////////////////////////////////////////////////////////

[[ACE-architectural-model]]
==== Architectural Model

ACE is architected as an _attached_ unit, meaning that ACE instructions act as messages across a tightly coupled coprocessor interface.
The ACE unit receives the operations from the hart, executes them independently of the issuing hart, and returns results.

Beside implementations of ACE within a CPU core, this model also allows a single hardware instance of the ACE unit to be shared by multiple cores, with separate architectural states for each client hart.  The specification mandates only behavior, not implementation.

The ACE unit may lock certain architectural statesвЂ”e.g., Vector Registers, CRs, and CSRs.
The hart stalls when attempting to read them until the ACE operation using those resources completes.

This design allows a certain level of concurrency.
Long-running ACE operations may proceed even if the hart is preempted.
//For example, consider a UвЂ‘mode process executing an ACE instruction.
In this case, when the contextвЂ‘switch handler accesses a locked register, different behaviors are allowed:
the hart may wait for the operation to finish;
the implementation may adopt a precise exception model, whereby the ACE unit is halted and sets `acestart` to allow later resumption;
or the system may impose a timeout before halting.
The architecture permits all these approaches.
It only specifies the allowed interruption points for its instructions and algorithms.

Conceptually, for each of the 32 CRs, ACE maintains a full 128-bit Metadata Header and an offset into internal memory pointing to the CR's Content (if not empty). The Metadata Header indicates whether a CR is configured. The actual representation of CRs in a concrete implementation may differ significantly.

// ////////////////////////////////////////////////////////////////////

[[ACE-extensions-overview-unpriv]]
=== Extensions Overview

[%header,cols="15%,47%,18%,10%,10%"]
|===
| Extension       | Features                                                                                                            | Defined in:                                    | Minimum version | Lifecycle state
| `Zlv`           | ACE with support for vector registers.^1^                                                                           | <<ACE-instructions-detailed>>                  | v0.0.0          | --
| `Zlio`          | ACE with support for `ace.input` and `ace.output`.^2^                                                               | <<ACE-usage-input-output>>                     | v0.0.0          | --
| `Zlaes128p`     | AES-128 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes192p`     | AES-192 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes256p`     | AES-256 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlsm4p`        | ShangMi 4 encryption/decryption.^3^                                                                                 | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlctrm`        | CTR and CTR with set initial counter.^4^                                                                            | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxctrm`       | XCTR and XCTR with set initial counter.^4^                                                                          | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxexm`        | XEX construction.^5^                                                                                                | <<ACE-XEX-XTS-modes>>                          | v0.0.0          | --
| `Zlgcmm`        | GCM and GCM with set IV.^4^                                                                                         | <<ACE-GCM-mode>>                               | v0.0.0          | --
| `Zlgcmsivm`     | GCM-SIV.^4^                                                                                                         | <<ACE-GCM-SIV-mode>>                           | v0.0.0          | --
| `Zlocbm`        | OCB3 and OCB3 with set IV.^5^                                                                                       | <<ACE-OCB-mode>>                               | v0.0.0          | --
| `Zlcmacm`       | CMAC.^4^                                                                                                            | <<ACE-CMAC-mode>>                              | v0.0.0          | --
| `Zlesha2h`      | SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, and SHA-512/256.                                                   | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlesha3h`      | SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128, and SHAKE256.                                                     | <<ACE-SHA-3>>                                  | v0.0.0          | --
| `Zlsm3h`        | ShangMi 3 (SM3) hash function.                                                                                      | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlhmacm`       | HMAC function with hidden key (with SHA2 when `Zlesha2h` is supported, and with SHA3 when `Zlesha3h` is supported). | TBD                                            | v0.0.0          | --
| `Zlkmacm`       | KMAC function with hidden key. Depends on `Zlesha3h`, since KMAC is only defined with SHA3.                         | TBD                                            | v0.0.0          | --
| `Zlascon`       | Ascon-AEAD128 (base, with set Nonce, or with Nonce Masking), Ascon-Hash256, Ascon-XOF128 and Ascon-CXOF128.         | <<ACE-Ascon-AEAD128>> to <<ACE-Ascon-CXOF128>> | v0.0.0          | --
4+| _Point arithmetic and signature generation and verification algorithms for curves in various standards:_                      | {empty}
| `Zlsecp256r1c`  | -- NIST curve secp256r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp384r1c`  | -- NIST curve secp384r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp521r1c`  | -- NIST curve secp521r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled25519c`    | -- Edwards curve ed25519.                                                                                           | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled448c`      | -- Edwards curve ed448.                                                                                             | <<ACE-ECC>>                                    | v0.0.0          | --
| `ZlbpP256r1c`   | -- Brainpool curve brainpoolP256r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlbpP384r1c`   | -- Brainpool curve brainpoolP384r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlbpP512r1c`   | -- Brainpool curve brainpoolP512r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlSM2c`        | -- Chinese 256-bit SM2 curve.                                                                                       | TBD                                            | v0.0.0          | --
| `Zlkn`        2+| NIST Symmetric Suite. Depends on `Zlaes128`, `Zlaes256`, `Zlesha2`, `Zlgcmm`, `Zlxexm`, and `Zlgcmsivm`.          | v0.0.0                                         | --
5+| ^1^ Requires V (or a suitable subset thereof). Must support the following CSRs: `acestart` (this is a dependency for Zicsr); must support the following instructions: `ace.prov`, all four forms of `ace.exec`, `ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size` (and thus `ace.avail`), and `ace.restrict`; must support `Zlkn`.
5+| ^2^ Must support the following CSRs: `acestart` (this is a dependency for Zicsr), `aceiobuflen` and `aceiobuftop`; must support the following instructions: `ace.prov`, Form D of `ace.exec`, `ace.input` and `ace.output`, `ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size` (and thus `ace.avail`), and `ace.restrict`; must support `Zlkn`.
5+| ^3^ Beside defining the basic encryption and decryption operations, these extensions also select which ciphers can be used with the various modes of operations that follow.
5+| ^4^ The mode is applicable to all versions of AES and to SM4.
5+| ^5^ The mode is applicable to all versions of AES.
|===

At least one of `Zlv` or `Zlio` must be implemented.

// ////////////////////////////////////////////////////////////////////

=== Programmer-Visible Architectural State

[[ACE-cryptographic-registers]]
==== Context Registers

{empty}
(((Cryptographic Context)))
ACE defines 32 Context Registers (CRs), numbered 0 to 31 and denoted `K0`вЂ“`K31`.

CRs are architectural state, i.e., per-hart, like the GPRs or the vector registers.

Unlike a conventional register, a CR can be _unconfigured_, meaning it does not contain a CC.

A CR is addressed directly, as a 5-bit immediate, or indirectly, via a GPR value.
An additional instruction-encoding bit is used to select how the CR is addressed.
Accessing a CR with an indirect index outside [0..31] raises an illegal instruction exception.

An implementation must wait before accessing a CR that is still being written to asynchronously.

[NOTE]
====
Indirect CR addressing also an important microarchitectural implication.
Supporting CR renaming is possible but would significantly increase microarchitectural complexity.
CRs are redefined far less frequently than GPRs or FP registers (excluding implicit internal state changes).
Hence, CR renaming is not expected to significantly affect performance.
====

(((Context Register File)))
CRs reside in a dedicated, per-hart _CR file_ (CRF) accessible only to the ACE implementation. This memory shall guarantee
confidentiality and integrity of its contents, including the inability for an attacker to roll-back the latter to a previous state.
We do not require that accesses to this memory are hardened against physical side-channel attacks at the hardware level,
however, the implementation of side-channel protected algorithms in the ACE unit shall provide resistance to such attacks as well.

The amount of CRF capacity consumed by each CR depends on the algorithm encoded in the metadata, and it may differ from one CR to another.

Insufficient residual CRF capacity may prevent execution of a configuration instruction (`ace.prov`, `ace.import`, `ace.clone`):
Capacity is freed by unconfiguring other CRs.

The CRF capacity is implementation-defined. Implementations shall provide sufficient
capacity for all supported operations. At a minimum, the CRF must hold the
largest possible single CR, or the largest CR pair used in cloning operations.
An optional, implementation-specific mechanism for estimating required capacity
is described in <<ACE-instruction-size>>.

Any corruption of the CRF associated with a hart shall cause an unrecoverable error condition.
The entire architectural state of the ACE unit associated with the hart is reset, and exception `ace_guru_meditation` is raised (cf. <<ACE-exceptions>>).

We list the most important operations on CRs, so we can refer to them before they are fully defined.

* `ace.prov` (<<ACE-instruction-init>>) loads metadata and plaintext Content into a CR, binding them together.
* `ace.clear` (<<ACE-instruction-clear>>) unconfigures and clears a CR.
* `ace.export` (<<ACE-instruction-export>>) exports a CR to memory as an SCC.
* `ace.import` (<<ACE-instruction-import>>) imports a SCC into a CR.
* `ace.exec` (<<ACE-instruction-exec>>) performs cryptographic operations as specified by the algorithm configured in a CR and according to the state of the CR.
* `ace.setst` (<<ACE-instruction-setst>>) transitions between states of a cryptographic algorithm.
//* `ace.getmd` (<<ACE-instruction-getmd>>) reads the metadata of a CR.
* `ace.clone` (<<ACE-instruction-clone>>) creates a copy of a CR into a second CR.

// ////////////////////////////////////////////////////////////////////

==== Inputs and Outputs, RVV-mini

ACE inputs and outputs may use vector registers or an architectural input/output buffer (ACEIOBUF)
that can be loaded from and stored to external memory. Both mechanisms may be supported simultaneously.

When vector registers are used, the full V extension is not required. ACE depends only on a minimal subset, termed _RVV-mini_.
(((RVV-mini)))
RVV-mini must be fully opcode-compatible with RVV: code written for RVV-mini must execute with identical behavior under RVV. The required features are:

* Vector registers wide enough to support the inputs and outputs of the implemented algorithms;
* The `vsetvli` instruction with restricted parameters (e.g., `vsetvli zero,4,e32,m1,ta,ma` for 128-bit operations);
  unsupported configurations must raise an illegal instruction exception;
* Unit-strided vector loads and stores; and
* Vector bitwise logical operations: `vxor`, `vand`, and `vor`.

ACE instructions (currently) do not use vector masking and do not define masked versions of `ace.exec`.
Therefore, the algorithms currently defined require unmasked inputs and outputs.

Floating-point, fixed-point, and general arithmetic vector operations are not required.
Complex operations for certain cryptographic algorithms may be performed in GPRs, with data inserted into vector registers and result
extracted from them via `vins`/`vext`.

[WARNING]
RVV-mini need not be finalized before ACE ratification begins; it
may be defined later, and the ACE specification amended accordingly.
This allows additional requirements to be collected, for example, whether to mandate
`vclmul.v[vx]` and `vclmulh.v[vx]` from `Zvbc`.

The optional per-hart input/output buffer (ACEIOBUF) may be used in place of vector registers.
The ACEIOBUF is not part of the CRF.
Instructions `ace.input` and `ace.output` are used to write inputs to the ACEIOBUF and read outputs from it.
When the ACEIOBUF is used in place of vector registers, instructions `ace.exec` and `ace.setst` that use vector registers are replaced by instruction sequences  as described in <<ACE-usage-input-output>>.

To determine the lengths of the inputs and outputs of its operations when the vector registers are used, ACE uses `VL*SEW`.
The actual choice of `VL` and `SEW` is not significant. For instance, both `VL`=2, `SEW`=64 and `VL`=4, `SEW`=32 define a 128-bit input.
The CPU instruction-decoding side of ACE uses `VL` and `SEW` to determine the amount of data to send to the ACE unit proper.
The ACE unit itself only needs the product `VL*SEW` (or `aceiobuftop`) for its functionality.

// ////////////////////////////////////////////////////////////////////

[[ACE-metadata-short]]
==== Metadata

The Data Formats and Algorithms specification (<<ACE-algorithms>>) defines a 128-bit metadata block.
We mentions here the fields that the instructions directly depend upon.
The detailed description of these fields is given in <<ACE-Metadata>>.

[[ACE-metadata-section-summary]]
.Summary of the Fields of Metadata Header
[width="100%",cols="15%,85%",options="header"]
|===
| Name              | Description
| _Algorithm_       | Cryptographic algorithm (primitive, mode, or protocol).
| _AlgorithmPolicy_ | Allowed algorithm variants(s) _or_ extension of the _Algorithm_ field.
| _SCProtection_    | Side-channel protection level.
| _KeyType_         | 0: key is an explicit value in Content. 1: key is an index into the system-specific System Keys Table (SKT).
| _State_           | Current state of the CR/algorithm, encoded as an integer.
This includes also value signifying: _Off_ (0), i.e., that the CR is not configured, and certain Error States (<<ACE-states-error>>).
| _Sequence_        | Tracks the progress in the replacement sequence of an `ace.exec` or `ace.setst` instruction. The `aceactivecr` CSR must match the CR number.
| _UsagePolicy_     | Usage (Control) Policy. Bits 0, 1, 2, 4 and 4 of the field,, when set, disallow CC usage in U-mode, (V)S-mode, H-mode, M-Mode, and Debug mode, respectively.
| _Locality_        | Zero, or an index determining a Locality Secret.
| _VarDataLen_      | If non-zero, indicates an additional variable-length data section appended to the Content. The length of this section is _VarDataLen_ * 16 bytes (up to 512 KiB).
| _ExpirationDate_  | If non-zero, the expiration date of this CC.
|===

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-unpriv]]
==== CSRs

ACE provides a number of unprivileged CSRs.
// The privileged CSRs are documented in <<ACE-priv>>.

[[ACE-CSRs-unpriv]]
.ACE Unprivileged CSRs.
[cols="^10%,^10%,<18%,<62%"]
[float="center",options="header"]
|===
|  Address | Privilege | Field            | Description
|  0xXXX   |  RO       | `acemarchid`     | ID of the microarchitecture of the ACE unit.
| `vstart` | URW       | `acestart`       | ACE start bit index.
|  0xXXX   | URW       | `aceiobuflen`    | ACE input/output buffer length.
|  0xXXX   |  RO       | `acemaxiobuflen` | ACE maximum input/output buffer length. Read only.
|  0xXXX   | URW       | `aceiobuftop`    | ACE input/output buffer limit for current transfers.
|  0xXXX   | URW       | `aceactivecr`    | Active CR for `ace.input`/`ace.output`.
|===

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acemarchid]]
===== `acemarchid`

{empty}
(((CSR, `acemarchid`)))
`acemarchid` identifies the microarchitectural version of the ACE unit, analogously to `marchid` for the hart.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acestart]]
===== `acestart`

{empty}
(((CSR, `acestart`)))
`acestart` is an alias for `vstart`. Therefore, it is an XLEN-bit RW CSR.
ACE defines it also when the V extension is not enabled.

`acestart` tracks the progress of interruptible ACE instructions, namely
`ace.prov`, `ace.import`, `ace.export`, `ace.input`, and `ace.output`. It also
applies to `ace.exec` when iteratively processing a multi-block operand, as
`ace.exec` may be interrupted between blocks. Only these instructions honor a
nonzero `acestart`; all other instructions ignore it and are restarted, with
`acestart` also being cleared. Provisioning, import, and export are
resumed only under certain conditions, as explained in
<<ACE-provisioning-export-import>>.

`acestart` records the progress of an interrupted operation.
Since ACE does not have an _intrinsic_ concept of element length, `acestart` counts the number of bits processed so far, not the number of elements.

Hardware writes this register on interruption.
Software may save and restore the register across context switches.
For certain algorithms, writing zero to `acestart` to force a full restart of `ace.exec` may lead to inconsistent or unpredictable results.
Writing an invalid or non-supported nonzero value raises an illegal instruction exception.

When a vector instruction is interrupted, the CSR follows `vstart` semantics as expected, i.e., it counts the number of processed elements.
When an ACE instruction is interrupted, the CSR follows the `acestart` semantics described here.

[WARNING]
The reason `vstart` can be reused as `acestart` comes from the fact that the Risc-V ISA exposes a computation model in which the observable results are the same as if the instructions were executed in order.
If an implementation has executed instructions past the PC when an interrupt occurs, those instructions are discarded and must be reвЂ‘executed upon return from the handler. Only the instruction at the PC may be interrupted in a way that it saves temporary state that allows it to be resumed later.
There is no situation in which the microarchitecture of a hart can simultaneously interrupt multiple instructions allowing them to resume at the same time.
Hence, `vstart` can safely be reused by ACE as `acestart`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acemaxiobuflen]]
===== `acemaxiobuflen`

{empty}
(((CSR, `acemaxiobuflen`)))
`acemaxiobuflen` is an XLEN-bit RO CSR that reports the maximum configurable length of the ACEIOBUF.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuflen]]
===== `aceiobuflen`

{empty}
(((CSR, `aceiobuflen`)))
`aceiobuflen` is an XLEN-bit URW CSR that programs the ACEIOBUF length in bits for use by `ace.input` and `ace.output`.
Writing this register-even when re-writing the current value-also zeroes the buffer and sets `aceiobuftop` to the same length and `acestart` to zero.

When `aceiobuflen` is zero, the ACEIOBUF is _unconfigured_.
Attempting to execute an operation that expects an input or an output in the ACEIOBUF while the latter is unconfigured raises exception `ace_exc_buf_unconf`.

Writing a value larger than `acemaxiobuflen` raises exception `ace_exc_out_of_mem`.

As per the Privileged Architecture, the dirtiness of the ACEIOBUF is not tracked except as part of the entire ACE state in `*status`.
Context switching code is expected to save and restore the contents of the ACEIOBUF up to `aceiobuflen`.
We recommend software to set `aceiobuflen` to zero once the contents of the ACEIOBUF are no longer needed.
Context switching code can use this information to avoid unnecessary save and restore of ACEIOBUF contents.


_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuftop]]
===== `aceiobuftop`

{empty}
(((CSR, `aceiobuftop`)))
`aceiobuftop` is an XLEN-bit URW CSR that marks the upper bound in bits of the buffer range used by `ace.input` and `ace.output`.
Together with `acestart`, it defines the active transfer window.

The constraints `acestart` {le} `aceiobuftop` {le} `aceiobuflen` must hold.
Violating either bound raises an illegal instruction exception.
Modifying `aceiobuftop` does not modify buffer contents.

NOTE: `aceiobuftop` enables per-operation length adjustments without the need to reconfigure the ACEIOBUF using `aceiobuflen`, which can be expensive due to the fact that it clears the buffer and may lead to internal garbage collection.
This can be used similarly to the reconfiguration of `VL*SEW` to provide an partial вЂњlast blockвЂќ or to supply a short IV/nonce to cryptographic algorithms.

Using a replacement sequence for `ace.exec` or `ace.setst` for any Form with an input or output
when `aceiobuftop` в€’ `acestart` is zero (and `aceiobuflen` nonzero) will result in no operation being performed.

Using ACEIOBUF when `aceiobuftop` в€’ `acestart` is an invalid length raises an illegal instruction exception.

Since context switching code saves and restores the contents of the ACEIOBUF up to `aceiobuflen`, the contents between `aceiobuftop` and `aceiobuflen` are preserved.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceactivecr]]
===== `aceactivecr`

{empty}
(((CSR, `aceactivecr`)))
`aceactivecr` is an XLEN-bit URW CSR; only the low 5 bits are defined.
It binds `ace.input`, `ace.output`, `ace.exec`, and `ace.setst` to a specific CR.
The valid values are 0вЂ“31, which are used to bind to a CR, or 32, which disables any such binding.

When `aceactivecr` is not 32, the CR operand in all single-CR instructions and the source CR in `ace.clone` must equal the selected value, and the
_Sequence_ metadata field of that CR must track the operation in an instruction replacement sequence.

// At any given moment, only one _Sequence_ field in the Metadata Sections of all CRs may be non-zero, and `aceactivecr` must match the number of that CR.

Any deviation from these behaviors raises an illegal instruction exception.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

//

// ////////////////////////////////////////////////////////////////////

[[ACE-instructions-detailed]]
=== Instructions

[WARNING]
====
The encodings presented here are preliminary.
====

ACE provides a number of unprivileged instructions.
This section specifies their semantics and encodings.

The notation `K(Xd)` denotes the CR whose index is held in GPR `Xd`. `Kn|K(Xn)`
indicates two alternative encodings: a 5-bit immediate CR index (`Kn`) or a CR
number supplied by GPR `Xn`. Use of the zero register `X0` as a CR index
register raises an illegal instruction exception unless explicitly indicated
otherwise.

Each instruction is characterized by the following properties:

* _Modifies state_: whether the instruction may modify ACE architectural state;
* _Usage-controlled_: whether the instruction is subject to usage control
  policies (_UsagePolicy_);
// * Trappable: whether the instruction may be implemented by privileged code
//   via trap-and-emulate; and
// * _Interruptible_: whether execution may be interrupted (e.g., by a context
//   switch or page fault) and later resumed or restarted.

NOTE: Trappability refers solely to the CPU-side implementationвЂ”for example, to
enable decomposition of certain ACE instructions into smaller custom
operations. This is distinct from custom algorithm implementations within the
ACE unit itself (e.g., via a secure embedded CPU with updatable firmware),
which are outside the scope of this specification.

NOTE: ACE does not have concepts of
Element Group Width, Effective Element Width,
and
Element Group Size like the vector crypto extension.
Because of the fact that the architecture decouples instructions like `ace.exec` from the
actual operations, the high level architecture of ACE only needs to know the total size
of the inputs and output, which is `ACELEN`, namely either `VL*SEW` or the length
`aceiobuftop` of the ACEIOBUF as defined in <<ACE-notation>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-init]]
==== ace.prov

_Synopsis_::
Provision Metadata and secrets into a CR.

_Mnemonic_::
`ace.prov Kd|K(Xd), %offset(Xs)`
(((ACE, instruction, ace.prov)))

_Encoding_::
`ace.prov` is an I-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x0b, attr: ['custom-0'] },
    { bits:  5, name: 'context', attr: ['Kd','K(Xd)'] },
    { bits:  3, name: 'ace.prov', attr: [0x4,0x5] },
    { bits:  5, name: 'Xs' },
    { bits: 12, name: 'immed12', attr: ['offset'] },
]}
....

_Description_::
`ace.prov` provisions a CR with Metadata and Content to create a CC. `Kd` or
`K(Xd)` denotes the CR to be provisioned. `Xs` points to the region of memory
containing the Metadata and the key material. The PI must be stored at an
8-byte aligned address.
+
If the instruction fails, the target CR is unconfigured, with the same
semantics as if `ace.clear` were invoked on the same CR
(<<ACE-instruction-clear>>).
+
If the combination of _Algorithm_, _AlgorithmPolicy_, and _SCProtection_ is not supported, exception `ace_exc_invalid` may be raised as defined in the Privileged Architecture.
The handler may simply set the CR to error state `ace_state_not_impl` and return to the original control flow.
+
Exception `ace_exc_invalid` is raised if the Metadata is invalid (other
than unimplemented algorithm), such as, for instance: a nonzero _State_ or
reserved field; or an unsupported _Locality_ value.
The handler may simply set the CR to error state `ace_state_invalid` and
return to the original control flow.
+
Similarly to vector load instructions, `ace.prov` appears to other harts as a sequence of individual loads.
+
The operation is described in detail in <<ACE-provisioning-export-import>>.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
//Trappable: *YES*. +
//Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

NOTE: `ace.prov`, like `ace.import`, `ace.export`, `ace.input`, and
`ace.output`, which are described later, can be viewed as special kinds of load
and store instructions, and therefore they do not violate the load/store
architecture principle.

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clear]]
==== ace.clear/ace.reset

_Synopsis_::
Clears and unconfigures a CR, or the ACE state.

_Mnemonic_::
`ace.clear Kd|K(Xd)` +
(((ACE, instruction, ace.clear)))
`ace.reset`
(((ACE, instruction, ace.reset)))

_Encoding_::
`ace.clear`/`ace.reset` are pseudo instructions, implemented as `ace.setst` (see <<ACE-instruction-setst>>) with no auxiliary operands, and the immediate for _State_ set to `ace_state_off` (as defined in <<ACE-State-field>>, i.e., 0).

_Description_::
`ace.clear` unconfigures the state of the CR `Kd` or `K(Xd)` and releases its resources in the CRF.
+
`ace.reset` unconfigures all the CRs and the ACEIOBUF.
It uses the encoding of `ace.setst` described above with indirect CR addressing and `Xd` = `X0`.

_Properties_::
Possibly modifies state: `ace.clear` only makes any status flag (global of
per-CR) Dirty if the CR was configured before. Usage-controlled: *NO*. +
// Trappable: +
// ``{fournbsp}ace.clear``: *NO*; +
// ``{fournbsp}ace.reset``: *YES* (it can be implemented as multiple `ace.clear`
// and a write to `aceiobuflen`). +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-export]]
==== ace.export

_Synopsis_::
Export a CR as a SCC in memory.

_Mnemonic_::
`ace.export %offset(Xd), Ks|K(Xs)`
(((ACE, instruction, ace.export)))

_Encoding_::
`ace.export` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 'ace.export', attr: [0x0,0x1] },
    { bits:  5, name: 'Xd' },
    { bits:  5, name: 'context', attr: ['Ks','K(Xs)'] },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Description_::
Exports the CR `Ks` or `K(Xs)` to memory at address `Xd`, using the procedure
described in <<ACE-provisioning-export-import>>. The SCC must be stored at an
8-byte aligned address.
+
`ace.export` appears to other harts as a sequence of individual stores.
+
The operation is described in detail in <<ACE-provisioning-export-import>>.

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +
// Trappable: *YES*. +
// Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-import]]
==== ace.import/ace.import.S

_Synopsis_::
Import a SCC from memory into a CR.

_Mnemonics_::
`ace.import{nbsp}{nbsp}{nbsp}Kd|K(Xd), %offset(Xn)` +
`ace.import.S{nbsp}Kd|K(Xd), %offset(Xn)`
(((ACE, instruction, ace.import)))
(((ACE, instruction, ace.import.S)))

_Encoding_::
`ace.import` is an I- (or R-) type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x0b, attr: ['custom-0'] },
    { bits:  5, name: 'context', attr: ['Kd','K(Xd)'] },
    { bits:  3, name: 'ace.import', attr: ['0В В В В 0В В В В S','0В В В В 1В В В В S'] },
    { bits:  5, name: 'Xn' },
    { bits: 12, name: 'immed12' },
]}
....

_Description_::
`Kd` or `K(Xd)` denotes the CR into which the SCC is to be imported. `Xn` is
the GPR containing the base address of the buffer with the source SCC. The SCC
base address must be 8-byte aligned.
+
If the instruction fails, the target CR is unconfigured, with the same
semantics as if `ace.clear` were invoked on the same CR
(<<ACE-instruction-clear>>).
+
If the combination of _Algorithm_,
_AlgorithmPolicy_, and _SCProtection_ is not supported, exception `ace_exc_invalid` may be raised as defined in the Privileged Architecture.
The handler may simply set the CR to error state `ace_state_not_impl` and return to the original control flow.
+
Exception `ace_exc_invalid` is raised if the Metadata is invalid (other than unimplemented algorithm), such as, for instance: nonzero bits in reserved fields;
unsupported _Locality_ value;
or a value of _State_ which is not allowed by the current _Algorithm_ and _AlgorithmPolicy_.
+
The bit S takes the values 0 (false) or 1 (true). It is set to true if the key
is in a system-defined format (`ace.import.S`) and not the format defined by
the present architecture (`ace.import`).
+
`ace.import` appears to other harts as a sequence of individual loads.
+
The operation of `ace.import` is described in detail in
<<ACE-provisioning-export-import>>.
+
The behavior of `ace.import.S` is implementation-defined. If there are no
system-defined formats, `ace.import.S` raises an illegal instruction exception.

NOTE: The instruction encoding includes a single bit to indicate a
system-defined format. If multiple system-defined formats are supported, the
system is responsible for distinguishing them. These formats do not necessarily
include the key value itself, they may contain a вЂњrecipeвЂќ for an
implementation-defined mechanism to generate the key. Such system generated
keys are system-specific and the вЂњrecipeвЂќ is in general not portable. After
internal key generation, the actual key valueвЂ”not the recipeвЂ”is stored in the
CR and SCC. For all keys provisioned using `ace.import.S`, the _KeyType_ field
in the Metadata is 0, denoting a key represented by value.

NOTE: The `ace.export` instruction does not have an `ace.export.S` analog to
`ace.import.S`. This means that system-specific dynamically generated keys can
be imported but not exported in the same form: they must be exported in the
format architected here for ACE CCs.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
// Trappable: *YES*. +
// Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-exec]]
==== ace.exec

_Synopsis_::
Perform a cryptographic operation in the ACE unit.

_Mnemonic_::
The `ace.exec` instruction admits four Forms, namely
(((ACE, instruction, ace.exec)))

[upperalpha]
. `ace.exec  Vd, Kn|K(Xn), Vs` {nbsp}{nbsp} takes an input vector and writes to an output vector.
. `ace.exec  {nbsp}{nbsp}{nbsp}{nbsp}Kn|K(Xn), Vs` {nbsp}{nbsp} takes an input vector but does not write to an output vector.
. `ace.exec  Vd, Kn|K(Xn){nbsp}{nbsp}{nbsp}{nbsp}` {nbsp}{nbsp} does not take an input but writes to an output vector.
. `ace.exec  {nbsp}{nbsp}{nbsp}{nbsp}Kn|K(Xn){nbsp}{nbsp}{nbsp}{nbsp}` {nbsp}{nbsp} does not take an input vector and does not write to an output vector.

// Without this comment, the next part is not properly formatted...

_Encoding_::
`ace.exec` is an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'rd', attr: ['Vd','вЂ”','Vd','вЂ”'] },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Kn|K(Xn)'] },
    { bits:  5, name: 'rs2', attr: ['Vs','Vs','вЂ”','вЂ”'] },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 'Form', attr: ['0В В В В 0','0В В В В 1','1В В В В 0','1В В В В 1'] },
    { bits:  2, name: 0x0 },
]}
....
+
Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an
immediate, and it takes the value 1 if a GPR (scalar integer value) is used to
reference it.
+
For the four Forms AвЂ“D above, the encodings are:
+
[upperalpha]
. `Form` = `0b00`.
. `Form` = `0b01` and `rd` = `0b00000`.
. `Form` = `0b10` and `rs2` = `0b00000`.
. `Form` = `0b11` and `rs2` = `rd` = `0b00000`.

// To make indent in next line correct

_Description_::
Performs a cryptographic operation such as an encryption or decryption,
absorbing a value in a hash, an elliptic curve point addition or scalar
multiplication, etc., and possibly returning a value.
+
If the V extension register file is not implemented, only Form D `ace.exec`
is supported and `ace.input`, `ace.output` are used to provide inputs and
extract outputs from `ace.exec`, as described in <<ACE-usage-input-output>>.

// As a rule,

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *NO*. +
// Interruptible: See interruptibility rules in <<ACE-generic-rules>>. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv` (Forms A-D)    | v0.0.0          | --
| `Zlio` (Forms D)     | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-setst]]
==== ace.setst

_Synopsis_::
Change the state of the algorithm encoded in the CC in a CR.

_Mnemonic_::
The `ace.setst` instruction admits three Forms, namely
(((ACE, instruction, ace.setst)))

[upperalpha]
. `ace.setst Kd|K(Xd), #immed7{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.setst Kd|K(Xd), #immed7, Xs{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.setst Kd|K(Xd), #immed7, Vs{nbsp}{nbsp}` with an auxiliary input in a vector register.

//

_Encoding_::
`ace.setst` is an R-type instruction.
+
[wavedrom, ,svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 'ace.setst', attr: ['0В В В В 0В В В В 1','0В В В В 1В В В В 0','0В В В В 1В В В В 1'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'rs1', attr: ['вЂ”','Xs','Vs'] },
    { bits:  7, name: 'immed7' },
]}
....
+
The encodings for the three Forms are:
[upperalpha]
. `ace.setst` = `0b001`.
. `ace.setst` = `0b010`.
. `ace.setst` = `0b011`.

// ////////////////////////////////////////////////////////////////////

_Description_::
+
--
The instruction is used to modify the _State_ field of the metadata of the CR `Kd` or `K(Xd)`.
This can be used to move from one stage of an algorithm to another-for example, advancing from initialization to data absorption in a hash function, then to finalization and output of the digest.

The `#immed` operand is a constant from a set of admissible values defined for each algorithm. Optionally, `Xs` or `Vs` contain an auxiliary input.

If the `#immed` is zero, i.e., the value corresponding to the _Off_ state, the CR is cleared.

It is always allowed to use an error state (see <<ACE-states-error>>) for the
`#immed`. This will also invalidate the contents of the CR and possibly release them.
Setting an error state does _not_ however trigger an exception, even if reaching
that state implicitly would normally do. This does not prevent further usage of
the same CR from raising exceptions (for instance by issuing an `ace.exec` instruction later).

In the last two cases, the CRF capacity used by the Content of the CR
may also be released, including any additional variable-length data, in which case the
_VarDataLen_ metadata field will be set to zero.
--
+

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

// The state numbers used in this specification are defined in <<ACE-states-valid>> and <<ACE-state-constants-symmetric>>.

It is allowed to repeat `ace.setst` instructions to the current state. When the
algorithm needs to prevent this, it will automatically transition to a
different state after completing `ace.setst`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
| Extension | Minimum version | Lifecycle state
| `Zlv`     | v0.0.0          | --
| `Zlio`    | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getmd]]
==== ace.getmd

_Synopsis_::
Read the Metadata Header of a CR.

_Mnemonic_::
`ace.getmd Xd, Ks|K(Xs)`
(((ACE, instruction, ace.getmd)))

_Encoding_::
`ace.getmd` is an R-type instruction and its encoding is a variant of Form C `ace.exec`.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Ks|K(Xs)'] },
    { bits:  5, name: 0x00  },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 0x2 },
    { bits:  1, name: 0x1 },
    { bits:  1, name: 0x0 },
]}
....
+
Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an
immediate, and it takes the value 1 if a GPR (scalar integer value) is used to
reference it. The instruction differs from Form C `ace.exec` in two ways: the
destination is a GPR and Bit 30 is set to 1.

_Description_::
+
--
On RV64, `d` must be even.
The instruction copies bits [63:0] of
the Metadata Header of a CR `Ks` or `K(Xs)` into GPR `Xd`.
and bits [126:64] into GPR `X[d+1]`.

On RV32, `d` must be a multiple of 4.
The instruction copies bits [31:0] of the Metadata Header of a CR `Ks` or `K(Xs)` into GPR `Xd`.
bits [63:32] into GPR `X[d+1]`,
bits [95:64] into GPR `X[d+2]`,
and bits [127:96] into GPR `X[d+3]`.
--
+

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getst]]
==== ace.getst

_Synopsis_::
Returns the _State_ field of the metadata of the source CR.
This is useful to determine whether a CR is in an error state, as defined in <<ACE-State-field>>.

_Mnemonic_::
`ace.getst Xd, Ks|K(Xs)`
(((ACE, instruction, ace.getst)))

_Encoding_::
The operations is a pseudo-instruction.

_Description_::
`ace.getst` is implemented as a read of the source CR's metadata using `ace.getmd`
followed by logical or bit manipulation instructions to extract the _State_ field of the latter.
Onb RV64, the operations are, essentially:

 . `ace.getmd Xd, Ks` or `K(Xs)`
 . `srli  Xd, Xd, 20`
 . `andi  Xd, Xd, 0x1F`

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-restrict]]
==== ace.restrict

_Synopsis_::
Restrict the policies encoded in a CC in a CR.

_Mnemonic_::
`ace.restrict{nbsp}{nbsp}Kd|K(Xd), Xs1`
// `ace.restrict{nbsp}{nbsp}Kd|K(Xd), Xs1, Xs2`
(((ACE, instruction, ace.restrict)))

// Without this comment, the next part is not properly formatted...
_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 equal to 1 and
`func2` equal to 1. It is thus an R-type instruction. The source register field
encodes a GPR and not a vector register.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'Xs1' },
    { bits:  1, name: 0x1 },
    { bits:  1, name: 'r' },
    { bits:  3, name: 0x0 },
    { bits:  2, name: 0x1, attr: ['func2'] },
]}
....
+
Bit r (i.e., bit 26) takes the value 0 if the context is encoded as an
immediate in Bits [11:7], and it takes the value 1 if a GPR (also encoded in
[11:7]) is used to reference it.

// comment

_Description_::
+
--
This instruction can be used to:

* Activate the side-channel protection of the CC or increase it;
* Restrict the use of encryption or decryption in a CC that allows both;
* Restrict the usage of a CC (as stored in a CR) to specific modes; and
* Add a Locality or replace a Locality with a stricter one.

Let `mh` be the Metadata Header of the CC in the destination CR.

On RV64, the semantics of the instruction are:

* `Xs` follows the format of the Metadata Header.
Only the fields _AlgorithmPolicy_, _SCProtection_, _Locality_, _UsagePolicy_,
and _ExpirationDate_ of `Xs` may be defined. All other fields must be 0, else
exception `ace_exc_invalid` is raised.

* `Xs`._AlgorithmPolicy_ is used to set the new `mh`._AlgorithmPolicy_ of the
  CR, if the CC configured in the latter makes use of this field.
  No currently disabled operation may be enabled, any attempt to do so raises
  exception `ace_exc_invalid`. In some cases, a zero value is not permitted, such as
  disabling both encryption and decryption.

* `Xs`._SCProtection_ is used to turn on side-channel protection or raise its
  level. Attempting to remove or downgrade side channel protection, or to set a
  non-implemented level raises exception `ace_exc_invalid`.

* If `Xs`._Locality_ is non-zero, then it can be used to restrict the Locality, either by adding a new one or by replacing one.
  Allowed replacements of Locality are described in <<ACE-Localities>>.

* A zero in any of bits `Xs`._UsagePolicy_ means that the
  corresponding policy is _not_ changed.

* A one in any of the bits `Xs`._UsagePolicy_ means that usage by the
  corresponding mode is not allowed, and the corresponding bit in the Metadata
  of the destination CC is set to 1.

* If `Xs`._ExpirationDate_ is zero, the corresponding policy in
  `mh`._ExpirationDate_ is _not_ changed.

* A non-zero value in `Xs`._ExpirationDate_ will be copied to
  `mh`._ExpirationDate_, but only if that policy was not already programmed before
  or the original value of `mh`._ExpirationDate_ was equal to the new value or larger.
  Otherwise exception `ace_exc_invalid` is raised.
--
+
On RV32:

* `s` must be even, the register pair `X[s]` and `X[s+1]` are read, and
  `(X[s+1] @ X[s])` replaces `Xs` in the RV64 description.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[NOTE]
====
This instruction enables several practical use cases:

*   Enabling side-channel protection when supported by the microarchitecture,
    even if the original CC was not configured with it.
*   Allowing privileged code to give a CC to several processes in a
    fine-grained manner. This can be achieved by cloning the CR and customizing
    the Filter for each clone to an authorized process, or by exporting it with
    a per-process _SSecret_ Locality.
*   Similarly, enabling privileged code to split a CC capable of both
    encryption and decryption into two CCs, one only capable of encryption and
    the other only capable of decryption, thereby creating a one-way channel
    between processes.

The ability to perform such customizations saves both time and computational
resources by avoiding additional round-trips to trusted environments.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clone]]
==== ace.clone

_Synopsis_::
Copy a CR into another CR.

_Mnemonic_::
`ace.clone Kd|K(Xd), Ks|K(Xs)`
(((ACE, instruction, ace.clone)))

_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 equal to 1 and
`func2` equal to 2. The instruction is encoded using the Form D' `ace.exec`
encoding, and is thus an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks|K(Xs)' },
    { bits:  5, name: 0x0 },
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'R' },
    { bits:  2, name: 0x0 },
    { bits:  2, name: 0x2, attr: ['func2'] },
]}
....
+
Bits [27:26], i.e., field `R`, take the following values depending on how the
CRs are given:
+
[upperalpha]
. `00`{nbsp}{nbsp} if the source and the output CRs are both encoded as
  immediate values.
. `01`{nbsp}{nbsp} if the source CR is encoded as immediate and the output CR
  is selected using a GPR.
. `10`{nbsp}{nbsp} if the source CR is selected using a GPR and the output CR
  is encoded as an immediate value.
. `11`{nbsp}{nbsp} if the source and the output CRs are both selected using the
  values of GPRs.

// Comment to ensure proper indentation in the next Description

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
// Trappable: *YES*, it can be implemented as an export followed by an import in a handler. +
// Interruptible: *NO*. +

_Description_::
Clones source CR `Ks` (or the CR indexed by `Xs`) into destination CR `Kd` (or the CR indexed by `Xd`).

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

////

[[ACE-instruction-derive]]
==== ace.derive
_Synopsis_::
Derive a CR from a source CR, such as a key derivation.
_Mnemonic_::
The `ace.derive` instruction admits three Forms, namely
(((ACE, instruction, ace.derive)))
[upperalpha]
. `ace.derive Kd|K(Xd), Ks1|K(Xs1) {fournbsp}{nbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.derive Kd|K(Xd), Ks1|K(Xs1), Xs2{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.derive Kd|K(Xd), Ks1|K(Xs1), Vs2{nbsp}{nbsp}` with an auxiliary input in a vector register.
_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 equal to 1 and `func2` equal to 3.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x6b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks1|K(Xs1)' },
    { bits:  5, name: 'rs2'},
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'R' },
    { bits:  1, name: 'v' },
    { bits:  1, name: 'g' },
    { bits:  2, name: 0x3, attr: ['func2'] },
]}
....
+
Bits [27:26], i.e., field `R`, is encoded exactly as for `ace.clone` (<<ACE-instruction-clone>>).
Bit 28 determines whether a vector register (or register group) is used to pass an auxiliary parameter to the key derivation mechanism or not.
Bit `v` (i.e., bit 28) is 0 for Forms A and B and 1 for Form C. +
Bit `g` (i.e., bit 29) is used to distinguish Form A, with `g` = 0, from Form B, with `g` = 1. +
The value (`g`,`v`) = (1,1) is currently an illegal instruction and reserved for future use.
_Description_::
Derive a new context from an existing one, with its own opaque key material, for instance using a key derivation mechanism.
The behavior of the instruction is not expected to be deterministic.
It can be used multiple times, to generate multiple derived contexts.
_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

_Included in_::
+--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `ZlSM2c`  v0.0.0          | --
|===
--
+

////

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-size]]
==== ace.size

_Synopsis_::
Return the size of a CC or an error value.

_Mnemonics_::
There are four Forms of the `ace.size` instruction:
(((ACE, instruction, ace.size)))

[upperalpha]
. `ace.size Xd, Ks|K(Xs)` - Size from a context.
. `ace.size Xd, Xs` - Size from Metadata Header.
. `ace.size.internal Xd, Xs` - Internal capacity estimate for a CR.
. `ace.size.iobuf Xd, Xs` - Internal capacity estimate for the ACEIOBUF.

// Without this comment, the next part is not properly formatted...

_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 (the lsb of
`func7`) equal to 1 and the two msbs of `func7` equal to 0.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks/K(Xs)/Xs' },
    { bits:  5, name: 0x0 },
    { bits:  1, name: 0x1 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 'F' },
    { bits:  2, name: 0x0, attr: ['func2'] },
]}
....
+
The `F` field and the `r` bit may assume the following values:

* `F` = `0b00`, `r` = `0` {implies} Form A: Size from a context given as `Ks`.
* `F` = `0b00`, `r` = `1` {implies} Form A: Size from a context given indirectly as `K(Xs)`.
* `F` = `0b01`, `r` = `0` {implies} Form B: Size from Metadata Header.
* `F` = `0b11`, `r` = `0` {implies} Form C: Internal capacity of the ACEIOBUF.

_Description_:: {empty}

* Form A `ace.size` returns the total size (in bytes) of the memory buffer that
  would be necessary to store the exported SCC, including the authentication tag and the additional variable-length data.
  Knowing this size is necessary
  for any feature that relies on `ace.export`, including context switching. The
  instruction returns 0 if the CR is unconfigured.

* Form B `ace.size` returns the total size (in bytes) of an SCC having the
  Metadata section given in `Xn` into GPR `Xd` including the additional variable-length data,
  `NOT(bin(ace_state_not_impl, XLEN))` if the algorithm is not
  supported, and `NOT(bin(ace_state_invalid, XLEN))` if the Metadata is invalid.
 +
On RV32, `s` must be even and `Xs` and `X[s+1]` contain bits [31:0] and [63:32] of the Metadata.

* Form C: The source register contains the desired byte length of the buffer to
  be allocated, and the destination register contains the size of the buffer in
  the ACE unit.

NOTE: In general, no correlation may be assumed between the size of a PI, the
corresponding CR's usage of internal resources, and the size of the SCC.
// The size of the SCC can differ significantly from the internal resource usage to store the CC's data in a CR.
// On one hand, there is an overhead due to the SIV.
// On the other hand, in case of threshold implementations, where keys are exported in reconstructed form, or in modes where some derived keys are not exported, the SCC may be smaller than the internal resource usage.

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +
// Trappable: *NO*. +
// Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv` (Forms A-B)   | v0.0.0          | --
| `Zlio` (Forms A-C)  | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-available]]
==== ace.avail

_Synopsis_::
Verify whether an algorithm is supported.

_Mnemonic_::
`ace.avail Xd, Xs`
(((ACE, instruction, ace.avail)))

_Encoding_::
`ace.avail` is an alias to Form B of `ace.size`, as the latter returns 0 if the
algorithm is not supported.

_Properties_::
Same as `ace.size`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-input]]
==== ace.input

_Synopsis_::
Load data into the ACEIOBUF.

_Mnemonic_::
`ace.input %offset(Xs), Xl`
(((ACE, instruction, ace.input)))

_Encoding_::
`ace.input` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 0x2, attr: ['ace.input'] },
    { bits:  5, name: 'Xl' },
    { bits:  5, name: 'Xs' },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Description_::
If the vector registers are not sufficiently long, or not implemented, inputs can be read directly from memory and outputs written directly to memory.
For this reason, the architecture defines `ace.input` and `ace.output` (cf. next section).
`ace.input` loads `Xl` bytes from memory starting at address `%offset(Xs)` and copies them to the ACEIOBUF, starting at offset `acestart`.
+
If `Xl` == 0, the operation is a NOP.
+
If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.
+
The intended usage of `ace.input` and `ace.output` is explained in detail in
<<ACE-usage-input-output>>.

If ``aceactivecr``'s value is 32, `ace.output` (see below) and `ace.input`
can be used to save and restore the contents of the ACEIOBUF, for
instance by context switching code.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *YES*. +
// Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-output]]
==== ace.output

_Synopsis_::
Save the contents of the ACEIOBUF to memory.

_Mnemonic_::
`ace.output %offset(Xd), Xl`
(((ACE, instruction, ace.output)))

_Encoding_::
`ace.output` is an I-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x3, attr: ['ace.output'] },
    { bits:  5, name: 'Xl' },
    { bits: 12, name: 'immed' },
]}
....

_Description_::
This is the output operation corresponding to `ace.input`.
`ace.output` writes the contents of the input buffer, starting at offset `acestart`, to memory starting at address `%offset(Xs)`.
+
If `Xl` == 0, the operation is a NOP.
+
If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
// Trappable: *YES*. +
// Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+
// ////////////////////////////////////////////////////////////////////

[[ACE-usage-input-output]]
=== Usage of `ace.input` and `ace.output` to Replace Vector Inputs and Outputs

When ACEIOBUF is implemented, in all algorithms the following applies: any
occurrence of the вЂњOriginal InstructionsвЂќ in <<ACE-replacement-instructions>>
may be substituted by the corresponding вЂњReplacement SequenceвЂќ where
`ace.input` and `ace.output` instructions are used in place of the vector
register inputs and outputs.
The use of such Replacement Sequences is implied in all algorithms and not explicitly written each time.

[[ACE-replacement-instructions]]
.Replacement sequences for `ace.exec` and `ace.setst` using `ace.input` and `ace.output`
[float="center",align="center",width="100%",cols="<24%,<38%,<38%",options="header"]
|===
| Instruction and Form | Original Instruction          | Replacement Sequence
| `ace.exec`, Form A   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K(Xn), Vs` | `1: ace.input{nbsp}{nbsp}Xl, %offset(Xs)` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
`3: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.exec`, Form B   | `ace.exec{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}Kn\|K(Xn), Vs`     | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
| `ace.exec`, Form C   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K(Xn)`     | `1: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
`2: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.setst`, Form C  | `ace.setst{nbsp}Kd\|K(Xd), #immed, Vs` | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.setst{nbsp}{nbsp}Kd\|K(Xd), #immed` +
// | `ace.derive`, Form C | `ace.derive Kd\|K(Xd), Ks1\|K(Xs1), Vs2` | `1: ace.input{nbsp}{nbsp}%offset(Xs2), Xl` +
// `2: ace.derive{nbsp}Kd\|K(Xd), Ks1\|K(Xs1)` +
|===

The sole functions of `ace.input` and `ace.output` are to supply inputs to cryptographic operations and to read out their outputs. No computation is performed on the data by these instructions. All computations and internal state changes of `ace.exec` and `ace.setst` remain within those operations.

`ace.input` and `ace.output` may be used only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero. Otherwise, exception `ace_exc_buf_unconf` is raised. If `aceiobuflen` is non-zero but the range size `aceiobuftop - acestart` is invalid for the algorithm, exception `ace_exc_invalid` is raised and no cryptographic operation is performed.

The `ace.input` and `ace.output` instructions must be tied to a specific context to determine the allowed sequences.
This is done by setting the `aceactivecr` CSR (<<ACE-CSR-aceactivecr>>).
It is the responsibility of the user to reset it to the value of 32 at the end of the code.

If the execution of any `ace.exec` or `ace.setst` operation leads to an error state for the `aceactivecr` CR, the implementation must reset `aceactivecr` to teh value of 32.

The architecture uses the _Sequence_ field in the metadata field of each CR to track the progress of the replacement sequences.
The initial value of _Sequence_ is 0.
It remains zero while the forms of `ace.exec` and `ace.setst` specified in the algorithm are used.
As soon as one of the following events happens:

. An `ace.input` is completed in place of a Form A or B `ace.exec`, or Form C `ace.setst`; or
. A Form D `ace.exec` is completed in place of a Form C `ace.exec`,

then _Sequence_ is set to 1, to denote that the first instruction in the
replacement sequence has completed, provided that `aceactivecr` is configured
correctly to the CR used in the original instruction, and not 32.
Then, _Sequence_ keeps track of how many instructions of the replacement sequence have been completed.
At the end of the replacement sequence, _Sequence_  is reset to 0.

The ordering of the instructions in a replacement sequence is enforced by the
architecture according to the value of _Sequence_ and the state number of
the CR configured in `aceactivecr`. Not following the instruction ordering
raises an illegal instruction exception and invalidates the CR.

// ////////////////////////////////////////////////////////////////////

[[ACE-interruptibility]]
=== Interruptibility of ACE instructions

`ace.clear`, `ace.reset`, `ace.setst`, `ace.getst`, `ace.restrict`, `ace.clone`, `ace.size` and `ace.avail` are uninterruptible.
`ace.prov`, `ace.import`, `ace.export`, `ace.input`, and `ace.output` may be interrupted.
For `ace.prov`, `ace.import`, and `ace.export`, see <<ACE-provisioning-export-import>>.
For `ace.input` and `ace.output`, the value of `acestart` will reflect the amount of data read or written before the interrupt and resumption will start from that point.

The operation of `ace.exec` on a basic processing unit is uninterruptible, unless explicitly allowed by the algorithm.
Most cryptographic primitives cannot be interrupted; therefore, state information to encode round number or round key value is not needed.
For certain very long running operations, such as public key primitives, an algorithm specific interruptibility behavior is defined.

When processing multiple blocks iteratively, `ace.exec` handles each block atomically, but it may be interrupted between blocks.
On an interrupt during block processing, the implementation may either complete the current block before yielding to the handler, or discard the partial computation and restore the state from before its processing.
`acestart` is updated accordingly.

// ////////////////////////////////////////////////////////////////////
