[[ACE-registers]]
=== Registers

The atomic cryptography extension does not add a register file, but it adds 32 Cryptographic Contexts and
some unprivileged CSRs to a base scalar RISC-V ISA -- as well some privileged CSRs.
It also requires a subset of the V extension to be implemented.

==== Cryptographic Contexts

The atomic cryptography extension defines 32 Cryptographic Contexts (CCs) for storing cryptographic keys and metadata.
Each CC is identified by a number from 0 to 31, which the ACE unit uses to access its contents.
CCs are addressed via static 5-bit immediate addressing (as normal registers) as well as, unlike traditional registers, via a value from 0 to 31 in any general-purpose register.

CCs reside in a dedicated internal _context file_ (CF) that is inaccessible to any entity outside the ACE security perimeter, including software, other hardware blocks, and invasive debug interfaces. CF memory capacity is implementation-defined, in theory up to 32 times the size of the largest possible CC, but in practice a smaller amount of memory can be used.

CC sizes are dynamic, determined by the cryptographic algorithm defined in each CC.
ACE returns an error when insufficient memory prevents `ace.init` or `ace.import` operations, requiring the software to free memory by exporting or clearing a different CC. Implementations must provide sufficient CF memory to prevent infinite `ace.export`/`ace.import` loops.

==== ACE field in `misa`

We define the `misa.ACE` field to reflect that the ACE has been implemented, as the `K` bit (bit number 10).

==== ACES field in `*status`

An ACE context status field, ACES, is added to `mstatus`[26:25] and shadowed in `sstatus`[26:25],
and possibly `vsstatus`[26:25] if the hypervisor extension is present.
It can be used, like the FS and VS fields, to optimize context switching.
Its status encoding differs from the FS, VS, and XS fields (which are defined in <<fsxsencoding>>).
The three possible status values are: Disabled-Clean, Disabled-Dirty, and Enabled, as described in <<ACE-fsxsencoding>>.

[[ACE-fsxsencoding]]
.Encoding of ACES[1:0] status field
[float="center",align="center",width="100%",cols="^7%,<18%,<75%",options="header"]
|===
|Status |Name |Meaning
|   0   | Disabled-Clean     | ACE ISE not enabled, SW assumes no context being configured for this hart. The ACE unit will erase all contexts if ACE is enabled by writing to the `acecsr` CSR.
|   1   | Disabled-Clobbered | ACE ISE not enabled, SW assumes there are configured contexts left for this hart from other environments.  The hart will trap if ACE ISE is enabled by writing to the `acecsr` CSR. To be used only if explicitly supported in system SW stack, otherwise Disabled-Clean should be used.
|   2   | Enabled            | ACE ISE enabled.
|   3   | Invalid            | Reserved.
|===

The Disabled-Clean and Disabled-Clobbered states are set by the parent mode to optimize context switching. Disabled-Clobbered is used when the parent-mode software stack does not save cryptographic contexts before transferring control to a process that does not (yet) have enabled ACE. If that process later enables ACE by writing to `acecsr`, the hart traps to the parent mode, allowing lazy context save; the parent must then manually reset all cryptographic contexts. In contrast, a software stack that always saves the contexts of a switched-out process should configure only the Disabled-Clean state, as enabling ACE in this case will automatically reset all contexts. The Disabled-Clobbered state is primarily intended for small devices where thread migration between harts is infrequent.

Changing the setting of ACES has no effect on the contents of the CCs.
In particular, setting ACES=Disabled-Clean or Disabled-Clobbered does not destroy the state, nor does setting ACES=Enabled clear the contents.

==== Trap address for feature enablement

[.red]#*TBD* _We need a CSR to store the address of the trap handler for ACE enablement/an entry in the trap table._#

==== `aceenable`

`aceenable` is a CSR that has only one bit defined.

Enabling ACE in user mode is done by writing a 1 to `aceenable`.
This will allow the unit to perform operations, access the general purpose and vector registers, as well as the cryptographic contexts.
Disabling ACE in user mode is done by writing a zero to `aceenable`.
This will also clear the contents of all cryptographic contexts.

[.red]#*TBD* _Describe also the effect on `aceccactive` and `aceccdirty`._#

While the standard floating-point and vector extensions do not support user-mode disable/enable instructions, the ACE unit can be enabled and disabled in user mode. Instead of using an OS call or trapping, enablement and disablement will be mostly performed inside the ACE unit. However, if, as described above, the ACE unit contains state from a different process, and its interface is disabled for the current one, enabling it will trap to the parent mode to allow the parent to first save the state in case it was not saved before and then clear it (lazy context switch), or only clear it if it was saved earlier.

==== `aceerror`

The `aceerror` CSR contains only as many bits as needed to encode the error status.

// All other bits are reserved for future use.
// It is not a complete analogue of `fcsr` or `vcsr` since, for instance, it does not have to encode information such as rounding modes.
// Also, the error status is a field and not a set of distinct condition codes.

==== `acectk`

To program the CTK in the ACE unit, we need 256-bit worth of CSRs, reserved to M mode.

For this purpose, eight 32-bit CSRs are allocated, called `acectk0`, `acectk1` .. `acectk7`.

`acectk{i}` contains bits [stem:[31+32\,i:32\,i]] of the CTK.

The `acectk` block, if writable, is writable exclusively by MM.
Either all the `acectk` CSRs are writable, or none of them are.

The `acectk` block reads as zero in all cases.

There is need to raise exceptions if SW running in an any other mode tries to write to it or read it.

[.red]#*TBD*: _How to discover whether `acectk` is writable or not by MM?_
Can we use a second `misa` bit?
Low priority.#


==== Tracking CC dirtiness

This is done by using two CSRs, which track the usage and dirtiness of the CCs individually:

[arabic]
. `aceccactive`: 32 bits, with a bit per CC to denote whether the register is in use or not (cleared contextually to CC erasure to dispose of the key). Read-only.
. `aceccdirty`: 32 bits, with a bit per CC to track whether the corresponding CC has been modified since the last time the same bit has been cleared. +

Two types actions can modify a CC and thus must update also `aceccdirty`:

* An explicit configuration/import; and
* Certain cryptographic operations, such as absorbing information in a hash function, that modify the internal state.

It is also possible to directly write to `aceccdirty` (this is useful to optimize context switching).

Implementations are required to track the dirtiness of any CC precisely and individually.
This is different from the tracking of the dirtiness of the floating-point state, for instance.

==== Reuse ASID and VMID?

Two CSRs at U, resp., S level, namely `UKSID` (User Key Space ID ) and/or `SKSID` (Supervisor Key Space ID), which are only writable at S, resp., a higher mode.
(*TBD*) We may reuse the CSRs for `ASID`, resp., `VMID` for `UKSID`, resp., `SKSID`.
Therefore, the maximal bit length of `UKSID` is 9 for Sv32 addresses or 16 for Sv39, Sv48, and Sv57.
Similarly, the maximal bit length of `SKSID` is 7 for Sv32x4 or 14 for Sv39x4, Sv48x4, and Sv57x4.
In the metadata fields, `UKSID` and `SKSID` are always zero padded to the maximal lengths of 16 and 14 bits, respectively.

*Remark {counter:remark}*:: _We do not envision direct key sharing across Worlds/Supervisor Domains, so consider defining a Hypervisor or World "Key Space ID" as redundant.
It is the responsibility of the MM to change CTKs between Worlds/Supervisor Domains._


*Remark {counter:remark}*:: _The software in each World/Supervisor Domain is normally responsible to generate or obtain their own keys, and if a process (applet) in one World/Supervisor Domain is responsible to provide keys to other Worlds/Supervisor Domains, it is the responsibility of the MM to properly import/switch the CTK/export._
// If `ASID`/`VMID` are reused for `UKSID`/`SKSID`, we still need to distinguish somehow the use for separating key spaces even if these fields are not used to build GVAs/GPAs (TBD).
