[[ACE-unpriv]]
== ACE Unprivileged Architecture

// Good judgment comes from experience.
// Experience comes from bad judgment.
// ŌĆöMULLAH NASRUDIN, 1200s AD

=== Introduction

ACE relies on certain fundamental concepts, which are introduced here. While
this leads to some repetitions, this also brings better clarity to the
presentation.

[[ACE-concepts]]
==== Fundamental Concepts and Definitions

Cryptographic Context:::
(((Cryptographic Context)))
The *Cryptographic Context* (CC) is the foundation of ACE. A CC is an indivisible structure consisting of a *Metadata* header and a *Content* section; all cryptographic operations performed by ACE execute within the constraints defined by a CC. The Metadata has a fixed format and specifies the cryptographic algorithm and various optional policies associated with the CC.
(((Cryptographic Context, Metadata)))
The Content has an algorithm-specific format and holds sensitive material such as keys and internal algorithm state.
(((Cryptographic Context, Content)))
The Metadata requires integrity; the Content requires both integrity and confidentiality.
These requirements are architecturally enforced by ACE and by the cryptographic algorithms it implements.

Context Register:::
(((Context Register)))
To create CCs, ACE uses *Context Registers* (CRs), per-hart architectural containers that safeguard their contents.
A CR is *provisioned* by writing Metadata and Content into it; this operation binds the latter to form a CC.
There is no store-like instruction to extract the Content of the CR in a manner that compromises its confidentiality.
A CC may be used for cryptographic operations only while resident in a CR. Only the ACE unit may access or modify a CC residing in a CR, in accordance with architectural rules and the algorithm bound to the CC.

Sealed Cryptographic Context:::
(((Cryptographic Context, sealed)))

To support context switching while at the same time protecting CCs outside architectural state, a CC may be *exported* from a CR as a *Sealed Cryptographic Context* (SCC), an encrypted and authenticated representation of a CC that can later be *imported* into a CR. SCC export and import use a _Context Sealing Key_ (CSK), which may be programmable by M-mode.
A CC sealed under one CSK cannot be re-imported under a different CSK, enabling cryptographic domain separation across spatial and temporal domains.

Object-Orientation:::
(((Cryptographic Context, object-oriented)))
CCs act as *objects* exposing a uniform interface across algorithms.
A CC encapsulates algorithm-specific behavior, enabling interchangeable use of different primitives (e.g., AES-128, AES-256, SM4) in identical modes (e.g., ECB, GCM-SIV, XTS) without requiring changes to compiled code.
Side-channel attack (SCA) resistant variants are supported transparently.

Usage Control Policy:::
(((Cryptographic Context, usage control)))
(((Cryptographic Context, management operations)))
(((Cryptographic Context, usage operations)))
ACE distinguishes between CC/CR *management* and *usage* operations.
(((Cryptographic Context, export)))
Management operations include *configuration* (e.g., CR provisioning, SCC import, and cloning) and *export* of a CR as an SCC. Usage operations include cryptographic operations and state changes.
(((Cryptographic Context, access)))
All operations represent a form of *access* to CRs.
To prevent denial-of-service scenarios, management operations, in particular configuration operations, are far less restricted than usage operations. _Usage Control_ policies restrict only certain CC/CR usage operations.

Localities:::
(((Cryptographic Context, Locality)))
ACE can bind CCs to a *Localities*, i.e., restrict usage to specific devices or device classes, hardware configurations, physical or virtual boot cycles, and process domains at various privilege modes. This binding is achieved by using the Localities as _tweaks_ in the encryption and decryption of SCCs.

// ////////////////////////////////////////////////////////////////////

[[ACE-architectural-model]]
==== Architectural Model

ACE is architected as an _attached_ unit, meaning that ACE instructions act as messages across a tightly coupled coprocessor interface.
The ACE unit receives the operations from the hart, executes them independently of the issuing hart, and returns results.

Beside implementations of ACE within a CPU core, this model also allows a single hardware instance of the ACE unit to be shared by multiple cores, with separate architectural states for each client hart.  The specification mandates only behavior, not implementation.

The ACE unit may lock certain architectural statesŌĆöe.g., Vector Registers, CRs, and CSRs.
The hart stalls when attempting to read them until the ACE operation using those resources completes.

This design allows a certain level of concurrency.
Long-running ACE operations may proceed even if the hart is preempted.
//For example, consider a UŌĆæmode process executing an ACE instruction.
In this case, when the contextŌĆæswitch handler accesses a locked register, different behaviors are allowed:
the hart may wait for the operation to finish;
the implementation may adopt a precise exception model, whereby the ACE unit is halted and sets `acestart` to allow later resumption;
or the system may impose a timeout before halting.
The architecture permits all these approaches.
It only specifies the allowed interruption points for its instructions and algorithms.

Conceptually, for each of the 32 CRs, ACE maintains a full 128-bit Metadata Header and an offset into internal memory pointing to the CR's Content (if not empty). The Metadata Header indicates whether a CR is configured. The actual representation of CRs in a concrete implementation may differ significantly.

// ////////////////////////////////////////////////////////////////////

[[ACE-extensions-overview-unpriv]]
=== Extensions Overview

[%header,cols="15%,47%,18%,10%,10%"]
|===
| Extension       | Features                                                                                                            | Defined in:                                    | Minimum version | Lifecycle state
| `Zlv`           | ACE with support for vector registers.^1^                                                                           | <<ACE-instructions-detailed>>                  | v0.0.0          | --
| `Zlio`          | ACE with support for `ace.input` and `ace.output`.^2^                                                               | <<ACE-usage-input-output>>                     | v0.0.0          | --
| `Zlaes128p`     | AES-128 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes192p`     | AES-192 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes256p`     | AES-256 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlsm4p`        | ShangMi 4 encryption/decryption.^3^                                                                                 | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlctrm`        | CTR and CTR with set initial counter.^4^                                                                            | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxctrm`       | XCTR and XCTR with set initial counter.^4^                                                                          | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxexm`        | XEX construction.^5^                                                                                                | <<ACE-XEX-XTS-modes>>                          | v0.0.0          | --
| `Zlgcmm`        | GCM and GCM with set IV.^4^                                                                                         | <<ACE-GCM-mode>>                               | v0.0.0          | --
| `Zlgcmsivm`     | GCM-SIV.^4^                                                                                                         | <<ACE-GCM-SIV-mode>>                           | v0.0.0          | --
| `Zlocbm`        | OCB3 and OCB3 with set IV.^5^                                                                                       | <<ACE-OCB-mode>>                               | v0.0.0          | --
| `Zlcmacm`       | CMAC.^4^                                                                                                            | <<ACE-CMAC-mode>>                              | v0.0.0          | --
| `Zlesha2h`      | SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, and SHA-512/256.                                                   | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlesha3h`      | SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128, and SHAKE256.                                                     | <<ACE-SHA-3>>                                  | v0.0.0          | --
| `Zlsm3h`        | ShangMi 3 (SM3) hash function.                                                                                      | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlhmacm`       | HMAC function with hidden key (with SHA2 when `Zlesha2h` is supported, and with SHA3 when `Zlesha3h` is supported). | TBD                                            | v0.0.0          | --
| `Zlkmacm`       | KMAC function with hidden key. Depends on `Zlesha3h`, since KMAC is only defined with SHA3.                         | TBD                                            | v0.0.0          | --
| `Zlascon`       | Ascon-AEAD128 (base, with set Nonce, or with Nonce Masking), Ascon-Hash256, Ascon-XOF128 and Ascon-CXOF128.         | <<ACE-Ascon-AEAD128>> to <<ACE-Ascon-CXOF128>> | v0.0.0          | --
4+| _Point arithmetic and signature generation and verification algorithms for curves in various standards:_                      | {empty}
| `Zlsecp256r1c`  | -- NIST curve secp256r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp384r1c`  | -- NIST curve secp384r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp521r1c`  | -- NIST curve secp521r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled25519c`    | -- Edwards curve ed25519.                                                                                           | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled448c`      | -- Edwards curve ed448.                                                                                             | <<ACE-ECC>>                                    | v0.0.0          | --
| `ZlbpP256r1c`   | -- Brainpool curve brainpoolP256r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlbpP384r1c`   | -- Brainpool curve brainpoolP384r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlbpP512r1c`   | -- Brainpool curve brainpoolP512r1.                                                                                 | TBD                                            | v0.0.0          | --
| `ZlSM2c`        | -- Chinese 256-bit SM2 curve.                                                                                       | TBD                                            | v0.0.0          | --
| `Zlkn`        2+| NIST Symmetric Suite. Depends on `Zlaes128`, `Zlaes256`, `Zlesha2`, `Zlgcmm`, `Zlxexm`, and `Zlgcmsivm`.          | v0.0.0                                         | --
5+| ^1^ Requires V (or a suitable subset thereof). Must support the following CSRs: `acestart` (this is a dependency for Zicsr); must support the following instructions: `ace.prov`, all four forms of `ace.exec`, `ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size` (and thus `ace.avail`), and `ace.restrict`; must support `Zlkn`.
5+| ^2^ Must support the following CSRs: `acestart` (this is a dependency for Zicsr), `aceiobuflen` and `aceiobuftop`; must support the following instructions: `ace.prov`, Form D of `ace.exec`, `ace.input` and `ace.output`, `ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size` (and thus `ace.avail`), and `ace.restrict`; must support `Zlkn`.
5+| ^3^ Beside defining the basic encryption and decryption operations, these extensions also select which ciphers can be used with the various modes of operations that follow.
5+| ^4^ The mode is applicable to all versions of AES and to SM4.
5+| ^5^ The mode is applicable to all versions of AES.
|===

At least one of `Zlv` or `Zlio` must be implemented.

// ////////////////////////////////////////////////////////////////////

=== Programmer-Visible Architectural State

[[ACE-cryptographic-registers]]
==== Context Registers

{empty}
(((Cryptographic Context)))
ACE defines 32 Context Registers (CRs), numbered 0 to 31 and denoted `K0`ŌĆō`K31`.

CRs are architectural state, i.e., per-hart, like the GPRs or the vector registers.

Unlike a conventional register, a CR can be _unconfigured_, meaning it does not contain a CC.

A CR is addressed directly, as a 5-bit immediate, or indirectly, via a GPR value.
An additional instruction-encoding bit is used to select how the CR is addressed.
Accessing a CR with an indirect index outside [0..31] raises an illegal instruction exception.

An implementation must wait before accessing a CR that is still being written to asynchronously.

[NOTE]
====
Indirect CR addressing also an important microarchitectural implication.
Supporting CR renaming is possible but would significantly increase microarchitectural complexity.
CRs are redefined far less frequently than GPRs or FP registers (excluding implicit internal state changes).
Hence, CR renaming is not expected to significantly affect performance.
====

(((Context Register File)))
CRs reside in a dedicated, per-hart _CR file_ (CRF) accessible only to the ACE implementation. This memory shall guarantee
confidentiality and integrity of its contents, including the inability for an attacker to roll-back the latter to a previous state.
We do not require that accesses to this memory are hardened against physical side-channel attacks at the hardware level,
however, the implementation of side-channel protected algorithms in the ACE unit shall provide resistance to such attacks as well.

The amount of CRF capacity consumed by each CR depends on the algorithm encoded in the metadata, and it may differ from one CR to another.

Insufficient residual CRF capacity may prevent execution of a configuration instruction (`ace.prov`, `ace.import`, `ace.clone`):
Capacity is freed by unconfiguring other CRs.

The CRF capacity is implementation-defined. Implementations shall provide sufficient
capacity for all supported operations. At a minimum, the CRF must hold the
largest possible single CR, or the largest CR pair used in cloning operations.
An optional, implementation-specific mechanism for estimating required capacity
is described in <<ACE-instruction-size>>.

Any corruption of the CRF associated with a hart shall cause an unrecoverable error condition.
The entire architectural state of the ACE unit associated with the hart is reset, and exception `ace_guru_meditation` is raised (cf. <<ACE-exceptions>>).

We list the most important operations on CRs, so we can refer to them before they are fully defined.

* `ace.prov` (<<ACE-instruction-init>>) loads metadata and plaintext Content into a CR, binding them together.
* `ace.clear` (<<ACE-instruction-clear>>) unconfigures and clears a CR.
* `ace.export` (<<ACE-instruction-export>>) exports a CR to memory as an SCC.
* `ace.import` (<<ACE-instruction-import>>) imports a SCC into a CR.
* `ace.exec` (<<ACE-instruction-exec>>) performs cryptographic operations as specified by the algorithm configured in a CR and according to the state of the CR.
* `ace.setst` (<<ACE-instruction-setst>>) transitions between states of a cryptographic algorithm.
//* `ace.getmd` (<<ACE-instruction-getmd>>) reads the metadata of a CR.
* `ace.clone` (<<ACE-instruction-clone>>) creates a copy of a CR into a second CR.

// ////////////////////////////////////////////////////////////////////

==== Inputs and Outputs, RVV-mini

ACE inputs and outputs may use vector registers or an architectural input/output buffer (ACEIOBUF)
that can be loaded from and stored to external memory. Both mechanisms may be supported simultaneously.

When vector registers are used, the full V extension is not required. ACE depends only on a minimal subset, termed _RVV-mini_.
(((RVV-mini)))
RVV-mini must be fully opcode-compatible with RVV: code written for RVV-mini must execute with identical behavior under RVV. The required features are:

* Vector registers wide enough to support the inputs and outputs of the implemented algorithms;
* The `vsetvli` instruction with restricted parameters (e.g., `vsetvli zero,4,e32,m1,ta,ma` for 128-bit operations);
  unsupported configurations must raise an illegal instruction exception;
* Unit-strided vector loads and stores; and
* Vector bitwise logical operations: `vxor`, `vand`, and `vor`.

ACE instructions (currently) do not use vector masking and do not define masked versions of `ace.exec`.
Therefore, the algorithms currently defined require unmasked inputs and outputs.

Floating-point, fixed-point, and general arithmetic vector operations are not required.
Complex operations for certain cryptographic algorithms may be performed in GPRs, with data inserted into vector registers and result
extracted from them via `vins`/`vext`.

[WARNING]
RVV-mini need not be finalized before ACE ratification begins; it
may be defined later, and the ACE specification amended accordingly.
This allows additional requirements to be collected, for example, whether to mandate
`vclmul.v[vx]` and `vclmulh.v[vx]` from `Zvbc`.

The optional per-hart input/output buffer (ACEIOBUF) may be used in place of vector registers.
The ACEIOBUF is not part of the CRF.
Instructions `ace.input` and `ace.output` are used to write inputs to the ACEIOBUF and read outputs from it.
When the ACEIOBUF is used in place of vector registers, instructions `ace.exec` and `ace.setst` that use vector registers are replaced by instruction sequences  as described in <<ACE-usage-input-output>>.

To determine the lengths of the inputs and outputs of its operations when the vector registers are used, ACE uses `VL*SEW`.
The actual choice of `VL` and `SEW` is not significant. For instance, both `VL`=2, `SEW`=64 and `VL`=4, `SEW`=32 define a 128-bit input.
The CPU instruction-decoding side of ACE uses `VL` and `SEW` to determine the amount of data to send to the ACE unit proper.
The ACE unit itself only needs the product `VL*SEW` (or `aceiobuftop`) for its functionality.

// ////////////////////////////////////////////////////////////////////

[[ACE-data-formats-intro]]
==== Data Formats

ACE defines two external CC formats:

. The _Provisioning Input_ (PI), loaded into a CR to create a CC; and
. The _Sealed Cryptographic Context_ (SCC), an encrypted and authenticated representation of a CC used when exporting a CR to memory for later import.

{empty}
(((Cryptographic Context,Metadata)))
(((Cryptographic Context,Metadata,Header)))
Both formats begin with a 128-bit Metadata Header, whose format we define next.

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata]]
===== Metadata Header

The following table lists the fields of the 128-bit Metadata Header.
Currently, 79 bits are defined and 49 are reserved for future use.

[[ACE-metadata-section]]
.Format of the 128-bit Metadata Header
[width="100%",cols="^9%,^7%,14%,70%",options="header"]
|===
|  Field   | Width | Name              | Description
|  [11:0]  | 12    | _Algorithm_       | Cryptographic algorithm (primitive, mode, or protocol). See <<ACE-Algorithm-field>>.
|  [13:12] | 2     | _AlgorithmPolicy_ | Allowed algorithm variants(s) _or_ extension of the _Algorithm_ field. See <<ACE-Algorithm-field>>.
|  [15:14] | 2     | Reserved          | Reserved for future expansion of _AlgorithmPolicy_ field.
|  [18:16] | 3     | _SCProtection_    | Side-channel protection level. See <<ACE-SCProtection-field>>.
|  [19:19] | 1     | _KeyType_         | 0: key is an explicit value in Content. 1: key is an index into the system-specific System Keys Table (SKT).
|  [24:20] | 5     | _State_           | Current state of the CR/algorithm, encoded as an integer.
|  [26:25] | 2     | _Sequence_        | Tracks the progress in the replacement sequence of an `ace.exec` or `ace.setst` instruction. The `aceactivecr` CSR must match the CR number.
|  [31:27] | 5     | Reserved          | Reserved for future use. Currently, it must be equal to zero.
|  [35:32] | 4     | _UsagePolicy_     | Usage (Control) Policy. Bits 0, 1, 2 and 3 of the field,, when set, disallow CC usage in U-mode, (V)S-mode, H-mode, and M-Mode, respectively.
|  [36:36] | 1     | Reserved          | Reserved for future use. Currently, it must be equal to zero.
|  [44:37] | 8     | _Locality_        | Zero, or an index determining a Locality Secret. See <<ACE-Localities>>.
|  [47:45] | 3     | Reserved          | Reserved for future use. Currently, it must be equal to zero.
|  [63:48] | 16    | _AddDataSize_     | If non-zero, indicates an additional data section appended to Content. The length of this additional data section is _AddDataSize_ * 16 bytes (up to 512 KiB).
|  [89:64] | 26    | _ExpirationDate_  | If non-zero, the expiration date of this CC. See <<ACE-Metadata-expiration-date>>. Minutes since 00:00, January 1, 2027. (127 years...)
| [127:90] | 38    | Reserved          | Reserved for future use.  Currently, it must be equal to zero.
|===

In the following subsections we describe the fields of the Metadata section.

//

[[ACE-Algorithm-field]]
===== _Algorithm_ and _AlgorithmPolicy_ Fields

Algorithms are encoded in a 12-bit field. Values 0ŌĆō3071 and 4095 are architecture-defined.
The list of encodings is maintained by RVI (see <<ACE-algorithms>>).
The remaining values are available for custom algorithms.

For encryption/decryption primitives and modes, the _AlgorithmPolicy_ field indicates whether the CC may be used for encryption (lower bit set), decryption (upper bit set), or both. At least one of the bits must be set.

For asymmetric primitives supporting signatures, the lower bit permits signature generation and the upper bit permits verification.
Such an asymmetric primitive can be configured to support primitives such as key agreement or key encapsulation but _not_ signatures, and in this case both bits are zero.

For other primitives, the _AlgorithmPolicy_ field may encode additional algorithm identifiers to expand the effective encoding space of the _Algorithm_ field.

// ////////////////////////////////////////////////////////////////////

[[ACE-SCProtection-field]]
===== _SCProtection_ Field

The architecture defines the following side-channel protection levels.

[[ACE-SC-protection-levels]]
.Encoding of Side-Channel Protection levels
[%autowidth,float="center",align="center",cols="^,<"options="header"]
|===
| Value | Description
|   0   | No protection.
|   1   | Data-independent execution latency (DIEL); first-order threshold implementation.
|   2   | DIEL; first-order threshold, fault-tolerant implementation.
|   3   | Custom, algorithm-dependent.
|===

Custom algorithms offering stronger protection than encodings 0ŌĆō2 shall set
_SCProtection_ to 3.

// ////////////////////////////////////////////////////////////////////

[[ACE-State-field]]
===== _State_ Field

The _State_ field is used to track the currently state of an algorithm, including certain types of errors.

The architected values of _State_ which are common to all algorithms are defined in
<<ACE-states-valid>>.

[[ACE-states-valid]]
.Global CC State Numbers: Valid States
[float="center",align="center",width="100%",cols="^7%,<27,<15%,<51%",options="header"]
|===
| Value | Mnemonic                  | State Name     | Description
|   0   | `ace_state_off`           | _Off_          | The CR is not configured.
|   1   | `ace_state_initial`       | _Initial_      | The state of a CC immediately after provisioning; ready for operation.
| 2-20  3+| Defined by the specification of the Algorithm encoded in the _Algorithm_ field.
|  21   | `ace_state_success`       | _Success_      | Algorithm completed successfully. No further cryptographic operations may be performed until the CC is reset.
|  22   | `ace_state_failure`       | _Failure_      | Failure in an algorithm, usually an authentication failure in AE(AD) algorithms or a signature verification failure. No further cryptographic operations may be performed until the CC is reset.
|===

[[ACE-states-error]]
.Global CC State Numbers: Interrupted and Error States
[float="center",align="center",width="100%",cols="^7%,<27,<15%,<51%"]
|===
|  23    | `ace_state_partial_config`  | _Partial_Config_  | Provisioning or import interrupted.
|  24    | `ace_state_expired`         | _Expired_         | The CR has expired.  This is set by the hardware even if the condition also raises an exception.
|  25    | `ace_state_import_auth`     | _Auth_Failed_     | Authentication failure with `ace.import`.
|  26    | `ace_state_priv_viol`       | _Priv_Viol_       | Violation of Usage Control policies.
|  27    | `ace_state_out_of_mem`      | _Out_of_Memory_   | Insufficient CRF memory for configuration instruction. This may be set by privileged code in case they do not handle the CR allocation.
|  28    | `ace_state_not_impl`        | _Not_Impl_        | Not implemented algorithm. It is set by the hardware upon an attempt to provision or import a CR that is not supported by the implementation.
| 29, 30 | (Reserved)                 |                   | Reserved for future use.
|  31    | `ace_state_invalid`         | _Invalid_         | Invalid/invalidated state, for instance because of the use of an invalid value (argument, state, or metadata).
|===

The state with value 0 is termed _Off_, and is used to indicate that the CR is not configured.

All states in the range 1-22 are termed _valid_. This includes both _Success_ and _Failure_ states, which must be used for
normal termination of an algorithm in the cases of its successful completion or failure.

State 23, i.e., _Partial_Config_, is used to report that provisioning or import was interrupted.

States 24-31 are termed _error states_, and are used to report certain specific ACE errors.
(((ACE, algorithm, invalid state)))
(((Context Register, invalidation)))
In particular, if the State is `ace_state_invalid`, we say that the CR is _invalidated_.

An error state can be set by software using `ace.setst` (with no auxiliary input).

Error conditions that lead to exceptions are treated in <<ACE-exceptions>>.

If an algorithm defines 22 or fewer valid states (including _Initial_, _Success_, and _Failure_), the current state is stored in the _State_ field.
For algorithms with more than 22 valid states, additional state information resides in the Content section.

The following rules are generic and apply to all algorithms:

. The Metadata's _State_ field must reflect the current state whenever the CC is in _Initial_, _Success_, _Failure_, or any error state.
This ensures that these states can be unambiguously determined from the _State_ field alone, without inspecting the Content.

. In States _Success_ and _Failed_, only the following ACE instructions are permitted: `ace.prov`, `ace.import`, `ace.export`, `ace.clear`, `ace.size`, `ace.setst`, and `ace.getst`.

. In States _Success_ and _Failed_, `ace.setst` can only be used permitted to transition to _Initial_ (or _Off_ if used as `ace.clear`).

. Unless an algorithm's specification explicitly states otherwise, a transition from any valid state to _Initial_ using instruction `ace.setst` is always permitted.

. Upon transitioning to an error state, the Content of a CR is invalidated and emptied.
Internal resources associated with the Content may also be released. In that case, any Additional Data is released and the _AddDataSize_ field is set to 0.
The CR then retains only the Metadata Header.

. Exporting a CR in an error state exports only the metadata (and the authentication tag).
  Requesting the SCC's size (`ace.size` <<ACE-instruction-size>>) wil reflect this.
  The resulting SCC can be reimported, allowing software to take appropriate actions even after a context switch.

. If a CR is in any error state, it can still be reconfigured, cloned, or cleared. In particular, `ace.setst` can only transition it to _Off_.

. The metadata of a CR in an error state can be read (using `ace.getmd`: <<ACE-instruction-getmd>>).

. Attempts to _use_ a CR in any error state will not perform any operation, and in particular they leave the _State_ field unchanged.

. If a CR is in State _Partial_Config_, transitioning it to any State other than _Off_ or _Invalid_ is only possible as a consequence of a restart or resumption of the interrupted configuration instruction.  `ace.setst` can only transition it to _Off_ or _Invalid_.

. Any _usage_ instruction that would violate the Usage Control policies will not perform its operation, and will set _State_ to `ace_state_priv_viol` instead.

We note that the State after `ace.setst` is issued may differ from the State specified by the instruction.
A common example is MAC verification: after `ace.setst` is issued with an `ace_state_hash_verify` immediate as the next state and the value to be verified as the additional parameter, the algorithm transitions to either _Success_ or _Failure_. This is done to prevent the manipulation of a CR's state and to reduce code size.
An `ace.exec` instruction may also trigger a state change.

// ////////////////////////////////////////////////////////////////////

[[ACE-Localities]]
===== _Locality_ Field

ACE maintains a table of 128-bit Locality Secrets (LS), called the Locality Secrets Table (LST).
Some entries are fixed or are configurable only through an implementation-specific authenticated hardware procedure.
These are global, shared across all ACE units within the same SoC.
Other entries are per-hart architectural state, programmed by privileged modes.

<<ACE-locality-indexes>> lists the architected Localities.
Eleven LST entries are defined: the first six form the _HW Binding Group_, which binds SCCs to the hardware;
entries 6ŌĆō7 form the _Boot Session Group_;
entries 8ŌĆō10 form the _SW Filter Group_.
Seven of the eight _Locality_ field bits are defined.
Bit 7 is zero for the architected Localities.
For each Locality, the table provides: index in the LST; domain (SoC-, device-, VM-wide, or per-process); configurability; bit-field encoding; and value.

[[ACE-locality-indexes]]
.Architected Localities (Bit 7 = 0)
[width="100%",cols="^5%,15%,50%,^9%,^9%,^6%,^6%",options="header"]
|===
|  Idx  | Locality                  | Description                                                                      | Domain | Config?|  Bits  | Value
2+|    No HW Binding                | Independent of Chip, OEM, Device                                                ^|  --   ^|   --   | [2:0]  |   0
|   0   | _SiPScrt_                 | Identifies the designer of the SoC. Permanent.                                   |  SoC   |   No   | [2:0]  |   1
|   1   | _ChipFamScrt_             | Identifies specific chip/SoC model/family. Permanent.                            |  SoC   |   No   | [2:0]  |   2
|   2   | _ChipScrt_                | Unique for each SoC. Permanent.                                                  |  SoC   |   No   | [2:0]  |   3
|   3   | _OEMScrt_                 | Provisioned by OEM to differentiate their products from the competition.
Permanent, or reconfigurable via a custom hardware authenticated mechanism.                                            | Device |   HW   | [2:0]  |   4
|   4   | _ProdScrt_                | Identifies device/system type/model (product).
Permanent or reconfigurable like OEMScrt.                                                                              | Device |   HW   | [2:0]  |   5
|   5   | _DevScrt_                 | Unique device (entire system) secret.
Shared across all harts in a SoC and shareable across multiple SoCs in a single device using an implementation-defined mechanism.
Reconfigurable like OEMScrt.                                                                                           | Device |   HW   | [2:0]  |   6
2+|   No Boot Binding               | Independent of Physical or Virtual Boot Session                                 ^|  --   ^|   --   | [4:3]  |   0
|   6   | _PhysBootScrt_            | Unique per the boot session of the host hardware and its firmware stack.
Configured by M-mode during the boot process of the host (see <<ACE-CSR-macePhysBootScrt>>).                           | Device |   M    | [4:3]  |   1
|   7   | _VirtBootScrt_            | Unique per the boot session of the virtual hardware and its software stack.
Regenerated by H or higher at each virtual boot of a VM (see <<ACE-CSR-haceVirtBootScrt>>).                            |   VM   |  H/M   | [4:3]  |   2
2+|    No Binding at Modes          | Independent of M-, S-, or VS-mode filters.                                      ^|  --   ^|   --   | [6:5]  |   0
|   8   | _MLocality_               | Configurable at M to restrict import of SCCs                                     |  < M   |   M    | [6:5]  |   1
|   9   | _HLocality_               | Configurable at H to restrict import of SCCs                                     |  < H   |   H    | [6:5]  |   2
|  10   | _SLocality_               | Configurable at (V)S to restrict import of SCCs                                  | < (V)S |  (V)S  | [6:5]  |   3
|===

Implementations are not required to populate every entry in the HW Binding
Group, except for _ChipFamScrt_ and _DevScrt_. If an entry is unconfigured, it is
transparently replaced by the next defined entry in its chain: _SiPScrt_
{rightarrow} _ChipFamScrt_ {rightarrow} _ChipScrt_, and _OEMScrt_ {rightarrow}
_ProdScrt_ {rightarrow} _DevScrt_ .

_HLocality_ is active only when the H extension is enabled and V=1; otherwise, it mirrors _MLocality_.

NOTE: A system-key index may refer to keys with unrelated purposes on different
devices, leading to unspecified behavior. Implementations shall assign usage
policies at least as restrictive as the key's own native policies, and supply
an appropriate _Locality_ during CR provisioning.

Up to three architected Localities may be active concurrently:
one from the HW Binding Group,
one of either _PhysBootScrt_ or _VirtBootScrt_,
and one from the SW Filter
Group.
In <<ACE-provisioning-export-import>> it is explained how the associated policies are enforced.

If bit 7 is set, bits [6:0] are used to define custom, implementation-defined Localities instead.
Each defined custom value bits [6:0] will be translated into one or more 128-bit values that are used in the same way as the architected ones in <<ACE-provisioning-export-import>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-UsagePolicy-field]]
===== _UsagePolicy_ Field

Bit 0, 1, resp., 2 of this field is ignored if U-, S-, resp., H-mode is not
supported or not enabled.

// ////////////////////////////////////////////////////////////////////

[[ACE-extra-content]]
===== _AddDataSize_ Field

The _AddDataSize_ Metadata field records the length of the _Additional Data Section_ of the content, which is a variable-size part and may
depend on the state of the algorithm.

The format of the _Additional Data Section_ is described in <<ACE-data-formats>>.

The first eight bytes of the Implementation-Specific Additional Data Section of the Content, if not empty, always hold a copy of the `acemarchid` CSR (<<ACE-CSR-acemarchid>>) of the originating machine, and are counted within the length recorded by the _AddDataSize_ field.
The importing implementation uses this value to determine whether any information in the Implementation-Specific Data Section can be used.

It is the responsibility of the *algorithm* to determine the lengths of the two parts of the Additional Data Section.
If the Implementation-Specific Additional Data Section is not empty, the *implementation* will check the value of `acemarchid` stored therein to decide whether the Implementation-Specific part can be used or should be ignored.

[NOTE]
====
Examples of Additional Data are:

. ŌĆ£Decryption AES keysŌĆØ, i.e., the last one or two AES round keys, from which one can work backwards when performing AES decryptions.
. Precomputed point multiples for elliptic curve scalar multiplication (their computation can be far more expensive than their
encryption and decryption);
. Information, such as additional elliptic curve points or random numbers used by Elliptic Curve algorithms only in certain states;
. any auxiliary data for side-channel-protected implementations, such as key shares or other data to accelerate share reconstruction.

Examples 1., 2., and 4. are optional data, and therefore are stored in the _Implementation-Specific_ ADS.
The third example, however, describes information that is required for the correct functioning of the algorithm. Therefore, its format must be defined by the algorithm specification and the data should be stored in the _Architected_ ADS.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata-expiration-date]]
===== _ExpirationDate_ Field

If non-zero, _ExpirationDate_ specifies the CC expiration time as a number of minutes elapsed since the base date of January 1, 2027.
The 26-bit field provides for a span of approximately 127 years (2^26^ minutes).

Checking against the _ExpirationDate_ field is, semantically, the first step performed by any operation.
When a non-configuration instruction is executed on a CR whose _ExpirationDate_ lies in the past, the hardware immediately sets the Metadata _State_ field to `ace_state_expired` and performs any action prescribed for error states, including implementation-specific tasks such as releasing the CRF capacity held by the Content.  If the instruction is a usage instruction, the operation is suppressed and exception `ace_exc_invalid` is raised (cf. <<ACE-exceptions>>) if the ACE privileged architecture is implemented.  Exporting, cloning, or configuring an expired CR is allowed.

When an expired CR is used, privileged code may take appropriate actionŌĆöfor example, provisioning a new key or returning to the caller for handling.

Since privileged code may replace expired CRs, any user code that uses CRs that are known to potentially expire should always export the CR when it has finished using it, in case it may be needed later, instead of recovering it from a previously saved copy.

// ////////////////////////////////////////////////////////////////////

[[ACE-data-formats]]
===== Provisioning Input, Sealed Cryptographic Context, and Content

Determining the length of a PI or SCC requires the knowledge of only the first 64 bits of the Metadata Header.

The format of a Provisioning Input (PI) is shown in <<ACE-PI>>.

[[ACE-PI]]
.Format of the Provisioning Input (PI), All Sections in Order
[width="100%",cols="28%,44%,28%",options="header"]
|===
| Section                      | Size | Description
| Metadata Header              | 128 bits | Contains the metadata information as described in <<ACE-Metadata>>.
| Provisioning Content         | Depends only on the _Algorithm_, _AlgorithmPolicy_, and _KeyType_ fields of the Metadata Header. Always a multiple of 128 bits. | Contains keys and other algorithm-specific information.
|===

The length of a PI must be a multiple of 128 bits.

The CR itself may contain significantly more information than the Provisioning Content.
This information may be categorized under different classes:

. Information that is necessary for the algorithm to function, and cannot be reconstructed from other information.
For instance, random values that are generated in the _Initial_ state.

. Information that may be easily reconstructed from other information in the State, so that there is no need to export it.
In this case, the *algorithm* may choose to not include it into an SCC.

. Data that can be used to optimize performance on a specific *implementation*, and that is more expensive to recompute than encrypting and storing externally. The hardware may choose to export such data in a custom format inside an SCC for efficient reuse.
A different implementation that receives the same SCC (i.e., with a `acemarchid` mismatch) may safely ignore this data during import.

The format of a Sealed Cryptographic Context (SCC) is shown in <<ACE-SCC>>.

[[ACE-SCC]]
.Plaintext Sealed Cryptographic Context (SCC) Format, All Sections in Order
[width="100%",cols="28%,44%,28%",options="header"]
|===
| Section                      | Size     | Description
| Metadata Header              | 128 bits | Contains the metadata information as described in <<ACE-Metadata>>.
//
| Content: _Fixed Data Section_
| Empty if the context is in an error state, otherwise it depends only
on the _Algorithm_, _AlgorithmPolicy_, and _KeyType_ fields of the Metadata Header.
 Always a multiple of 128 bits.
| Contains keys and other algorithm-specific information.
//
| Content: _Architected Additional Data Section_ (Architected ADS)
| Empty if the context is in an error state, otherwise it depends on the information contained in the Metadata and Fixed Data Sections.
  Always a multiple of 128 bits.
| The data in this Section is necessary for the correct functioning of the algorithm.
//
| Content: _Implementation (Specific) Additional Data Section_ (Implementation ADS)
| Empty if the context is in an error state, otherwise it is Implementation-Specific.
  Always a multiple of 128 bits.
| The data in this Section is _not_ necessary for the correct functioning of the algorithm.
|===

The second and third parts together of the Content form the _Additional Data Section_ of the Content.

The Metadata _AddDataSize_ field specifies the total size of the _Additional Data Section_. It does not partition this total between the Architected and Implementation-Specific components. The ordering of sections within the SCC allows to determine the lengths of these two components before reading them.

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-unpriv]]
==== CSRs

ACE provides a number of unprivileged CSRs.
// The privileged CSRs are documented in <<ACE-priv>>.

[[ACE-CSRs-unpriv]]
.ACE Unprivileged CSRs.
[cols="^10%,^10%,<18%,<62%"]
[float="center",options="header"]
|===
|  Address | Privilege | Field            | Description
|  0xXXX   |  RO       | `acemarchid`     | ID of the microarchitecture of the ACE unit.
| `vstart` | URW       | `acestart`       | ACE start bit index.
|  0xXXX   | URW       | `aceiobuflen`    | ACE input/output buffer length.
|  0xXXX   |  RO       | `acemaxiobuflen` | ACE maximum input/output buffer length. Read only.
|  0xXXX   | URW       | `aceiobuftop`    | ACE input/output buffer limit for current transfers.
|  0xXXX   | URW       | `aceactivecr`    | Active CR for `ace.input`/`ace.output`.
|===

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acemarchid]]
===== `acemarchid`

{empty}
(((CSR, `acemarchid`)))
`acemarchid` identifies the microarchitectural version of the ACE unit, analogously to `marchid` for the hart.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acestart]]
===== `acestart`

{empty}
(((CSR, `acestart`)))
`acestart` is an alias for `vstart`. Therefore, it is an XLEN-bit RW CSR.
ACE defines it also when the V extension is not enabled.

`acestart` tracks the progress of interruptible ACE instructions, namely
`ace.prov`, `ace.import`, `ace.export`, `ace.input`, and `ace.output`. It also
applies to `ace.exec` when iteratively processing a multi-block operand, as
`ace.exec` may be interrupted between blocks. Only these instructions honor a
nonzero `acestart`; all other instructions ignore it and are restarted, with
`acestart` also being cleared. Provisioning, import, and export are
resumed only under certain conditions, as explained in
<<ACE-provisioning-export-import>>.

`acestart` records the progress of an interrupted operation.
Since ACE does not have an _intrinsic_ concept of element length, `acestart` counts the number of bits processed so far, not the number of elements.

Hardware writes this register on interruption.
Software may save and restore the register across context switches.
For certain algorithms, writing zero to `acestart` to force a full restart of `ace.exec` may lead to inconsistent or unpredictable results.
Writing an invalid or non-supported nonzero value raises an illegal instruction exception.

When a vector instruction is interrupted, the CSR follows `vstart` semantics as expected, i.e., it counts the number of processed elements.
When an ACE instruction is interrupted, the CSR follows the `acestart` semantics described here.

[WARNING]
The reason `vstart` can be reused as `acestart` comes from the fact that the Risc-V ISA exposes a computation model in which the observable results are the same as if the instructions were executed in order.
If an implementation has executed instructions past the PC when an interrupt occurs, those instructions are discarded and must be reŌĆæexecuted upon return from the handler. Only the instruction at the PC may be interrupted in a way that it saves temporary state that allows it to be resumed later.
There is no situation in which the microarchitecture of a hart can simultaneously interrupt multiple instructions allowing them to resume at the same time.
Hence, `vstart` can safely be reused by ACE as `acestart`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acemaxiobuflen]]
===== `acemaxiobuflen`

{empty}
(((CSR, `acemaxiobuflen`)))
`acemaxiobuflen` is an XLEN-bit RO CSR that reports the maximum configurable length of the ACEIOBUF.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuflen]]
===== `aceiobuflen`

{empty}
(((CSR, `aceiobuflen`)))
`aceiobuflen` is an XLEN-bit URW CSR that programs the ACEIOBUF length in bits for use by `ace.input` and `ace.output`.
Writing this register-even when re-writing the current value-also zeroes the buffer and sets `aceiobuftop` to the same length and `acestart` to zero.

When `aceiobuflen` is zero, the ACEIOBUF is _unconfigured_.
Attempting to execute an operation that expects an input or an output in the ACEIOBUF while the latter is unconfigured raises exception `ace_exc_buf_unconf`.

Writing a value larger than `acemaxiobuflen` raises exception `ace_exc_out_of_mem`.

As per the Privileged Architecture, the dirtiness of the ACEIOBUF is not tracked except as part of the entire ACE state in `*status`.
Context switching code is expected to save and restore the contents of the ACEIOBUF up to `aceiobuflen`.
We recommend software to set `aceiobuflen` to zero once the contents of the ACEIOBUF are no longer needed.
Context switching code can use this information to avoid unnecessary save and restore of ACEIOBUF contents.


_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuftop]]
===== `aceiobuftop`

{empty}
(((CSR, `aceiobuftop`)))
`aceiobuftop` is an XLEN-bit URW CSR that marks the upper bound in bits of the buffer range used by `ace.input` and `ace.output`.
Together with `acestart`, it defines the active transfer window.

The constraints `acestart` {le} `aceiobuftop` {le} `aceiobuflen` must hold.
Violating either bound raises an illegal instruction exception.
Modifying `aceiobuftop` does not modify buffer contents.

NOTE: `aceiobuftop` enables per-operation length adjustments without the need to reconfigure the ACEIOBUF using `aceiobuflen`, which can be expensive due to the fact that it clears the buffer and may lead to internal garbage collection.
This can be used similarly to the reconfiguration of `VL*SEW` to provide an partial ŌĆ£last blockŌĆØ or to supply a short IV/nonce to cryptographic algorithms.

Using a replacement sequence for `ace.exec` or `ace.setst` for any Form with an input or output
when `aceiobuftop` ŌłÆ `acestart` is zero (and `aceiobuflen` nonzero) will result in no operation being performed.

Using ACEIOBUF when `aceiobuftop` ŌłÆ `acestart` is an invalid length raises an illegal instruction exception.

Since context switching code saves and restores the contents of the ACEIOBUF up to `aceiobuflen`, the contents between `aceiobuftop` and `aceiobuflen` are preserved.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

// [[ACE-CSR-acesequence]]
// ===== `acesequence`
//
// {empty}
// (((CSR, `acesequence`)))
// `acesequence` is an XLEN-bit URW CSR.
// Currently, only the two least significant bits are defined and the other bits read as zero.
//
// `acesequence` is zero when vector registers are used for the current ACE instruction, and takes nonzero values when `ace.input`/`ace.output` are used in place of vector registers, as described in <<ACE-usage-input-output>>.
//
// `acesequence` may only be modified the corresponding CR is _Off_ or in an error mode.
//
// _Included in_::
// +
// --
// [%header,cols="4,2,2"]
// |===
// |Extension | Minimum version | Lifecycle state
// | `Zlio`   | v0.0.0          | --
// |===
// --
// +

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceactivecr]]
===== `aceactivecr`

{empty}
(((CSR, `aceactivecr`)))
`aceactivecr` is an XLEN-bit URW CSR; only the low 5 bits are defined.
It binds `ace.input`, `ace.output`, `ace.exec`, and `ace.setst` to a specific CR.
The valid values are 0ŌĆō31, which are used to bind to a CR, or 32, which disables any such binding.

When `aceactivecr` is not 32, the CR operand in all single-CR instructions and the source CR in `ace.clone` must equal the selected value, and the
_Sequence_ metadata field of that CR must track the operation in an instruction replacement sequence zzz

// At any given moment, only one _Sequence_ field in the Metadata Sections of all CRs may be non-zero, and `aceactivecr` must match the number of that CR.

Any deviation from these behaviors raises an illegal instruction exception.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

//

// ////////////////////////////////////////////////////////////////////

[[ACE-instructions-detailed]]
=== Instructions

[WARNING]
====
The encodings presented here are preliminary.
====

ACE provides a number of unprivileged instructions.
This section specifies their semantics and encodings.

The notation `K(Xd)` denotes the CR whose index is held in GPR `Xd`. `Kn|K(Xn)`
indicates two alternative encodings: a 5-bit immediate CR index (`Kn`) or a CR
number supplied by GPR `Xn`. Use of the zero register `X0` as a CR index
register raises an illegal instruction exception unless explicitly indicated
otherwise.

Each instruction is characterized by the following properties:

* _Modifies state_: whether the instruction may modify ACE architectural state;
* _Usage-controlled_: whether the instruction is subject to usage control
  policies (_UsagePolicy_);
* _Trappable_: whether the instruction may be implemented by privileged code
  via trap-and-emulate; and
* _Interruptible_: whether execution may be interrupted (e.g., by a context
  switch or page fault) and later resumed or restarted.

NOTE: Trappability refers solely to the CPU-side implementationŌĆöfor example, to
enable decomposition of certain ACE instructions into smaller custom
operations. This is distinct from custom algorithm implementations within the
ACE unit itself (e.g., via a secure embedded CPU with updatable firmware),
which are outside the scope of this specification.

NOTE: ACE does not have concepts of
Element Group Width, Effective Element Width,
and
Element Group Size like the vector crypto extension.
Because of the fact that the architecture decouples instructions like `ace.exec` from the
actual operations, the high level architecture of ACE only needs to know the total size
of the inputs and output, which is `ACELEN`, namely either `VL*SEW` or the length
`aceiobuftop` of the ACEIOBUF as defined in <<ACE-notation>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-init]]
==== ace.prov

_Synopsis_::
Provision Metadata and secrets into a CR.

_Mnemonic_::
`ace.prov Kd|K(Xd), %offset(Xs)`
(((ACE, instruction, ace.prov)))

_Encoding_::
`ace.prov` is an I-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x0b, attr: ['custom-0'] },
    { bits:  5, name: 'context', attr: ['Kd','K(Xd)'] },
    { bits:  3, name: 'ace.prov', attr: [0x4,0x5] },
    { bits:  5, name: 'Xs' },
    { bits: 12, name: 'immed12', attr: ['offset'] },
]}
....

_Description_::
`ace.prov` provisions a CR with Metadata and Content to create a CC. `Kd` or
`K(Xd)` denotes the CR to be provisioned. `Xs` points to the region of memory
containing the Metadata and the key material. The PI must be stored at an
8-byte aligned address.
+
If the instruction fails, the target CR is unconfigured, with the same
semantics as if `ace.clear` were invoked on the same CR
(<<ACE-instruction-clear>>).
+
If the combination of _Algorithm_, _AlgorithmPolicy_, and _SCProtection_ is not supported, exception `ace_exc_invalid` may be raised as defined in the Privileged Architecture.
The handler may simply set the CR to error state `ace_state_not_impl` and return to the original control flow.
+
Exception `ace_exc_invalid` is raised if the Metadata is invalid (other
than unimplemented algorithm), such as, for instance: a nonzero _State_ or
reserved field; or an unsupported _Locality_ value.
The handler may simply set the CR to error state `ace_state_invalid` and
return to the original control flow.
+
Similarly to vector load instructions, `ace.prov` appears to other harts as a sequence of individual loads.
+
The operation is described in detail in <<ACE-provisioning-export-import>>.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
Trappable: *YES*. +
Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

NOTE: `ace.prov`, like `ace.import`, `ace.export`, `ace.input`, and
`ace.output`, which are described later, can be viewed as special kinds of load
and store instructions, and therefore they do not violate the load/store
architecture principle.

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clear]]
==== ace.clear/ace.reset

_Synopsis_::
Clears and unconfigures a CR, or the ACE state.

_Mnemonic_::
`ace.clear Kd|K(Xd)` +
(((ACE, instruction, ace.clear)))
`ace.reset`
(((ACE, instruction, ace.reset)))

_Encoding_::
`ace.clear`/`ace.reset` are pseudo instructions, implemented as `ace.setst` (see <<ACE-instruction-setst>>) with no auxiliary operands, and the immediate for _State_ set to `ace_state_off` (i.e., 0).

_Description_::
`ace.clear` unconfigures the state of the CR `Kd` or `K(Xd)` and releases its resources in the CRF.
+
`ace.reset` unconfigures all the CRs and the ACEIOBUF.
It uses the encoding of `ace.setst` described above with indirect CR addressing and `Xd` = `X0`.

_Properties_::
Possibly modifies state: `ace.clear` only makes any status flag (global of
per-CR) Dirty if the CR was configured before. Usage-controlled: *NO*. +
Trappable: +
``{fournbsp}ace.clear``: *NO*; +
``{fournbsp}ace.reset``: *YES* (it can be implemented as multiple `ace.clear`
and a write to `aceiobuflen`). +
Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-export]]
==== ace.export

_Synopsis_::
Export a CR as a SCC in memory.

_Mnemonic_::
`ace.export %offset(Xd), Ks|K(Xs)`
(((ACE, instruction, ace.export)))

_Encoding_::
`ace.export` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 'ace.export', attr: [0x0,0x1] },
    { bits:  5, name: 'Xd' },
    { bits:  5, name: 'context', attr: ['Ks','K(Xs)'] },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Description_::
Exports the CR `Ks` or `K(Xs)` to memory at address `Xd`, using the procedure
described in <<ACE-provisioning-export-import>>. The SCC must be stored at an
8-byte aligned address.
+
`ace.export` appears to other harts as a sequence of individual stores.
+
The operation is described in detail in <<ACE-provisioning-export-import>>.

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +
Trappable: *YES*. +
Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-import]]
==== ace.import/ace.import.S

_Synopsis_::
Import a SCC from memory into a CR.

_Mnemonics_::
`ace.import{nbsp}{nbsp}{nbsp}Kd|K(Xd), %offset(Xn)` +
`ace.import.S{nbsp}Kd|K(Xd), %offset(Xn)`
(((ACE, instruction, ace.import)))
(((ACE, instruction, ace.import.S)))

_Encoding_::
`ace.import` is an I- (or R-) type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x0b, attr: ['custom-0'] },
    { bits:  5, name: 'context', attr: ['Kd','K(Xd)'] },
    { bits:  3, name: 'ace.import', attr: ['0┬Ā┬Ā┬Ā┬Ā0┬Ā┬Ā┬Ā┬ĀS','0┬Ā┬Ā┬Ā┬Ā1┬Ā┬Ā┬Ā┬ĀS'] },
    { bits:  5, name: 'Xn' },
    { bits: 12, name: 'immed12' },
]}
....

_Description_::
`Kd` or `K(Xd)` denotes the CR into which the SCC is to be imported. `Xn` is
the GPR containing the base address of the buffer with the source SCC. The SCC
base address must be 8-byte aligned.
+
If the instruction fails, the target CR is unconfigured, with the same
semantics as if `ace.clear` were invoked on the same CR
(<<ACE-instruction-clear>>).
+
If the combination of _Algorithm_,
_AlgorithmPolicy_, and _SCProtection_ is not supported, exception `ace_exc_invalid` may be raised as defined in the Privileged Architecture.
The handler may simply set the CR to error state `ace_state_not_impl` and return to the original control flow.
+
Exception `ace_exc_invalid` is raised if the Metadata is invalid (other than unimplemented algorithm),  such as, for instance: nonzero bits in reserved fields;
unsupported _Locality_ value;
or an undefined value of _State_ for the _Algorithm_ and _AlgorithmPolicy_.
+
The bit S takes the values 0 (false) or 1 (true). It is set to true if the key
is in a system-defined format (`ace.import.S`) and not the format defined by
the present architecture (`ace.import`).
+
`ace.import` appears to other harts as a sequence of individual loads.
+
The operation of `ace.import` is described in detail in
<<ACE-provisioning-export-import>>.
+
The behavior of `ace.import.S` is implementation-defined. If there are no
system-defined formats, `ace.import.S` raises an illegal instruction exception.

NOTE: The instruction encoding includes a single bit to indicate a
system-defined format. If multiple system-defined formats are supported, the
system is responsible for distinguishing them. These formats do not necessarily
include the key value itself, they may contain a ŌĆ£recipeŌĆØ for an
implementation-defined mechanism to generate the key. Such system generated
keys are system-specific and the ŌĆ£recipeŌĆØ is in general not portable. After
internal key generation, the actual key valueŌĆönot the recipeŌĆöis stored in the
CR and SCC. For all keys provisioned using `ace.import.S`, the _KeyType_ field
in the Metadata is 0, denoting a key represented by value.

NOTE: The `ace.export` instruction does not have an `ace.export.S` analog to
`ace.import.S`. This means that system-specific dynamically generated keys can
be imported but not exported in the same form: they must be exported in the
format architected here for ACE CCs.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
Trappable: *YES*. +
Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-exec]]
==== ace.exec

_Synopsis_::
Perform a cryptographic operation in the ACE unit.

_Mnemonic_::
The `ace.exec` instruction admits four Forms, namely
(((ACE, instruction, ace.exec)))

[upperalpha]
. `ace.exec  Vd, Kn|K(Xn), Vs` {nbsp}{nbsp} takes an input vector and writes to an output vector.
. `ace.exec  {nbsp}{nbsp}{nbsp}{nbsp}Kn|K(Xn), Vs` {nbsp}{nbsp} takes an input vector but does not write to an output vector.
. `ace.exec  Vd, Kn|K(Xn){nbsp}{nbsp}{nbsp}{nbsp}` {nbsp}{nbsp} does not take an input but writes to an output vector.
. `ace.exec  {nbsp}{nbsp}{nbsp}{nbsp}Kn|K(Xn){nbsp}{nbsp}{nbsp}{nbsp}` {nbsp}{nbsp} does not take an input vector and does not write to an output vector.

// Without this comment, the next part is not properly formatted...

_Encoding_::
`ace.exec` is an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'rd', attr: ['Vd','ŌĆö','Vd','ŌĆö'] },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Kn|K(Xn)'] },
    { bits:  5, name: 'rs2', attr: ['Vs','Vs','ŌĆö','ŌĆö'] },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 'Form', attr: ['0┬Ā┬Ā┬Ā┬Ā0','0┬Ā┬Ā┬Ā┬Ā1','1┬Ā┬Ā┬Ā┬Ā0','1┬Ā┬Ā┬Ā┬Ā1'] },
    { bits:  2, name: 0x0 },
]}
....
+
Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an
immediate, and it takes the value 1 if a GPR (scalar integer value) is used to
reference it.
+
For the four Forms AŌĆōD above, the encodings are:
+
[upperalpha]
. `Form` = `0b00`.
. `Form` = `0b01` and `rd` = `0b00000`.
. `Form` = `0b10` and `rs2` = `0b00000`.
. `Form` = `0b11` and `rs2` = `rd` = `0b00000`.

// To make indent in next line correct

_Description_::
Performs a cryptographic operation such as an encryption or decryption,
absorbing a value in a hash, an elliptic curve point addition or scalar
multiplication, etc., and possibly returning a value.
+
If the V extension register file is not implemented, only Form D `ace.exec`
is supported and `ace.input`, `ace.output` are used to provide inputs and
extract outputs from `ace.exec`, as described in <<ACE-usage-input-output>>.

// As a rule,

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
Trappable: *NO*. +
Interruptible: See interruptibility rules in <<ACE-generic-rules>>. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv` (Forms A-D)    | v0.0.0          | --
| `Zlio` (Forms D)     | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-setst]]
==== ace.setst

_Synopsis_::
Change the state of the algorithm encoded in the CC in a CR.

_Mnemonic_::
The `ace.setst` instruction admits three Forms, namely
(((ACE, instruction, ace.setst)))

[upperalpha]
. `ace.setst Kd|K(Xd), #immed7{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.setst Kd|K(Xd), #immed7, Xs{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.setst Kd|K(Xd), #immed7, Vs{nbsp}{nbsp}` with an auxiliary input in a vector register.

//

_Encoding_::
`ace.setst` is an R-type instruction.
+
[wavedrom, ,svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 'ace.setst', attr: ['0┬Ā┬Ā┬Ā┬Ā0┬Ā┬Ā┬Ā┬Ā1','0┬Ā┬Ā┬Ā┬Ā1┬Ā┬Ā┬Ā┬Ā0','0┬Ā┬Ā┬Ā┬Ā1┬Ā┬Ā┬Ā┬Ā1'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'rs1', attr: ['ŌĆö','Xs','Vs'] },
    { bits:  7, name: 'immed7' },
]}
....
+
The encodings for the three Forms are:
[upperalpha]
. `ace.setst` = `0b001`.
. `ace.setst` = `0b010`.
. `ace.setst` = `0b011`.

// ////////////////////////////////////////////////////////////////////

_Description_::
The instruction is used to modify the _State_ field of the metadata of the CR `Kd` or `K(Xd)`.
This can be used to move from one stage of an algorithm to another-for example, advancing from initialization to data absorption in a hash function, then to finalization and output of the digest.
 +
The `#immed` operand is a constant from a set of admissible values defined for each algorithm. Optionally, `Xs` or `Vs` contain an auxiliary input.
 +
If the `#immed` is zero, i.e., the value corresponding to the _Off_ state, the CR is cleared.
 +
It is always allowed to use an error state (see <<ACE-states-error>>) for the
`#immed`. This will also invalidate the contents of the CR and possibly release them.
Setting an error state does _not_ however trigger an exception, even if reaching
that state implicitly would normally do. This does not prevent further usage of
the same CR from raising exceptions (for instance by issuing an `ace.exec` instruction later).
 +
In these last two cases, the internal ACE memory used by Contents of the CR
may also be released, including any Additional Data, in which case the
_AddDataSize_ field of the metadata will be set to zero.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
Trappable: *NO*. +
Interruptible: *NO*. +

// The state numbers used in this specification are defined in <<ACE-states-valid>> and <<ACE-state-constants-symmetric>>.

It is allowed to repeat `ace.setst` instructions to the current state. When the
algorithm needs to prevent this, it will automatically transition to a
different state after completing `ace.setst`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
| Extension | Minimum version | Lifecycle state
| `Zlv`     | v0.0.0          | --
| `Zlio`    | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getmd]]
==== ace.getmd

_Synopsis_::
Read the Metadata Header of a CR.

_Mnemonic_::
`ace.getmd Xd, Ks|K(Xs)`
(((ACE, instruction, ace.getmd)))

_Encoding_::
`ace.getmd` is an R-type instruction and its encoding is a variant of Form C `ace.exec`.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Ks|K(Xs)'] },
    { bits:  5, name: 0x00  },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 0x2 },
    { bits:  1, name: 0x1 },
    { bits:  1, name: 0x0 },
]}
....
+
Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an
immediate, and it takes the value 1 if a GPR (scalar integer value) is used to
reference it. The instruction differs from Form C `ace.exec` in two ways: the
destination is a GPR and Bit 30 is set to 1.

_Description_::
+
--
On RV64, `d` must be even.
The instruction copies bits [63:0] of
the Metadata Header of a CR `Ks` or `K(Xs)` into GPR `Xd`.
and bits [126:64] into GPR `X[d+1]`.

On RV32, `d` must be a multiple of 4.
The instruction copies bits [31:0] of the Metadata Header of a CR `Ks` or `K(Xs)` into GPR `Xd`.
bits [63:32] into GPR `X[d+1]`,
bits [95:64] into GPR `X[d+2]`,
and bits [127:96] into GPR `X[d+3]`.
--
+

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +
Trappable: *NO*. +
Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getst]]
==== ace.getst

_Synopsis_::
Returns the _State_ field of the metadata of the source CR.
This is useful to determine whether a CR is in an error state, as defined in <<ACE-State-field>>.

_Mnemonic_::
`ace.getst Xd, Ks|K(Xs)`
(((ACE, instruction, ace.getst)))

_Encoding_::
The operations is a pseudo-instruction.

_Description_::
`ace.getst` is implemented as a read of the source CR's metadata using `ace.getmd`
followed by logical or bit manipulation instructions to extract the _State_ field of the latter.
Onb RV64, the operations are, essentially:

 . `ace.getmd Xd, Ks` or `K(Xs)`
 . `srli  Xd, Xd, 20`
 . `andi  Xd, Xd, 0x1F`

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-restrict]]
==== ace.restrict

_Synopsis_::
Restrict the policies encoded in a CC in a CR.

_Mnemonic_::
`ace.restrict{nbsp}{nbsp}Kd|K(Xd), Xs1`
// `ace.restrict{nbsp}{nbsp}Kd|K(Xd), Xs1, Xs2`
(((ACE, instruction, ace.restrict)))

// Without this comment, the next part is not properly formatted...
_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 equal to 1 and
`func2` equal to 1. It is thus an R-type instruction. The source register field
encodes a GPR and not a vector register.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'Xs1' },
    { bits:  1, name: 0x1 },
    { bits:  1, name: 'r' },
    { bits:  3, name: 0x0 },
    { bits:  2, name: 0x1, attr: ['func2'] },
]}
....
+
Bit r (i.e., bit 26) takes the value 0 if the context is encoded as an
immediate in Bits [11:7], and it takes the value 1 if a GPR (also encoded in
[11:7]) is used to reference it.

// comment

_Description_::
+
--
This instruction can be used to:

* Activate the side-channel protection of the CC or increase it;
* Restrict the use of encryption or decryption in a CC that allows both;
* Restrict the usage of a CC (as stored in a CR) to specific modes; and
* Add a Locality or replace a Locality with a stricter one.

Let `mh` be the Metadata Header of the CC in the destination CR.

On RV64, the semantics of the instruction are:

* `Xs` follows the format of the Metadata Header.
Only the fields _AlgorithmPolicy_, _SCProtection_, _Locality_, _UsagePolicy_,
and _ExpirationDate_ of `Xs` may be defined. All other fields must be 0, else
exception `ace_exc_invalid` is raised.

* `Xs`._AlgorithmPolicy_ is used to set the new `mh`._AlgorithmPolicy_ of the
  CR. No currently disabled operation may be enabled, any attempt to do so raises
  exception `ace_exc_invalid`. In some cases, a zero value is not permitted, such as
  disabling both encryption and decryption.

* `Xs`._SCProtection_ is used to turn on side-channel protection or raise its
  level. Attempting to remove or downgrade side channel protection, or to set a
  non-implemented level raises exception `ace_exc_invalid`.

* If `Xs`._Locality_ is non-zero, then it can be used to restrict the Locality.
  Allowed replacements of Locality are:

 ** _SiPScrt_ {rightarrow} _ChipFamScrt_, _ChipScrt_;
 ** _ChipFamScrt_ {rightarrow} _ChipScrt_;
 ** _OEMScrt_ {rightarrow} _ProdScrt_, _DevScrt_;
 ** _ProdScrt_ {rightarrow} _DevScrt_;
 ** _MLocality_ {rightarrow} _HLocality_, _SLocality_; and
 ** _HLocality_ {rightarrow} _SLocality_.

Then, when the CR is exported as a CR, it will use the new Locality values to
tweak the export and import algorithms. Generalizing the Locality is not
permitted. Attempting to do so raises exception `ace_exc_invalid`.

* A zero in any of the three bits `Xs`._UsagePolicy_ means that the
  corresponding policy is _not_ changed.

* A one in any of the three bits `Xs`._UsagePolicy_ means that usage by the
  corresponding mode is not allowed, and the corresponding bit in the Metadata
  of the destination CC is set to 1.

* If `Xs`._ExpirationDate_ is zero, the corresponding policy in
  `mh`._ExpirationDate_ is _not_ changed.

* A non-zero value in `Xs`._ExpirationDate_ will be copied to
  `mh`._ExpirationDate_, but only if that policy was not already programmed before
  or the original value of `mh`._ExpirationDate_ was equal or larger.
  Otherwise exception `ace_exc_invalid` is raised.
--
+
On RV32:

* `s` must be even, the register pair `X[s]` and `X[s+1]` are read, and
  `(X[s+1] @ X[s])` replaces `Xs` in the RV64 description.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
Trappable: *NO*. +
Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[NOTE]
====
This instruction enables several practical use cases:

*   Enabling side-channel protection when supported by the microarchitecture,
    even if the original CC was not configured with it.
*   Allowing privileged code to give a CC to several processes in a
    fine-grained manner. This can be achieved by cloning the CR and customizing
    the Filter for each clone to an authorized process, or by exporting it with
    a per-process _SSecret_ Locality.
*   Similarly, enabling privileged code to split a CC capable of both
    encryption and decryption into two CCs, one only capable of encryption and
    the other only capable of decryption, thereby creating a one-way channel
    between processes.

The ability to perform such customizations saves both time and computational
resources by avoiding additional round-trips to trusted environments.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clone]]
==== ace.clone

_Synopsis_::
Copy a CR into another CR.

_Mnemonic_::
`ace.clone Kd|K(Xd), Ks|K(Xs)`
(((ACE, instruction, ace.clone)))

_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 equal to 1 and
`func2` equal to 2. The instruction is encoded using the Form D' `ace.exec`
encoding, and is thus an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks|K(Xs)' },
    { bits:  5, name: 0x0 },
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'R' },
    { bits:  2, name: 0x0 },
    { bits:  2, name: 0x2, attr: ['func2'] },
]}
....
+
Bits [27:26], i.e., field `R`, take the following values depending on how the
CRs are given:
+
[upperalpha]
. `00`{nbsp}{nbsp} if the source and the output CRs are both encoded as
  immediate values.
. `01`{nbsp}{nbsp} if the source CR is encoded as immediate and the output CR
  is selected using a GPR.
. `10`{nbsp}{nbsp} if the source CR is selected using a GPR and the output CR
  is encoded as an immediate value.
. `11`{nbsp}{nbsp} if the source and the output CRs are both selected using the
  values of GPRs.

// Comment to ensure proper indentation in the next Description

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *NO*. +
Trappable: *YES*, it can be implemented as an export followed by an import in a handler. +
Interruptible: *NO*. +

_Description_::
Clones source CR `Ks` (or the CR indexed by `Xs`) into destination CR `Kd` (or the CR indexed by `Xd`).

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

////

[[ACE-instruction-derive]]
==== ace.derive
_Synopsis_::
Derive a CR from a source CR, such as a key derivation.
_Mnemonic_::
The `ace.derive` instruction admits three Forms, namely
(((ACE, instruction, ace.derive)))
[upperalpha]
. `ace.derive Kd|K(Xd), Ks1|K(Xs1) {fournbsp}{nbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.derive Kd|K(Xd), Ks1|K(Xs1), Xs2{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.derive Kd|K(Xd), Ks1|K(Xs1), Vs2{nbsp}{nbsp}` with an auxiliary input in a vector register.
_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 equal to 1 and `func2` equal to 3.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x6b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K(Xd)' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks1|K(Xs1)' },
    { bits:  5, name: 'rs2'},
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'R' },
    { bits:  1, name: 'v' },
    { bits:  1, name: 'g' },
    { bits:  2, name: 0x3, attr: ['func2'] },
]}
....
+
Bits [27:26], i.e., field `R`, is encoded exactly as for `ace.clone` (<<ACE-instruction-clone>>).
Bit 28 determines whether a vector register (or register group) is used to pass an auxiliary parameter to the key derivation mechanism or not.
Bit `v` (i.e., bit 28) is 0 for Forms A and B and 1 for Form C. +
Bit `g` (i.e., bit 29) is used to distinguish Form A, with `g` = 0, from Form B, with `g` = 1. +
The value (`g`,`v`) = (1,1) is currently an illegal instruction and reserved for future use.
_Description_::
Derive a new context from an existing one, with its own opaque key material, for instance using a key derivation mechanism.
The behavior of the instruction is not expected to be deterministic.
It can be used multiple times, to generate multiple derived contexts.
_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
Trappable: *NO*. +
Interruptible: *NO*. +

_Included in_::
+--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `ZlSM2c`  v0.0.0          | --
|===
--
+

////

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-size]]
==== ace.size

_Synopsis_::
Return the size of a CC or an error value.

_Mnemonics_::
There are four Forms of the `ace.size` instruction:
(((ACE, instruction, ace.size)))

[upperalpha]
. `ace.size Xd, Ks|K(Xs)` - Size from a context.
. `ace.size Xd, Xs` - Size from Metadata Header.
. `ace.size.internal Xd, Xs` - Internal capacity estimate for a CR.
. `ace.size.iobuf Xd, Xs` - Internal capacity estimate for the ACEIOBUF.

// Without this comment, the next part is not properly formatted...

_Encoding_::
The encoding shares `func3` with `ace.exec`, however with bit 25 (the lsb of
`func7`) equal to 1 and the two msbs of `func7` equal to 0.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks/K(Xs)/Xs' },
    { bits:  5, name: 0x0 },
    { bits:  1, name: 0x1 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 'F' },
    { bits:  2, name: 0x0, attr: ['func2'] },
]}
....
+
The `F` field and the `r` bit may assume the following values:

* `F` = `0b00`, `r` = `0` {implies} Form A: Size from a context given as `Ks`.
* `F` = `0b00`, `r` = `1` {implies} Form A: Size from a context given indirectly as `K(Xs)`.
* `F` = `0b01`, `r` = `0` {implies} Form B: Size from Metadata Header.
* `F` = `0b11`, `r` = `0` {implies} Form C: Internal capacity of the ACEIOBUF.

_Description_:: {empty}

* Form A `ace.size` returns the total size (in bytes) of the memory buffer that
  would be necessary to store the exported SCC, including the authentication tag and the Additional Data.
  Knowing this size is necessary
  for any feature that relies on `ace.export`, including context switching. The
  instruction returns 0 if the CR is unconfigured.

* Form B `ace.size` returns the total size (in bytes) of an SCC having the
  Metadata section given in `Xn` into GPR `Xd` including the Additional Data,
  `NOT(bin(ace_state_not_impl, XLEN))` if the algorithm is not
  supported, and `NOT(bin(ace_state_invalid, XLEN))` if the Metadata is invalid.
 +
On RV32, `s` must be even and `Xs` and `X[s+1]` contain bits [31:0] and [63:32] of the Metadata.

* Form C: The source register contains the desired byte length of the buffer to
  be allocated, and the destination register contains the size of the buffer in
  the ACE unit.

NOTE: In general, no correlation may be assumed between the size of a PI, the
corresponding CR's usage of internal resources, and the size of the SCC.
// The size of the SCC can differ significantly from the internal resource usage to store the CC's data in a CR.
// On one hand, there is an overhead due to the SIV.
// On the other hand, in case of threshold implementations, where keys are exported in reconstructed form, or in modes where some derived keys are not exported, the SCC may be smaller than the internal resource usage.

_Properties_::
Possibly modifies state: *NO*. +
Usage-controlled: *NO*. +
Trappable: *NO*. +
Interruptible: *NO*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv` (Forms A-B)   | v0.0.0          | --
| `Zlio` (Forms A-C)  | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-available]]
==== ace.avail

_Synopsis_::
Verify whether an algorithm is supported.

_Mnemonic_::
`ace.avail Xd, Xs`
(((ACE, instruction, ace.avail)))

_Encoding_::
`ace.avail` is an alias to Form B of `ace.size`, as the latter returns 0 if the
algorithm is not supported.

_Properties_::
Same as `ace.size`.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-input]]
==== ace.input

_Synopsis_::
Load data into the ACEIOBUF.

_Mnemonic_::
`ace.input %offset(Xs), Xl`
(((ACE, instruction, ace.input)))

_Encoding_::
`ace.input` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 0x2, attr: ['ace.input'] },
    { bits:  5, name: 'Xl' },
    { bits:  5, name: 'Xs' },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Description_::
If the vector registers are not sufficiently long, or not implemented, inputs can be read directly from memory and outputs written directly to memory.
For this reason, the architecture defines `ace.input` and `ace.output` (cf. next section).
`ace.input` loads `Xl` bytes from memory starting at address `%offset(Xs)` and copies them to the ACEIOBUF, starting at offset `acestart`.
+
If `Xl` == 0, the operation is a NOP.
+
If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.
+
The intended usage of `ace.input` and `ace.output` is explained in detail in
<<ACE-usage-input-output>>.

If ``aceactivecr``'s value is 32, `ace.output` (see below) and `ace.input`
can be used to save and restore the contents of the ACEIOBUF, for
instance by context switching code.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
Trappable: *YES*. +
Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-output]]
==== ace.output

_Synopsis_::
Save the contents of the ACEIOBUF to memory.

_Mnemonic_::
`ace.output %offset(Xd), Xl`
(((ACE, instruction, ace.output)))

_Encoding_::
`ace.output` is an I-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x3, attr: ['ace.output'] },
    { bits:  5, name: 'Xl' },
    { bits: 12, name: 'immed' },
]}
....

_Description_::
This is the output operation corresponding to `ace.input`.
`ace.output` writes the contents of the input buffer, starting at offset `acestart`, to memory starting at address `%offset(Xs)`.
+
If `Xl` == 0, the operation is a NOP.
+
If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.

_Properties_::
Possibly modifies state: *YES*. +
Usage-controlled: *YES*. +
Trappable: *YES*. +
Interruptible: *YES*. +

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--
+
// ////////////////////////////////////////////////////////////////////

[[ACE-usage-input-output]]
=== Usage of `ace.input` and `ace.output` to Replace Vector Inputs and Outputs

When ACEIOBUF is implemented, in all algorithms the following applies: any
occurrence of the ŌĆ£Original InstructionsŌĆØ in <<ACE-replacement-instructions>>
may be substituted by the corresponding ŌĆ£Replacement SequenceŌĆØ where
`ace.input` and `ace.output` instructions are used in place of the vector
register inputs and outputs.
The use of such Replacement Sequences is implied in all algorithms and not explicitly written each time.

[[ACE-replacement-instructions]]
.Replacement sequences for `ace.exec` and `ace.setst` using `ace.input` and `ace.output`
[float="center",align="center",width="100%",cols="<24%,<38%,<38%",options="header"]
|===
| Instruction and Form | Original Instruction          | Replacement Sequence
| `ace.exec`, Form A   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K(Xn), Vs` | `1: ace.input{nbsp}{nbsp}Xl, %offset(Xs)` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
`3: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.exec`, Form B   | `ace.exec{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}{nbsp}Kn\|K(Xn), Vs`     | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
| `ace.exec`, Form C   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K(Xn)`     | `1: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K(Xn)` +
`2: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.setst`, Form C  | `ace.setst{nbsp}Kd\|K(Xd), #immed, Vs` | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.setst{nbsp}{nbsp}Kd\|K(Xd), #immed` +
// | `ace.derive`, Form C | `ace.derive Kd\|K(Xd), Ks1\|K(Xs1), Vs2` | `1: ace.input{nbsp}{nbsp}%offset(Xs2), Xl` +
// `2: ace.derive{nbsp}Kd\|K(Xd), Ks1\|K(Xs1)` +
|===

The sole functions of `ace.input` and `ace.output` are to supply inputs to cryptographic operations and to read out their outputs. No computation is performed on the data by these instructions. All computations and internal state changes of `ace.exec` and `ace.setst` remain within those operations.

`ace.input` and `ace.output` may be used only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero. Otherwise, exception `ace_exc_buf_unconf` is raised. If `aceiobuflen` is non-zero but the range size `aceiobuftop - acestart` is invalid for the algorithm, exception `ace_exc_invalid` is raised and no cryptographic operation is performed.

The `ace.input` and `ace.output` instructions must be tied to a specific context to determine the allowed sequences.
This is done by setting the `aceactivecr` CSR (<<ACE-CSR-aceactivecr>>).
It is the responsibility of the user to reset it to the value of 32 at the end of the code.

If the execution of any `ace.exec` or `ace.setst` operation leads to an error state for the `aceactivecr` CR, the implementation must reset `aceactivecr` to teh value of 32.

The architecture uses the _Sequence_ field in the metadata field of each CR to track the progress of the replacement sequences.
The initial value of _Sequence_ is 0.
It remains zero while the forms of `ace.exec` and `ace.setst` specified in the algorithm are used.
As soon as one of the following events happens:

. An `ace.input` is completed in place of a Form A or B `ace.exec`, or Form C `ace.setst`; or
. A Form D `ace.exec` is completed in place of a Form C `ace.exec`,

then _Sequence_ is set to 1, to denote that the first instruction in the
replacement sequence has completed, provided that `aceactivecr` is configured
correctly to the CR used in the original instruction, and not 32.
Then, _Sequence_ keeps track of how many instructions of the replacement sequence have been completed.
At the end of the replacement sequence, _Sequence_  is reset to 0.

The ordering of the instructions in a replacement sequence is enforced by the
architecture according to the value of _Sequence_ and the state number of
the CR configured in `aceactivecr`. Not following the instruction ordering
raises an illegal instruction exception and invalidates the CR.

// ////////////////////////////////////////////////////////////////////

[[ACE-interruptibility]]
=== Interruptibility of ACE instructions

`ace.clear`, `ace.reset`, `ace.setst`, `ace.getst`, `ace.restrict`, `ace.clone`, `ace.size` and `ace.avail` are uninterruptible.
`ace.prov`, `ace.import`, `ace.export`, `ace.input`, and `ace.output` may be interrupted.
For `ace.prov`, `ace.import`, and `ace.export`, see <<ACE-provisioning-export-import>>.
For `ace.input` and `ace.output`, the value of `acestart` will reflect the amount of data read or written before the interrupt and resumption will start from that point.

The operation of `ace.exec` on a basic processing unit is uninterruptible, unless explicitly allowed by the algorithm.
In general, most cryptographic primitives cannot be interrupted; therefore, state information to encode round number or round key value is not needed.
For certain very long running operations, such as public key primitives, an algorithm specific interruptibility behavior is defined.

When `ace.exec` processes multiple blocks iteratively, each block is handled atomically but the instruction may be interrupted between blocks.
Upon receiving an interrupt during block processing, the implementation may either
complete the current block before yielding to the interrupt handler
or
discard the partially executed block and restore the state prior to that block's processing.
`acestart` is set accordingly.

// ////////////////////////////////////////////////////////////////////

[[ACE-provisioning-export-import]]
=== Provisioning, Export and Import of Cryptographic Contexts

In this section we implicitly refer throughout to <<ACE-data-formats-intro>>, and in particular to <<ACE-PI>> and <<ACE-SCC>>.

The entire Metadata and Content are authenticated, but only the Content is encrypted.
The AEAD method used for this purpose is described in <<ACE-SCC-AEAD>>.

In an algorithm specification (<<ACE-algorithms>>), under Data Structures there is a section named ŌĆ£Serialized ContentŌĆØ: It defines the structure of the `content[]` array.  Architecturally, `content[]` is the serialization of the content of a CR for export as an SCC.
This array is this the concatenation of the Fixed Data Section and of the Architected and Implementation ADSs.

[NOTE]
--
While `content[]` provides a view of (certain fields of) the content of a CR
that matches the serialized SCC format, it need not be converted to and from
the internal representation and explicitly stored in the ACE unit's memory
before export and after import.

`content[]` is a virtual representation: its byte ordering does not imply
physical contiguity within the CR, nor is there a direct byte-for-byte
correspondence. Changes to `content[]` are reflected in the underlying CR
representation (except for excluded fields), and vice versa.

In a threshold implementation, a single key byte in `content[]` may correspond to multiple bytes distributed across all key shares within the CR.
Reading that byte returns the XOR of the corresponding bytes from the shares, which may not be stored contiguously.
Writing to that byte may trigger multiple writes of single bytes, one per share, such that their XOR equals the input.
Alternatively, these operations may be deferred until the end of a provisioning or import instruction.
For example, writing to `content[]` may initially write the unmasked value to the first share; the remaining shares are generated only when the instruction completes.
--

// ////////////////////////////////////////////////////////////////////

[[ACE-system-keys]]
==== System Keys and Randomly Generated Key Values

In a PI or SCC, System Keys are encoded as a 64-bit index into an internal, system-specific System Keys Table (SKT).
This replaces the key value itself, which may reduce the size of the PI or SCC content.

For threshold implementations of system keys, ACE may copy key material from the SKT into the CR and expand it into multiple shares.
The key is still exported as a single index.

For the purpose of accelerating key share reconstruction in a threshold implementation, some shares of a system key can be included in the content's Additional Data, as long as the key cannot be recovered from those shares alone.

An all-ones (i.e., `ones(64)`) system key index in a PI means that the key material is generated randomly upon provisioning.
The _KeyType_ field in the metadata is then internally set to 0, and the key is then exported by value.
This applies to all keys at once in an algorithms, unless otherwise specified.

// ////////////////////////////////////////////////////////////////////

[[ACE-size-functions]]
==== Notation for the Size Functions

Let `mh` denote a Metadata Header.
In order to determine the total lengths of the PI and of the SCC, the implementation provides the following functions or an equivalent mechanism:

. ``MH_size`` returns the byte length of the Metadata Header. It is always 16.

. ``PI_content_size(mh)`` returns the byte length of the content section of a PI. It depends only on `mh`._Algorithm_, `mh`._AlgorithmPolicy_, and `mh`._KeyType_.

. ``fixed_content_size(mh)`` returns the byte length of the fixed part of the content section of an SCC. It depends only on  `mh`._Algorithm_,
  `mh`._AlgorithmPolicy_, and `mh`._KeyType_. It does not include the length of the Additional Data of the Content, of length _AddDataSize_ * 16 bytes.

The total size in bytes of a PI is therefore

`{fournbsp}{fournbsp}len_in_bytes(PI){nbsp}` = `MH_size` + `PI_content_size(mh)`,

and the total size in bytes of an SCC is

`{fournbsp}{fournbsp}len_in_bytes(SCC)` = `MH_size` + 16 + `fixed_content_size(mh)` + _AddDataSize_ * 16.

// ////////////////////////////////////////////////////////////////////

[[ACE-interruption-points]]
==== Interruptibility of Configuration and Export Operations

During `ace.prov` and `ace.import`, _State_ is set to _Partial_Config_ for the duration of the operation. It is updated to the correct value only upon successful completion (see <<ACE-provisioning-export-import>>).

This transition to _Partial_Config_ does not occur during `ace.export`.

Provisioning and import instructions may resume from the point of interruption only if control returns directly after the interrupt handler completes.
This is characterized by a CR with _State_ set to _Partial_Config_ and a nonzero `acestart` value.
The privileged interrupt handler must guarantee restart only in this case.

A partially configured CR cannot be exported.
Therefore, at context save privileged code must clear a partially configured CR.
Before returning control flow to the process of the interrupted configuration operation, the CR must be cleared as well to force the instruction's restart.

Provisioning, export, and import are interruptible only before any memory access they perform.
This means that interrupts other than memory exceptions must wait until the next memory access, or can be served immediately provided
the CR is reverted to the last interruptible point.

Upon returning to the original control flow from an interrupt or exception,
an export may resume only if the CR has not been modified.
The mechanism to enforce this rule is described in <<ACE-SCC-export>>.

The rules for resuming configuration and export operations imply that these
can only occur on the same hart where they have been interrupted. In particular,
these resumptions can only occur on the same microarchitecture and therefore
the implementation can define arbitrary interruption points and corresponding
non-zero values of `acestart`.

// ////////////////////////////////////////////////////////////////////

[[ACE-provisioning]]
==== Provisioning

We start with the algorithm performed by `ace.prov`, which loads a PI and uses
it to provision a CR.

[[ACE-provisioning-listing]]
.Provisioning a CR with Metadata and content
[]
----
function ace.prov(&CR, M[]) ={
  mh : bits(128) ŌåÉ & CR.Metadata;           // By reference, from the CR

  mh ŌåÉ M[0 .. 7]
  z ŌåÉ PI_content_size(Metadata[31:0]);

  CR.Metadata.State ŌåÉ ace_state_partial_config;

  if (there is not enough memory for the algorithm encoded in the Metadata)
    raise exception ace_exc_out_of_mem;

  if (Metadata is inconsistent)
    raise exception ace_exc_invalid;

  // Complete Metadata parsing.
  // Deserialize the z bytes at M+16.

  CR.Metadata.State ŌåÉ ace_state_initial;
}
----

// ////////////////////////////////////////////////////////////////////

[[ACE-SCC-AEAD]]
==== Key Derivation and POLYVAL

AES-GCM-SIV cite:[DBLP-journals-iacr-GueronLL17,RFC8452] is used to export and
import CRs.

[WARNING]
AES-GCM-SIV has been chosen because it only required single passes of data in
main memory, reducing the number of external memory accesses. GCM uses also a
single pass but requires separate nonce and tag values, increasing the size of
the exported data by one block.

We define the Key Derivation (<<ACE-SCC-RFC8452-derivation>>) and POLYVAL
(<<ACE-SCC-POLYVAL>>) functions first. The generation of an SCC from a CR
(<<ACE-SCC-export>>) and the import of an SCC into a CR (<<ACE-SCC-import>>)
are defined next.

[[ACE-SCC-RFC8452-derivation]]
.RFC8452 Key Derivation
[]
----
function RFC8452_KeyDeriv(key : bits(256)) =
{
  struct {
    AESE256(key, (zeros(125) @ 0b101))[63:0] @ AESE256(key, (zeros(125) @ 0b100))[63:0] @
    AESE256(key, (zeros(125) @ 0b011))[63:0] @ AESE256(key, (zeros(125) @ 0b010))[63:0],
    AESE256(key, (zeros(125) @ 0b001))[63:0] @ AESE256(key, (zeros(125) @ 0b000))[63:0]
  }
}
----

NOTE: Due to the computational cost of the derivation functions,
implementations may cache recently used derived keys.

`POLYVAL` is a so-called Almost XOR-Universal (AXU) Hash Function.
The SIV is the encryption of the computation of this AXU hash on the concatenation of the Locality Secrets, the Metadata zero-padded to 128 bits, and the Content of the CR. In the pseudocode below for POLYVAL, the digested data is an array with an integral number of 16-byte blocks.

[[ACE-SCC-POLYVAL]]
.Polyval Hashing Function
[]
----
function POLYVAL(&tmp : bits(128), auth_key : bits(128), blocks[0..n-1] : bits(128)) =
{
  tmp ŌåÉ zeros(128);
  local i : int;
  foreach(i from 0 to n-1) {
    tmp ŌåÉ tmp xor blocks[i];
    tmp ŌåÉ Montmul(tmp, auth_key);
  }
}
----

[[ACE-SCC-export]]
==== Export

During SCC export and import, the Locality Secrets associated with the
Localities encoded in the _Locality_ field of the Metadata are prepended, in ascending index order, to the input of the AEAD tag computation, before the metadata.
If the _Locality_ field is zero, no Locality Secrets are prepended.

The ACE architecture supports only one export/import operation per hart at a time.
Accordingly, an implementation will maintain only a single per hart instance of variables for `SIV` and `tmp`.
The implementation maintains information to track an export in progress:
a 1-bit flag `ace_exporting` and a 5-bit value `ace_exported_cr` recording the number of the CR being exported.
`ace_exporting` and `ace_exported_cr` are set when an export is started, and cleared when it is completed.
If the export is interrupted, `acestart` is set accordingly.
When this flag is set, any instruction that modifies the internal state of CR number `ace_exported_cr` clears `ace_exporting`.
Export may be resumed only if the flag is set and only for the recorded CR.
Otherwise the export is restarted and `acestart` is ignored.
Without this protection, resuming an export could produce an incorrect SIV for the remaining SCC data.

[[ACE-SCC-export-listing]]
.Generation of an SCC from a CR
[]
----
function ace.export(&CR, M[]) =
{
  mh : bits(128) = & CR.Metadata;          // By reference, from the CR
  external CSK : bits(256);
  external enc_key : bits(256);            // RFC8452_KeyDeriv(CSK)
  external auth_key : bits(128);

  external SIV, tmp : bits(128);
  local z : int ŌåÉ fixed_content_size(mh);  // can be recomputed upon resumption
  z ŌåÉ z + mh._AddDataSize_ * 16;

  CR.content = array of z bytes; // includes the Additional Data
  // In external memory: Metadata Header, then SIV, then Content
  M = array of (MH_size + 16 + z) bytes.

  local let num_blocks : int ŌåÉ ceil(z / 16);
  local L : string of bits;

  // Start POLYVAL
  // Absorb Locality "prefix" (zero or more bit blocks)
  tmp ŌåÉ zeros(128);
  foreach(i from 0 to number of localities - 1)
    if (CR.Metadata.Locality includes locality[i]) {
      tmp ŌåÉ tmp xor LST[i];
      tmp ŌåÉ Montmul(tmp, auth_key);
    }

  // Absorb the metadata block into POLYVAL
  tmp ŌåÉ tmp xor mh;
  tmp ŌåÉ Montmul(tmp, auth_key);

  // Absorb the entire content into POLYVAL
  foreach(i from 0 to num_blocks - 1) {
    tmp ŌåÉ tmp xor CR.content[i*16 .. 15+i*16];
    tmp ŌåÉ Montmul(tmp, auth_key);
  }
  // compute the SIV
  SIV ŌåÉ AESE(enc_key, 0 @ tmp[126:0]);

  // Export metadata and the SIV to memory
  M[0 .. 7]  ŌåÉ mh;
  M[8 .. 23] ŌåÉ SIV;

  //
  foreach(i from 0 to num_blocks - 1) {
    M[24+i*16 .. 39+i*16] ŌåÉ CR.content[i*16 .. 15+i*16]
            xor AESE(enc_key, 1 @ SIV[126:32] @ (SIV[31:0]+bin(i,32) % 2**32);
  }
}
----

// ///////////////////////////////////////////////////////////////////

[[ACE-SCC-import]]
==== Import

The import algorithm needs some special care:

* At the beginning of the import operation, the hardware saves the value of
  `State` from the original metadata and sets `mh.State <-
  ace_state_partial_config`. At the end of the import operation, `mh.State` is
  set to the saved value.
* The SCC to be imported may have been generated by a different implementation
  than the one importing it. This is detected by an `acemarchid` mismatch.
  In this case, the SCC may even contain an Implementation-Specific ADS
  that exceed the maximum size supported by the importing hardware for the
  specific algorithm encoded in the Metadata.
  Once the Metadata and the Fixed Content Data Sections have been
  read, the implementation must determine the length of the Architected ADS
  corresponding to the algorithm's state, and ignore all writes to `content[]`
  beyond the end of the Architected ADS in case there is an `acemarchid` mismatch.
  It must still process the entire SCC to verify the authentication tag.
  After successful verification, the _AddDataSize_ field will be adjusted
  to the size of the Architected ADS.
  The Implementation-Specific ADS will be ignored.
  The details of this adjustment are not reflected in the pseudocode
  <<ACE-SCC-import-listing>> to avoid excessive complexity.

[[ACE-SCC-import-listing]]
.Importing an SCC into a CR
[]
----
function ace.import(&CR, M[]) =
{
  // M : array of bytes;   from memory
  local saved_SN : bits(4);                // This is a "hidden" state as well
  external SIV, tmp, t2 : bits(128);

  external CSK : bits(256);
  external enc_key : bits(256);
  external auth_key : bits(128);

  tmp ŌåÉ M[0 .. 15];         // read Metadata Header

  saved_SN ŌåÉ ((Metadata field)tmp).State;
  CR.Metadata ŌåÉ tmp;
  CR.Metadata.State ŌåÉ ace_state_partial_config;

  & mh = CR.Metadata;

  z ŌåÉ fixed_content_size(mh);
  z ŌåÉ z + mh._AddDataSize_ * 16;

  if (there is not enough memory for the algorithm encoded in the Metadata)
    raise exception ace_exc_out_of_mem;

  num_blocks ŌåÉ ceil(z / 16);

  // Start POLYVAL
  // Absorb Locality "prefix" (zero or more 128-bit blocks)
  tmp ŌåÉ zeros(128);
  foreach(i from 0 to number of localities - 1) {
    if (CR.Metadata.Locality includes locality[i]) {
      tmp ŌåÉ tmp xor LST[i];
      tmp ŌåÉ Montmul(tmp, auth_key);
    }
  }

  SIV ŌåÉ M[8 .. 23];
  tmp ŌåÉ tmp xor mh;
  tmp ŌåÉ Montmul(tmp, auth_key);

  foreach(i from 0 to num_blocks - 1) {
    t2 ŌåÉ M[24+i*16 .. 39+i*16]
         xor AESE(enc_key, 1 @ SIV[126:32] @ (SIV[31:0]+bin(i,32) % 2**32);
    content[i*16 .. 15+i*16] ŌåÉ t2;
    tmp ŌåÉ tmp xor t2;
    tmp ŌåÉ Montmul(tmp, auth_key);
  }
  tmp ŌåÉ AESE(enc_key, 0 @ tmp[126:0]);

  if (tmp != SIV) {
    mh ŌåÉ zeros(128)
    mh.State ŌåÉ ace_state_import_auth
    Clear all Contents and possibly release their memory
    return
  }

  // Now the content can be deserialized.
  // This includes computing any derived values not saved as part of the SCC,
  // as well as creating shares for threshold implementations.

  // FINALLY, restore the State from the SCC
  mh.State ŌåÉ saved_SN;
}
----

// ////////////////////////////////////////////////////////////////////
