// ////////////////////////////////////////////////////////////////////

[[ACE-algorithms]]
== Book 2: Algorithms

_This chapter is normative._

This chapter specifies the behavior of the ACE instructions for the supported
cryptographic algorithms. Some specifications define algorithm families
instantiable with any primitive meeting certain properties—typically,
constraints on block size `b` and key size `k`. For example, GCM and GCM-SIV
are well defined not only with AES but also with other block ciphers such as
SM4. In contrast, other algorithm suites are tied to specific primitives, for
instance Ascon.

<<ACE-exec-encodings>> defines the encoding of symmetric
algorithms in the MDH field _Algorithm_.
The encoding uses two sub-fields: _Type_ in bits [5:0] and _Mode_ in bits [10:6].
Bit 11 is zero.
Other groups of algorithms may subdivide the _Algorithm_ field differently.
The suffix "(reserved)" indicates that the algorithm's specification
is not yet complete or contains ambiguities.

[[ACE-exec-encodings]]
.Algorithm Type and Mode Encodings
[float="center",align="center",width="72%",cols="^8%,^8%,<28%,<28%",options="header"]
|===
| Type | Mode | Algorithm name             | Extensions Requirement
| 0    | 0    | `AES128_ECB`               | `Zlaes128p`
| 0    | 1    | `AES128_CTR`               | `Zlaes128p` and `Zlctrm`
| 0    | 2    | `AES128_LFSR` (reserved)   | `Zlaes128p` and `Zlctrm`
| 0    | 3    | `AES128_XCTR`              | `Zlaes128p` and `Zlxctrm`
| 0    | 4    | `AES128_XLFSR` (reserved)  | `Zlaes128p` and `Zlxctrm`
| 0    | 5    | `AES128_XEX1` (one key)    | `Zlaes128p` and `Zlxexm`
| 0    | 6    | `AES128_XEX2` (two keys)   | `Zlaes128p` and `Zlxexm`
| 0    | 7    | `AES128_GCM`               | `Zlaes128p` and `Zlgcmm`
| 0    | 8    | `AES128_GCM_IV`            | `Zlaes128p` and `Zlgcmm`
| 0    | 9    | `AES128_GCM_SIV`           | `Zlaes128p` and `Zlgcmsivm`
| 0    | 10   | `AES128_CMAC`              | `Zlaes128p` and `Zlcmac`
| 0    | 11   | `AES128_OCB`               | `Zlaes128p` and `Zlocbm`
| 0    | 12   | `AES128_OCB_IV`            | `Zlaes128p` and `Zlocbm`
//
| 1    | 0    | `AES192_ECB`               | `Zlaes192p`
| 1    | 1--12 2+| Analogues to Modes 1--11 for `AES128`, but with 192 replacing 128.
//
| 2    | 0    | `AES256_ECB`               | `Zlaes256p`
| 2    | 1--12 2+| Analogues to Modes 1--11 for `AES128`, but with 256 replacing 128.
//
| 3    | 0    | `SM4_ECB`                  | `Zlsm4p`
| 3    | 1--10 2+| Analogues to Modes 1--10 for `AES128`, but with `SM4`, resp., `sm4` replacing `AES128`, resp., `aes128`.
//
| 4    | 0    | `SHA2-224`                 | `Zlesha2h`
| 4    | 1    | `SHA2-256`                 | `Zlesha2h`
| 4    | 2    | `SHA2-384`                 | `Zlesha2h`
| 4    | 3    | `SHA2-512`                 | `Zlesha2h`
| 4    | 4    | `SHA2-512/224`             | `Zlesha2h`
| 4    | 5    | `SHA2-512/256`             | `Zlesha2h`
| 4    | 6    | `SHA2-224_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 7    | `SHA2-256_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 8    | `SHA2-384_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 9    | `SHA2-512_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 10   | `SHA2-512/224_HMAC`        | `Zlesha2h` and `Zlhmacm`
| 4    | 11   | `SHA2-512/256_HMAC`        | `Zlesha2h` and `Zlhmacm`
//
| 5    | 0    | `SHA3-224`                 | `Zlesha3h`
| 5    | 1    | `SHA3-256`                 | `Zlesha3h`
| 5    | 2    | `SHA3-384`                 | `Zlesha3h`
| 5    | 3    | `SHA3-512`                 | `Zlesha3h`
| 5    | 4    | `SHAKE128`                 | `Zlesha3h`
| 5    | 5    | `SHAKE256`                 | `Zlesha3h`
| 5    | 6    | `SHA3-224_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 7    | `SHA3-256_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 8    | `SHA3-384_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 9    | `SHA3-512_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 10   | `KMAC128`                  | `Zlesha3h` and `Zlkmacm`
| 5    | 11   | `KMAC256`                  | `Zlesha3h` and `Zlkmacm`
//
| 6    | 0    | `SM3`                      | `Zlsm3h`
| 7    | 0    | `Ascon-AEAD128`            | `Zlascon`
| 7    | 1    | `Ascon-AEAD128_Nonce`      | `Zlascon`
| 7    | 2    | `Ascon-AEAD128_Nonce_Mask` | `Zlascon`
| 7    | 3    | `Ascon-Hash256`            | `Zlascon`
| 7    | 4    | `Ascon-XOF128`             | `Zlascon`
| 7    | 5    | `Ascon-CXOF128`            | `Zlascon`
//| 8    | 0    | Move vector register to CR at offset `acestart`, and increment `acestart` by `vl`. | `Zlaes128p`
|===

//

=== Definition of an Algorithm in ACE

Each algorithm is fully defined by the following information:

Parameters:::
+
--
These include:

* The _block size_ `b`, which is the bit length of the basic unit of information
  processed by the algorithm, usually the block size of the main underlying
  primitive;
* The _key size_ `k`, also in bits, for keyed algorithms; and
* Any other parameter needed to instantiate the algorithm with compatible
  primitives.
--
+

Data Structures:::
+
--
These include:

. *Provisioning Input*:
The fields are listed in the order they appear in the PI,
each with its length.

. *Internal State*:
Information maintained in the internal state of a CC.
Field ordering is unspecified, and field lengths may differ from those listed—for example, in threshold or fault-tolerant implementations.
This information is necessary to be able to define the algorithms and their semantics, and must exist internally, though not necessarily in a prescribed format.
An actual implementation may define the internal state and the behavior at each state in a different way, however the semantics of the algorithm must be equivalent to those defined in this specification.

. *Serialized Context*:
The plaintext of the SCC.
The fields are listed in the order they appear in an SCC, each with its length.
--
+

Algorithm-Specific Functions:::
Any other function that is specific to the algorithm.

State Machine:::
+
--
The state machine is defined by the following information:

. A list of *States* in which the internal state machine of the logic is
  executed, together with their representation according to the rules set in
  <<ACE-State-field>>.
. A complete list of the *allowed state transitions*, including the precise
  conditions under which each transition is allowed, the Form of `ace.setst`
  used for each of these transitions and the meaning of any additional
  parameter;
. The enumeration of the *allowed/expected instructions* at each state and their
  *behavior*.
  Besides configuration and export instructions,
  the instructions permitted in each algorithm state are typically `ace.exec` and `ace.setst`.
  For `ace.exec`, only one of its Forms (see <<ACE-instruction-exec>>) is _expected_ per state.
  By this we intend that either the specified Form must be issued, or Form D `ace.exec` or
  Form C `ace.setst` instead, with appropriate setup instructions for the ACEIOBUF.
  Issuing the `ace.input`/`ace.output` instructions are not enforced, as properly
  handling of the inputs and outputs is the responsibility of the caller.
--
+

//

Pseudocode is provided in <<ACE-pseudocode-examples>>
to illustrate the software implementation of ACE-supported algorithms using the ACE ISA.
The pseudocode uses the vector registers and omits the alternative sequences based on ACEIOBUF.
The examples are non-normative.

// ////////////////////////////////////////////////////////////////////

[[ACE-generic-rules]]
=== Generic Rules

. Opening a CR for export and import, as well as `ace.clone`, and `ace.clear` are always allowed in any State, even if not explicitly mentioned in an algorithm specification.

. If a usage instruction that may modify the state of a CR is issued, or a state transition is requested in `ace.setst`, that are not explicitly allowed by the current state of the algorithm encoded in the CC in the CR an _illegal instruction exception_ is raised, and the CR is invalidated.

// ////////////////////////////////////////////////////////////////////

[[ACE-notation]]
==== Notation in the Algorithm Descriptions

* `INPUT`: The input data to be processed by `ace.exec` or `ace.setst`. This
  can be the input vector register, or the ACEIOBUF, as described in
  <<ACE-usage-input-output>>.

* `OUTPUT`: The output data produced by `ace.exec`. This can be the output
  vector register, or the ACEIOBUF, as described in <<ACE-usage-input-output>>.

* `ACELEN`: Either `VL*SEW` or the length `aceiobuftop` of the ACEIOBUF in
  bits, depending on whether vector registers are used or the ACEIOBUF is
  used.

// ////////////////////////////////////////////////////////////////////

[[ACE-rules-system-keys]]
==== Representation of System Keys in the Data Structures

System Keys will change all the algorithms described here in the following way:

. In a PI and in an SCC, the key field will contain the SKID of the system key in place of the value.
. This field is reduced from the original key size to a 64-bit value. This
  saves space in an SCC and allows for faster export and import operations.
. For algorithms that require more than one key, such as XEX/XTS, a single
  SKID is used to refer retrieve multiple keys from the SKS.

=== Padding

As a general rule, inputs shorter than a full vector length must be handled by the caller.
The caller is responsible for proper padding and for passing the actual input length to the algorithm at the appropriate places using the correct instructions, usually `ace.setst`.
An exception applies when an algorithm specification defines such handling itself for cryptographic security reasons.

// ////////////////////////////////////////////////////////////////////

[[ACE-states-symmetric]]
=== States for the Symmetric Algorithms Defined in this Specification

The following table, together with
<<ACE-state-off>>, <<ACE-states-valid>>, and <<ACE-states-error>>,
defines the states used by the symmetric algorithms in this specification.

[[ACE-state-constants-symmetric]]
.Constants defining CC states for symmetric algorithms
[float="center",align="center",width="100%",cols="^6%,<30%,<17%,<47%",options="header"]
|===
| Value | Mnemonic for the Constant         | State Name          | Description
.2+| 2  |  `ace_state_operate`              |  _Operate_          | Generic operational state.
<|  `ace_state_hash_absorb`                 | _Hash_Absorb_       | (Same value as _Operate_. This is just a more intuitive mnemonic for hash functions.)
Start and initialize a hash function of the tag/MAC part of an algorithm and start absorbing blocks of data (in the case of an AEAD algorithm, this usually is the associated data).
|   3   |  `ace_state_hash_last_block`      | _Hash_Last_Block_   | In this state additional data may be absorbed, such as partial blocks and lengths, if the hash/tag algorithm processes the last block of its input or of the associated data part of its input in a different way from the other blocks.
|   4   |  `ace_state_hash_finalize`        | _Hash_Finalize_     | Finalize the internal state of a hash/tag function.
|   5   |  `ace_state_hash_verify`          | _Hash_Verify_       | Compare the internal hash/tag value to the provided one.
|   6   |  `ace_state_hash_output`          | _Hash_Output_       | Enter the hash output phase of a hash/tag function.
|   7   |  `ace_state_encrypt`              | _Encrypt_           | In this state encryption is performed, as well as an update to the tag computation if this operation is part of the algorithm.
|   8   |  `ace_state_decrypt`              | _Decrypt_           | In this state decryption is performed, as well as an update to the tag computation if this operation is part of the algorithm.
|   9   |  `ace_state_enc_last_block`       | _Enc_Last_Block_    | For the encryption path of authenticated encryption modes of operation to process the last block separately.
|  10   |  `ace_state_dec_last_block`       | _Dec_Last_Block_    | For the decryption path of authenticated encryption modes of operation to process the last block separately.
|  11   |  `ace_state_enc_tag_finalize`     | _Enc_Tag_Finalize_  | Finalize the tag computation for AE mode encryption.
|  12   |  `ace_state_dec_tag_finalize`     | _Dec_Tag_Finalize_  | Finalize internal tag computation for AE mode decryption, verify the value.
|  13   |  `ace_state_set_aux_value`        | _Set_Aux_Value_     | Set a public/auxiliary value in an algorithm.
|===

// NOTE: The `ace.setst` instruction used to transition to states _Hash_Absorb_, _Encrypt_, or _Decrypt_ often also sets a public value.
// For algorithms requiring multiple public values or additional parameters (e.g., tag length), these can be set by transitioning to State _Set_Aux_Value_ using a Form of `ace.setst` with an auxiliary argument, i.e., Form B or C.

// ////////////////////////////////////////////////////////////////////

[[ACE-ECB-mode]]
==== Electronic Codebook Modes (Direct Encryption/Decryption)

ECB mode cite:[nist-SP-800-38A-1] is the simplest way to use a block cipher.
(((ACE, algorithm, ECB)))

Parameters:::

* `b` = bit length of a block (8|`b`). `ACELEN` must be a multiple of `b` (including `b`).
* `k` = bit length of a key (8|`k`).

Data Structures:::
* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128            | MDH
|  ii  | `k` or 64      | Key or System Key Identifier
|===
--

 * *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: `k` bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|   i   | 128            | MDH
|  ii   | `k` or 64      | Key or System Key Identifier
|===
--

Algorithm-Specific Functions:::
* `enc_blk(K,p) -> c` encrypts plaintext block `p` using the key `K`, and
  returns the ciphertext result `c`.
* `dec_blk(K,c) -> p` decrypts ciphertext block `c` using the key `K`, and
  returns the plaintext result `p`.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Encrypt_: Encrypting blocks of input.
 ** _Decrypt_: Decrypting blocks of input.

* *Allowed State Transitions:*
 ** From any valid state to _Encrypt_, if encryption is allowed.
 ** From any valid state to _Decrypt_, if decryption is allowed.

* *Behavior:*
 ** In State _Initial_, no `ace.exec` instruction is allowed.
 ** In States _Encrypt_ or _Decrypt_, Form A `ace.exec` instructions can be issued, i.e.,
+
“`ace.exec OUTPUT, Kn|K{Xn}, INPUT`.”

  *** If the state is _Encrypt_, then `OUTPUT <- enc_blk(key, INPUT)`.
  *** If the state is _Decrypt_, then `OUTPUT <- dec_blk(key, INPUT)`.
  *** If `ACELEN` > `b`, then “`ace.exec OUTPUT, Kn|K{Xn}, INPUT`”
      encrypts/decrypts block-by-block. Here, and in the rest of this document,
      this means from the blocks in the least significant positions to the most
      significant positions:
      . `foreach(i from 0 to ACELEN-b by b)` {
      ..   `OUTPUT[i+b-1:i] <- enc_blk(key, INPUT[i+b-1:i])` }

//

In <<ACE-pseudocode-ECB-encryption>> we illustrate how to use an ECB CC to
encrypt a block of data.

// // ////////////////////////////////////////////////////////////////////

[[ACE-chaining]]
==== Chaining/Feedback Modes

There is no need to explicitly architect the behavior of chaining modes, such
as Cipher Block Chaining (CBC), Cipher Feedback (CFB) and Output Feedback
(OFB)–all defined in cite:[nist-SP-800-38A-1]–as they are easily implemented in
software on top of the ECB, with no intermediate value requiring
confidentiality.

// ////////////////////////////////////////////////////////////////////

[[ACE-keystream-modes]]
==== CTR/LFSR/XCTR/XLFSR Keystream Generation

In the “non-X” modes, i.e., CTR mode and its analog with an LFSR replacing the
arithmetic counter, the sum of the lengths of IV and counter/LFSR equals the
block size of the underlying keyed PRP or PRF. IV and counter/LFSR are
concatenated to form the input to the latter.
(((ACE, algorithm, keystream generation)))

In the “X” modes, both IV and counter/LFSR have the same size as the block size
of the underlying keyed PRP or PRF. IV and counter/LFSR are ``xor``ed together
to form the input to the keyed PRP or PRF.

Parameters:::
* `b` = block size (8|`b`). For this algorithm `ACELEN` must be a multiple of `b`.
* `k` = key size (8|`k`).
* `j` = counter size (8|`j`).
* `n` = IV size (8|`n`).
* If the mode is CTR or LFSR, it is `b = n + j`, else it is `b = n = j`.

Data Structures:::
* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|  ii  | `k` or 64     | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: `k` bits.
 ** `IV`: `n` bits.
 ** `ctr`: `j` bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | 128            | MDH
|   ii  | `k` or 64       | `key` or System Key Identifier
|  iii  | `n`             | `IV`
|   iv  | `j`             | `ctr`
|===
--

Algorithm-Specific Functions:::
* `keystream_block(p) -> c` -- usually an encryption function.
* `tick_ctr()` -- updates the `ctr` (either by a modular increment or a LFSR).

State Machine:::
* *States:*
  ** _Initial_: The CC is ready.
  ** _Operate_: In this state the CC will produce a keystream.

* *Allowed State Transitions:* any.

* *Behavior:*
 ** In State _Initial_, the `ctr` and `IV` fields are set to 0 (`ctr` is set to
    1 if the algorithm is LFSR-based).

 ** To transition to State _Operate_, a Form C ``ace.setst`` instruction must
    be issued.
  *** This sets the value of `IV` to `INPUT`.
  *** If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are
      considered.

  ** In State _Operate_, ``ace.exec`` instructions are expected to be of Form C.
     “```ace.exec OUTPUT, Kn|K{Xn}```” performs:
+
--
  . If in a CTR or LFSR mode then `tmp ← keystream_block(IV @ ctr)`,
    else (i.e., if in a XCTR or XLFSR mode) `tmp ← keystream_block(IV xor ctr)`,
  . `tick_ctr()`, and
  . `OUTPUT ← tmp`.
--
+
If `ACELEN` is a multiple of `b`, the above three commands are applied to each
of the `ACELEN/b` `b`-bit blocks of `INPUT`, producing the corresponding `b`-bit
block of `OUTPUT` each time.
// If the number `x` of blocks to be processed in an entire run of the algorithm is not a multiple of `ACELEN`/`b`, `VL` can be set to the remainder of the division of `x` by `ACELEN`/`b` for the last instruction.

Note that if `ace.setst` is issued to return to State _Initial_, the CC can be
reused with a new IV.

Example pseudocode is given in <<ACE-pseudocode-keystream-modes>> (for the case
`b` = `ACELEN` = 128).

// ////////////////////////////////////////////////////////////////////

[[ACE-XEX-XTS-modes]]
==== XEX/XTS modes (one or two keys)

The XTS mode was designed for storage confidentiality
cite:[DBLP-journals-ieeesp-Martin10] and made into a Recommendation by NIST in
2010 cite:[nist-SP-800-38E]. XTS is based on the XEX construction, formalized
by Phillip Rogaway cite:[DBLP-conf-asiacrypt-Rogaway04], to design _Tweakable
Block Ciphers_ cite:[DBLP-conf-crypto-LiskovRW02]. A Tweakable Block Cipher
(TBC) is a block cipher which, besides the key and the plaintext or ciphertext,
also takes a tweak as input. The tweak is used together with the key to select
the permutation computed by the block cipher.

The XEX construction builds a TBC `Ẽ` from a block cipher `E`, with key `K`,
tweak `T`, and plaintext `P`,  as follows: +
 +
`{fournbsp}{fournbsp}`
`Ẽ(K, T, P) = E(K, P xor M) xor M` `{nbsp}{nbsp}` where `{nbsp}{nbsp}` `M = E(K, T)` `{nbsp}{nbsp}` is called a _mask_. +
 +
In XEX mode, once a mask is computed, it is then updated by using a Galois
Multiplication for any successive block instead of updating the tweak and
encrypting it again.

The NIST standard uses two different keys, one for the data encryption path and
one for the encryption of the tweak. The use of a single key or two
independently sampled keys is determined by the algorithm, and it is not a
configuration parameter for the algorithm. We first define XEX mode
functionality.
(((ACE, algorithm, XEX)))

Parameters:::

* `b` = block size (8|`b`). For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = key size (8|`k`).

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)     | Field
|   i   | 128            | MDH
|  ii   | `k` or 64       | `key1` or System Key Identifier
| iii   | `k` or 0        | `key2` or empty if `key1` given
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key1`: `k` bits.
 ** `key2`: `k` bits -- omitted if only one key is used or if both keys come from an entry in the SKS.
 ** `mask`: `b` bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128            | MDH
|  ii  | `k` or 64     | `key1` or System Key Identifier
| iii  | `k` or 0      | `key2` or empty if `key1` given
|  iv  | `b`           | `mask`
|===
--

Algorithm-Specific Functions:::

* `enc_blk(K, p) -> c` encrypts block `p` using the key `K`, and returns the result `c`.
* `dec_blk(K, c) -> p` decrypts block `c` using the key `K`, and returns the result `p`.
* `update_mask(mask) -> mask` updates the mask by a Galois Field multiplication in GF(2^b^).

State Machine:::

* *States:* _Initial_, _Encrypt_, and _Decrypt_ (defined as before, cf. <<ACE-ECB-mode>>).

* *Allowed State Transitions:*
 ** _Initial_ -> _Encrypt_, if encryption is allowed.
 ** _Initial_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_, _Decrypt_ -> _Initial_.

* *Behavior:*
 ** In State _Initial_:
  *** The `mask` field is set to zero.
  *** No ``ace.exec`` operation is allowed.
 ** The ``ace.setst`` instruction to transition to either _Encrypt_ or _Decrypt_ is expected to be of Form C.
    It sets the tweak, and the `mask` field is used to store it: `mask <- INPUT`.
  *** If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.
  *** Then, the following operations are performed:
  . if two independent keys are used then
  .. `mask <- enc_blk(key2, mask)`
  . else
  ..  `mask <- enc_blk(key1, mask)`
  ..  `mask <- update_mask(mask)`.

  ** In States _Encrypt_ and _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.
    “```ace.exec OUTPUT, Kn|K{Xn}, INPUT```” performs the following operations:
+
--
  . `OUTPUT` is computed as follows:
  .. In State _Encrypt_, `OUTPUT <- mask xor enc_blk(key1, INPUT xor mask)`.
  .. In State _Decrypt_, `OUTPUT <- mask xor dec_blk(key1, INPUT xor mask)`.
  . `mask <- update_mask(mask)`.
--
+
If `ACELEN` is a multiple of `b`, the above commands are executed `ACELEN/b` times, processing each `b`-bit block of `INPUT` into a `b`-bit block of `OUTPUT`.

//

Note that if `ace.setst` is issued to return to State _Initial_, the CC can be reused with a new tweak.

Encryption pseudocode is provided in  <<ACE-pseudocode-basic-IV-mode>>,
decryption is similar

// ////////////////////////////////////////////////////////////////////

[[ACE-tweakable]]
==== Generic Tweakable Block Ciphers

The specification of a generic tweakable block cipher is similar to that of a
non-tweakable block cipher in ECB mode. Since `ace.exec` does not admit
variants with two inputs, and we have a single input buffer, we set the tweak
with a separate instruction. If block and tweak sizes are different, a
reconfiguration of the vector length may be required between operations, unless
the tweak is shorter than the block size, in which case the instruction setting
the tweak will only consider the necessary bits.

Some commonly used TBCs are `Deoxys` cite:[Deoxys-141], `Skinny`
cite:[DBLP-conf-crypto-BeierleJKL0PSSS16], `QARMA`
cite:[DBLP-journals-tosc-Avanzi17], and ```QARMA```{empty}```v2```
cite:[DBLP-journals-tosc-AvanziBDEGNR23].

Parameters:::

* `b` = block size (8|`b`). For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = key size (8|`k`).
* `t` = tweak size (8|`k`).

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128            | MDH
|  ii  | `k` or 64       | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: `k` bits.
 ** `tweak`: `t` bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i   | 128            | MDH
|  ii  | `k` or 64     | `key` or System Key Identifier
| iii  | `t`           | `tweak`
|===
--

State Machine:::

* *States:*
 ** _Initial_, _Encrypt_, and _Decrypt_ defined as before.
 ** _Set_Aux_Value_, for setting the tweak value in the next encryption or decryption operation.

* *Allowed State Transitions:*.
 ** _Initial_ -> _Set_Aux_Value_
 ** _Set_Aux_Value_ -> _Encrypt_, if encryption is allowed.
 ** _Set_Aux_Value_ -> _Decrypt_, if decryption is allowed.

 * *Behavior:*
  ** In State _Initial_:
   *** Upon entering the state, the `tweak` field is cleared.
  ** In each state, Form C `ace.setst` instructions can be issued, which perform:
   . `tweak <- INPUT`, and,
   . Instead of transitioning to State _Set_Aux_Value_, the State remains
     unchanged (can be initial, encrypt, or decrypt).
  ** In State _Encrypt_, respectively, _Decrypt_, besides Form C `ace.setst`
     instructions, ``ace.exec`` instructions are expected to be of Form A, where
     “```ace.exec OUTPUT, Kn|K{Xn}, INPUT```” encrypts, respectively, decrypts
     `INPUT` into `OUTPUT`.
  ** This algorithm does not automatically update the tweak value.

// ////////////////////////////////////////////////////////////////////

[[ACE-GCM-mode]]
==== GCM Mode

The GCM mode was designed by David McGrew and John Viega
cite:[DBLP-conf-indocrypt-McGrewV04] and was made into a NIST Recommendation in
2007 cite:[nist-SP-800-38D].
(((ACE, algorithm, GCM)))

Parameters:::

* `k` = key size (8|`k`).
* `b` = block size (8|`b`). For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `c` = counter size (8|`b`). It must be `c < b`.

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i   | 128            | MDH
|  ii  | `k` or 64     | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: `k` bits.
 ** `ctr`:  ``c`` bits.
 ** `IV`:  `b`-`c` bits.
 ** `auth_key`, `tag`: `b` bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|   i   | 128            | MDH
|  ii   | `k` or 64     | `key` or System Key Identifier
| iii   | ``c``         | `ctr`
|  iv   | ``b``-``c``   | `IV`
|   v   | `b`           | `tag`
|===
--

NOTE: There are no fields for the lengths of the AD and of the plaintext, as
they are maintained by the calling software. Also, `hash_key` is not
serialized, and thus it is recomputed upon `ace.import`.

Algorithm-Specific Functions:::

* `enc_blk(key, p) -> c` encrypts block `p` using the key, and returns the
  result `c`.

* `absorb(data)` absorbs data into the hash function by performing:
  . `tag <- tag xor INPUT`.
  . `tag <- Galoismul(tag, hash_key)`.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Process Associated Data (AD) into the tag.
 ** _Encrypt_: Encrypt the plaintext and absorb the ciphertext into the tag.
 ** _Enc_Tag_Finalize_: Finalize the encryption tag, prepare to return its value.
 ** _Decrypt_: Absorb the ciphertext into the tag and decrypt it.
 ** _Dec_Tag_Finalize_: Finalize the encryption tag and keep it internally.
 ** _Hash_Verify_: Compare the tag against a user supplied value.
 ** _Success_: The algorithm has completed its operation correctly.
 ** _Failure_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_.
 ** _Hash_Absorb_ -> _Encrypt_, if encryption is allowed.
 ** _Hash_Absorb_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_ -> _Enc_Tag_Finalize_ -> _Success_.
 ** _Decrypt_ -> _Dec_Tag_Finalize_ -> _Hash_Verify_ -> _Success_ or _Failure_.

* *Behavior:*
 ** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `hash_key <- enc_blk(key, zeros(b))`,
   . `tag <- zeros(b)`,
   . `ctr <- zeros(c-1) @ 1`, and
   . `IV <- zeros(b)`.

 ** To transition to State _Hash_Absorb_: the ``ace.setst`` instruction must be
    a Form C to set the IV, i.e., the fixed part of the counter. Then:
   . `IV <- INPUT[b-c-1:0]`.
  *** If the ``ace.setst`` instruction is repeated, it will just update the
      counter again.

 ** If the AD is empty, the transition to State _Hash_Absorb_ is necessary to
    initialize the counter.

 ** In State _Hash_Absorb_, an ``ace.exec`` instruction of Form B is expected, whereby
 “```ace.exec Kn|K{Xn}, INPUT```” absorbs a data block in `tag`, i.e.:
+
--
 . `absorb(INPUT)`.
--
+
If `ACELEN` > `b`, the above operation is executed `ACELEN/b` times.

** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A.
   “```ace.exec OUTPUT, Kn|K{Xn}, INPUT```” encrypts `INPUT` into `OUTPUT`, and
   absorbs `OUTPUT` into the `tag`, namely:
+
--
  . If `ctr = ones(c-1)`, then
  ..  the CR is *invalidated*.
  . else
  .. `tmp <- INPUT xor enc_blk(key, IV @ ctr)`.
  .. `absorb(tmp)`.
  .. `ctr <- ctr + 1 % 2^c^`.
  .. `OUTPUT <- tmp`.
--
+
If `ACELEN` is a multiple of `b`, the above operations are executed `ACELEN/b` times, encrypting each `b`-bit block of `INPUT` into the corresponding `b`-bit block of `OUTPUT`.

** To transition to State _Enc_Tag_Finalize_, a Form C `ace.setst` instruction is issued, with the following value, as computed by the software itself:
+
--
[none]
* `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2){nbsp}` .

The authentication tag is then computed as follows:

. `absorb(INPUT)`.
  . `tag <- tag xor enc_blk(key, IV @ zeros(c))`.

Finally, `tag` is returned in `OUTPUT`, and the state is changed to _Success_.

If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.
--
+

** {empty}
In State _Enc_Tag_Finalize_, ``ace.exec`` instructions are expected to be of Form C.
“``ace.exec OUTPUT, Kn|K{Xn}``” writes the `tag` to `OUTPUT`, and the state transitions to _Success_.

** {empty}
+
--
In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.
``ace.exec OUTPUT, Kn|K{Xn}, INPUT`` absorbs the ciphertext `INPUT` into `tag`,
then decrypts `INPUT` into `OUTPUT`, namely:

 . If `ctr = ones(c-1)`, then
  .. the CR is *invalidated*.
  . else
  .. `absorb(INPUT)`.
  .. `OUTPUT  <- INPUT xor enc_blk(key, IV @ ctr)`.
  .. `ctr <- ctr + 1 % 2^c^`.

If `ACELEN` is a multiple of `b`, the same behavior applies as in State
_Encrypt_, namely the above operations are executed `ACELEN/b` times, decrypting
each `b`-bit block of `INPUT` into the corresponding `b`-bit block of `OUTPUT`.
--
+

** To transition to State _Dec_Tag_Finalize_, a Form C ``ace.setst`` instruction is expected to provide the following value, which must be set by the software:
+
--
[none]
* `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2)`

The authentication tag is computed as follows:

. `absorb(INPUT)`.
  . `tag <- tag xor enc_blk(key, ctr[b-1,c] @ zeros(c))`.
--
+
If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.

** To transition to State _Hash_Verify_, a Form C ``ace.setst`` instruction
   must be used to provide the value against which the internally computed tag
   must be compared: If the values match, state
   transitions to _Success_, else it transitions to _Failure_.

** Upon completion of `ace.import`, the ACE unit recomputes `hash_key`, i.e.:
  . `hash_key <- enc_blk(key, zeros(b))`.

//

<<ACE-pseudocode-GCM-encryption>> and <<ACE-pseudocode-GCM-decryption>> provide
pseudocode for GCM encryption and decryption.

//

[NOTE]
====
GCM security is not compromised if `H` is revealed. Consequently, an
implementation of GCM based on an ECB mode CC would be acceptable, for instance
as in <<ACE-pseudocode-GCM-encryption-alternate>>. However, this significantly
increases code size and requires support for carry-less multiplication, which
may not be available in all hardware.

Furthermore, a GCM implementation is necessary to support the use case where
the IV is also set in advance and not modifiable by the user. it must be
possible to configure a GCM CC with both secret key and the IV. This is
described in the next section.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-GCM-with-IV-mode]]
==== GCM with Set IV

The mode of operation “GCM with a Set IV” is a variant of the GCM mode where
the initialization vector (IV) is predefined and not generated randomly. This
variant _cannot_ be emulated with an ECB CC because it would reveal the
internal data.

A key difference between GCM and GCM with Set IV is in the format of the
Provisioning Input:

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|   i   | 128           | MDH
|  ii   | `k` or 64     | `key` or System Key Identifier
|  iii  | ``b``-``c``   | `IV`
|  iv   | (Padding)     | Zero padding
|===
--

* *Internal State*: {empty}
+
--
Same as for GCM.
--
+

* *Serialized Context*: {empty}
+
--
Same as for GCM.
--
+

* *States and Allowed Transitions:* {empty}
+
--
Same as for GCM.
--
+

* *State Machine Behavior:* {empty}
+
--
The differences with respect to GCM are:

 ** To transition to State _Hash_Absorb_: The ``ace.setst`` instruction shall
    be of Form A, i.e., _without any additional inputs_, since the IV is
    already included in the PI.
 ** When transitioning back to State _hash_Initial_: The CR's `IV` field is
    _not_ reset to zero.
--
+

NOTE: For all the following IV- or nonce-based modes, versions with a set IV or
nonce (such as for GCM-SIV) can also be similarly defined. For instance, for
GCM-SIV (<<ACE-GCM-SIV-mode>>), `nonce` would be included in the PI exactly as
`IV` is included in the PI for GCM, and the transition to _Hash_Absorb_ would
also use a Form A ``ace.setst``. All other semantics would be unchanged.

// ////////////////////////////////////////////////////////////////////

[[ACE-GCM-SIV-mode]]
==== GCM-SIV Mode

The GCM-SIV mode is described in cite:[DBLP-journals-iacr-GueronLL17] and
cite:[RFC8452]. While GCM-SIV's decryption state machine is similar to the
GCM's, the encryption state machine is different:

* During encryption, the _Hash_Absorb_ state absorbs the entire associated data
  and plaintext. The _Enc_Tag_Finalize_ state then absorbs the lengths and
  produces the SIV/tag. Finally, the _Encrypt_ state performs a second pass to
  encrypt the plaintext using the SIV/tag as the initialization vector.
* During decryption, the _Hash_Absorb_ state absorbs only the associated data.
  The _Decrypt_ state decrypts the ciphertext and simultaneously absorbs the
  plaintext into the hash. Finally, the _Dec_Tag_Finalize_ state absorbs the
  lengths, produces the SIV/tag, and internally compares it to the provided
  SIV/tag.

//

Parameters:::

* `k` = key size (64|`k`).
* `b` = block size, (64|`b`). For this algorithm, `ACELEN` must be an integer
  multiple of `b`.
* It must be `k = b` or `k = 2b`.
* The authentication tag is `b` bits long.

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|  ii  | `k` or 64     | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`, `enc_key`: `k` bits.
 ** `auth_key`: `b` bits.
 ** `nonce`: `3b/4` bits.
 ** `ctr`: `b/4` bits.
 ** `SIV`: `b` bits.
 ** `tmp`: `b` bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)     | Field
|    i  | 128             | MDH
|   ii  | `k` or 64       | `key` or System Key Identifier
|  iii  | 3``b``/4        | `nonce`
|   iv  | `b`/4           | `ctr`
|    v  | `b`             | `SIV`
|   vi  | `b`             | `tmp`
|===
--

NOTE: The internal state fields `enc_key` and `auth_key` are not serialized,
and must be recomputed upon each `ace.import`.

//

Algorithm-Specific Functions:::

* `enc_blk(key, p) -> c` encrypts block `p` using the key, and returns the
  result `c`.
* `absorb(data)` absorbs data into the hash function by performing a step of (a variant of) POLYVAL:
  . `tmp <- tmp xor INPUT`.
  . `tmp <- Montmul(tmp, hash_key)`.

State Machine:::
* *States:*
 ** _Initial_: The CC is ready.
 ** _Set_Aux_Value_: Set the value of `nonce`.
 ** _Hash_Absorb_: Set the SIV and process AD and, if encrypting, also the plaintext into the partial tag (this is accumulated in the state variable `tmp`).
 ** _Encrypt_: Encrypt the plaintext.
 ** _Enc_Tag_Finalize_: Finalize the SIV with the AD and PT lengths, prepare to return its value.
 ** _Decrypt_: Absorb the ciphertext into the partial tag and decrypt it.
 ** _Dec_Tag_Finalize_: Finalize the tag with the AD and CT lengths, then compare it against the `SIV`.
 ** _Success_: The algorithm has completed its operation correctly.
 ** _Failure_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Set_Aux_Value_ -> _Hash_Absorb_.
 ** For encryption: _Hash_Absorb_ -> _Enc_Tag_Finalize_ -> _Encrypt_.
 ** For decryption: _Hash_Absorb_ -> _Decrypt_ -> _Dec_Tag_Finalize_ -> _Success_ or _Failure_.
 ** Transition to _Encrypt_ possible only if encryption is allowed.
 ** Transition to _Decrypt_ possible only if decryption is allowed.

* *Behavior:*
 ** In State _Initial_ :
  *** Upon entering the state, the following initialization operations are performed:
   . (`enc_key`, `auth_key`) `<-` `RFC8452_RFC8452_KeyDeriv(key)`,
   . `nonce`, `ctr`, `tmp`, `SIV <- 0`.
 *** No ``ace.exec`` operation is allowed.

 *** Upon issuing a Form C ```ace.setst Kn|K{Xn}, #ace_state_set_aux_value, INPUT```,
  the value of `nonce` is set to `INPUT`.
  (If the instruction is repeated, there is no harm, since it just overwrites
  the `nonce` before any other operation is performed.)

  ** In State _Set_Aux_Value_:
   *** Upon issuing a Form C ```ace.setst Kn|K{Xn}, #ace_state_hash_absorb, INPUT```:
+
--
**** The value of `SIV` is set to `INPUT`.

NOTE: This version of the instruction is meant to be used during decryption. It
is harmless to invoke it during encryption, however, as the `SIV` field will be
overwritten later with the correct synthetic value.
--
+

*** Upon issuing a Form A ```ace.setst Kn|K{Xn}, #ace_state_hash_absorb```:
+
--
**** The `SIV` is not modified (it is assumed to be already zero).

NOTE: This version of the instruction is meant to be used during encryption. If
used during decryption, by leaving the `SIV` to zero it will most likely lead
to an authentication error.
--
+

** {empty}
+
--
In State _Hash_Absorb_, Form B ``ace.exec`` instructions are expected.

Such an instruction absorbs its `INPUT` in the internal state variable `tmp`, i.e., it performs `absorb(INPUT)`.

If `ACELEN` is a multiple of `b`, `absorb()` is executed on each of the `ACELEN/b` blocks in `INPUT`.
--
+

** In State _Enc_Tag_Finalize_, an ``ace.exec`` instruction of Form A is expected. Its input value
+
--
[none]
  *** `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2)`,
--
+
is set by the user.
Then, “```ace.exec```” finalizes the SIV computation by performing:
+
--
  . `absorb(INPUT)`.
  . `tmp <- enc_blk(enc_key, 0 @ (tmp xor N)[b-2:0])`
  . `SIV <- 0 @ tmp[b-2:0]` and `OUTPUT <- SIV`,
--
+

If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.

 ** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A, namely
    “```ace.exec OUTPUT, Kn|K{Xn}, INPUT```,” to encrypt `INPUT` into `OUTPUT`
    as follows:
+
--
. If `ctr == 0`, then the CR is *invalidated*.
   . ``OUTPUT <- INPUT `` +
      ``{fournbsp}{fournbsp}xor enc_blk(enc_key, 1 @ SIV[b-2:b/4] @ (SIV[b/4-1:0] + ctr % 2^b/4^)),``
   . `ctr <- ctr + 1`.
--
+
If `ACELEN` > `b`, the above operations are applied to each of the `ACELEN/b`
blocks in `INPUT`.

 ** In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.
 “```ace.exec OUTPUT, Kn|K{Xn}, INPUT```” decrypts `INPUT` into `OUTPUT` and then absorbs the plaintext `OUTPUT` into the `tmp`:
+
--
     . If `ctr == 0`, then the CR is *invalidated*.
     . ``OUTPUT <- INPUT `` +
          ``{fournbsp}{fournbsp}xor enc_blk(enc_key, 1 @ SIV[b-2:b/4] @ (SIV[b/4-1:0] + ctr % 2^b/4^))``,
     . `absorb(OUTPUT)`.
     . `ctr <- ctr + 1`.
--
+
If `ACELEN` > `b`, the above operations are applied to each of the `ACELEN/b`
blocks in `INPUT`.

 ** In State _Dec_Tag_Finalize_,
   a single ``ace.exec`` instruction of Form B is expected,
   namely “```ace.exec Kn|K{Xn}, INPUT```,” where it is the responsibility of the user to set
+
--
[none]
  ***  `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2)`.
--
+
``ace.exec`` then performs the following operations:
+
--
  . `absorb(INPUT)` (which modifies `tmp`).
  . `tmp <- enc_blk(enc_key, 0 @ (tmp xor N)[b-2:0])`.
  . `tmp <- tmp[n-2:0]`,
   . If `tmp` and `SIV` match, then
   ..  `State <- ace_state_success`
   . else
   ..  `State <- ace_state_failure`
--
+
If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.

 ** Upon completion of `ace.import`, the ACE unit recomputes `enc_key` and `auth_key`, i.e.:
  . (`enc_key`, `auth_key`) <- `RFC8452_RFC8452_KeyDeriv(key)`.

//

Encryption and decryption pseudocode is found in <<ACE-GCM-SIV-mode-examples>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-OCB-mode]]
==== OCB Mode

We only architect the OCB3 variant of OCB as specified in RFC{nbsp}7253
cite:[RFC7253] and cite:[DBLP-journals-joc-KrovetzR21]. While this algorithm is
asymptotically more efficient than GCM and GCM-SIV, it has a much heavier setup
and its exported state requires significantly more memory than the other modes.
On the other hand, since it uses only a single key and no derived keys, with
ciphers with an expensive key expansion like the AES it may use fewer internal
resources.

The state machine of this algorithm closely follows RFC{nbsp}7253 (except for
the numbering of the bit fields, which is big endian in the RFC). The algorithm
is identical to the RFC for 128-bit-wide block ciphers, with a straightforward
generalization to other widths according to the security proof of the original
algorithm and a lower bound on nonce length following
cite:[cryptoeprint-2023-326].

Parameters:::
+
--
* `b` = block size. `b` is a power of two, and {ge} 64. For OCB, `ACELEN` must
  be an integer multiple of `b`.
* `k` = key size, `b`|`k`.
--
+
Also, define `g` = `log_2(b)`.

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128            | MDH
|  ii  | `k` or 64       | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: `k` bits.
 ** `N`: `u+1` bits (at most `u` bits are used).
 ** `L`, `offset`, `hash_A`, `hash_P` : `b` bits.
 ** `N_len`, `tag_len`, `last_blk_len`: `g` bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)            | Field
|    i  | 128                    | MDH
|   ii  | `k` or 64              | `key` or System Key Identifier
|  iii  |  `b`                   | `N`
|   iv  |  `b`                   | `L` (only `u+1` bits used)
|    v  |  `b`                   | `offset`
|   vi  |  `b`                   | `hash_A`
|  vii  |  `b`                   | `hash_P`
| viii  |   16                   | `tag_len`
|   ix  |   16                   | `last_blk_len`
|    x  |   16                   | `N_len`
|   xi  |   16 or 80             | Padding
|===
--

//

Algorithm-Specific Functions:::

* `enc_blk(K,p) -> c` encrypts block `p` using the key `K` and returns the result `c`.
* `dec_blk(K,c) -> p` decrypts block `c` using the key `K` and returns the result `p`.
* `double(S)`:
Let `C` be  `0x1B` for `b` = 64, `0x87` for `b` = 128, and `0x425` for `b` = 256, then:
+
[none]
** If S[`b`-1] == 0, then { `double(S) <- S << 1` } else { `double(S) <- (S << 1) xor C` } .

State Machine:::
* *States:*
 ** _Initial_: The CC is ready.
 ** _set_aux_value:_ Set the length and the value of the nonce.
 ** _Hash_Absorb_: Set the tag length, and process the AD.
 ** _Hash_Finalize_: Set the length of the final block of the AD and process
    it.
 ** _Encrypt_: Process the plaintext by absorbing it into the tag and
    encrypting it.
 ** _Enc_Last_Block_: Provide the last block of the plaintext, then process it.
 ** _Enc_Tag_Finalize_: Return the tag.
 ** _Decrypt_: Process the ciphertext by decrypting it and absorbing the
    plaintext into the tag.
 ** _Dec_Last_Block_: Provide the last block of the ciphertext, then process
    it.
 ** _Hash_Verify_: Compare a user-provided value with the internally computed
    tag.
  ** _Success_: The algorithm has completed its operation correctly.
  ** _Failure_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Set_Aux_Value_ -> _Hash_Absorb_ -> _Hash_Finalize_
 ** _Hash_Finalize_ -> _Encrypt_, if encryption is allowed.
 ** _Hash_Finalize_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_ -> _Enc_Last_Block_ -> _Enc_Tag_Finalize_ -> _Success_.
 ** _Decrypt_ -> _Dec_Last_Block_ -> _Hash_Verify_ -> _Success_ or _Failure_.

* *Behavior:*
** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `N <- 1 @ zeros(u)`.
   . `hash_A <- zeros(b)`
   . `hash_P <- zeros(b)`

** To move to _Set_Aux_Value_, a Form B `ace.setst` is expected, where the
   auxiliary argument `Xs` sets the nonce length `N_len`. `N_len` must be at
   least `g-1`. If not, `State <- ace_state_invalid`, that is, the CR is
   enters an Error State.

** In State _Set_Aux_Value_, ``ace.exec`` instructions are expected to be of Form B, namely
   “```ace.exec Kn|K{Xn}, INPUT```”, whereby `N` is set to
   `INPUT`, namely `N <- zeros(u-N_len) @ INPUT[N_len-1:0]`
  *** If “```ace.exec Kn|K{Xn}, INPUT```,” is repeated, it will rewrite `N`.
  *** If no such `ace.exec` is issued, `N` is not changed, which means that its
      most significant bit is 1. This condition results in an error when
      transitioning to State _Hash_Absorb_.

** To move to _Hash_Absorb_, a Form B `ace.setst` instruction is expected, where the
   auxiliary argument `Xs` sets the tag length `tag_len`.
  *** If this argument (interpreted as an unsigned value) is larger than `b` or
      is equal to `0` (the latter occurs also if `X0` is passed as the
      auxiliary argument), and the CR is invalidated.
  *** If `N[u] == 1`, this means that `N` was not set in State _Set_Aux_Value_.
      Nonce setting cannot be skipped, as this mode is not secure under nonce
      reuse, therefore in this case the CR is invalidated.
  *** Following operations are performed:
  . `tag_len <- Xs`.
  . `offset <- zeros(b)`
  . `L <- enc_blk(key, zeros(b))`
  . `L <- double(double(L))`

** In State _Hash_Absorb_, ``ace.exec`` instructions are expected to be of Form B, whereby
  “```ace.exec Kn|K{Xn}, INPUT```” absorbs a data block in `tag`, i.e.:
+
--
    . `L <- double(L)`
    . `offset <- offset xor L`
    . `hash_A <- hash_A xor enc_blk(key, INPUT xor offset)`
--
+
If `ACELEN` > `b`, the above operation is executed `ACELEN/b` times.

** To move to _Hash_Finalize_, a Form B `ace.setst` operation is expected, to set the length of the final block of the AD in `last_blk_len`.

** In State _Hash_Finalize_, only a single `ace.exec` instruction of Form B is
   expected if `last_blk_len` != `0`. “```ace.exec Kn|K{Xn}, INPUT```” which
   absorbs the last data block in `tag`, i.e.:
+
--
  * `tmp : bits(b)`

[]
  . `offset <- offset xor enc_blk(key, zeros(b))`
  . `tmp <- (zeros(b-last_blk_len-1) @ 1 @ INPUT[last_blk_len-1:0]) xor offset`
  . `hash_A <- hash_A xor enc_blk(K, tmp)`
--
+
If `last_blk_len` == 0, however, no `ace.exec` can be executed, and only an
`ace.setst` instruction is allowed to enter State _Encrypt_ or _Decrypt_.

** Upon entering states `_Encrypt_` or `_Decrypt_`, the “setup” and “init”
   stages of the OCB algorithm are performed:
+
--
 * `N_ext : bits(b)` (`N_ext` means “N, extended”)
 * `Stretch : bits(3b/2)`
 * `bot : bits(g-1)`
 * `Ktop : bits(b)`

[]
 . `offset <- zeros(b)`
 . `L <- enc_blk(key, zeros(b))`
 . `L <- double(double(L))`
 . `N_ext <- N[N_len-1:0] @ 1 @ zeros(b-g-1-N_len) @ bin(tag_len,g)`
 . `bottom <- int(N_ext[b-1:b-g+1])`  // Rogaway numbers the bits in the opposite order.
 . `Ktop <- enc_blk(key, zeros(g-1) @ N_ext[b-g:0])`
 . `Stretch <- (Ktop[b/2-1:0] xor Ktop[b/2+7:8]) @ Ktop`
 . `offset <- Stretch[b+bottom:bottom]`
--
+
** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A:
   “```ace.exec OUTPUT, Kn|K{Xn}, INPUT```” absorbs the plaintext `INPUT` into
   the `tag` and encrypts `INPUT` into `OUTPUT`, namely:
+
--
 . `L <- double(L)`
 . `offset <- offset xor L`
 . `hash_P <- hash_P xor INPUT`
 . `OUTPUT <- offset xor enc_blk(key, INPUT xor offset)`
--
+
If `ACELEN > b`, the above operation sequence is executed `ACELEN/b` times,
encrypting each `b`-bit block of `INPUT` into the corresponding `b`-bit block
of `OUTPUT`.

** To move to _Enc_Last_Block_, a Form B `ace.setst` instruction is expected to be issued
   to set the bit length of the final block of the plaintext in `last_blk_len`.

** {empty}
+
--
In State _Enc_Last_Block_, if `last_blk_len` is nonzero a single ``ace.exec`` instruction of Form A
   “```ace.exec OUTPUT, Kn|K{Xn}, INPUT``` is expected.
In this case, following operations are performed:

 * `tmp : bits(last_blk_len)`
 * `tmp2 : bits(b)`
 * `aux : bits(b)`

[]
 . `aux <- enc_blk(key, zeros(b))`
 . `offset <- offset xor aux`
 . `tmp <- enc_blk(key, offset)[last_blk_len-1:0]`
 . `tmp <- INPUT[last_blk_len-1:0] xor tmp`
 . `OUTPUT <- zeros(b-last_blk_len) @ tmp`
 . `tmp2 <- (zeros(b-last_blk_len-1) @ 1 @ tmp) xor offset`
 . `aux <- double(aux)`
 . `hash_P <- enc_blk(key, hash_P xor tmp2 xor offset xor aux) xor hash_A`
--
+
On the other hand, if `last_blk_len` is zero, only an ``ace.exec`` instruction
of Form D, “```ace.exec Kn|K{Xn}```,” is expected, which performs:
+
--
* `aux : bits(b)`

[]
  . `aux <- enc_blk(key, zeros(b))`
  . `aux <- double(aux)`
  . `hash_P <- enc_blk(key, hash_P xor offset xor aux) xor hash_A`
--
+
In both cases the state then transitions to _Enc_Tag_Finalize_.

** In State _Enc_Tag_Finalize_, only a single ``ace.exec`` instruction of Form C,
   “```ace.exec OUTPUT,Kn|K{Xn}```,” is expected, which performs `OUTPUT <-
   zeros(b-tag_len) @ hash_P[tag_len-1:0]`.

** In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.
   Such an ``ace.exec`` decrypts `INPUT` into `OUTPUT`, and absorbs the
   plaintext `OUTPUT` into the `tag`, namely:
+
--
  * `tmp : bits(b)`

[]
  . `L <- double(L)`
  . `offset <- offset xor L`
  . `tmp <- offset xor enc_blk(key, INPUT xor offset)`
  . `hash_P <- hash_P xor tmp`
  . `OUTPUT <- tmp`
--
+
If `ACELEN` > `b`, the same behavior applies as in State _Encrypt_.

** To move to State _Dec_Last_Block_, a Form B `ace.setst` operation must be
   used to also contextually set the bit length of the final block of the
   ciphertext in `last_blk_len`.

** In State _Dec_Last_Block_, only a single ``ace.exec`` instruction of Form A
   "```ace.exec OUTPUT, Kn|K{Xn}, INPUT```" is expected if `last_blk_len` is
   nonzero. In this case, the same operations as in State _Enc_Last_Block_ are
   performed except for Line 6, which is instead
+
--
[start=6]
. `tmp2 <- (zeros(b-last_blk_len-1) @ 1 @ INPUT[last_blk_len-1:0]) xor offset`
--
+
and the state is changed to _Hash_Verify_.
+
If `last_blk_len` is zero, only a single ``ace.exec`` instruction of Form D,
“```ace.exec Kn|K{Xn}```,” is expected, which performs the same operations as in
State _Enc_Last_Block_, except for the final state transition, which also in
this case is to _Hash_Verify_.

** To complete the algorithm in the decryption branch, a Form C ``ace.setst``
   operation is expected, to (confirm the) transition to State _Hash_Verify_
   and compare the `tag_len` least significant bits of `INPUT` with the
   `tag_len` least significant bits of `hash_P`:
+
--
  . If the values match, then the State transitions to _Success_, else it transitions to _Failure_.
--
+

//

Pseudocode for OCB encryption is given in <<ACE-OCB-mode-examples>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-CMAC-mode]]
==== CMAC Functions

{empty}
(((ACE, algorithm, CMAC)))
CMAC is an algorithm for message authentication codes constructed from a block
cipher. It was designed by Tetsu Iwata and Kaoru Kurosawa and became a NIST
Recommendation in May 2005 cite:[nist-SP-800-38B].

Parameters:::

* `b` = block size (8|`b`).  For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = key size (8|`k`).

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|  ii  | `k` or 64     | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: `k` bits.
 ** `hash`: `b` bits.
 ** `last_block_len`: 64 bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|   i   | 128            | MDH
|    i  | `k` or 64     | `key` or System Key Identifier
|   ii  | `b`           | `hash`
|  iii  | 64            | `last_block_len`
|===
--

//

Algorithm-Specific Functions:::

* `enc_blk(key, p) -> c` encrypts block `p` using the key `key`, and returns the result `c`.
* `gen_subkeys(K) -> (K1,K2)` generates subkeys `K1` and `K2` from the master key `K` as follows: +
Let `C` be `0x1B` for `b` = 64, `0x87` for `b` = 128, and `0x425` for `b` = 256, then

 . `L <- enc_blk(K, zeros(b))`
 . if (`msb(L){nbsp}{nbsp}== 0`) then
   { `K1 <- L{nbsp}{nbsp}<< 1` }
   else
   { `K1 <- (L{nbsp}{nbsp}<< 1) xor C` }.
 . if (`msb(K1){nbsp}== 0`) then
   { `K2 <- K1{nbsp}<< 1` }
   else
   { `K2 <- (K1{nbsp}<< 1) xor C` }.
 . return ```(K1, K2)```.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Absorb data into the CMAC function.
 ** _Hash_Last_Block_: Set the length of the last block to absorb, then absorb it.
 ** _Hash_Output_: Output the CMAC.
 ** _Success_: The CC has completed the CMAC operation.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Last_Block_ -> _Hash_Output_ -> _Success_.
 ** From any valid state to State _Initial_.
* *Behavior:*
 ** In State _Initial_:
  *** `last_block_len <- zeros(64)`
  *** `hash <- zeros(b)`
  *** No {nbsp}```ace.exec```{nbsp} operation is allowed.

 ** In State _Hash_Absorb_, ``ace.exec`` instructions are expected to be of Form B. +
 “```ace.exec Kn|K{Xn}, INPUT```,” absorbs the data block `INPUT` into the hash as follows:
+
--
   . `hash <- enc_blk(key, hash xor INPUT)`.
--
+
If `ACELEN` > `b`, then the above operations are applied to each `b`-bit block of `INPUT`.

 ** Upon issuing a Form B “```ace.setst Kn|K{Xn}, #ace_state_hash_last_block, Xs```” where `Xs` contains the bit length of the last block, the following happens:
   . if `last_block_len` != 0, then the CR is *invalidated*. (The previous block is not complete.)
   . if `Xs > b` then the CR is *invalidated*.
   . `last_block_len <- Xs`.

 ** In State _Hash_Last_Block_, only a single ``ace.exec`` instruction of Form B may be issued, i.e., “```ace.exec Kn|K{Xn}, INPUT```”, to absorb the data block `INPUT`. If `ACELEN` > `b`, only the least significant `b` bits of `INPUT` are considered.
+
--
  . `(K1, K2) <- gen_subkeys(key)`.
  . if `last_block_len` == `b`, then {
    .. `tmp <- hash xor INPUT xor K1`
  . } else {
    .. `tmp <- INPUT`
    .. Remove the `b` - `last_block_len` most significant bits of `tmp` and pad the resulting value with a `1` and sufficiently many `0` bits to make it `b` bits long.
    .. `tmp <- hash xor tmp xor K2` }
  . `hash <- enc_blk(key, tmp)`
  . The state is changed to _Hash_Output_.
--
+

** In State _Hash_Output_, we can issue one ``ace.exec`` instruction of Form C, i.e., “```ace.exec OUTPUT, Kn|K{Xn}```”, to output the hash into `OUTPUT`.
   If `ACELEN` > `b`, only the bits of `OUTPUT` beyond the `b`-th are cleared.
   Upon issuing that instruction, the CC transitions to State _Success_ with no error.

//

Pseudocode is given in <<ACE-CMAC-mode-example>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-hash-functions]]
==== Hash and MAC Functions, and XOFs

{empty}
(((ACE, algorithm, general hashing)))
(((ACE, algorithm, MAC functions)))
(((ACE, algorithm, XOF)))
This section defines an interface for hash and MAC functions. A completely
general interface cannot be defined because of the variety of constructions.
However, the one given here is sufficiently general to allow describing most
common functions, such as, for instance, the SHA2 cite:[nist-fips-180-4], SHA3
and SHAKE cite:[nist-fips-202], as well as HMAC cite:[nist-fips-198-1].

Parameters:::

* `b` = block size (8|`b`). This is the size of an absorbed block and may be
  different from the size of the internal state that is kept by the function.
  For a sponge function, this value is the _rate_.
* `t` = tag len (8|`t`). This is the size of the digest, or of the block that
  is output each time in a XOF. The present description assumes `t` {le} `b`.
* `n` = size of the internal state that is kept by the function (8|`n`).  For a
  sponge function, `n-b` is the _capacity_ of the function. Either the block
  size is an integer multiple of the vector length or the vector length is an
  integer multiple of the block size.
* `k` = key size (8|`k`). Present only if keyed, i.e., a MAC.

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)             | Field
|   i  | 128                     | MDH
|  ii  | If keyed: `k`, else 64  | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: `k` bits. Present only if keyed, i.e., a MAC.
 ** `state`: `n` bits.
 ** `last_block_len`: int. Present only if this Hash/MAC provides special
    treatment for a last block that goes beyond padding and appending the
    length. The latter must be handled by user software instead.
 ** `input_base`: int. Offset within input/output to read from/write to.
 ** `block_base`: int. Length of absorbed data so far for the current block.
    Only if needed by the algorithm.
 ** `cumul_len`: int. Cumulative length of data absorbed so far (if the
    algorithm must process and incorporate it in the hash on its own).
 ** `block`: `b` bits.  Included only if a partial block must be maintained—for
    instance when the inputs are not directly absorbed into `state`.


* *Serialized Context*:
+
--
[cols="^6%,<21%,<18%,<55%",options="header"]
|===
|  Pos. | Size (Bits)             | Field                        | Notes
|   i   | 128                     | MDH              | --
.2+| ii | If keyed: `k` or 64     | `key` or SKID                | --
<|        If unkeyed: 0           | none                         | --
|   iii | `n`                     | `state`                      | --
|    iv | 16                      | `last_block_len`             | Present only if this Hash/MAC has special internal treatment for a fractional last block that goes beyond padding and appending the length, which are handled by user software.
|    v | 16                       | `block_base`                 | Amount of data stored so far into `block`.  Only if used by the algorithm, else zero padding.
|   vi | 32                       | `cumul_len`                  | Cumulative length of all data absorbed so far. Only if the algorithm must process and incorporate it in the hash on its own, else zero padding.
|  vii | 64{interpunct}{lceil}``block_base``/64{rceil} | `block` | Only if `block_base` is defined and != 0 and the block must be stored separately from the `state`.
| viii | 0 or 64                  | Padding                      | To reach a multiple of 128 bits.
|===
--

//

NOTE: Regarding the `last_block_len`/`block_base`/`cumul_len` group: if any of
these fields is not used, it is replaced by a corresponding padding block. If
all three are not used by the hashing algorithm, then the 64-bit block is
omitted, and `block` is clearly also

Algorithm-Specific Functions:::

* `absorb()`: Process `block` into the hash or MAC.
* `absorb_last_block()`: Process `block` into the hash or MAC, using a function
  for the last block.
* `finalize()`: Process the `state` into the digest value. We assume this
  either re-uses `block` (the entire digest, or a unit of XOF output should not
  be bigger than that) or the digest will be part of `state`.
* `update()`: Updates the `state` during the digest output stage.

State Machine:::

* *States:* _Initial_, _Hash_Absorb_, _Hash_Last_Block_, _Hash_Output_ and _Success_.

 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Absorb data into the hash function.
 ** _Hash_Last_Block_: Set the length of the last block to absorb, then absorb it.
 ** _Hash_Output_: Output the hash.
 ** _Success_: The CC has completed the operation (XOFs do not have this state).

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Last_Block_ -> _Hash_Output_ -> _Success_.
 ** From any valid state to State _Initial_.

* *Behavior:*
 ** In State _Initial_:
  *** `last_block_len`, `block_base` and `block` are set to zero.
  *** `state`: the initial value is set as specified by the algorithm.
  *** Any `ace.exec` will result in the CR being *invalidated*.

 ** In State _Hash_Absorb_, only ``ace.exec`` instructions of Form B may be issued, i.e., +
 “```ace.exec Kn|K{Xn}, INPUT```”, to absorb the data block `INPUT` into the hash as follows.
+
--
  . `input_base <- 0` // or `acestart` upon resumption
  . while `(input_base < ACELEN)` do { // as long as we have input to process
  .. `amount <- min(ACELEN-input_base, b-block_base)`
  .. ``block[block_base + amount - 1 : block_base] <-`` +
      ``{fournbsp} <- INPUT[input_base + amount - 1 : input_base]`` +
        ``{nbsp}{nbsp}``(If there is no `block` field, could also be something like +
        ``{fournbsp}state[block_base + amount - 1 : block_base] <- `` +
        ``{fournbsp}{fournbsp}{nbsp}<- state[block_base + amount - 1 : block_base] + `` +
        ``{fournbsp}{fournbsp}{nbsp}+ INPUT[input_base + amount - 1 : input_base]`` , +
        ``{nbsp}{nbsp}{nbsp}``it could directly replace part of `state`, or some other function.)
  .. `input_base <- input_base + amount`
  .. `block_base <- block_base + amount`
  .. if (`block_base` == `b`) then { // it's time to absorb the block
  ... `absorb()`
  ... `block_base <- 0`
  ... *Here* the instruction may be interrupted, with `acestart <- input_base`.

[none]
  . }``{nbsp}{nbsp}`` }
--
+

//
 ** Upon issuing a Form B “`ace.setst Kn|K{Xn}, #ace_state_hash_last_block,
    Xs`” where `Xs` contains the length of the last block, the following
    happens:
+
--
 . if `block_base` != 0, then the CR is *invalidated*. (The previous block is not complete.)
 . if `Xs > b`, then the CR is *invalidated*.
 . if `Xs == 0`, then the CR is *invalidated*.
 . `last_block_len <- Xs`.
--
+
Then, state transitions to _Hash_Last_Block_ as expected.

 ** State _Hash_Last_Block_ is very similar to _Hash_Absorb_, the differences
    being:
  *** `last_block_len` is used in place of `b` throughout.
  *** `absorb_last_block()` is called instead of `absorb()` in Step 3.d.i.
  *** The instruction is terminated after `absorb_last_block()`—only one block
      is absorbed—and the state transitions to _Hash_Output_.

 ** In State _Hash_Output_, the cases where the current function is a hash
    function or a XOF behave differently.
  *** Upon entering the state, the following operations are first performed:
  . `block[t - 1 : 0] <- finalize()`
  . `block_base <- 0`
 *** For each Form C `ace.exec` instruction “`ace.exec OUTPUT, Kn|K{Xn}`”, the
     following operations are performed:
+
--
    * `amount : int`, `{nbsp}` amount of data to copy from `block` to `OUTPUT`
    * `#define output_base input_base`

[]
   . `output_base <- 0` // or `acestart` upon resumption
    . while (`output_base` < `ACELEN`) do { // as long as there is room in the OUTPUT
     .. `amount <- min(ACELEN - output_base, t - block_base)`
     .. ``OUTPUT[output_base + amount - 1 : output_base] <- `` +
           ``{fournbsp}{fournbsp}<- block[block_base + amount - 1 : block_base + amount]``
     .. `output_base <- output_base + amount`
     .. `block_base <- block_base + amount`
     .. if (`block_base` == `t`) then {
      ... if we are in a Hash function, transition to State _Success_, and return.
      ... `update()`
      ... `block_base <- 0`
      ... *Here* the instruction can be interrupted, with `acestart <- output_base`.

[none]
      . }``{nbsp}{nbsp}`` }
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-HMAC]]
==== HMAC

Hash function acceleration is sufficient to compute HMACs, and no dedicated
algorithms are needed for either performance or security reasons.

// ////////////////////////////////////////////////////////////////////

[[ACE-SHA-3]]
==== SHA-3 Family Specific Rules

{empty}
(((ACE, algorithm, SHA-3)))
We describe here the algorithms for the primitives in the SHA-3 family, which
currently includes SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128 and
SHAKE256. These primitives are designed around a special parameter choice of
KECCAK cite:[DBLP-conf-eurocrypt-BertoniDPA13] standardized by NIST
cite:[nist-fips-202]. These are instantiations of the algorithm specified in
<<ACE-hash-functions>>, and we need to describe only the differences with
respect to the behavior described there.

//

Parameters:::

* `b` = rate (8|`b`). It is `b` = 1600 - `c`, where `c` = 448, 512, 768, or 1024 is the capacity.
* `n` = 1600
* `t` = `c/2`

Data Structures:::

* *Provisioning Input*: Empty.
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `state`: `n` bits.
 ** `last_block_len`: int.
 ** `input_base`: int.
 ** `block_base`: int.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i   | 128            | MDH
|  ii  | 1600            | `state`
| iii  | 16              | `last_block_len`
|  iv  | 16              | `block_base`
|   v  | 96              | Padding
|===
--

Algorithm-Specific Functions:::

 * `P()`: computes `KECCAK-p[1600, 24]` on `state`.
 * `absorb()`: in this case there is no explicit operation to copy data into
   `state`, as the inputs will be directly XORed into it, however `absorb`
   applies `P()` to the state.
 * `absorb_last_block()`: this is a NOP.
 * `finalize()`: this is a NOP.
 * `update()`: updates the `state` during the digest output stage.  It applies
   `P()` to the state.

State Machine:::
* *States:* _Initial_, _Hash_Absorb_, _Hash_Last_Block_, _Hash_Finalize_,
  _Hash_Output_ and _Success_.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Last_Block_ -> _Hash_Finalize_ ->
    _Hash_Output_ -> _Success_.
 ** From any valid state to State _Initial_.

* *Behavior:*
 ** In State _Initial_, `state` is zeroed.
 ** In State _Hash_Absorb_, the input data is directly XORed to `state`.
 ** In State _Hash_Last_Block_, the input data is directly XORed to `state`.
 ** Upon transitioning to State _Hash_Output_:
  . The suffix and padding string `S` is generated.
  . If the bit length of `S` is `b-block_base`:
   .. `S` is directly XORed to rate part of the state, and
   .. `P()` is applied.
  . If the bit length of `S` is `2b-block_base`:
   .. The first `b-block_base` bits are XORed to the rate part of the state,
   .. `P()` is applied,
   .. the remaining `b` bits are XORed to the rate part of the state, and
   .. `P()` is applied again.

The rest of the algorithm follows <<ACE-hash-functions>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-AEAD128]]
==== Ascon-AEAD128

{empty}
(((ACE, algorithm, Ascon)))
Ascon is a public permutation cite:[DBLP-journals-joc-DobraunigEMS21]
standardized by the NIST cite:[nist-SP-800-232] together with various
cryptographic algorithms designed around it.

[WARNING]
====
In all ASCON algorithms, the ordering of the bits must be verified!
====

Ascon-AEAD128 is an AEAD algorithm. In Ascon-AEAD128, it is the responsibility
of the user to apply proper padding to the AD and plaintext. The inputs are
therefore assumed to be properly padded. Similarly, it is the responsibility of
the user to remove the padding from the decryption of the ciphertext to recover
the original plaintext.

Parameters:::

* `b` = 128. For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = 128.

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|  ii  | 128 or 64     | `key` or System Key Identifier
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `key`: 128 bits, or 64 bits if it is a System Key Identifier.
 ** `state[0 .. 4]`: five 64-bit words, i.e., 320 bits.
 ** `tag_len`: 8 bits as int.
 ** `last_block_len`: 9 bits as int.
 ** `AD_empty`: Boolean;

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)     | Field
|    i | 128             | MDH
|   ii | 128 or 64       | `key` or System Key Identifier
|  iii | 64              | `state`[0]
|   iv | 64              | `state`[1]
|    v | 64              | `state`[2]
|   vi | 64              | `state`[3]
|  vii | 64              | `state`[4]
| viii | 16              | `last_block_len`
|   ix | 16              | `tag_len`
|    x | 32 or 96        | Padding
|===
--

Algorithm-Specific Functions:::
* `ASCON(p)` applies `p` rounds of ASCON to the `state`.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Set the nonce, and process the AD.

 ** _Encrypt_: Encrypt the plaintext.
 ** _Enc_Last_Block_: Encrypt the last block of the plaintext.
 ** _Hash_Output_: Return the tag.

 ** _Decrypt_: Decrypt the ciphertext.
 ** _Dec_Last_Block_: Decrypt the last block of the ciphertext.
 ** _Hash_Verify_: Compare a user-provided value with the internally computed tag.

 ** _Success_: The algorithm has completed its operation without errors.
 ** _Success_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_.
 **  _Hash_Absorb_ -> _Encrypt_, if encryption is allowed.
 **  _Hash_Absorb_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_ -> _Enc_Last_Block_ -> _Hash_Output_ -> _Success_.
 ** _Decrypt_ -> _Dec_Last_Block_ -> _Hash_Verify_ -> _Success_ or _Success_.

* *Behavior:*
** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `state[0] <- 0x00001000808c0001`
   . `state[1] <- key[63:0]`
   . `state[2] <- key[127:64]`
   . `state[3] <- zeros(64)`
   . `state[4] <- zeros(64)`
   . `tag_len <- 128`
   . `AD_empty <- true`

** To transition to State _Hash_Absorb_, a Form C ``ace.setst`` is expected,
   whose `INPUT` sets the nonce of the algorithm as follows:
+
--
  . `state[3] <- INPUT[63:0]`
    . `state[4] <- INPUT[127:64]`
    . `ASCON(12)`
    . `state[3] <- state[3] xor key[63:0]`
    . `state[4] <- state[4] xor key[127:64]`
--
+
If `ACELEN` > 128, only the 128 least significant bits of `INPUT` are considered.

** In State _Hash_Absorb_, only  ``ace.exec`` instructions of Form B are expected.
 “```ace.exec Kn|K{Xn}, INPUT```” absorbs a data block into the state, i.e.:
+
--
 . `AD_empty <- false`
 . `ASCON(8)`
 . `state[0] <- state[0] xor INPUT[63:0]`
 . `state[1] <- state[1] xor INPUT[127:64]`
--
+
If `ACELEN` > 128, this sequence of four operations is executed `ACELEN/128`
times, once for each 128-bit block of `INPUT`.
** Upon entering State _Encrypt_ or _Decrypt_, the following domain separation
   operation is performed:
 . `lsb(state[4]) <- lsb(state[4]) xor 1`

** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A, whereby
   “```ace.exec OUTPUT, Kn|K{Xn}, INPUT```” encrypts `INPUT` into `OUTPUT`, namely:
+
--
 . `state[0] <- state[0] xor INPUT[63:0]`
 . `state[1] <- state[1] xor INPUT[127:64]`
 . `OUTPUT <- state[1] @ state[0]`
 . `ASCON(8)`
--
+
If `ACELEN` is a multiple of 128, these operations are executed `ACELEN/128`
times, encrypting each 128-bit block of `INPUT` into the corresponding 128-bit
block of `OUTPUT`.

** In State _Enc_Last_Block_, only one ``ace.exec`` instruction of Form A is expected to be issued, to
   encrypt the last block.
“```ace.exec OUTPUT, Kn|K{Xn}, INPUT```”  performs
+
--
 . `state[0] <- state[0] xor INPUT[63:0]`
 . `state[1] <- state[1] xor INPUT[127:64]`
 . `OUTPUT <- state[1] @ state[0]` // only the 128 lsbs of `OUTPUT` are written to.
 .  The state machine then transitions to State _Hash_Output_.
--
+
In this state only one 128-bit block is processed. +
The differences between the operation of `ace.exec` in this state and in State
_Encrypt_ are the absence of the final `ASCON(8)` and the automatic transition
to State _Hash_Output_.

** In State _Hash_Output_, only one ``ace.exec`` instruction of Form C is expected to be issued, to compute the tag.
“```ace.exec OUTPUT, Kn|K{Xn}```”  performs
+
--
 . `state[2] <- state[2] xor key[63:0]`
 . `state[3] <- state[3] xor key[127:64]`
 . `ASCON(12)`
 . `state[3] <- state[3] xor key[63:0]`
 . `state[4] <- state[4] xor key[127:64]`
 . `OUTPUT <- state[4] @ state[3]` // only the 128 lsbs of `OUTPUT` are written to.
 . The state machine then transitions to State _Success_.
--
+
In this state only one 128-bit block is processed.

** In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A, i.e.,
 `ace.exec OUTPUT,Kn|K{Xn},INPUT`. This operation performs:
+
--
* `tmp : bits(128)`

[]
. `tmp <- (state[0] xor INPUT[63:0]) @ (state[1] xor INPUT[127:64])`
. `state[0] <- INPUT[63:0]`
. `state[1] <- INPUT[127:64]`
. `ASCON(8)`
. `OUTPUT <- tmp`
--
+
If `ACELEN` is a multiple of 128, these operations are executed `ACELEN/128`
times, decrypting each 128-bit block of `INPUT` into the corresponding 128-bit
block of `OUTPUT`.

** In State _Dec_Last_Block_, only a Form A ``ace.exec`` instruction is expected.
“```ace.exec OUTPUT, Kn|K{Xn}, INPUT```” performs:
+
--
* `tmp : bits(128)`

[]
. `tmp <- (state[1] xor INPUT[127:64]) @ (state[0] xor INPUT[63:0])`
. `state[0] <- INPUT[63:0]`
. `state[1] <- INPUT[127:64]`
. The state machine transitions to State _Hash_Verify_
. `OUTPUT <- tmp`
--
+

** In State _Dec_Tag_Finalize_, a Form B `ace.setst Kn|K{Xn},
   #ace_state_dec_tag_finalize, Xs` instruction may be executed, setting the
   tag len `tag_len` to the value of `Xs`, provided it is not smaller than 32
   and not larger than 128. If the value is out of bounds, the CR is *invalidated*.

** In State _Hash_Verify_, only one ``ace.exec`` instruction of Form D is
   expected to be issued, to verify the tag.
“```ace.exec Kn|K{Xn}, INPUT```” performs
+
--
. `state[2] <- state[2] xor key[63:0]`
. `state[3] <- state[3] xor key[127:64]`
. `ASCON(12)`
. `state[3] <- state[3] xor key[63:0]`
. `state[4] <- state[4] xor key[127:64]`
. `INPUT[tag_len-1:0]` is compared to `(state[4] @ state[3])[tag_len-1:0]`.
. If the values match, then the State transitions to _Success_,
  else it transitions to _Failure_.
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-AEAD128-wsn]]
==== Ascon-AEAD128 with set Nonce

Similarly to GCM with Set IV, Ascon-AEAD128 can also be made into a version with a set nonce.
In this case the State _Set_Aux_Value_ is not present and is thus skipped, and the PI has the following form.

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|  ii  | 128 or 64     | `key` or System Key Identifier
| iii  | 128           | `nonce`
|===
--

In State _Initial_, words 3 and 4 of `state` are initialized thus:

. `state[3] <- nonce[63:0]`
. `state[4] <- nonce[127:64]`

Everything else is as for Ascon-AEAD128.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-AEAD128-N-masking]]
==== Ascon-AEAD128 with Nonce Masking

The NIST specification also describes a version of Ascon-AEAD128 with _Nonce
Masking_. This variant is described as follows:

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|  ii  | 128 or 64     | `K1` or System Key Identifier
| iii  | 128 or 0      | `K2` or System Key Identifier in `K1`
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 . `K1`: 128 bits, or 64 bits if it is a System Key Identifier.
 . `K2`: 128 bits, omitted if a System Key is used.
 ** `state[0 .. 4]`: five 64-bit words, i.e., 320 bits.
 ** `tag_len`: 8 bits.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | 128            | MDH
|   ii  | 128 or 64     | `K1` or System Key Identifier
|  iii  | 128 or 0      | `K2` or System Key Identifier in `K1`
|   iv  | 64            | `state`[0]
|    v  | 64            | `state`[1]
|   vi  | 64            | `state`[2]
|  vii  | 64            | `state`[3]
| viii  | 64            | `state`[4]
|   ix  | 16            | `tag_len`
|    x  | 48 or 112     | Padding
|===
--

The algorithm has the same states as Ascon-AEAD128 as described in
<<ACE-Ascon-AEAD128>>, with the key `key` equal to `K1` and the nonce `N`
replaced throughout by `N xor K2`.

For encryption and decryption with both nonce masking and a set nonce, the
algorithm described in <<ACE-Ascon-AEAD128-wsn>> is used, giving `K1` as the
key `key` and providing `N xor K2` as the nonce value.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-Hash256]]
==== Ascon-Hash256

In this mode it is the responsibility of the user to apply proper padding to
the inputs.

Parameters:::

* `b` = 64. For this algorithm, `ACELEN` must be an integer multiple of `b`.

Data Structures:::

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|===
--

* *Internal State*:
 ** Metadata Header: 77 bits.
 ** `state[0 .. 4]`: five 64-bit words, i.e., 320 bits.
 ** `countdown` : integer going from 3 down to 0.

* *Serialized Context*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | 128            | MDH
|   ii  | 64              | `state`[0]
|  iii  | 64              | `state`[1]
|   iv  | 64              | `state`[2]
|    v  | 64              | `state`[3]
|   vi  | 64              | `state`[4]
|  vii  | 8               | `countdown` (from 3 down to 0)
| viii  | 56              | Padding
|===
--

Algorithm-Specific Functions:::

* `ASCON(p)` applies `p` rounds of ASCON to the `state`.

State Machine:::

* *States:* _Initial_, _Hash_Absorb_, _Hash_Finalize_, and _Success_.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Finalize_ -> _Success_.

* *Behavior:*
 ** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `state[0] <- 0x0000080100cc0002`
   . `state[1] <- zeros(64)`
   . `state[2] <- zeros(64)`
   . `state[3] <- zeros(64)`
   . `state[4] <- zeros(64)`
   . `ASCON(12)`

  ** In State _Hash_Absorb_, only  ``ace.exec`` instructions of Form B are expected to be issued.
 “```ace.exec Kn|K{Xn}, INPUT```” absorbs a data block into the state, i.e.:
+
--
 . `state[0] <- state[0] xor INPUT`
 . `ASCON(12)`
--
+
If `ACELEN` > `64`, these operations are executed `ACELEN/64` times, once for
each `64`-bit block of `INPUT`.

** Upon entering _Hash_Finalize_, `countdown` is set to 3.

** In State _Hash_Finalize_, at most four ``ace.exec`` instructions of Form C
   are expected to be issued. To compute the tag, "```ace.exec OUTPUT, Kn|K{Xn}```"  performs
+
--
. `ASCON(12)`
. `OUTPUT <- state[0]`
. if `countdown == 0` then transition to State _Success_.
. `countdown <- countdown - 1`
--
+
If `ACELEN` {ge} `128`, these operations are executed `ACELEN/64` times, writing
to `OUTPUT`[63:0] the first time, then `OUTPUT`[127:64], `OUTPUT`[191:128] and
`OUTPUT`[255:192]. If more than one ``ace.exec`` instructions are required,
writing restarts from `OUTPUT`[63:0]. If `countdown` reaches zero before the
entire output registers is written to, the state of the unwritten bits is
undefined: for instance this may occur if `ACELEN` = `192` or `ACELEN` > `256`.
This is usually not a problem, since the output vectors will be usually
configured for 64-bit, 128-bit, or 256-bit blocks, in which case four, two, or
one ``ace.exec`` instructions are required, respectively.

//

NOTE: There is no need to provide “keyed” versions of this algorithm. This can
be done by a trusted entity by providing a CC after absorbing some secret
content in it first.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-XOF128]]
==== Ascon-XOF128

The algorithm is the same as Ascon-Hash256 (<<ACE-Ascon-Hash256>>) with the
following differences:

. The IV written to `state[0]` in State _Initial_ is `0x0000080100cc0002`.
. There is no `countdown` field (and therefore also no padding: the last 64
  bits of the Serialized Context of Ascon-Hash256 are not present).
. As much output as desired can be produced in State _Hash_Finalize_, and the
  algorithm never transitions to State _Success_.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-CXOF128]]
==== Ascon-CXOF128

Ascon-CXOF128 differs from Ascon-XOF128 in that the message is prepended with
the customization string. Except for the initialization of the state,
Ascon-CXOF128 is identical to Ascon-XOF128 with customization string and
message concatenated. The IV for Ascon-CXOF128 is `0x0000080000cc0004` (in
place of `0x0000080000cc0003`), and it is set by the algorithm. The states and
their semantics are otherwise identical to Ascon-XOF128, and the management of
the customization string is left to the user.

// ////////////////////////////////////////////////////////////////////

[[ACE-ECC]]
=== Elliptic Curve Asymmetric Algorithms

Elliptic Curve Asymmetric Algorithms provide following functionality:

. Scalar multiplication with known and unknown base point.
//This can be used to implement Diffie-Hellman key exchange.
. ECDSA/EdDSA signature generation and verification.

[NOTE]
====
Support for Key Encapsulation Mechanisms (KEMs) and Public-Key Encryption (PKE) schemes
is difficult to provide in full generality, given the variety of options for KDFs,
hash functions, and input formats. Covering all combinations would be impractical.
Amongst all elliptic curve standards, only the Chinese SM2 standards fully specify
an integrated encryption scheme cite:[GMT-0003-4-2012].
We therefore leave the implementation of specific KEM and PKE schemes to user code,
based on the scalar multiplication feature. The user must be aware that any
derived key value will be present in the environment's memory, and must be
used immediately to provision a CR, and then erased.
====

When an elliptic curve is provisioned into a CR, the default base point (“generator”) according to the standards listed is configured as the `Generator` field in the CR.
This field may be overwritten, and when `ace.setst` is issued on the CR with _Initial_ destination state, the default base point may be restored.

All values (integers, coordinates, etc.) are in little-endian format.

Parameters:::

The parameters that are used in this section are:
+
--
 . The bit length `b` of the main fields, such as coordinates, signature R and S fields, scalars;
 . The bit length `h` of the hash used in the signature scheme;
 . The bit length `j` of the random number used as nonce in signature generation;
 . The number `u` of coordinates used to represent a point (`u` can be 1 or 2); and
 . The number `v` of elements used to represent a signature (`v` can be 1 or 2).
--
+
The parameters for the defined curves are:
+
--
 * NIST cite:[NIST-SP-800-186,nist-fips-186-5]:
  ** secp256r1 (NIST P-256): `b` = `h` = `j` = 256, `u` = `v` = 2.
  ** secp384r1 (NIST P-384): `b` = `h` = `j` = 384, `u` = `v` = 2.
  ** secp521r1 (NIST P-521): `b` = 576 (55 msbs set to zero), `h` = `j` = 512, `u` = `v` = 2.
 * Edwards cite:[RFC7748]:
  ** ed25519:  `b` = `h` = `j` = 256; `u` = `v` = 1.
  ** ed448: `b` = `h` = `j` = 448; `u` = `v` = 1.
 * Brainpool cite:[RFC5639,RFC8734]:
  ** brainpoolP256r1: `b` = `h` = `j` = 256; `u` = `v` = 2.
  ** brainpoolP384r1: `b` = `h` = `j` = 384; `u` = `v` = 2.
  ** brainpoolP512r1: `b` = `h` = `j` = 512; `u` = `v` = 2.
 * SM2 cite:[GMT-0003-1-2012,GMT-0003-2-2012,GMT-0003-3-2012,GMT-0003-4-2012]: `b` = `h` = `j` = 256; `u` = `v` = 2.

Depending on the specifications of the algorithms, non-compressed or compressed points may be used.

All curves currently used are defined over fields of odd characteristic.
Since the all-ones strings do not represent any valid field value, these are used as coordinate(s) values of a point to represent the point at infinity.
--
+

//

Data Structures:::
* *MDH*:
+
--
The elliptic curve algorithm use the _StateExtension_ field as follows:

[[ACE-ECC-StateExtension]]
.StateExtension bits used by the elliptic curve algorithms
[cols="^7%,<20%,<73%",width="100%",options="header"]
|===
|  Bit  | Name            | Description
|   0   | `HasSecondPt`   |  A second point has been set.
|   1   | `HasSignature`  |  A signature has been set.
|   2   | `HasHash`       |  A hash has been set.
|   3   | `HasRndNum`     |  A random number has been set.
|===

The elliptic curve algorithm use the _AlgorithmUse_ field as follows:

[[ACE-ECC-AlgorithmUse]]
.AlgorithmUse bits used by the elliptic curve algorithms
[cols="^7%,<20%,<73%",width="100%",options="header"]
|===
|  Bits   | Name            | Description
|   0     | `OutputType`    |  Determines whether the output is a point (and thus comes from `SecondPt`) or a signature (and thus comes from `Signature`).
|  [19:1] | `Progress`      |  May be used by the implementation to track the progress of long running operations in a non-portable way.
|===

For ECC algorithms, the flags in _AlgorithmPolicy_ enable signature generation (_AlgorithmPolicy_[0]) and verification (_AlgorithmPolicy_[1]), where all four combinations are admissible.
--
+

* *Provisioning Input*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128           | MDH
|===
--

* *Internal State*:
 ** MDH: 81-97 bits.
 ** `OutputType`: Bool.
 ** `Progress`: integer (16 bits, MDH field _AlgorithmUse_ is used).
 ** `block_base`: integer.
 ** `Generator` (X, {Y}): one or two `b`-bit strings representing the X {and Y} coordinate{s}.
 ** `SecondPt` (X, {Y}): one or two `b`-bit strings representing the X {and Y} coordinate{s}.
 ** `Scalar`: `b`-bit string.
 ** If signature generation or verification is allowed:
  *** `PublicKey` (X, {Y}): one or two `b`-bit strings representing the X {and Y} coordinate{s}}.
  *** `Signature` (R,S): two `b`-bit strings representing the `R` and `S` components.
  *** `Hash`: a `h`-bit string representing the hash.
 ** If signature generation or a public-key encryption mechanism are allowed:
  *** `RndNum`: a `h`-bit string representing the random number.
 ** Additional data, for instance precomputed multiples of the Generator.

* *Serialized Context*:
+
--
[cols="^7%,<33%,<60%",width="100%",options="header"]
|===
|   Pos.  | Size (Bits)        | Field
|     i   | 128                | MDH
|    ii   | 32                 | Padding
|   iii   | `ub`               | `Generator`, X coordinate, followed by Y coordinate if `u=2`.
|    iv   | `b`                | `Scalar`: `b`-bit string. Can be the Private Key.
|===

The following fields are also optionally included in the `Content1[]` field of the SCC

[cols="^7%,<33%,<60%",width="100%",options="header"]
|===
|   Pos.  | Size (Bits)                             | Field
|     v   | If `HasSecondPt`: `ub`, else: 0         | `SecondPt`, X coordinate, followed by Y coordinate if `u=2`. Can be the Public Key.
|    vi   | If `HasSignature`: `vb`, else: 0        | `Signature`, R value, followed by S coordinate if `v=2`.
|   vii   | If `HasHash`: `h`, else: 0              | `Hash`: a `h`-bit string representing the hash.
|  viii   | If `HasRndNum`: `j`, else: 0            | `RndNum`.
not empty.
|===

`SCC_content_size()` returns the length of the content from Position i to Position viii, and thus the elliptic curve algorithms make use
of the _StateExtension_ MDH field to determine the length of the SCC.

The `HasRndNum` flag is set and the `RndNum` field is used only during signature generation.
`RndNum` is exported only if the signature operation is interrupted.

The size in bits of Fields vii to x is:

`{fournbsp}{fournbsp}` `varlen` <- 8 + (`HasSecondPt` != 0) {interpunct} ``ub``/8 + (`HasSignature` != 0) {interpunct} ``vb``/8 + +
`{fournbsp}{fournbsp}{fournbsp}{fournbsp}{fournbsp}{fournbsp}{fournbsp}` + (`HasHash` != 0) {interpunct} ``h``/8 + (`HasRndNum` != 0) {interpunct} ``j``/8.

If _ImpDataLen_ > `varlen`, Position x contains the microarchitectural dependent part, which starts with
the Implementation Qualifier `aceunitid`.
--
+

State Machine::: {empty}
+
--
* *States:*
Beside
_Initial_ (1),
_Success_ (21),
_Failure_ (22), and the Error States,
ECC algorithms define:
 ** _Set_Generator_ (2)
 ** _Set_Scalar_ (3)
 ** _Gen_Rnd_Scalar_ (4)
 ** _Point_Mul_ (5)
 ** _Sign_Generate_ (6)
 ** _Sign_Verify_ (7)
 ** _Set_Hash_ (8)
 ** _Set_SecondPt_ (9)
 ** _Set_Signature_ (10)
 ** _Output_ (11)
--
+

* *Allowed State Transitions:*
+
--
 ** _Initial_ -> _Set_Generator_, _Set_Scalar_, _Set_Hash_, _Set_SecondPt_, _Sign_Generate_, _Set_Signature_.
 ** One can freely transition between _Set_Generator_, _Set_Scalar_, _Set_Hash_, and _Set_SecondPt_.
 ** From any of _Initial_, _Set_Generator_, _Set_Scalar_, _Set_Hash_, _Set_SecondPt_ -> one of:
  *** _Point_Mul_;
  *** _Sign_Generate_ only if `HasSecondPt`, and `HasHash`;
  *** _Sign_Verify_ only if `HasSecondPt`, `HasHash`, and `HasSignature`.
 ** _Point_Mul_ -> _Output_.
 ** _Sign_Generate_ -> _Output_ -> _Success_.
 ** _Sign_Verify_ -> _Success_ or _Failure_.

[none]
* In State _Set_Generator_ we can set a group generator, or a default one.
* In State _Set_Scalar_ we can either set a scalar for scalar multiplication or private key.
* For each __Var__ {in} {`Generator`, `Scalar`, `Hash`, `SecondPt`, `Signature`},
the Boolean variable ``Has``__Var__ is set when all operations required in State _set_Var_ have been successfully executed.
--
+

* *Behavior:*

 ** When the CC is created, i.e., provisioned, the `Generator` is set to the default parameter, and `Scalar` is set to zero.

 ** All the “set” and “output” operations work like the input and output of blocks in the Hash functions, in other words, they use `Progress` (just as the Hash/MAC functions use `block_base`) to track how much information has been read in or written out.

 ** To transition to State _Set_Generator_, a Form A or B `ace.setst` is used.

 *** If no parameter is given, or the value of the GPR used in the Form B `ace.setst` is zero:
  . The default generator of the curve is set.
  . A state change operation can be issued, including to states that require a set `Generator`.

 *** Otherwise:
  . `Progress` <- 0.
  . A value for `Generator` is loaded, using one or more Form B `ace.exec` operations, each one increasing `Progress` by the amount of data provided by `ace.exec`.
  . Once `Progress` has reached the length of the generator point (excess data in the last `ace.exec` is ignored):
   **** No further `ace.exec` instructions may be issued.
   **** A state change operation can be issued, including to states that require a set `Generator`. This state change also clears `Progress`.

 ** To transition to any of the States _Set_Scalar_, _Set_Hash_, _Set_SecondPt_, or _Set_Signature_ a Form A `ace.setst` is used.
 . If there is a current value in the corresponding field _X_ = `Scalar`, `Hash`, `SecondPt`, or `Signature`,
     it is erased, and the Boolean ``Has``_X_ is set to False.
 . `Progress` <- 0, and a value for Field _X_ is loaded, using one or more Form B `ace.exec` operations (similarly to `Generator`).
 . Once the values `Progress` has reached the length of field _X_  (excess data in the last `ace.exec` is ignored):
  *** The corresponding Boolean ``Has``_X_ is set to True.
  *** No further `ace.exec` instructions may be issued.
  *** A state change operation can be issued, including to states that require a value for _X_ to be set. This state change also clears `Progress`.

 ** It is allowed to transition to _Set_Scalar_ also using a Form B `ace.setst` with a non-zero value in the GPR.
    In this case, a random value is set.

 ** When the operations in states _Point_Mul_ and _Sign_Generate_ are completed:
   . If the output is a point, then `OutputType` <- False, and if the output is a signature, then `OutputType` <- True.
     This allows the ACE implementation to determine not only which output must be written out, but also its length.
     *** If `OutputType` == False, the output is in `SecondPt`.
     *** If `OutputType` == True,  the output is in `Signature`.
   . `Progress` <- 0.
   . One or more Form C `ace.exec` instructions may be issued to export sections of the result to memory, each time increasing `Progress` by the length of the output of `ace.exec`.
     . Data beyond the length of the output is replaced with zeros in the last exported part.
     . Once `Progress` has reached the length of the output, the state transitions to _Success_.

 ** If, after any computation, either `Generator` or `SecondPt` is the point at infinity, then the corresponding field is set to the special value that encodes it.

 ** Upon returning to State _Initial_:
  *** If a Form B `ace.setst` is used, the parameter `Xs` will determine whether the fields
 `Generator`, `Scalar`, and `SecondPt` are reset/erased or kept for further operations.
 This is determined by Bits 0, 1, 2, and 3 of `Xs` as follows:
   **** If Bit 0, 1, 2, resp., 3 is set, then `Generator` is reset to the default value, `SecondPt`, `Scalar`, resp., `SecondPt` is erased, and in the second case flag `HasSecondPt` is unset as well.
   **** If Bit 4 is set, then `Generator` is copied onto `SecondPt`. If Bit 0 is set, then `Generator` is set to the default value.
   **** If Bit 5 is set, then `SecondPt` is copied onto `Generator`. If Bit 1 is set, then `SecondPt` is erased afterwards and `HasSecondPt` is set to False.
  *** A Form A `ace.setst` does not modify these states.
  *** `Signature` and the corresponding Boolean `HasSignature` are always reset.

  ** {empty}
+
--
`Progress` can be used by operations such as Point Multiplication, Signature Generation or Verification, to track the progress of the operations in case they are interrupted.

In this case, if the CR is exported, the Additional Data Section may contain an implementation-specific section that contain sufficient information to allow resumption, such as certain precomputed multiples of the base point.

The importing implementation, after comparing `acevendorid`, `acearchid` and `aceimpid` with the values in `IMPQUAL`, decides whether it can retain the additional data and trust the random number generator of the originating implementation, in which case it can then resume the computation.
Otherwise, it will discard the additional data at Position x and `RndNum` (Position ix, if present), and restart the operation.
--
+
// ////////////////////////////////////////////////////////////////////
