[[ACE-Algorithms]]
== Instruction Semantics and Data Formats for Various Algorithms

In this chapter we give the semantics of `ace.exec`, `ace.stage`, `ace.input` and `ace.output` for various algorithms.
Some of these are generic, others are specific to certain algorithms.


=== Generic Rules

For modes of operations that can be instantiated with various primitives, the differences being the primitives themselves, and possibly the width of their inputs, we certain rules apply, such as.

* one
* two
* anything else?


==== Note on threshold implementations

Any CC with its algorithms implemented as threshold implementation will always export _all_ its keys and secrets in a single, reconstructed share.
The Configuration and SCC Formats will be the same as for the non-threshold implementations variants of the same algorithm, with the only difference being, in principle, the Side Channel Protection MD bits.
This implies that reconstructing a key or re-randomizing it are fast operations, such as `xor`s with random values.
This in turn implies that ACE XU must have access to a source of randomness or a PRNG.

This guarantees not only the compactness of the SCC format, but also that the key can be ported across architectures.
In fact, some threshold implementations may need 2, 3 or even more shares.

*Example*:
_AES-128 with a threshold implementation of a key. On implementations with two shares, the CC contains
`[metadata, first share, second share]`
and on implementations with three shares, the CC contains
`[metadata, first share, second share, third share]`. +
The SCC will however always contain data in one of the following two formats: +
{nbsp} `1.` {nbsp} `[metadata (64 bits), Nonce (96 bits), SIV (96 bits), key (encrypted)]` or +
{nbsp} `2.` {nbsp} `[metadata (128 bits), Nonce (128 bits), SIV (128 bits), key (encrypted)]`. +
This allows, for instance, a key to be migrated from a machine that has 2-share implementation to a machine with a 3-share implementation._


==== Electronic Codebook Modes (Direct Encryption/Decryption)

*TBD*

==== Counter/LFSR Modes

*TBD*


=== Specific Rules

*TBD*
