[[ACE-concepts]]
=== Fundamental Concepts

Opaque Key:::
The fundamental concept of ACE is the _opaque key_, i.e., a cryptographic key whose value remains hidden to software even while being used in cryptographic operations.

Cryptographic Context:::
ACE implements the concept of opaque key through _Cryptographic Contexts_ (CCs), architectural containers that protect sensitive information.
Each CC consists of a *metadata section* and of a *content section*.
The metadata section defines the cryptographic algorithm and optional usage policies, while the content section comprises sensitive material—including keys, other secrets, and internal algorithm state.
The confidentiality and integrity of CC content is enforced by restricting modifications and access to architectural mechanisms that enforce rules defined by the configured algorithm.

Sealed Cryptographic Context:::
Only the ACE implementation can access CC content.
For protection outside the architectural state, a CC can be exported as a _Sealed Cryptographic Context_ (SCC), i.e., an encrypted and authenticated package containing metadata, a nonce, and authentication tag, and encrypted content.
SCCs can be reimported into CCs when needed.
These operations use a _Context Transport Key_ (CTK) stored in a CSR Machine Mode-only register.
Machine Mode manages the CTK unless it is hardwired or hardware-generated.
Besides the keys in a CC, also the keys in an SCC are called _opaque keys_.

Use Control Policy:::
An important distinction in ACE is between the _import_ and _export_ operations on CCs, and the _use_ of CCs in cryptographic operations.
It must be always possible to import and export SCCs, and also to clear and overwrite CCs for the purpose of managing cryptographic operations, otherwise a process may be prevented from performing cryptographic operations by clobbering all the CCs.
Therefore, the _use control policies_ in the metadata section may optionally restrict only the operations that perform algorithms that are configured by a CC's metadata, including modifying its state, to specified Modes, ASIDs and VMIDs.

Locale:::
In addition to use control policies,
ACE can bind opaque keys to a _Locale_, restricting their use to a specific device, device class, software or hardware configuration, or boot cycle.
This binding uses both metadata and a _Locale CTK_ derived from the CTK and a locale-specific secret via a key derivation function for the purpose of importing and exporting opaque keys.
The system maintains a _Locale Secrets Table_ (LST) containing both system-wide values which are fixed, values that can be configured in an externally defined way,
and fields that can be programmed by Machine Mode.
The metadata stores the Locale as an index into this table.

Object-Oriented Architecture:::
The CCs are, essentially, objects, and in some cases they support the same interface even when they expose different algorithms to the user: a CC (and a SCC) encapsulates its own identity.
For instance, CCs that contain AES-128, AES-256, Калина-128, Калина-256 or SM4 share the same interface, and could be used interchangeably by the same user code.
The same applies for modes of operations that are designed around these algorithms, for instance, GCM-SIV can be used with any of these algorithms, but the user code would be the same, regardless of the key size, since the latter impacts only the size of the SCC, which is discoverable.
No change is required in the code to support also side-channel resistant versions of these algorithms.
