<<<
[discrete]
[[ACE-separation]]
== Structure of the ACE Specification: Separation of Architecture and Data Formats

The ACE ISA is split into three normative Books and one non-normative Book.

* Book 1 defines the fixed part of the Unprivileged Architecture (see <<ACE-unpriv>>).
The instructions and architectural state are specified independently of the exact data formats they operate on.
Book 1 should be a chapter in the Unprivileged Architecture Part of the complete RISC-V specification document.

* {empty}
+
--
Book 2 defines the Data Structures and Algorithms of the Unprivileged Architecture (see <<ACE-Algorithms>>).

Within the RISC-V architecture, conformance to Book 1 requires full conformance to Book 2.
In other words, each implemented non-custom algorithm must fully exhibit the behavior specified in Book 2.

Book 2 is kept separate from Book 1 because the data formats used to manage keys are intended to be interoperable across different ISAs that implement ACE or equivalent functionality. These formats are therefore not specific to RISC-V, and such ISAs must also support the Metadata Header format and the semantics of its fields verbatim. We envision that is could be later expunged and made it into an independent industry standard accepted by other architecture designers.
--

* Book 3 defines the Privileged Architecture (see <<ACE-priv>>).
Book 3 should be a chapter in the Privileged Architecture Part of the complete RISC-V specification document.

* Book 4 provides non-normative pseudocode examples illustrating the intended use of the algorithms defined in Book 2.
Its rightful place would be in an appendix of the complete specification document.
