== Examples

=== Key Management and Provisioning Applications

Software environments that implement key management operations for other domains require their own CTK. A system may contain multiple such software environments.

A Key Management Applet (KMA) will

[arabic]
. Generate or retrieve a key matching a request.
. Configure a CHR with this key and its associated metadata.
. Export this CHR to a SCC in memory.
. Relinquish control to the MM.

The MM, which controls the CTK, can the

[arabic, start=5]
. Set the CTK to the KMA’s CTK.
. Re-import the SCC into a CHR
. Change the CTK to match the requester domain's CTK.
. Export the key for the Requester's use.
. Relinquish control to the Requester.

This is the most generic approach and allows each piece of software to use a CHR of choice to generate and import SCCs.
Furthermore, it protects the key from other SW environments that may be crossed while transferring control between the Requester process, the MM, and the Key Management application.

Various optimizations are possible, which can be interesting for embedded environments: Steps 3., 5., and 6. can be omitted if the CHR used for these operations is fixed and the overall SW/FW stack is simple enough.
Similarly, Step 8. can be omitted.
These are choices of the ABI architect of a specific SW/FW stack.
