<<<
[discrete]
[[ACE-separation]]
== Structure of the ACE Specification: Separation of Architecture and Data Formats

The ACE ISA is split into three normative Books and a non-normative one.

. Book 1 of the ACE Architecture is the fixed part of the Unprivileged Architecture.
The instructions can be defined without specifying the exact data formats they consume. In this document, Book 1 is <<ACE-unpriv>>.

. Book 2 is the Data Structures and Algorithms Unprivileged Architecture. In this document, it is found in <<ACE-algorithms>>.
The actual data formats of the inputs used to provision, export and import keys are meant to be interoperable across different ISAs that implement the same functionality as ACE, so they are not necessarily limited to Risc-V.
Similarly, the algorithms implemented by ACE, shall have a well defined behavior, and produce internal states that are exported in a compatible way across different ISAs.
Implementing Book 1 in Risc-V requires full adherence to Book 2 as well.

. Book 3 is the Privileged Architecture (<<ACE-priv>>).

. Book 4 contains some pseudocode examples of ACE operations to show how the various algorithms in Book 2 are expected to be used.
