// ////////////////////////////////////////////////////////////////////

[[ACE-algorithms]]
== Book 2: Unprivileged Architecture, Data Formats + Algorithms

This chapter is normative.

[[ACE-data-formats-intro]]
=== Data Formats

ACE defines two external CC formats:

. The _Provisioning Input_ (PI), loaded into a CR to create a CC; and
. The _Sealed Cryptographic Context_ (SCC), an encrypted and authenticated representation of a CC used when exporting a CR to memory for later import.

{empty}
(((Cryptographic Context,Metadata)))
(((Cryptographic Context,Metadata,Header)))
Both formats begin with a 128-bit Metadata Header, whose format we define next.

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata]]
==== Metadata Header Format

The following table lists the fields of the 128-bit Metadata Header.
Currently, 81 bits are defined and 47 are reserved for future use.

[[ACE-metadata-section]]
.Format of the 128-bit Metadata Header
[width="100%",cols="^9%,^7%,14%,70%",options="header"]
|===
|  Field   | Width | Name              | Description
|  [11:0]  | 12    | _Algorithm_       | Cryptographic algorithm (primitive, mode, or protocol). See <<ACE-Algorithm-field>>.
|  [13:12] | 2     | _AlgorithmPolicy_ | Allowed algorithm variants(s) _or_ extension of the _Algorithm_ field. See <<ACE-Algorithm-field>>.
|  [15:14] | 2     | Reserved          | Reserved for future expansion of _AlgorithmPolicy_ field.
|  [18:16] | 3     | _SCProtection_    | Side-channel protection level. See <<ACE-SCProtection-field>>.
|  [20:19] | 2     | _KeyType_         | 0: key is an explicit value in Content. 1:  1: Key is a system-specific System Key Identifier. See <<ACE-system-keys>>.
|  [25:21] | 5     | _State_           | Current state of the CR/algorithm, encoded as an integer.
|  [26:26] | 1     | _Provisioning_    | Set if the CR has been only partially configured.
|  [27:27] | 1     | _Importing_       | Set if the CR has been only partially imported.
|  [31:28] | 4     | Reserved          | Reserved for future use. Currently, it must be equal to zero.
|  [36:32] | 5     | _UsagePolicy_     | Usage (Control) Policy. Bits 0, 1, 2, 4 and 4 of the field,, when set, disallow CC usage in U-mode, (V)S-mode, H-mode, M-Mode, and Debug mode, respectively.
|  [46:37] | 10    | _Locality_        | Zero, or an index determining a Locality Secret. See <<ACE-Localities>>.
|  [47:47] | 1     | Reserved          | Reserved for future use.
|  [63:48] | 16    | _VarDataLen_      | If non-zero, indicates that an additional, variable-length data section appended to Content. The length of this additional data section is _VarDataLen_ * 128 bits (up to 512 KiB).
|  [89:64] | 26    | _ExpirationDate_  | If non-zero, the expiration date of this CC. See <<ACE-Metadata-expiration-date>>. Minutes since 00:00, January 1, 2027 (about 127 years).
| [127:90] | 38    | Reserved          | Reserved for future use.  Currently, it must be equal to zero.
|===

In the following subsections we describe the fields of the Metadata section.

//

[[ACE-Algorithm-field]]
===== _Algorithm_ and _AlgorithmPolicy_ Fields

Algorithms are encoded in a 12-bit field. Values 0ŌĆō3071 and 4095 are architecture-defined.
The list of encodings is maintained by RVI (see <<ACE-algorithms>>).
The remaining values are available for custom algorithms.

For encryption/decryption primitives and modes, the _AlgorithmPolicy_ field indicates whether the CC may be used for encryption (lower bit set), decryption (upper bit set), or both. At least one of the bits must be set.

For asymmetric primitives supporting signatures, the lower bit permits signature generation and the upper bit permits verification.
Such an asymmetric primitive can be configured to support primitives such as key agreement or key encapsulation but _not_ signatures, and in this case both bits are zero.

For other primitives, the _AlgorithmPolicy_ field may encode additional algorithm identifiers to expand the effective encoding space of the _Algorithm_ field.

// ////////////////////////////////////////////////////////////////////

[[ACE-SCProtection-field]]
===== _SCProtection_ Field

The architecture defines the following side-channel protection levels.

[[ACE-SC-protection-levels]]
.Encoding of Side-Channel Protection levels
[%autowidth,float="center",align="center",cols="^,<"options="header"]
|===
| Value   | Description
|   0     | Data-independent execution latency (DIEL) for cryptographic operations.
|   1     | First-order threshold implementation.
|   2     | DIEL; first-order threshold, fault-tolerant implementation.
|  {ge} 3 | Currently not defined.
|===

Custom implementations of algorithms offering different protection than encodings 0ŌĆō2 shall set
_SCProtection_ to additional values.
In this case, the _VarDataLen_ field shall be non-zero to ensure that the `macearchid` value
is checked in order to allow the implementation to verify whether it can accept the
_SCProtection_ values.

NOTE: To discuss with the ARC: use values 3-5 for potential expansion of the architecture and
values 6-7 for implementation-dependent custom values. Only the latter two would need the
copy of `macearchid` and therefore a non-zero _VarDataLen_.

// ////////////////////////////////////////////////////////////////////

[[ACE-State-field]]
===== _State_ Field

The _State_ field is used to track the currently state of an algorithm, including certain types of errors.

The architected values of _State_ which are common to all algorithms are defined in
<<ACE-states-valid>>.

[[ACE-states-valid]]
.Global CC State Numbers: Valid States
[float="center",align="center",width="100%",cols="^7%,<27,<15%,<51%",options="header"]
|===
| Value | Mnemonic                  | State Name     | Description
|   0   | `ace_state_off`           | _Off_          | The CR is not configured.
|   1   | `ace_state_initial`       | _Initial_      | The state of a CC immediately after provisioning; ready for operation.
| 2-20  3+| Defined by the specification of the Algorithm encoded in the _Algorithm_ field.
|  22   | `ace_state_success`       | _Success_      | Algorithm completed successfully. No further cryptographic operations may be performed until the CC is reset.
|  23   | `ace_state_failure`       | _Failure_      | Failure in an algorithm, usually an authentication failure in AE(AD) algorithms or a signature verification failure. No further cryptographic operations may be performed until the CC is reset.
|===

[[ACE-states-error]]
.Global CC State Numbers: Interrupted and Error States
[float="center",align="center",width="100%",cols="^7%,<27,<15%,<51%"]
|===
|  24    | `ace_state_not_impl`        | _Not_Impl_        | Not implemented algorithm. It is set by the hardware upon an attempt to provision or import a CR that is not supported by the implementation.
|  25    | `ace_state_invalid`         | _Invalid_         | Invalid/invalidated state, for instance because of the use of an invalid value (argument, state, or metadata).
|  26    | `ace_state_out_of_mem`      | _Out_of_Memory_   | Insufficient CRF memory for configuration instruction. This may be set by privileged code in case they do not handle the CR allocation.
|  27    | `ace_state_import_auth`     | _Auth_Failed_     | Authentication failure with `ace.import`.
|  28    | `ace_state_priv_viol`       | _Priv_Viol_       | Violation of Usage Control policies.
|  29    | `ace_state_expired`         | _Expired_         | The CR has expired.  This is set by the hardware even if the condition also raises an exception.
| 30, 31 | (Reserved)                  |                   | Reserved for future use.
|===

The state with value 0 is termed _Off_, and is used to indicate that the CR is not configured.

All states in the range 1-23 are termed _valid_. This includes both _Success_ and _Failure_ states, which must be used for
normal termination of an algorithm in the cases of its successful completion or failure.

// (((ACE, CR, partially configured)))
// State 23, i.e., _Partially_Configured_, is used to report that provisioning or import was interrupted.
// It is never allowed to set the State to _Partially_Configured_ directly using `ace.setst`.

(((ACE, algorithm, error states)))
States 24-31 are termed _Error States_, and are used to report certain specific ACE errors.
(((ACE, algorithm, invalid state)))
(((Context Register, invalidation)))
In particular, if the State is `ace_state_invalid`, we say that the CR is _invalidated_.

The Error States are currently listed in decreasing severity order, with Error State 24 being the most severe and Error State 29 the least severe.
Error States 30 and 31, if defined, will not necessarily have a lower priority than Error State 29, and may be therefore not in order.

(((ACE, instruction, invalid state)))
(((ACE, instruction, ace.setst)))
An error state can be set by software using `ace.setst` (with no auxiliary input).

Error conditions that lead to exceptions are treated in <<ACE-exceptions>>.

If an algorithm defines 23 or fewer valid states (including _Initial_, _Success_, and _Failure_), the current state is stored in the _State_ field.
For algorithms with more than 23 valid states, additional state information resides in the Content section.

The following rules are generic and apply to all algorithms:

. The Metadata's _State_ field must reflect the current state whenever the CC is in _Initial_, _Success_, _Failure_, or any Error State.
This ensures that these states can be unambiguously determined from the _State_ field alone, without inspecting the Content.

. In States _Success_ and _Failed_, only the following ACE instructions are permitted: `ace.prov`, `ace.import`, `ace.export`, `ace.clear`, `ace.size`, `ace.setst`, and `ace.getst`.

. In States _Success_ and _Failed_, `ace.setst` can only be used permitted to transition to _Initial_ (or _Off_ if used as `ace.clear`).

. Unless an algorithm's specification explicitly states otherwise, a transition from any valid state to _Initial_ using instruction `ace.setst` is always permitted.

. Upon transitioning to an Error State, the Content of a CR is invalidated and emptied.
Internal resources associated with the Content may also be released. In that case, any additional variable-length data is released as well and the _VarDataLen_ field is set to 0.
The CR then retains only the Metadata Header.

. Exporting a CR in an Error State exports only the metadata (and the authentication tag).
  Requesting the SCC's size (`ace.size` <<ACE-instruction-size>>) wil reflect this.
  The resulting SCC can be reimported, allowing software to take appropriate actions even after a context switch.

. If a CR is in any Error State, it can still be reconfigured, cloned, or cleared. `ace.setst` can only be used to change the Error State (for instance by an exception handler) or transition the CR to _Off_.

. The metadata of a CR in an Error State can be read (using `ace.getmd`: <<ACE-instruction-getmd>>).

. Attempts to _use_ a CR in any Error State will not perform any operation, and in particular they leave the _State_ field unchanged.

. If a CR is _partially configured_ (i.e., one of the bits _Provisioning_ or _Importing_ is set), transitioning it to any State other than _Off_ or _Invalid_ is only possible as a consequence of a restart or resumption of the interrupted configuration instruction.  `ace.setst` can only transition it to _Off_ or _Invalid_.

. Any _usage_ instruction that would violate the Usage Control policies will not perform its operation, and will set _State_ to `ace_state_priv_viol` instead.

We note that the State after `ace.setst` is issued may differ from the State specified by the instruction.
A common example is MAC verification: after `ace.setst` is issued with an `ace_state_hash_verify` immediate as the next state and the value to be verified as the additional parameter, the algorithm transitions to either _Success_ or _Failure_. This is done to prevent the manipulation of a CR's state and to reduce code size.
An `ace.exec` instruction may also trigger a state change.

In <<ACE-states-graph>> we display the default possible state transitions.

[[ACE-states-graph]]
.Default State Transitions
[float="center",align="center"]
image::../../src/statestikz-2.svg[]

////
[[ACE-states-graph]]
.Default State Transitions
[tikz,,svg,float="center",align="center",preamble=true,command=lualatex]
....
\usetikzlibrary{calc,trees,matrix,positioning,chains,fit,intersections}
\usetikzlibrary{arrows,shapes.arrows,shapes.geometric,shapes.multipart,shapes.symbols}
\tikzset{
   state/.style={ rectangle, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
   partial state/.style={trapezium, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
   error state/.style={ rectangle, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
   off state/.style={ circle, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
   branch/.style={ fill, shape=circle, minimum size=3pt, inner sep=0pt},
   cross line/.style={preaction={draw=white, -, shorten >=3pt, shorten <=3pt, line width=2pt}},
   >=latex
}
\usepackage{fontspec}
\setmainfont[UprightFont={Petrona-Light.ttf},
             BoldFont={Petrona-Medium.ttf},
             ItalicFont={Petrona-LightItalic.ttf},
             BoldItalicFont={Petrona-MediumItalic.ttf},
            ]{Petrona-Light.ttf}
~~~~
\begin{tikzpicture}[scale=1.1]
  \node[off state]  at (-2,0)    (off)            {Off\,};

  \node[error state] at (2,0)    (invalid)        {Invalid};
  \node[error state] at (2,2)    (various errors) {\footnotesize\begin{tabular}{@{}c@{}}Privilege Violation,\\Not Implemented, or\\Out of Memory\end{tabular}};
  \node[error state] at (2,3.5)  (authfail)       {\begin{tabular}{@{}c@{}}Authentication\\Failure\end{tabular}};
  \node[error state] at (2,-2)   (expired)        {Expired};
  \node[partial state] at (2,-3.5) (partial)      {\!\!\!\!\!\begin{tabular}{@{}c@{}}Partially\\Configured\end{tabular}\!\!\!\!\!};

  \node[circle,thick,draw=black] at (4.75,2.75) (configuration hub) {};
  \node[above=0mm  of configuration hub,xshift=5mm] (ignore) {\small\textit{Configuration}};

  \node[coordinate] at ($(expired.east)+(0.5,0)$) (before expired) {};
  \node[below right=0mm and -4mm of before expired] (ignore) {\small\textit{Expiration}};

  \node[state, thick] at (6,0)    (initial)           {Initial};
  \node[state, thick] at (9,-1.5) (algorithm defined) {\begin{tabular}{@{}c@{}}Algorithm-Defined\end{tabular}};
  \node[state, thick] at (9,1.5)  (success failure)   {\begin{tabular}{@{}c@{}}Success/Failure\end{tabular}};

  \draw[-,densely dashed]   (before expired) to[out=9,in=270,looseness=0.8] (initial);
  \draw[-,densely dashed]   (before expired) to[out=7,in=225,looseness=0.8] (algorithm defined);
  \draw[-,densely dashed]   (before expired) to[out=3,in=225,looseness=0.8] (success failure);
  \draw[->,densely dashed]  ($(before expired)+(-0.1,0)$) -- (expired);

  \draw[<->,densely dotted] (configuration hub) to[out=-40,in=90,looseness=0.8] (initial);
  \draw[<->,densely dotted] (configuration hub) to[out=-20,in=125] ($(algorithm defined.north)+(-0.333,0)$);
  \draw[<->,densely dotted] (configuration hub) to[out=0,in=140] ($(success failure.north)!0.5!(success failure.north west)$);
  \draw[<-,densely dotted,cross line] (configuration hub)  to[out=270,in=0,looseness=0.8] (partial);
  \draw[<->,densely dotted] (configuration hub) to[out=160,in=0] (authfail);
  \draw[<->,densely dotted] (configuration hub) to[out=190,in=10] (various errors);
  \draw[<->,densely dotted] (configuration hub) -- (invalid.north east);
  \draw[<->,densely dotted] (configuration hub) to[out=250,in=10,looseness=0.6] ($(expired.east)+(0,0.1)$);

  \draw[<->] (off) -- (invalid);
  \draw[<-]  (off) to[out=282,in=170,looseness=0.8] (partial);
  \draw[<->] (off) to[out=78,in=180,looseness=0.7] (authfail);
  \draw[<->] (off) to[out=66,in=180] (various errors);
  \draw[<->] (off) to[out=294,in=170,looseness=0.8] (expired);

  \draw[->] (algorithm defined) to[out=250,in=180] ($(algorithm defined)+(0,-1)$) to[out=0,in=290] (algorithm defined);
  \draw[->, cross line] (algorithm defined) -- (invalid);
  \draw[->,cross line] ($(algorithm defined.north)+(-0.667,0)$) to[out=130,in=0] (various errors);

  \draw[<->,cross line] (off) to[out=13,in=167,looseness=1.1] (initial);
  \draw[<->,cross line] (off) to[out=-33,in=180,looseness=0.4] (algorithm defined);
  \draw[<->,cross line] (off) to[out=33,in=180,looseness=0.4] (success failure);

  \draw[->,cross line]  ($(success failure.south)+(-1,0)$)   to[out=225,in=10,looseness=0.8] node[near start, above, yshift=-3pt] () {*} ($(initial.east)!0.5!(initial.north east)$);
  \draw[<->,cross line] ($(algorithm defined.north)+(-1,0)$) to[out=135,in=-10,looseness=0.8] ($(initial.east)!0.5!(initial.south east)$);
  \draw[->,cross line] (algorithm defined) -- (success failure);

\end{tikzpicture}
....
////

The graph is read as follows:

. The double circled state is the _Off_ State.
. Valid States have single rounded rectangular borders.
. Error States have double rounded rectangular borders.
. The _Partially Configured_ conditions have a trapezium shape.
. The continuous edges represent state transitions induced by both configuration and usage instructions.
. However, a transition from _Success_ or _Failure_ to _Initial_ may be forbidden by certain single-use CRs as per the _Algorithm_'s policies.
. The transitions from _Off_ to any Error State are a result of configuration instructions, whereas the corresponding transitions from these Error States to _Off_ are a result of explicitly clearing the CR.
. The dashed edges represent state transitions induced by reaching the expiration date.
. The dotted edges represent state transitions induced by configuration instructions. We note that completion of a provisioning operations can only bring to the _Initial_ state, whereas completion of an import can bring a CR to any state.
. Partially configured conditions occur only while configuration operations are in progress and is therefore only reached via exceptions or interrupts.
//  This explains why there are no arrows leading to _Partially Configured_ from any other state.
. Any transition may be caused by an performing explicit operation performed while in a given state, or be caused implicitly by reaching the latter under conditions specified in the algorithm's specification.
. The round _Configuration_ ŌĆ£hubŌĆØ simplifies the graph to represent that it is always possible to reach any Error State, even from other Error States, by performing explicit configuration operations (or by using `ace.setst` between Error States).

// ////////////////////////////////////////////////////////////////////

[[ACE-Localities]]
===== _Locality_ Field

ACE maintains a table of 128-bit Locality Secrets (LS), called the Locality Secrets Table (LST).
Some entries are fixed or are configurable only through an implementation-specific authenticated hardware procedure.
These are global, shared across all ACE units within the same SoC.
Other entries are per-hart architectural state, programmed by privileged modes.

<<ACE-locality-indexes>> lists the architected Localities.
Twelve LST entries are defined: the first six form the _HW Binding Group_, which binds SCCs to the hardware;
entries 6ŌĆō7 form the _Boot Session Group_; and
entries 8ŌĆō11 form the _SW Filter Group_.

For each Locality, the table provides: index in the LST; domain (SoC-, device-, VM-wide, or per-process); configurability; bit-field encoding; and value.

Eight _Locality_ field bits are defined.

[[ACE-locality-indexes]]
.Architected Localities
[width="100%",cols="^5%,15%,50%,^9%,^9%,^6%,^6%",options="header"]
|===
|  Idx  | Locality                  | Description                                                                          | Domain | Config?|  Bits  | Value
2+|    No HW Binding                | Independent of Chip, OEM, Device                                                    ^|  --   ^|   --   | [2:0]  |  0
|   0   | _SiPScrt_                 | Identifies the designer of the SoC. Permanent.                                       |  SoC   |   No   | [2:0]  |  1
|   1   | _ChipFamScrt_             | Identifies specific chip/SoC model/family. Permanent.                                |  SoC   |   No   | [2:0]  |  2
|   2   | _ChipScrt_                | Unique for each SoC. Permanent.                                                      |  SoC   |   No   | [2:0]  |  3
|   3   | _OEMScrt_                 | Provisioned by OEM to differentiate their products from the competition.
Permanent, or reconfigurable via a custom hardware authenticated mechanism.                                                | Device |   HW   | [2:0]  |  4
|   4   | _ProdScrt_                | Identifies device/system type/model (product).
Permanent or reconfigurable like OEMScrt.                                                                                  | Device |   HW   | [2:0]  |  5
|   5   | _DevScrt_                 | Unique device (entire system) secret.
Shared across all harts in a SoC and shareable across multiple SoCs in a single device using an implementation-defined mechanism.
Reconfigurable like OEMScrt.                                                                                               | Device |   HW   | [2:0]  |  6
2+|   No Boot Binding               | Independent of Physical or Virtual Boot Session                                     ^|  --   ^|   --   | [4:3]  |  0
|   6   | _PhysBootScrt_            | Unique per the boot session of the host hardware and its firmware stack.
{empty}                   Configured by M-mode during the boot process of the host (see <<ACE-CSR-macePhysBootScrt>>).     | Device |   M    | [4:3]  |  1
|   7   | _VirtBootScrt_            | Unique per the boot session of the virtual hardware and its software stack.
Regenerated by H or higher at each virtual boot of a VM (see <<ACE-CSR-haceVirtBootScrt>>).                                |   VM   |  H/M   | [4:3]  |  2
2+| No Binding at Modes             | Independent of M-, S-, or any VS-mode Localities                                    ^|  --   ^|   --   | [6:5]  |  0
|   8   | _MLocality_               | Configurable at M.  Useful to separate Supervisor Domains/Security States.           |  < M   |   M    | [6:5]  |  1
|   9   | _HLocality_               | Configurable at H.                                                                   |  < H   |   H    | [6:5]  |  2
|  10   | _SLocality_               | Configurable at (V)S.                                                                | < (V)S |  (V)S  | [6:5]  |  3
|  11   | _Nonce_                   | Always re-configurable (out-of-band peer-to-peer nonce). Only the 96 bits _Nonce_[95:0] are defined. |  hart  |   U    | [7:7]  | 0/1
|===

Implementations are not required to populate every entry in the HW Binding Group, except for _ChipFamScrt_ and _DevScrt_.
If an entry is unconfigured, it is transparently replaced by the next defined entry in its chain: _SiPScrt_ {rightarrow} _ChipFamScrt_ {rightarrow} _ChipScrt_, and _OEMScrt_ {rightarrow} _ProdScrt_ {rightarrow} _DevScrt_ .
If no entry is configured in these chain but one Locality is requested, the implementation must raise an authentication failure error.

_HLocality_ is active only when the H extension is enabled and V=1; otherwise, it mirrors _MLocality_.

NOTE: A system key identifier may refer to keys with unrelated purposes on different devices, leading to unspecified behavior.
Implementations shall assign usage policies at least as restrictive as the key's own native policies, and supply an appropriate _Locality_ during CR provisioning.

Up to four architected Localities may be active concurrently: one from the HW Binding Group, one of either _PhysBootScrt_ or _VirtBootScrt_, one from the SW Filter Group and the _Nonce_.
In <<ACE-provisioning-export-import>>, it is explained how the associated policies are enforced.

//

The instruction `ace.restrict` can be used to set Localities, as well as replace Localities with more restrictive ones such as:

** _SiPScrt_ {rightarrow} _ChipFamScrt_, _ChipScrt_;
** _ChipFamScrt_ {rightarrow} _ChipScrt_;
** _OEMScrt_ {rightarrow} _ProdScrt_, _DevScrt_;
** _ProdScrt_ {rightarrow} _DevScrt_.
** _MLocality_ {rightarrow} _HLocality_, _SLocality_; and
** _HLocality_ {rightarrow} _SLocality_.

When the CR is exported, it will use the new Locality values to tweak the export algorithm.
Generalizing Localities is not permitted: Attempting to do so raises exception `ace_exc_invalid`, but the
State is not automatically set to _ace_state_invalid_ (the exception handler may of course do that).

// ////////////////////////////////////////////////////////////////////

[[ACE-UsagePolicy-field]]
===== _UsagePolicy_ Field

Any bit of this field is ignored if the corresponding mode is not supported or not enabled.

// ////////////////////////////////////////////////////////////////////

[[ACE-extra-content]]
===== _VarDataLen_ Field

The _VarDataLen_ Metadata field records the length of the _Additional Data Section_ of the content, which is a variable-size part and may depend on the state of the algorithm.

The format of the _Additional Data Section_ is described in <<ACE-data-formats>>.

The first 128 bits of the Implementation-Specific Variable-Length Data Section of the Content, if not empty, always hold a copy of the
following value
----
aceunitid := zeros(32) @ aceimpid @ acearchid @ acevendorid
----
(cf. <<ACE-CSR-impl-ids>>) of the originating machine, and are counted within the length recorded by the _VarDataLen_ field.
The importing implementation uses this value to determine whether any information in the Implementation-Specific Data Section can be used.

It is the responsibility of the *algorithm* to determine the lengths of the two parts of the Variable-Length Data Section.
If the Implementation-Specific Variable-Length Data Section is not empty, the *implementation* will check the `aceunitid`
stored therein to decide whether the Implementation-Specific part can be used or should be ignored.

[NOTE]
====
Examples of Variable-Length Data are:

. ŌĆ£Decryption AES keysŌĆØ, i.e., the last one or two AES round keys, from which one can work backwards when performing AES decryptions.
. Precomputed point multiples for elliptic curve scalar multiplication (their computation can be far more expensive than their
encryption and decryption);
. Information, such as additional elliptic curve points or random numbers used by Elliptic Curve algorithms only in certain states;
. any auxiliary data for side-channel-protected implementations, such as key shares or other data to accelerate share reconstruction.

Examples 1., 2., and 4. are optional data, and therefore are stored in the _Implementation-Specific_ VDS.
The third example, however, describes information that is required for the correct functioning of the algorithm. Therefore, its format must be defined by the algorithm specification and the data should be stored in the _Architected_ VDS.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata-expiration-date]]
===== _ExpirationDate_ Field

If non-zero, _ExpirationDate_ specifies the CC expiration time as a number of minutes elapsed since the base date of January 1, 2027.
The 26-bit field provides for a span of approximately 127 years (2^26^ minutes).

Checking against the _ExpirationDate_ field is, semantically, the first step performed by any operation.
When a non-configuration instruction is executed on a CR whose _ExpirationDate_ lies in the past, the hardware immediately sets the Metadata _State_ field to `ace_state_expired` and performs any action prescribed for Error States, including implementation-specific tasks such as releasing the CRF capacity held by the Content.  If the instruction is a usage instruction, the operation is suppressed and exception `ace_exc_invalid` is raised (cf. <<ACE-exceptions>>) if the ACE privileged architecture is implemented.  Exporting, cloning, or configuring an expired CR is allowed.

When an expired CR is used, privileged code may take appropriate actionŌĆöfor example, provisioning a new key or returning to the caller for handling.

Since privileged code may replace expired CRs, any user code that uses CRs that are known to potentially expire should always export the CR when it has finished using it, in case it may be needed later, instead of recovering it from a previously saved copy.

// ////////////////////////////////////////////////////////////////////

[[ACE-data-formats]]
===== Provisioning Input, Sealed Cryptographic Context, and Content

Only the first 64 bits of the Metadata Header are needed to determine the length of a PI or SCC.

The format of a Provisioning Input (PI) is shown in <<ACE-PI>>.

[[ACE-PI]]
.Format of the Provisioning Input (PI), All Sections in Order
[width="100%",cols="8%,26%,40%,26%",options="header"]
|===
| Section | Section Name                | Size | Description
| 1       | Metadata Header             | 128 bits | Contains the metadata information as described in <<ACE-Metadata>>.
| 2       | Provisioning Content        | Depends only on the _Algorithm_, _AlgorithmPolicy_, and _KeyType_ fields of the Metadata Header. Always a multiple of 128 bits. | Contains keys and other algorithm-specific information.
|===

The length of a PI must be a multiple of 128 bits.

The CR itself may contain significantly more information than the Provisioning Content.
This information may be categorized under different classes:

. Information that is necessary for the algorithm to function, and cannot be reconstructed from other information.
For instance, random values that are generated in the _Initial_ state.

. Information that may be easily reconstructed from other information in the State, so that there is no need to export it.
In this case, the *algorithm* may choose to not include it into an SCC.

. Data that can be used to optimize performance on a specific *implementation*, and that is more expensive to recompute than encrypting and storing externally. The hardware may choose to export such data in a custom format inside an SCC for efficient reuse.
A different implementation that receives the same SCC  may safely ignore this data during import
after checking `aceunitid`.

The format of a Sealed Cryptographic Context (SCC) is shown in <<ACE-SCC>>.

[[ACE-SCC]]
.Plaintext of the Sealed Cryptographic Context (SCC) Format, All Sections in Order
[width="100%",cols="6%,26%,42%,26%",options="header"]
|===
| Field | Field Name                   | Size     | Description
| 1     | Metadata Header              | 128 bits | The metadata information as described in <<ACE-Metadata>>.
| 2     | SIV                          | 128 bits | The SIV used to encrypt and authenticate sections 3 and 4.
//
| 3
| Content: _Fixed Data Section_
| If the CR is not in an Error State, the length depends only the
on the _Algorithm_, _AlgorithmPolicy_, and _KeyType_ fields of the Metadata Header.
 Always a multiple of 128 bits.
| Contains keys and other algorithm-specific information. Encrypted in memory and during import.
//
| 4
| Content: _Architected Variable-Length Data Section_ (Architected VDS)
| If the CR is not in an Error State, the length depends only on the information contained in the Metadata and Fixed Data Sections.
  Always a multiple of 128 bits.
| The data in this Section is necessary for the correct functioning of the algorithm.
//
| 5      | Implementation Identifier    | 128 bits if present | Used to identify the implementation of the ACE Unit
| 6.     | SIV2                         | 128 bits if present | The SIV used to encrypt and authenticate section 7.
| 7
| Content: _Implementation (Specific) Variable-Length Data Section_ (Implementation VDS)
| Implementation-Specific.
  Always a multiple of 128 bits.
| The data in this Section is _not_ necessary for the correct functioning of the algorithm.
  Encrypted in memory and during import.
|===

Fields 2-7 are empty if the context is exported in an Error State, in other words, the entire SCC consists only of a Metadata Header in plaintext.

The Metadata _VarDataLen_ field specifies the total size of the _Variable-Length Section_.
It does not partition this total between the Architected and Implementation-Specific segments.
The ordering of sections within the SCC allows to determine the lengths of these two parts before reading them.

// ////////////////////////////////////////////////////////////////////

[[ACE-provisioning-export-import]]
=== Provisioning, Export and Import of Cryptographic Contexts

// In this section we implicitly refer throughout to <<ACE-data-formats-intro>>, and in particular to <<ACE-PI>> and <<ACE-SCC>>.

The entire Metadata and Content are authenticated, but only the Content is encrypted.
The AEAD method used for this purpose is described in <<ACE-SCC-AEAD>>.

The ŌĆ£Serialized ContentŌĆØ section in the specification of each Algorithm (<<ACE-algorithms>>), defines the structure of the `ser_con[]` array.
Architecturally, `ser_con[]` is the serialization of the content of a CR for export as an SCC.
This array is the concatenation of all fields after the metadata header in a SCC specification.

[NOTE]
--
The structure of `ser_con[]` does not imply that the internal representation of a CR shall follow the same structure.

In some cases, this would not even be possible.
For instance, in a threshold implementation, a single key byte in `ser_con[]` may correspond to multiple bytes distributed across all key shares within the CR. Reading that byte returns the XOR of the corresponding bytes from the shares.
Writing to that byte may trigger multiple writes of single bytes, one per share, such that their XOR equals the input.
--

// `ser_con[]` is a virtual representation: its byte ordering does not imply
// physical contiguity within the CR, nor is there a direct byte-for-byte
// correspondence. Changes to `ser_con[]` are reflected in the underlying CR
// representation (except for excluded fields), and vice versa.

// ////////////////////////////////////////////////////////////////////

[[ACE-system-keys]]
==== System Keys and Randomly Generated Key Values

In a PI or SCC, System Keys are encoded as a 64-bit value used to retrieve the key from a system-specific structure, which we do not specify. The 64-bit value is called the System Key Identifier (SKID) and the structure is called the System Keys Store (SKS).
This replaces the key value itself, which may reduce the size of the PI or SCC content.

For threshold implementations of system keys, ACE may copy key material from the SKS into the CR and expand it into multiple shares.
The key is still exported as a SKID.

For the purpose of accelerating key share reconstruction in a threshold implementation, some shares of a system key can be included in the content's Additional Data, as long as the key cannot be recovered from those shares alone.

An all-ones (i.e., `ones(64)`) system key identifier in a PI means that the key material is generated randomly upon provisioning.
The _KeyType_ field in the metadata is then internally set to 0, and the key is then exported by value.
This applies to all keys at once in an algorithms, unless otherwise specified.

// ////////////////////////////////////////////////////////////////////

[[ACE-size-functions]]
==== Notation for the Size Functions

[WARNING]
====
Provisioning, import and export are being rewritten!
====

Let `MH` denote a Metadata Header.
In order to determine the total lengths of the PI and of the SCC, the implementation provides the following functions or an equivalent mechanism:

. ``MH_size`` returns the bit length of the Metadata Header. It is always 128.

. ``PI_content_size(MH)`` returns the bit length of the content section of a PI. It depends only on `MH`._Algorithm_, `MH`._AlgorithmPolicy_, and `MH`._KeyType_.

. ``base_content_size(MH)`` returns the bit length of the part of the content section of an SCC that depends only on  `MH`._Algorithm_,
  `MH`._AlgorithmPolicy_, and `MH`._KeyType_. It does not include the length of the Additional Data of the Content, of length _VarDataLen_ * 128 bits.

The total size in bits of a PI is therefore

`{fournbsp}{fournbsp}len_in_bits(PI){nbsp}` = `MH_size` + `PI_content_size(MH)`,

and the total size in bits of an SCC is

`{fournbsp}{fournbsp}len_in_bits(SCC)` = `MH_size` + 128 + `base_content_size(MH)` + _VarDataLen_ * 128 bits.

// ////////////////////////////////////////////////////////////////////

[[ACE-interruption-points]]
==== Interruptibility of Configuration and Export Operations

[WARNING]
====
Provisioning, import and export are being rewritten!
====

During `ace.prov`, flag _Provisioning_ is set to 1, and
during `ace.import`, flag _Importing_ is set to 1.
These flags are cleared to upon completion of `ace.prov` and `ace.import`.
It is updated to the correct value only upon successful completion (see <<ACE-provisioning-export-import>>).
This transition does not occur during `ace.export`.

A provisioning or import instruction may resume from the point of interruption only if control returns directly after the interrupt handler completes.
The implementation resumes such an instruction only if the CR has _State_ set to _Partially_Configured_ and a nonzero `acestart` value.
The privileged interrupt handler may allow resumption only in this case.

A partially configured CR cannot be exported.
At context save, therefore, privileged code must clear a partially configured CR.
Before returning control flow to the process of the interrupted configuration operation, the CR must be cleared as well, forcing the instruction to restart.

Upon returning to the original control flow from an interrupt or exception, an export may resume only if the CR has not been modified.
// This is achieved by the privileged code as follows: the `*crstatus` of the CR is saved and set to _Clear_.
// If, upon returning to the original control flow, the `*crstatus` is not _Clear_, the CR has been modified and therefore the code sets `acestart` to zero to force the export to restart. Otherwise, the code restores the saved `*crstatus` field and continues.
<<ACE-SCC-export>> describes the mechanism used to enforce this rule.

The above rules imply that interrupted configuration and export operations may resume only on the same hart.
This guarantees that resumption occurs on the same implementation, which is therefore free to define the interruption points and the corresponding non-zero values of `acestart`.

// ////////////////////////////////////////////////////////////////////

[[ACE-provisioning]]
==== Provisioning

[WARNING]
====
Provisioning, import and export are being rewritten!
====

We start with the algorithm performed by `ace.prov`, which loads a PI and uses
it to provision a CR.

[[ACE-provisioning-listing]]
.Provisioning a CR with Metadata and content
[]
----
function ace.prov(CR_number, M[]) =
{
  MH : bits(128) & ŌåÉ CR[CR_number].Metadata;  // By reference, from the CR
  MH ŌåÉ M[0 .. 15]
  MH.State ŌåÉ ace_state_partial_config;

  if (not enough memory for the algorithm encoded in the Metadata)
    raise exception ace_exc_out_of_mem;

  // Complete Metadata parsing
  if (Metadata is inconsistent)
    raise exception ace_exc_invalid;

  z ŌåÉ PI_content_size(Metadata[31:0]);

  * Read and deserialize the z bytes at M+16 into the CR.
  * This includes computing any derived values not saved as part of the SCC,
  * as well as creating shares for threshold implementations.

  MH.State ŌåÉ ace_state_initial;
}
----

// ////////////////////////////////////////////////////////////////////

[[ACE-SCC-AEAD]]
==== Key Derivation and POLYVAL

AES-GCM-SIV cite:[DBLP-journals-iacr-GueronLL17,RFC8452] is used to export and
import CRs.

NOTE: AES-GCM-SIV has been chosen because it only required single passes of data in
main memory, reducing the number of external memory accesses. GCM uses also a
single pass but requires separate nonce and tag values, increasing the size of
the exported data by one block.

We define the Key Derivation (<<ACE-SCC-RFC8452-derivation>>) and POLYVAL
(<<ACE-SCC-POLYVAL>>) functions first. The generation of an SCC from a CR
(<<ACE-SCC-export>>) and the import of an SCC into a CR (<<ACE-SCC-import>>)
are defined next.

[[ACE-SCC-RFC8452-derivation]]
.RFC8452 Key Derivation
[]
----
function RFC8452_KeyDeriv(key : bits(256))
    -> struct{enc_key : bits(256), auth_key : bits(128)} =
{
  return struct {
    AESE256(key, (zeros(125) @ 0b101))[63:0] @ AESE256(key, (zeros(125) @ 0b100))[63:0] @
    AESE256(key, (zeros(125) @ 0b011))[63:0] @ AESE256(key, (zeros(125) @ 0b010))[63:0],
    AESE256(key, (zeros(125) @ 0b001))[63:0] @ AESE256(key, (zeros(125) @ 0b000))[63:0]
  }
}
----

NOTE: Due to the computational cost of the derivation functions,
implementations may cache recently used derived keys.

The SIV ("synthetic IV") serves as both the initialization vector and the authentication tag in GCM-SIV.
It is computed by encrypting the `POLYVAL` hash of the concatenation of the Locality Secrets, the Metadata zero-padded to 128 bits, and the Content of the CR.
In the `POLYVAL` pseudocode below, the digested data is an array containing an integral number of 128-bit blocks.

[[ACE-SCC-POLYVAL]]
.Polyval Hashing Function
[]
----
function POLYVAL(auth_key : bits(128), blocks[0..n-1] : bits(128))
    -> bits(128) =
{
  local tmp : bits(128) ŌåÉ zeros(128);
  local i : int;
  foreach(i from 0 to n-1) {
    tmp ŌåÉ tmp xor blocks[i];
    tmp ŌåÉ Montmul(tmp, auth_key);
  }
  return tmp;
}
----

[[ACE-SCC-export]]
==== Export

[WARNING]
====
Provisioning, import and export are being rewritten!
====

During SCC export and import, the Locality Secrets associated with the Localities encoded in the Metadata's _Locality_ field are prepended to the input of the AEAD tag computation, in ascending index order, before the metadata.
If the _Locality_ field is zero, no Locality Secrets are prepended.

The ACE architecture supports at most one export or import resumable operation per hart at a time.

[NOTE]
====
This can be enforced as follows:

. An implementation maintains a single per-hart instance of the variables containing the `SIV` and related temporary state.
. To track an operation in progress, the implementation uses two 1-bit flags, `ace_exporting` and `ace_importing`, together with a 5-bit value `ace_expimported_cr` that records the number of the CR being exported or imported.
. These fields are set when an export or import begins and cleared upon completion.
. If the operation is interrupted, `acestart` is set accordingly.
. While `ace_exporting` is set, any instruction that modifies the internal state of CR `ace_expimported_cr` clears the flag.
. An export may resume only if the flag is still set and only for the recorded CR; otherwise, the export is restarted and `acestart` is ignored.

Without such a safeguard, resumption could yield an incorrect SIV.
While the pseudocode follows this mechanism to enforce the rule, implementation may choose to implement the rule differently.
====

[[ACE-SCC-export-listing]]
.Generation of an SCC from a CR
[]
----
function ace.export(CR_number, M[]) =
{
  MH : bits(128) & = CR[CR_number].Metadata;          // By reference

  * Create array of bytes ser_con[] from the CR's information.
  * ser_con[] can be either a serialization in a separate buffer, or temporary
  * in place, or even act like a functionof the actual information

  global ace_exporting, ace_importing : bool;
  global ace_expimported_cr : bits(5);
  global CSK : bits(256);
  global enc_key : bits(256), auth_key : bits(128); // RFC8452_KeyDeriv(CSK)
  global SIV, tmp : bits(128);

  ace_exporting ŌåÉ true;
  ace_expimported_cr ŌåÉ CR_number;
  ace_importing ŌåÉ false;

  local z : int ŌåÉ base_content_size(MH);  // can be recomputed upon resumption
  z ŌåÉ z + MH._VarDataLen_ * 128;           // Length of Content (in bits)
  local let num_blocks : int ŌåÉ ceil(z / 128);

  // In external memory: Metadata Header, then SIV, then Encrypted Content
  external M: array of ((MH_size + 128 + z) / 8) bytes.

  // Start POLYVAL: absorb Locality "prefix" (zero or more bit blocks)
  tmp ŌåÉ zeros(128);
  foreach(i from 0 to number of localities - 1, except "Nonce" Locality)
    if (CR.Metadata.Locality includes locality[i]) {
      tmp ŌåÉ tmp xor LST[i];
      tmp ŌåÉ Montmul(tmp, auth_key);
    }

  // POLYVAL: Absorb the metadata block into POLYVAL
  tmp ŌåÉ tmp xor MH;
  tmp ŌåÉ Montmul(tmp, auth_key);

  // POLYVAL: Absorb the entire content into POLYVAL
  foreach(i from 0 to num_blocks - 1) {
    tmp ŌåÉ tmp xor ser_con[i*16 .. 15+i*16];
    tmp ŌåÉ Montmul(tmp, auth_key);
  }

  if (MH.Locality includes the "Nonce" Locality) {
    tmp[95:0] <- tmp[95:0] xor LST[index of "Nonce" Locality][95:0];
  }
  SIV ŌåÉ AESE(enc_key, 0 @ tmp[126:0]);

  // Export metadata and the SIV to memory
  M[0 .. 15]  ŌåÉ MH;
  M[16 .. 31] ŌåÉ SIV;

  // Export encrypted context to memory
  foreach(i from 0 to num_blocks - 1)
    M[32+i*16 .. 47+i*16] ŌåÉ ser_con[i*16 .. 15+i*16]
            xor AESE(enc_key, 1 @ SIV[126:32] @ (SIV[31:0]+bin(i,32) % 2**32);

  ace_exporting ŌåÉ false;
}
----

// ///////////////////////////////////////////////////////////////////

[[ACE-SCC-import]]
==== Import

[WARNING]
====
Provisioning, import and export are being rewritten!
====

The import algorithm needs some special care:

* At the beginning of the import operation, the hardware saves the value of
  `State` from the original metadata and sets `MH.State <-
  ace_state_partial_config`. At the end of the import operation, `MH.State` is
  set to the saved value.
* The SCC to be imported may have been generated by a different implementation
  than the one importing it.
  The implementation will check the values of `acevendorid`, `acearchid`, and `aceimpid`
  in the `aceunitid` block to determine
  whether it known how to import the Implementation-Specific VDS.
  The SCC may even contain an Implementation-Specific VDS
  that exceed the maximum size supported by the importing hardware for the
  specific algorithm encoded in the Metadata.
  Once the Metadata and the Fixed Content Data Sections have been
  read, the implementation must determine the length of the Architected VDS
  corresponding to the algorithm's state, and ignore all writes to `ser_con[]`
  beyond the end of the Architected VDS in case it cannot import the implementation-dependent
  data after checking `acevendorid`, `acearchid` and `aceimpid`.
  It must still process the entire SCC to verify the authentication tag.
  After successful verification, the _VarDataLen_ field will be adjusted
  to the size of the Architected VDS.
  The Implementation-Specific VDS will be ignored.
  The details of this adjustment are not reflected in the pseudocode
  <<ACE-SCC-import-listing>> to avoid excessive complexity.

[[ACE-SCC-import-listing]]
.Importing an SCC into a CR
[]
----
function ace.import(CR_number, M[]) =
{
  // M : array of bytes;   from memory
  MH : bits(128) & = CR[CR_number].Metadata;          // By reference, from the CR

  local saved_SN : bits(5);                // This is a "hidden" state as well

  global ace_exporting, ace_importing : bool;
  global ace_expimported_cr : bits(5);
  global CSK : bits(256), enc_key : bits(256), auth_key : bits(128);
  global SIV, tmp, t2 : bits(128);

  ace_importing ŌåÉ true;
  ace_expimported_cr ŌåÉ CR_number;
  ace_exporting ŌåÉ false;

  tmp ŌåÉ M[0 .. 15];         // read Metadata Header
  saved_SN ŌåÉ ((Metadata field)tmp).State;
  MH ŌåÉ tmp;
  MH.State ŌåÉ ace_state_partial_config;

  z ŌåÉ base_content_size(MH);
  z ŌåÉ z + MH._VarDataLen_ * 128;

  if (there is not enough memory for the algorithm encoded in the Metadata)
    raise exception ace_exc_out_of_mem;

  num_blocks ŌåÉ ceil(z / 128);

  // Start POLYVAL
  // Absorb Locality "prefix" (zero or more 128-bit blocks)
  tmp ŌåÉ zeros(128);
  foreach(i from 0 to number of localities - 1, except "Nonce" Locality)
    if (MH.Locality includes locality[i]) {
      tmp ŌåÉ tmp xor LST[i];
      tmp ŌåÉ Montmul(tmp, auth_key);
    }
  }

  SIV ŌåÉ M[16 .. 31];
  tmp ŌåÉ tmp xor MH;
  tmp ŌåÉ Montmul(tmp, auth_key);

  * Create array of bytes ser_con[] to absorb the serialized content
  * It may internally overlap with the CR itself. Deserialization
  * can be performed in-place.

  foreach(i from 0 to num_blocks - 1) {
    t2 ŌåÉ M[32+i*16 .. 47+i*16]
         xor AESE(enc_key, 1 @ SIV[126:32] @ (SIV[31:0]+bin(i,32) % 2**32);
    ser_con[i*16 .. 15+i*16] ŌåÉ t2;
    tmp ŌåÉ tmp xor t2;
    tmp ŌåÉ Montmul(tmp, auth_key);
  }

  if (MH.Locality includes the "Nonce" Locality) {
    tmp[95:0] <- tmp[95:0] xor LST[index of "Nonce" Locality][95:0];
  }
  tmp ŌåÉ AESE(enc_key, 0 @ tmp[126:0]);

  if (tmp != SIV) {
    MH ŌåÉ zeros(128);
    MH.State ŌåÉ ace_state_import_auth;
    Clear all Contents and possibly release their memory;
    return;
  }

  * If the content has not been deserialized inline while absorbed,
  * it shall be deserialized here.
  * This includes computing any derived values not saved as part of the SCC,
  * as well as creating shares for threshold implementations.

  // FINALLY, restore the State from the SCC
  MH.State ŌåÉ saved_SN;

  ace_importing ŌåÉ false;
}
----

==== Why `ace.prov`, `ace.export`, and `ace.import` are CISC-like monolithic instructions

[WARNING]
====
This is a non-normative section describing why the current specification has CISC-like monolithic instructions `ace.prov`, `ace.export`, and `ace.import`.
====

It is envisionable that these operations could be described in a more RISC-like manner by splitting them into more operations.

*Import*
----
ace.open K0, import    // import is a flag/field
ld t0, 0(t6)           // load the medatada from memory
ace.setmd K0, t0       // this may fail if internal memory is not sufficient.
ace.size t1, t0        // now the size (except metadata) is in t1
ace.load K0, 8(t0), t1 // load t1 bytes or bits starting with the tag, fails if t1 is
                       // different than the expected data, but this can be checked
                       // asynchronously, so the actual size does not have to be
                       // fetched from the ACE unit
ace.seal K0            // this also decrypts and verifies
----

*Export*
----
ace.open K0, export    // export is a flag/field
ace.getmd t0, K0
ace.size t1, t0        // now the size of the SCC (except metadata) is in t1
sd 0(t6), t0           // store the metadata
ace.seal K0            // in this case, this computes the SIV
ace.store 8(t0), K0, t1 // stores t1 bytes or bits starting with the tag,
                       // fails if t1 is different than the expected data, etc
ace.close K0           // at this point, this is redundant...
----

*Provisioning*
----
ace.open K0, provision // provision is a flag/field
ld t0, 0(t6)           // load the medatada from memory
ace.setmd K0, t0       // this may fail if internal memory is not sufficient.
ace.size t1, t0, provision // now the size of the PI (except metadata) is in t1
ace.load K0, 8(t0), t1 // load t1 bytes or bits starting with the tag, fails if t1 is
                       // different than the expected data, etc
ace.seal K0            // this also reconstructs data if needed, makes CR useable
----

Shorter sequences could be as follows:

*Import*
----
ace.open K0, import // import is a flag/field
ld t0, 0(t6)
ace.setmd K0, t0    // this may fail if internal memory is not sufficient.
ace.load K0, 8(t0)  // load the right number of bytes or bits starting with the tag
ace.seal K0         // this also decrypts and verifies,
                    // then reconstructs the data if needed, makes CR useable
----

*Export*
----
ace.open K0, export // export is a flag/field
ace.getmd t0, K0
sd 0(t6), t0        // store the metadata
ace.seal K0         // in this case, this computes the SIV
ace.store 8(t0), K0 // stores t1 bytes or bits starting with the SIV,
                    // fails if t1 is different than the expected data, etc
----

*Provisioning*
----
ace.open K0, provision // provision is a flag/field
ld t0, 0(t6)
ace.setmd K0, t0       // this may fail if internal memory is not sufficient.
ace.load K0, 8(t0)     // load the right number of bytes or bits starting with the tag
ace.seal K0            // this also reconstructs data if needed, makes CR useable
----

On the opposite side, even longer instruction sequences could be used with explicit writing of XLEN-long values from the GPRs into a CR's state, in loops (a CSR and `acestart` or CSR indirect addressing can be used to implement such a mechanism.

However, such code cannot be safely resumed after preemption, particularly in the case of export.
The architecture does not guarantee that exporting and then reimporting a CR yields an identical CR; it only guarantees that the reimported CR can be used as if nothing had happened.
Hence, resuming when the CR may have been modified is hazardous.

In the current CISC-like model, this situation is handled naturally:
if for any reason the export operation must be restarted instead of resumed,
the single monolithic instruction will indeed be restarted.

With separate instructions, however (for example, `ace.open` followed by `ace.getmd`, then storing the metadata and emitting the contents via a single instruction or a loop), this situation cannot be avoided.
There is no general mechanism to restart an instruction sequence or force control flow to revert, since privileged code cannot be assumed to know the semantics of the interrupted sequence and backtrack accordingly.

Let us consider the case an export operation for a CR is preempted.
The CR expires during a context switch, or even during the brief time an exception is handled (for instance, a memory page access fault is remediated).
Upon restoration, the operation marks the CR as _Expired_ and may release internal resources.
The restored CR is therefore internally smaller than before.
If the export operation is then resumed in software, the hardware produces a smaller output, yielding an inconsistent SCC: the SIV will be incorrect, and the metadata will not match the version already written to memory.

_Unless the last `ace.open` instruction causes its PC to be written into a special CSR that can be used by privileged code to resume from there instead of from the PC. But this opens another can of worms since the loading code may be subtly different or have some side effects..._

// ////////

[[ACE-algorithms-spec]]
=== Algorithms

_This section is normative._

This section specifies the behavior of the ACE instructions for the supported
cryptographic algorithms. Some specifications define algorithm families that
can be instantiated with any primitive meeting certain properties, typically
constraints on the block size `b` and the key size `k`ŌĆösuch as GCM or GCM-SIV,
which are well defined not only with AES but also with other block ciphers,
such as SM4. By contrast, the specifications for other algorithm suites are
specific only to some primitives, for instance, Ascon.

<<ACE-exec-encodings>> defines the operation encodings for the symmetric
algorithms encoded in the metadata field _Algorithm_.
These algorithms are encoded using two sub-fields: Type and Mode.
Type is encoded in the six LSBs of _Algorithm_, and mode is encoded in the
next five LSBs of _Algorithm_.
For other algorithms, the subdivision of the _Algorithm_ field may be different.
The ŌĆØ(reserved)ŌĆØ suffix after an algorithm name indicates that the algorithm is
not completely defined or has some ambiguity because of the lack of a standard.

[[ACE-exec-encodings]]
.Algorithm Type and Mode Encodings
[float="center",align="center",width="72%",cols="^8%,^8%,<28%,<28%",options="header"]
|===
| Type | Mode | Algorithm name           | Extensions Requirement
| 0    | 0    | `AES128_ECB`               | `Zlaes128p`
| 0    | 1    | `AES128_CTR`               | `Zlaes128p` and `Zlctrm`
| 0    | 2    | `AES128_LFSR` (reserved)   | `Zlaes128p` and `Zlctrm`
| 0    | 3    | `AES128_XCTR`              | `Zlaes128p` and `Zlxctrm`
| 0    | 4    | `AES128_XLFSR` (reserved)  | `Zlaes128p` and `Zlxctrm`
| 0    | 5    | `AES128_XEX1` (one key)    | `Zlaes128p` and `Zlxexm`
| 0    | 6    | `AES128_XEX2` (two keys)   | `Zlaes128p` and `Zlxexm`
| 0    | 7    | `AES128_GCM`               | `Zlaes128p` and `Zlgcmm`
| 0    | 8    | `AES128_GCM_IV`            | `Zlaes128p` and `Zlgcmm`
| 0    | 9    | `AES128_GCM_SIV`           | `Zlaes128p` and `Zlgcmsivm`
| 0    | 10   | `AES128_CMAC`              | `Zlaes128p` and `Zlcmac`
| 0    | 11   | `AES128_OCB`               | `Zlaes128p` and `Zlocbm`
| 0    | 12   | `AES128_OCB_IV`            | `Zlaes128p` and `Zlocbm`
//
| 1    | 0    | `AES192_ECB`               | `Zlaes192p`
| 1    | 1--12 2+| Analogues to Modes 1--11 for `AES128`, but with 192 replacing 128.
//
| 2    | 0    | `AES256_ECB`               | `Zlaes256p`
| 2    | 1--12 2+| Analogues to Modes 1--11 for `AES128`, but with 256 replacing 128.
//
| 3    | 0    | `SM4_ECB`                  | `Zlsm4p`
| 3    | 1--10 2+| Analogues to Modes 1--10 for `AES128`, but with `SM4`, resp., `sm4` replacing `AES128`, resp., `aes128`.
//
| 4    | 0    | `SHA2-224`                 | `Zlesha2h`
| 4    | 1    | `SHA2-256`                 | `Zlesha2h`
| 4    | 2    | `SHA2-384`                 | `Zlesha2h`
| 4    | 3    | `SHA2-512`                 | `Zlesha2h`
| 4    | 4    | `SHA2-512/224`             | `Zlesha2h`
| 4    | 5    | `SHA2-512/256`             | `Zlesha2h`
| 4    | 6    | `SHA2-224_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 7    | `SHA2-256_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 8    | `SHA2-384_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 9    | `SHA2-512_HMAC`            | `Zlesha2h` and `Zlhmacm`
| 4    | 10   | `SHA2-512/224_HMAC`        | `Zlesha2h` and `Zlhmacm`
| 4    | 11   | `SHA2-512/256_HMAC`        | `Zlesha2h` and `Zlhmacm`
//
| 5    | 0    | `SHA3-224`                 | `Zlesha3h`
| 5    | 1    | `SHA3-256`                 | `Zlesha3h`
| 5    | 2    | `SHA3-384`                 | `Zlesha3h`
| 5    | 3    | `SHA3-512`                 | `Zlesha3h`
| 5    | 4    | `SHAKE128`                 | `Zlesha3h`
| 5    | 5    | `SHAKE256`                 | `Zlesha3h`
| 5    | 6    | `SHA3-224_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 7    | `SHA3-256_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 8    | `SHA3-384_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 9    | `SHA3-512_HMAC`            | `Zlesha3h` and `Zlhmacm`
| 5    | 10   | `KMAC128`                  | `Zlesha3h` and `Zlkmacm`
| 5    | 11   | `KMAC256`                  | `Zlesha3h` and `Zlkmacm`
//
| 6    | 0    | `SM3`                      | `Zlsm3h`
| 7    | 0    | `Ascon-AEAD128`            | `Zlascon`
| 7    | 1    | `Ascon-AEAD128_Nonce`      | `Zlascon`
| 7    | 2    | `Ascon-AEAD128_Nonce_Mask` | `Zlascon`
| 7    | 3    | `Ascon-Hash256`            | `Zlascon`
| 7    | 4    | `Ascon-XOF128`             | `Zlascon`
| 7    | 5    | `Ascon-CXOF128`            | `Zlascon`
|===

//

==== Padding

As a general rule, inputs shorter than a full vector length must be handled by the caller.
The caller is responsible for proper padding and for passing the actual input length to the algorithm at the appropriate places using the correct instructions, usually `ace.setst`.
An exception applies when an algorithm specification defines such handling itself for cryptographic security reasons.

==== Definition of an Algorithm in ACE

Each algorithm is fully defined by the following information:

Parameters:::
+
--
These include:

* The _block size_ `b`, which is the size of the basic unit of information
  processed by the algorithm, usually the block size of the main underlying
  primitive;
* The _key size_ `k`, for keyed algorithms; and
* Any other parameter needed to instantiate the algorithm with compatible
  primitives.
--
+

Data Structures:::
+
--
These include:

. *Provisioning Input* (Content):
The data following the Metadata Header in the PI, such as keys and other
required secrets. The fields are listed in the order they appear in the PI,
each with its length.

. *Internal State* (Content):
Information maintained in the internal state of a CC beyond what the metadata provides.
Field ordering is unspecified, and field lengths may differ from those listedŌĆöfor example, in threshold or fault-tolerant implementations.
This information is necessary to be able to define the algorithms and their semantics, and must exist internally, though not necessarily in a prescribed format.
An actual implementation may define the internal state and the behavior at each state in a different way, however the semantics of the algorithm must be equivalent to those defined in this specification.

. *Serialized Content*:
The data that follows the Metadata Header in the plaintext portion of an SCC.
The fields are listed in the order they appear in an SCC, each with its length.
--
+

Algorithm-Specific Functions:::
Any other function that is specific to the algorithm.

State Machine:::
+
--
The state machine is defined by the following information:

. A list of *States* in which the internal state machine of the logic is
  executed, together with their representation according to the rules set in
  <<ACE-State-field>>.
. A complete list of the *allowed state transitions*, including the precise
  conditions under which each transition is allowed, the Form of `ace.setst`
  used for each of these transitions and the meaning of any additional
  parameter;
. The enumeration of the *allowed/expected instructions* at each state and their
  *behavior*.
  Besides configuration and export instructions,
  the instructions permitted in each algorithm state are typically `ace.exec` and `ace.setst`.
  For `ace.exec`, only one of its Forms (see <<ACE-instruction-exec>>) is _expected_ per state.
  By this we intend that either the specified Form must be issued, or Form D `ace.exec` or
  Form C `ace.setst` instead, with appropriate setup instructions for the ACEIOBUF.
  Issuing the `ace.input`/`ace.output` instructions are not enforced, as properly
  handling of the inputs and outputs is the responsibility of the caller.

// [WARNING]
// ====
// CHANGE:
//
// ====
--
+

//

Pseudocode is provided to illustrate the software implementation of ACE-supported algorithms using the ACE ISA.
The pseudocode uses the vector registers and omits the alternative sequences based on ACEIOBUF.
The examples are non-normative.

// ////////////////////////////////////////////////////////////////////

[[ACE-generic-rules]]
==== Generic Rules

. `ace.prov`, `ace.import`, `ace.export`, `ace.clone`, and `ace.clear` are always allowed, even if not explicitly mentioned in an algorithm specification.

. If a usage instruction that may modify the state of a CR is issued, or a state transition is requested in `ace.setst`, that are not explicitly allowed by the current state of the algorithm encoded in the CC in the CR an _illegal instruction exception_ is raised, and the CR is invalidated.

// ////////////////////////////////////////////////////////////////////

[[ACE-notation]]
===== Notation in the Algorithm Descriptions

* `INPUT`: The input data to be processed by `ace.exec` or `ace.setst`. This
  can be the input vector register, or the ACEIOBUF, as described in
  <<ACE-usage-input-output>>.

* `OUTPUT`: The output data produced by `ace.exec`. This can be the output
  vector register, or the ACEIOBUF, as described in <<ACE-usage-input-output>>.

* `ACELEN`: Either `VL*SEW` or the length `aceiobuftop` of the ACEIOBUF in
  bits, depending on whether vector registers are used or the ACEIOBUF is
  used.

// ////////////////////////////////////////////////////////////////////

[[ACE-rules-threshold-implementations]]
===== Single-Share Key Export Rule for Threshold implementations

. Any CC with its algorithm implemented as a threshold implementation will always
provision, import and export _all_ its keys and secrets as _single_,
_reconstructed_ _shares_.

. The PI and SCC Formats will be the same as for the non-threshold implementation
variants of the same algorithm, with the only difference being the value of the
_SCProtection_ in the Metadata.

. {empty}
+
--
For the purpose of architecture specification, all values are also always
represented as a single share in this document. Threshold implementations are
simply implementation variants of the same algorithm.
(((ACE, algorithm, threshold variants)))

NOTE: This rule assumes that reconstructing or re-randomizing a key is a fast
operation, such as an ``xor`` with random values. This requires the ACE
execution unit to have access to a random number generator. Besides ensuring
the compactness of an SCC, this rule also guarantees key portability across
architectures that implement side-channel protection in different ways. If
reconstructing the values is efficient but generating the shares is a slow
process, the implementation may take advantage of the optional Additional Data
in the Content to store information that can accelerate share generation, such
as a copy of some (or all) shares.
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-rules-system-keys]]
===== Representation of System Keys in the Data Structures

System Keys will change all the algorithms described here in the following way:

. In a PI and in an SCC, the key field will contain the SKID of the system key in place of the value.
. This field is reduced from the original key size to a 64-bit value. This
  saves space in an SCC and allows for faster export and import operations.
. For algorithms that require more than one key, such as XEX/XTS, a single
  SKID is used to refer retrieve multiple keys from the SKS.

// ////////////////////////////////////////////////////////////////////

[[ACE-states-symmetric]]
==== States for the Symmetric Algorithms Defined in this Specification

The following table, together with <<ACE-states-valid>>, defines the states used by the symmetric algorithms in this specification.

[[ACE-state-constants-symmetric]]
.Constants defining CC states for symmetric algorithms
[float="center",align="center",width="100%",cols="^6%,<30%,<17%,<47%",options="header"]
|===
| Value | Mnemonic for the Constant         | State Name          | Description
.2+| 2  |  `ace_state_operate`              |  _Operate_          | Generic operational state.
<|  `ace_state_hash_absorb`                 | _Hash_Absorb_       | Start and initialize a hash function of the tag/MAC part of an algorithm and start absorbing blocks of data (in the case of an AEAD algorithm, this usually is the associated data).
|   3   |  `ace_state_hash_last_block`      | _Hash_Last_Block_   | In this state additional data may be absorbed, such as partial blocks and lengths, if the hash/tag algorithm processes the last block of its input or of the associated data part of its input in a different way from the other blocks.
|   4   |  `ace_state_hash_finalize`        | _Hash_Finalize_     | Finalize the internal state of a hash/tag function.
|   5   |  `ace_state_hash_verify`          | _Hash_Verify_       | Compare the internal hash/tag value to the provided one.
|   6   |  `ace_state_hash_output`          | _Hash_Output_       | Enter the hash output phase of a hash/tag function.
|   7   |  `ace_state_encrypt`              | _Encrypt_           | In this state encryption is performed, as well as an update to the tag computation if this operation is part of the algorithm.
|   8   |  `ace_state_decrypt`              | _Decrypt_           | In this state decryption is performed, as well as an update to the tag computation if this operation is part of the algorithm.
|   9   |  `ace_state_enc_last_block`       | _Enc_Last_Block_    | For the encryption path of authenticated encryption modes of operation to process the last block separately.
|  10   |  `ace_state_dec_last_block`       | _Dec_Last_Block_    | For the decryption path of authenticated encryption modes of operation to process the last block separately.
|  11   |  `ace_state_enc_tag_finalize`     | _Enc_Tag_Finalize_  | Finalize the tag computation for AE mode encryption.
|  12   |  `ace_state_dec_tag_finalize`     | _Dec_Tag_Finalize_  | Finalize internal tag computation for AE mode decryption, verify the value.
|  13   |  `ace_state_set_aux_value`        | _Set_Aux_Value_     | Set a public/auxiliary value in an algorithm.
|===

NOTE: _Operate_ and _Hash_Absorb_ have the same state number. _Hash_Absorb_ is simply a more intuitive mnemonic for hash functions.

NOTE: The `ace.setst` instruction used to transition to states _Hash_Absorb_,
_Encrypt_, or _Decrypt_ often also sets a public value. For algorithms
requiring multiple public values or additional parameters (e.g., tag length),
these can be set by transitioning to State _Set_Aux_Value_ using a Form of
`ace.setst` with an auxiliary argument, i.e., Form B or C.

// ////////////////////////////////////////////////////////////////////

[[ACE-ECB-mode]]
===== Electronic Codebook Modes (Direct Encryption/Decryption)

ECB mode cite:[nist-SP-800-38A-1] is the simplest way to use a block cipher.
(((ACE, algorithm, ECB)))

Parameters:::

* `b` = block size (8|`b`). `ACELEN` must be a multiple of `b` (including `b`).
* `k` = key size (8|`k`).

Data Structures:::
* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64      | Key or System Key Identifier
|===
--
+

 * *Internal State* (Content):
 ** `key`: `k` bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|   i   | `k` or 64      | Key or System Key Identifier
|===
--
+

Algorithm-Specific Functions:::
* `enc_blk(K,p) -> c` encrypts plaintext block `p` using the key `K`, and
  returns the ciphertext result `c`.
* `dec_blk(K,c) -> p` decrypts ciphertext block `c` using the key `K`, and
  returns the plaintext result `p`.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Encrypt_: Encrypting blocks of input.
 ** _Decrypt_: Decrypting blocks of input.

* *Allowed State Transitions:*
 ** From any valid state to _Encrypt_, if encryption is allowed.
 ** From any valid state to _Decrypt_, if decryption is allowed.

* *Behavior:*
 ** In State _Initial_, no `ace.exec` instruction is allowed.
 ** In States _Encrypt_ or _Decrypt_, Form A `ace.exec` instructions can be issued, i.e.,
+
ŌĆ£`ace.exec OUTPUT, Kn|K(Xn), INPUT`.ŌĆØ

  *** If the state is _Encrypt_, then `OUTPUT <- enc_blk(key, INPUT)`.
  *** If the state is _Decrypt_, then `OUTPUT <- dec_blk(key, INPUT)`.
  *** If `ACELEN` > `b`, then ŌĆ£`ace.exec OUTPUT, Kn|K(Xn), INPUT`ŌĆØ
      encrypts/decrypts block-by-block. Here, and in the rest of this document,
      this means from the blocks in the least significant positions to the most
      significant positions:
      . `foreach(i from 0 to ACELEN-b by b)` {
      ..   `OUTPUT[i+b-1:i] <- enc_blk(key, INPUT[i+b-1:i])` }

//

In <<ACE-pseudocode-ECB-encryption>> we illustrates how to use an ECB CC to
encrypt a block of data.

// // ////////////////////////////////////////////////////////////////////

[[ACE-chaining]]
===== Chaining/Feedback Modes

There is no need to explicitly architect the behavior of chaining modes, such
as Cipher Block Chaining (CBC), Cipher Feedback (CFB) and Output Feedback
(OFB)ŌĆōall defined in cite:[nist-SP-800-38A-1]ŌĆōas they are easily implemented in
software on top of the ECB, with no intermediate value requiring
confidentiality.

// ////////////////////////////////////////////////////////////////////

[[ACE-keystream-modes]]
===== CTR/LFSR/XCTR/XLFSR Keystream Generation

In the ŌĆ£non-XŌĆØ modes, i.e., CTR mode and its analog with an LFSR replacing the
arithmetic counter, the sum of the lengths of IV and counter/LFSR equals the
block size of the underlying keyed PRP or PRF. IV and counter/LFSR are
concatenated to form the input to the latter.
(((ACE, algorithm, keystream generation)))

In the ŌĆ£XŌĆØ modes, both IV and counter/LFSR have the same size as the block size
of the underlying keyed PRP or PRF. IV and counter/LFSR are ``xor``ed together
to form the input to the keyed PRP or PRF.

Parameters:::
* `b` = block size (8|`b`). For this algorithm `ACELEN` must be a multiple of `b`.
* `k` = key size (8|`k`).
* `j` = counter size (8|`j`).
* `n` = IV size (8|`n`).
* If the mode is CTR or LFSR, it is `b = n + j`, else it is `b = n = j`.

Data Structures:::
* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64     | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`: `k` bits.
 ** `IV`: `n` bits.
 ** `ctr`: `j` bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | `k` or 64       | `key` or System Key Identifier
|   ii  | `n`             | `IV`
|  iii  | `j`             | `ctr`
|===
--
+

Algorithm-Specific Functions:::
* `keystream_block(p) -> c` -- usually an encryption function.
* `tick_ctr()` -- updates the `ctr` (either by a modular increment or a LFSR).

State Machine:::
* *States:*
  ** _Initial_: The CC is ready.
  ** _Operate_: In this state the CC will produce a keystream.

* *Allowed State Transitions:* any.

* *Behavior:*
 ** In State _Initial_, the `ctr` and `IV` fields are set to 0 (`ctr` is set to
    1 if the algorithm is LFSR-based).

 ** To transition to State _Operate_, a Form C ``ace.setst`` instruction must
    be issued.
  *** This sets the value of `IV` to `INPUT`.
  *** If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are
      considered.

  ** In State _Operate_, ``ace.exec`` instructions are expected to be of Form C.
     ŌĆ£```ace.exec OUTPUT, Kn|K(Xn)```ŌĆØ performs:
+
--
  . If in a CTR or LFSR mode then `tmp ŌåÉ keystream_block(IV @ ctr)`,
    else (i.e., if in a XCTR or XLFSR mode) `tmp ŌåÉ keystream_block(IV xor ctr)`,
  . `tick_ctr()`, and
  . `OUTPUT ŌåÉ tmp`.
--
+
If `ACELEN` is a multiple of `b`, the above three commands are applied to each
of the `ACELEN/b` `b`-bit blocks of `INPUT`, producing the corresponding `b`-bit
block of `OUTPUT` each time.
// If the number `x` of blocks to be processed in an entire run of the algorithm is not a multiple of `ACELEN`/`b`, `VL` can be set to the remainder of the division of `x` by `ACELEN`/`b` for the last instruction.

Note that if `ace.setst` is issued to return to State _Initial_, the CC can be
reused with a new IV.

Example pseudocode is given in <<ACE-pseudocode-keystream-modes>> (for the case
`b` = `ACELEN` = 128).

// ////////////////////////////////////////////////////////////////////

[[ACE-XEX-XTS-modes]]
===== XEX/XTS modes (one or two keys)

The XTS mode was designed for storage confidentiality
cite:[DBLP-journals-ieeesp-Martin10] and made into a Recommendation by NIST in
2010 cite:[nist-SP-800-38E]. XTS is based on the XEX construction, formalized
by Phillip Rogaway cite:[DBLP-conf-asiacrypt-Rogaway04], to design _Tweakable
Block Ciphers_ cite:[DBLP-conf-crypto-LiskovRW02]. A Tweakable Block Cipher
(TBC) is a block cipher which, besides the key and the plaintext or ciphertext,
also takes a tweak as input. The tweak is used together with the key to select
the permutation computed by the block cipher.

The XEX construction builds a TBC `ß║╝` from a block cipher `E`, with key `K`,
tweak `T`, and plaintext `P`,  as follows: +
 +
`{fournbsp}{fournbsp}`
`ß║╝(K, T, P) = E(K, P xor M) xor M` `{nbsp}{nbsp}` where `{nbsp}{nbsp}` `M = E(K, T)` `{nbsp}{nbsp}` is called a _mask_. +
 +
In XEX mode, once a mask is computed, it is then updated by using a Galois
Multiplication for any successive block instead of updating the tweak and
encrypting it again.

The NIST standard uses two different keys, one for the data encryption path and
one for the encryption of the tweak. The use of a single key or two
independently sampled keys is determined by the algorithm, and it is not a
configuration parameter for the algorithm. We first define XEX mode
functionality.
(((ACE, algorithm, XEX)))

Parameters:::

* `b` = block size (8|`b`). For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = key size (8|`k`).

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)     | Field
|   i   | `k` or 64       | `key1` or System Key Identifier
|  ii   | `k` or 0        | `key2` or empty if `key1` given
|===
--
+

* *Internal State* (Content):
 ** `key1`: `k` bits.
 ** `key2`: `k` bits -- omitted if only one key is used or if both keys come from an entry in the SKS.
 ** `mask`: `b` bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64     | `key1` or System Key Identifier
|  ii  | `k` or 0      | `key2` or empty if `key1` given
| iii  | `b`           | `mask`
|===
--
+

Algorithm-Specific Functions:::

* `enc_blk(K, p) -> c` encrypts block `p` using the key `K`, and returns the result `c`.
* `dec_blk(K, c) -> p` decrypts block `c` using the key `K`, and returns the result `p`.
* `update_mask(mask) -> mask` updates the mask by a Galois Field multiplication in GF(2^b^).

State Machine:::

* *States:* _Initial_, _Encrypt_, and _Decrypt_ (defined as before, cf. <<ACE-ECB-mode>>).

* *Allowed State Transitions:*
 ** _Initial_ -> _Encrypt_, if encryption is allowed.
 ** _Initial_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_, _Decrypt_ -> _Initial_.

* *Behavior:*
 ** In State _Initial_:
  *** The `mask` field is set to zero.
  *** No ``ace.exec`` operation is allowed.
 ** The ``ace.setst`` instruction to transition to either _Encrypt_ or _Decrypt_ is expected to be of Form C.
    It sets the tweak, and the `mask` field is used to store it: `mask <- INPUT`.
  *** If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.
  *** Then, the following operations are performed:
  . if two independent keys are used then
  .. `mask <- enc_blk(key2, mask)`
  . else
  ..  `mask <- enc_blk(key1, mask)`
  ..  `mask <- update_mask(mask)`.

  ** In States _Encrypt_ and _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.
    ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```ŌĆØ performs the following operations:
+
--
  . `OUTPUT` is computed as follows:
  .. In State _Encrypt_, `OUTPUT <- mask xor enc_blk(key1, INPUT xor mask)`.
  .. In State _Decrypt_, `OUTPUT <- mask xor dec_blk(key1, INPUT xor mask)`.
  . `mask <- update_mask(mask)`.
--
+
If `ACELEN` is a multiple of `b`, the above commands are executed `ACELEN/b` times, processing each `b`-bit block of `INPUT` into a `b`-bit block of `OUTPUT`.

//

Note that if `ace.setst` is issued to return to State _Initial_, the CC can be reused with a new tweak.

Encryption pseudocode is provided in  <<ACE-pseudocode-basic-IV-mode>>,
decryption is similar

// ////////////////////////////////////////////////////////////////////

[[ACE-tweakable]]
===== Generic Tweakable Block Ciphers

The specification of a generic tweakable block cipher is similar to that of a
non-tweakable block cipher in ECB mode. Since `ace.exec` does not admit
variants with two inputs, and we have a single input buffer, we set the tweak
with a separate instruction. If block and tweak sizes are different, a
reconfiguration of the vector length may be required between operations, unless
the tweak is shorter than the block size, in which case the instruction setting
the tweak will only consider the necessary bits.

Some commonly used TBCs are `Deoxys` cite:[Deoxys-141], `Skinny`
cite:[DBLP-conf-crypto-BeierleJKL0PSSS16], `QARMA`
cite:[DBLP-journals-tosc-Avanzi17], and ```QARMA```{empty}```v2```
cite:[DBLP-journals-tosc-AvanziBDEGNR23].

Parameters:::

* `b` = block size (8|`b`). For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = key size (8|`k`).
* `t` = tweak size (8|`k`).

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|  i   | `k` or 64       | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`: `k` bits.
 ** `tweak`: `t` bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64     | `key` or System Key Identifier
|  ii  | `t`           | `tweak`
|===
--
+

State Machine:::

* *States:*
 ** _Initial_, _Encrypt_, and _Decrypt_ defined as before.
 ** _Set_Aux_Value_, for setting the tweak value in the next encryption or decryption operation.

* *Allowed State Transitions:*.
 ** _Initial_ -> _Set_Aux_Value_
 ** _Set_Aux_Value_ -> _Encrypt_, if encryption is allowed.
 ** _Set_Aux_Value_ -> _Decrypt_, if decryption is allowed.

 * *Behavior:*
  ** In State _Initial_:
   *** Upon entering the state, the `tweak` field is cleared.
  ** In each state, Form C `ace.setst` instructions can be issued, which perform:
   . `tweak <- INPUT`, and,
   . Instead of transitioning to State _Set_Aux_Value_, the State remains
     unchanged (can be initial, encrypt, or decrypt).
  ** In State _Encrypt_, respectively, _Decrypt_, besides Form C `ace.setst`
     instructions, ``ace.exec`` instructions are expected to be of Form A, where
     ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```ŌĆØ encrypts, respectively, decrypts
     `INPUT` into `OUTPUT`.
  ** This algorithm does not automatically update the tweak value.

// ////////////////////////////////////////////////////////////////////

[[ACE-GCM-mode]]
===== GCM Mode

The GCM mode was designed by David McGrew and John Viega
cite:[DBLP-conf-indocrypt-McGrewV04] and was made into a NIST Recommendation in
2007 cite:[nist-SP-800-38D].
(((ACE, algorithm, GCM)))

Parameters:::

* `k` = key size (8|`k`).
* `b` = block size (8|`b`). For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `c` = counter size (8|`b`). It must be `c < b`.

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64     | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`: `k` bits.
 ** `ctr`:  ``c`` bits.
 ** `IV`:  `b`-`c` bits.
 ** `auth_key`, `tag`: `b` bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|   i   | `k` or 64     | `key` or System Key Identifier
|  ii   | ``c``         | `ctr`
| iii   | ``b``-``c``   | `IV`
|  iv   | `b`           | `tag`
|===
--
+

NOTE: There are no fields for the lengths of the AD and of the plaintext, as
they are maintained by the calling software. Also, `hash_key` is not
serialized, and thus it is recomputed upon `ace.import`.

Algorithm-Specific Functions:::

* `enc_blk(key, p) -> c` encrypts block `p` using the key, and returns the
  result `c`.

* `absorb(data)` absorbs data into the hash function by performing:
  . `tag <- tag xor INPUT`.
  . `tag <- Galoismul(tag, hash_key)`.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Process Associated Data (AD) into the tag.
 ** _Encrypt_: Encrypt the plaintext and absorb the ciphertext into the tag.
 ** _Enc_Tag_Finalize_: Finalize the encryption tag, prepare to return its value.
 ** _Decrypt_: Absorb the ciphertext into the tag and decrypt it.
 ** _Dec_Tag_Finalize_: Finalize the encryption tag and keep it internally.
 ** _Hash_Verify_: Compare the tag against a user supplied value.
 ** _Success_: The algorithm has completed its operation correctly.
 ** _Failure_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_.
 ** _Hash_Absorb_ -> _Encrypt_, if encryption is allowed.
 ** _Hash_Absorb_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_ -> _Enc_Tag_Finalize_ -> _Success_.
 ** _Decrypt_ -> _Dec_Tag_Finalize_ -> _Hash_Verify_ -> _Success_ or _Failure_.

* *Behavior:*
 ** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `hash_key <- enc_blk(key, zeros(b))`,
   . `tag <- zeros(b)`,
   . `ctr <- zeros(c-1) @ 1`, and
   . `IV <- zeros(b)`.

 ** To transition to State _Hash_Absorb_: the ``ace.setst`` instruction must be
    a Form C to set the IV, i.e., the fixed part of the counter. Then:
   . `IV <- INPUT[b-c-1:0]`.
  *** If the ``ace.setst`` instruction is repeated, it will just update the
      counter again.

 ** If the AD is empty, the transition to State _Hash_Absorb_ is necessary to
    initialize the counter.

 ** In State _Hash_Absorb_, an ``ace.exec`` instruction of Form B is expected, whereby
 ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ absorbs a data block in `tag`, i.e.:
+
--
 . `absorb(INPUT)`.
--
+
If `ACELEN` > `b`, the above operation is executed `ACELEN/b` times.

** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A.
   ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```ŌĆØ encrypts `INPUT` into `OUTPUT`, and
   absorbs `OUTPUT` into the `tag`, namely:
+
--
  . If `ctr = ones(c-1)`, then
  ..  the CR is *invalidated*.
  . else
  .. `tmp <- INPUT xor enc_blk(key, IV @ ctr)`.
  .. `absorb(tmp)`.
  .. `ctr <- ctr + 1 % 2^c^`.
  .. `OUTPUT <- tmp`.
--
+
If `ACELEN` is a multiple of `b`, the above operations are executed `ACELEN/b` times, encrypting each `b`-bit block of `INPUT` into the corresponding `b`-bit block of `OUTPUT`.

** To transition to State _Enc_Tag_Finalize_, a Form C `ace.setst` instruction is issued, with the following value, as computed by the software itself:
+
--
[none]
* `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2){nbsp}` .

The authentication tag is then computed as follows:

. `absorb(INPUT)`.
  . `tag <- tag xor enc_blk(key, IV @ zeros(c))`.

Finally, `tag` is returned in `OUTPUT`, and the state is changed to _Success_.

If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.
--
+

** {empty}
+
--
In State _Enc_Tag_Finalize_, ``ace.exec`` instructions are expected to be of Form C.

ŌĆ£```ace.exec OUTPUT, Kn|K(Xn)```ŌĆØ writes the `tag` to `OUTPUT`, and the state
  transitions to _Success_.
--
+

** {empty}
+
--
In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.

 ```ace.exec OUTPUT, Kn|K(Xn), INPUT``` absorbs the ciphertext `INPUT` into the
 `tag`, then decrypts `INPUT` into `OUTPUT`, namely:

 . If `ctr == ones(c-1)`, then
  .. the CR is *invalidated*.
  . else
  .. `absorb(INPUT)`.
  .. `OUTPUT  <- INPUT xor enc_blk(key, IV @ ctr)`.
  .. `ctr <- ctr + 1 % 2^c^`.

If `ACELEN` is a multiple of `b`, the same behavior applies as in State
_Encrypt_, namely the above operations are executed `ACELEN/b` times, decrypting
each `b`-bit block of `INPUT` into the corresponding `b`-bit block of `OUTPUT`.
--
+

** To transition to State _Dec_Tag_Finalize_, a Form C ``ace.setst`` instruction is expected to provide the following value, which must be set by the software:
+
--
[none]
* `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2)`

The authentication tag is computed as follows:

. `absorb(INPUT)`.
  . `tag <- tag xor enc_blk(key, ctr[b-1,c] @ zeros(c))`.
--
+
If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.

** To transition to State _Hash_Verify_, a Form C ``ace.setst`` instruction
   must be used to provide the value against which the internally computed tag
   must be compared: If the values match, state
   transitions to _Success_, else it transitions to _Failure_.

** Upon completion of `ace.import`, the ACE unit recomputes `hash_key`, i.e.:
  . `hash_key <- enc_blk(key, zeros(b))`.

//

<<ACE-pseudocode-GCM-encryption>> and <<ACE-pseudocode-GCM-decryption>> provide
pseudocode for GCM encryption and decryption.

//

[NOTE]
====
GCM security is not compromised if `H` is revealed. Consequently, an
implementation of GCM based on an ECB mode CC would be acceptable, for instance
as in <<ACE-pseudocode-GCM-encryption-alternate>>. However, this significantly
increases code size and requires support for carry-less multiplication, which
may not be available in all hardware.

Furthermore, a GCM implementation is necessary to support the use case where
the IV is also set in advance and not modifiable by the user. it must be
possible to configure a GCM CC with both secret key and the IV. This is
described in the next section.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-GCM-with-IV-mode]]
===== GCM with Set IV

The mode of operation ŌĆ£GCM with a Set IVŌĆØ is a variant of the GCM mode where
the initialization vector (IV) is predefined and not generated randomly. This
variant _cannot_ be emulated with an ECB CC because it would reveal the
internal data.

A key difference between GCM and GCM with Set IV is in the format of the
Provisioning Input:

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|   i   | `k` or 64     | `key` or System Key Identifier
|  ii   | ``b``-``c``   | `IV`
|  iii  | (Padding)     | Zero padding
|===
--
+

* *Internal State* (Content): {empty}
+
--
Same as for GCM.
--
+

* *Serialized Content*: {empty}
+
--
Same as for GCM.
--
+

* *States and Allowed Transitions:* {empty}
+
--
Same as for GCM.
--
+

* *State Machine Behavior:* {empty}
+
--
The differences with respect to GCM are:

 ** To transition to State _Hash_Absorb_: The ``ace.setst`` instruction shall
    be of Form A, i.e., _without any additional inputs_, since the IV is
    already included in the PI.
 ** When transitioning back to State _hash_Initial_: The CR's `IV` field is
    _not_ reset to zero.
--
+

NOTE: For all the following IV- or nonce-based modes, versions with a set IV or
nonce (such as for GCM-SIV) can also be similarly defined. For instance, for
GCM-SIV (<<ACE-GCM-SIV-mode>>), `nonce` would be included in the PI exactly as
`IV` is included in the PI for GCM, and the transition to _Hash_Absorb_ would
also use a Form A ``ace.setst``. All other semantics would be unchanged.

// ////////////////////////////////////////////////////////////////////

[[ACE-GCM-SIV-mode]]
===== GCM-SIV Mode

The GCM-SIV mode is described in cite:[DBLP-journals-iacr-GueronLL17] and
cite:[RFC8452]. While GCM-SIV's decryption state machine is similar to the
GCM's, the encryption state machine is different:

* During encryption, the _Hash_Absorb_ state absorbs the entire associated data
  and plaintext. The _Enc_Tag_Finalize_ state then absorbs the lengths and
  produces the SIV/tag. Finally, the _Encrypt_ state performs a second pass to
  encrypt the plaintext using the SIV/tag as the initialization vector.
* During decryption, the _Hash_Absorb_ state absorbs only the associated data.
  The _Decrypt_ state decrypts the ciphertext and simultaneously absorbs the
  plaintext into the hash. Finally, the _Dec_Tag_Finalize_ state absorbs the
  lengths, produces the SIV/tag, and internally compares it to the provided
  SIV/tag.

//

Parameters:::

* `k` = key size (64|`k`).
* `b` = block size, (64|`b`). For this algorithm, `ACELEN` must be an integer
  multiple of `b`.
* It must be `k = b` or `k = 2b`.
* The authentication tag is `b` bits long.

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64       | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`, `enc_key`: `k` bits.
 ** `auth_key`: `b` bits.
 ** `nonce`: `3b/4` bits.
 ** `ctr`: `b/4` bits.
 ** `SIV`: `b` bits.
 ** `tmp`: `b` bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | `k` or 64       | `key` or System Key Identifier
|   ii  | 3``b``/4        | `nonce`
|  iii  | `b`/4           | `ctr`
|    v  | `b`             | `SIV`
|   iv  | `b`             | `tmp`
|===
--
+

NOTE: The internal state fields `enc_key` and `auth_key` are not serialized,
and must be recomputed upon each `ace.import`.

//

Algorithm-Specific Functions:::

* `enc_blk(key, p) -> c` encrypts block `p` using the key, and returns the
  result `c`.
* `absorb(data)` absorbs data into the hash function by performing a step of (a variant of) POLYVAL:
  . `tmp <- tmp xor INPUT`.
  . `tmp <- Montmul(tmp, hash_key)`.

State Machine:::
* *States:*
 ** _Initial_: The CC is ready.
 ** _Set_Aux_Value_: Set the value of `nonce`.
 ** _Hash_Absorb_: Set the SIV and process AD and, if encrypting, also the plaintext into the partial tag (this is accumulated in the state variable `tmp`).
 ** _Encrypt_: Encrypt the plaintext.
 ** _Enc_Tag_Finalize_: Finalize the SIV with the AD and PT lengths, prepare to return its value.
 ** _Decrypt_: Absorb the ciphertext into the partial tag and decrypt it.
 ** _Dec_Tag_Finalize_: Finalize the tag with the AD and CT lengths, then compare it against the `SIV`.
 ** _Success_: The algorithm has completed its operation correctly.
 ** _Failure_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Set_Aux_Value_ -> _Hash_Absorb_.
 ** For encryption: _Hash_Absorb_ -> _Enc_Tag_Finalize_ -> _Encrypt_.
 ** For decryption: _Hash_Absorb_ -> _Decrypt_ -> _Dec_Tag_Finalize_ -> _Success_ or _Failure_.
 ** Transition to _Encrypt_ possible only if encryption is allowed.
 ** Transition to _Decrypt_ possible only if decryption is allowed.

* *Behavior:*
 ** In State _Initial_ :
  *** Upon entering the state, the following initialization operations are performed:
   . (`enc_key`, `auth_key`) `<-` `RFC8452_RFC8452_KeyDeriv(key)`,
   . `nonce`, `ctr`, `tmp`, `SIV <- 0`.
 *** No ``ace.exec`` operation is allowed.

 *** Upon issuing a Form C ```ace.setst Kn|K(Xn), #ace_state_set_aux_value, INPUT```,
  the value of `nonce` is set to `INPUT`.
  (If the instruction is repeated, there is no harm, since it just overwrites
  the `nonce` before any other operation is performed.)

  ** In State _Set_Aux_Value_:
   *** Upon issuing a Form C ```ace.setst Kn|K(Xn), #ace_state_hash_absorb, INPUT```:
+
--
**** The value of `SIV` is set to `INPUT`.

NOTE: This version of the instruction is meant to be used during decryption. It
is harmless to invoke it during encryption, however, as the `SIV` field will be
overwritten later with the correct synthetic value.
--
+

*** Upon issuing a Form A ```ace.setst Kn|K(Xn), #ace_state_hash_absorb```:
+
--
**** The `SIV` is not modified (it is assumed to be already zero).

NOTE: This version of the instruction is meant to be used during encryption. If
used during decryption, by leaving the `SIV` to zero it will most likely lead
to an authentication error.
--
+

** {empty}
+
--
In State _Hash_Absorb_, Form B ``ace.exec`` instructions are expected.

Such an instruction absorbs its `INPUT` in the internal state variable `tmp`, i.e., it performs `absorb(INPUT)`.

If `ACELEN` is a multiple of `b`, `absorb()` is executed on each of the `ACELEN/b` blocks in `INPUT`.
--
+

** In State _Enc_Tag_Finalize_, an ``ace.exec`` instruction of Form A is expected. Its input value
+
--
[none]
  *** `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2)`,
--
+
is set by the user.
Then, ŌĆ£```ace.exec```ŌĆØ finalizes the SIV computation by performing:
+
--
  . `absorb(INPUT)`.
  . `tmp <- enc_blk(enc_key, 0 @ (tmp xor N)[b-2:0])`
  . `SIV <- 0 @ tmp[b-2:0]` and `OUTPUT <- SIV`,
--
+

If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.

 ** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A, namely
    ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```,ŌĆØ to encrypt `INPUT` into `OUTPUT`
    as follows:
+
--
. If `ctr == 0`, then the CR is *invalidated*.
   . ``OUTPUT <- INPUT `` +
      ``{fournbsp}{fournbsp}xor enc_blk(enc_key, 1 @ SIV[b-2:b/4] @ (SIV[b/4-1:0] + ctr % 2^b/4^)),``
   . `ctr <- ctr + 1`.
--
+
If `ACELEN` > `b`, the above operations are applied to each of the `ACELEN/b`
blocks in `INPUT`.

 ** In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.
 "```ace.exec OUTPUT, Kn|K(Xn), INPUT```" decrypts `INPUT` into `OUTPUT` and then absorbs the plaintext `OUTPUT` into the `tmp`:
+
--
     . If `ctr == 0`, then the CR is *invalidated*.
     . ``OUTPUT <- INPUT `` +
          ``{fournbsp}{fournbsp}xor enc_blk(enc_key, 1 @ SIV[b-2:b/4] @ (SIV[b/4-1:0] + ctr % 2^b/4^))``,
     . `absorb(OUTPUT)`.
     . `ctr <- ctr + 1`.
--
+
If `ACELEN` > `b`, the above operations are applied to each of the `ACELEN/b`
blocks in `INPUT`.

 ** In State _Dec_Tag_Finalize_,
   a single ``ace.exec`` instruction of Form B is expected,
   namely ŌĆ£```ace.exec Kn|K(Xn), INPUT```,ŌĆØ where it is the responsibility of the user to set
+
--
[none]
  ***  `INPUT <- bin(bit_length(AD), b/2) @ bin(bit_length(plaintext), b/2)`.
--
+
``ace.exec`` then performs the following operations:
+
--
  . `absorb(INPUT)` (which modifies `tmp`).
  . `tmp <- enc_blk(enc_key, 0 @ (tmp xor N)[b-2:0])`.
  . `tmp <- tmp[n-2:0]`,
   . If `tmp` and `SIV` match, then
   ..  `State <- ace_state_success`
   . else
   ..  `State <- ace_state_failure`
--
+
If `ACELEN` > `b`, only the `b` least significant bits of `INPUT` are considered.

 ** Upon completion of `ace.import`, the ACE unit recomputes `enc_key` and `auth_key`, i.e.:
  . (`enc_key`, `auth_key`) <- `RFC8452_RFC8452_KeyDeriv(key)`.

//

Encryption and decryption pseudocode is found in <<ACE-GCM-SIV-mode-examples>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-OCB-mode]]
===== OCB Mode

We only architect the OCB3 variant of OCB as specified in RFC{nbsp}7253
cite:[RFC7253] and cite:[DBLP-journals-joc-KrovetzR21]. While this algorithm is
asymptotically more efficient than GCM and GCM-SIV, it has a much heavier setup
and its exported state requires significantly more memory than the other modes.
On the other hand, since it uses only a single key and no derived keys, with
ciphers with an expensive key expansion like the AES it may use fewer internal
resources.

The state machine of this algorithm closely follows RFC{nbsp}7253 (except for
the numbering of the bit fields, which is big endian in the RFC). The algorithm
is identical to the RFC for 128-bit-wide block ciphers, with a straightforward
generalization to other widths according to the security proof of the original
algorithm and a lower bound on nonce length following
cite:[cryptoeprint-2023-326].

Parameters:::
+
--
* `b` = block size. `b` is a power of two, and {ge} 64. For OCB, `ACELEN` must
  be an integer multiple of `b`.
* `k` = key size, `b`|`k`.
--
+
Also, define `g` = `log_2(b)`.

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64       | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`: `k` bits.
 ** `N`: `u+1` bits (at most `u` bits are used).
 ** `L`, `offset`, `hash_A`, `hash_P` : `b` bits.
 ** `N_len`, `tag_len`, `last_blk_len`: `g` bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)          | Field
|    i  | `k` or 64              | `key` or System Key Identifier
|   ii  |  `b`                   | `N`
|  iii  |  `b`                   | `L` (only `u+1` bits used)
|   iv  |  `b`                   | `offset`
|    v  |  `b`                   | `hash_A`
|   vi  |  `b`                   | `hash_P`
|  vii  |   16                   | `tag_len`
| viii  |   16                   | `last_blk_len`
|   ix  |   16                   | `N_len`
|    x  |   16                   | Padding
|===
--
+

//

Algorithm-Specific Functions:::

* `enc_blk(K,p) -> c` encrypts block `p` using the key `K` and returns the result `c`.
* `dec_blk(K,c) -> p` decrypts block `c` using the key `K` and returns the result `p`.
* `double(S)`:
Let `C` be  `0x1B` for `b` = 64, `0x87` for `b` = 128, and `0x425` for `b` = 256, then:
+
[none]
** If S[`b`-1] == 0, then { `double(S) <- S << 1` } else { `double(S) <- (S << 1) xor C` } .

State Machine:::
* *States:*
 ** _Initial_: The CC is ready.
 ** _set_aux_value:_ Set the length and the value of the nonce.
 ** _Hash_Absorb_: Set the tag length, and process the AD.
 ** _Hash_Finalize_: Set the length of the final block of the AD and process
    it.
 ** _Encrypt_: Process the plaintext by absorbing it into the tag and
    encrypting it.
 ** _Enc_Last_Block_: Provide the last block of the plaintext, then process it.
 ** _Enc_Tag_Finalize_: Return the tag.
 ** _Decrypt_: Process the ciphertext by decrypting it and absorbing the
    plaintext into the tag.
 ** _Dec_Last_Block_: Provide the last block of the ciphertext, then process
    it.
 ** _Hash_Verify_: Compare a user-provided value with the internally computed
    tag.
  ** _Success_: The algorithm has completed its operation correctly.
  ** _Failure_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Set_Aux_Value_ -> _Hash_Absorb_ -> _Hash_Finalize_
 ** _Hash_Finalize_ -> _Encrypt_, if encryption is allowed.
 ** _Hash_Finalize_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_ -> _Enc_Last_Block_ -> _Enc_Tag_Finalize_ -> _Success_.
 ** _Decrypt_ -> _Dec_Last_Block_ -> _Hash_Verify_ -> _Success_ or _Failure__.

* *Behavior:*
** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `N <- 1 @ zeros(u)`.
   . `hash_A <- zeros(b)`
   . `hash_P <- zeros(b)`

** To move to _Set_Aux_Value_, a Form B `ace.setst` is expected, where the
   auxiliary argument `Xs` sets the nonce length `N_len`. `N_len` must be at
   least `g-1`. If not, `State <- ace_state_invalid`, that is, the CR is
   enters an Error State.

** In State _Set_Aux_Value_, ``ace.exec`` instructions are expected to be of Form B, namely
   ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ, whereby `N` is set to
   `INPUT`, namely `N <- zeros(u-N_len) @ INPUT[N_len-1:0]`
  *** If ŌĆ£```ace.exec Kn|K(Xn), INPUT```,ŌĆØ is repeated, it will rewrite `N`.
  *** If no such `ace.exec` is issued, `N` is not changed, which means that its
      most significant bit is 1. This condition results in an error when
      transitioning to State _Hash_Absorb_.

** To move to _Hash_Absorb_, a Form B `ace.setst` instruction is expected, where the
   auxiliary argument `Xs` sets the tag length `tag_len`.
  *** If this argument (interpreted as an unsigned value) is larger than `b` or
      is equal to `0` (the latter occurs also if `X0` is passed as the
      auxiliary argument), and the CR is invalidated.
  *** If `N[u] == 1`, this means that `N` was not set in State _Set_Aux_Value_.
      Nonce setting cannot be skipped, as this mode is not secure under nonce
      reuse, therefore in this case the CR is invalidated.
  *** Following operations are performed:
  . `tag_len <- Xs`.
  . `offset <- zeros(b)`
  . `L <- enc_blk(key, zeros(b))`
  . `L <- double(double(L))`

** In State _Hash_Absorb_, ``ace.exec`` instructions are expected to be of Form B, whereby
  ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ absorbs a data block in `tag`, i.e.:
+
--
    . `L <- double(L)`
    . `offset <- offset xor L`
    . `hash_A <- hash_A xor enc_blk(key, INPUT xor offset)`
--
+
If `ACELEN` > `b`, the above operation is executed `ACELEN/b` times.

** To move to _Hash_Finalize_, a Form B `ace.setst` operation is expected, to set the length of the final block of the AD in `last_blk_len`.

** In State _Hash_Finalize_, only a single `ace.exec` instruction of Form B is
   expected if `last_blk_len` != `0`. ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ which
   absorbs the last data block in `tag`, i.e.:
+
--
  * `tmp : bits(b)`

[]
  . `offset <- offset xor enc_blk(key, zeros(b))`
  . `tmp <- (zeros(b-last_blk_len-1) @ 1 @ INPUT[last_blk_len-1:0]) xor offset`
  . `hash_A <- hash_A xor enc_blk(K, tmp)`
--
+
If `last_blk_len` == 0, however, no `ace.exec` can be executed, and only an
`ace.setst` instruction is allowed to enter State _Encrypt_ or _Decrypt_.

** Upon entering states `_Encrypt_` or `_Decrypt_`, the ŌĆ£setupŌĆØ and ŌĆ£initŌĆØ
   stages of the OCB algorithm are performed:
+
--
 * `N_ext : bits(b)` (`N_ext` means ŌĆ£N, extendedŌĆØ)
 * `Stretch : bits(3b/2)`
 * `bot : bits(g-1)`
 * `Ktop : bits(b)`

[]
 . `offset <- zeros(b)`
 . `L <- enc_blk(key, zeros(b))`
 . `L <- double(double(L))`
 . `N_ext <- N[N_len-1:0] @ 1 @ zeros(b-g-1-N_len) @ bin(tag_len,g)`
 . `bottom <- int(N_ext[b-1:b-g+1])`  // Rogaway numbers the bits in the opposite order.
 . `Ktop <- enc_blk(key, zeros(g-1) @ N_ext[b-g:0])`
 . `Stretch <- (Ktop[b/2-1:0] xor Ktop[b/2+7:8]) @ Ktop`
 . `offset <- Stretch[b+bottom:bottom]`
--
+
** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A:
   ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```ŌĆØ absorbs the plaintext `INPUT` into
   the `tag` and encrypts `INPUT` into `OUTPUT`, namely:
+
--
 . `L <- double(L)`
 . `offset <- offset xor L`
 . `hash_P <- hash_P xor INPUT`
 . `OUTPUT <- offset xor enc_blk(key, INPUT xor offset)`
--
+
If `ACELEN > b`, the above operation sequence is executed `ACELEN/b` times,
encrypting each `b`-bit block of `INPUT` into the corresponding `b`-bit block
of `OUTPUT`.

** To move to _Enc_Last_Block_, a Form B `ace.setst` instruction is expected to be issued
   to set the bit length of the final block of the plaintext in `last_blk_len`.

** {empty}
+
--
In State _Enc_Last_Block_, if `last_blk_len` is nonzero a single ``ace.exec`` instruction of Form A
   ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT``` is expected.
In this case, following operations are performed:

 * `tmp : bits(last_blk_len)`
 * `tmp2 : bits(b)`
 * `aux : bits(b)`

[]
 . `aux <- enc_blk(key, zeros(b))`
 . `offset <- offset xor aux`
 . `tmp <- enc_blk(key, offset)[last_blk_len-1:0]`
 . `tmp <- INPUT[last_blk_len-1:0] xor tmp`
 . `OUTPUT <- zeros(b-last_blk_len) @ tmp`
 . `tmp2 <- (zeros(b-last_blk_len-1) @ 1 @ tmp) xor offset`
 . `aux <- double(aux)`
 . `hash_P <- enc_blk(key, hash_P xor tmp2 xor offset xor aux) xor hash_A`
--
+
On the other hand, if `last_blk_len` is zero, only an ``ace.exec`` instruction
of Form D, ŌĆ£```ace.exec Kn|K(Xn)```,ŌĆØ is expected, which performs:
+
--
* `aux : bits(b)`

[]
  . `aux <- enc_blk(key, zeros(b))`
  . `aux <- double(aux)`
  . `hash_P <- enc_blk(key, hash_P xor offset xor aux) xor hash_A`
--
+
In both cases the state then transitions to _Enc_Tag_Finalize_.

** In State _Enc_Tag_Finalize_, only a single ``ace.exec`` instruction of Form C,
   ŌĆ£```ace.exec OUTPUT,Kn|K(Xn)```,ŌĆØ is expected, which performs `OUTPUT <-
   zeros(b-tag_len) @ hash_P[tag_len-1:0]`.

** In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A.
   Such an ``ace.exec`` decrypts `INPUT` into `OUTPUT`, and absorbs the
   plaintext `OUTPUT` into the `tag`, namely:
+
--
  * `tmp : bits(b)`

[]
  . `L <- double(L)`
  . `offset <- offset xor L`
  . `tmp <- offset xor enc_blk(key, INPUT xor offset)`
  . `hash_P <- hash_P xor tmp`
  . `OUTPUT <- tmp`
--
+
If `ACELEN` > `b`, the same behavior applies as in State _Encrypt_.

** To move to State _Dec_Last_Block_, a Form B `ace.setst` operation must be
   used to also contextually set the bit length of the final block of the
   ciphertext in `last_blk_len`.

** In State _Dec_Last_Block_, only a single ``ace.exec`` instruction of Form A
   "```ace.exec OUTPUT, Kn|K(Xn), INPUT```" is expected if `last_blk_len` is
   nonzero. In this case, the same operations as in State _Enc_Last_Block_ are
   performed except for Line 6, which is instead
+
--
[start=6]
. `tmp2 <- (zeros(b-last_blk_len-1) @ 1 @ INPUT[last_blk_len-1:0]) xor offset`
--
+
and the state is changed to _Hash_Verify_.
+
If `last_blk_len` is zero, only a single ``ace.exec`` instruction of Form D,
ŌĆ£```ace.exec Kn|K(Xn)```,ŌĆØ is expected, which performs the same operations as in
State _Enc_Last_Block_, except for the final state transition, which also in
this case is to _Hash_Verify_.

** To complete the algorithm in the decryption branch, a Form C ``ace.setst``
   operation is expected, to (confirm the) transition to State _Hash_Verify_
   and compare the `tag_len` least significant bits of `INPUT` with the
   `tag_len` least significant bits of `hash_P`:
+
--
  . If the values match, then the State transitions to _Success_, else it transitions to _Failure_.
--
+

//

Pseudocode for OCB encryption is given in <<ACE-OCB-mode-examples>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-CMAC-mode]]
===== CMAC Functions

{empty}
(((ACE, algorithm, CMAC)))
CMAC is an algorithm for message authentication codes constructed from a block
cipher. It was designed by Tetsu Iwata and Kaoru Kurosawa and became a NIST
Recommendation in May 2005 cite:[nist-SP-800-38B].

Parameters:::

* `b` = block size (8|`b`).  For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = key size (8|`k`).

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | `k` or 64     | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`: `k` bits.
 ** `hash`: `b` bits.
 ** `last_block_len`: 64 bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | `k` or 64     | `key` or System Key Identifier
|   ii  | `b`           | `hash`
|  iii  | 64            | `last_block_len`
|===
--
+

//

Algorithm-Specific Functions:::

* `enc_blk(key, p) -> c` encrypts block `p` using the key `key`, and returns the result `c`.
* `gen_subkeys(K) -> (K1,K2)` generates subkeys `K1` and `K2` from the master key `K` as follows: +
Let `C` be `0x1B` for `b` = 64, `0x87` for `b` = 128, and `0x425` for `b` = 256, then

 . `L <- enc_blk(K, zeros(b))`
 . if (`msb(L){nbsp}{nbsp}== 0`) then
   { `K1 <- L{nbsp}{nbsp}<< 1` }
   else
   { `K1 <- (L{nbsp}{nbsp}<< 1) xor C` }.
 . if (`msb(K1){nbsp}== 0`) then
   { `K2 <- K1{nbsp}<< 1` }
   else
   { `K2 <- (K1{nbsp}<< 1) xor C` }.
 . return ```(K1, K2)```.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Absorb data into the CMAC function.
 ** _Hash_Last_Block_: Set the length of the last block to absorb, then absorb it.
 ** _Hash_Output_: Output the CMAC.
 ** _Success_: The CC has completed the CMAC operation.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Last_Block_ -> _Hash_Output_ -> _Success_.
 ** From any valid state to State _Initial_.
* *Behavior:*
 ** In State _Initial_:
  *** `last_block_len <- zeros(64)`
  *** `hash <- zeros(b)`
  *** No {nbsp}```ace.exec```{nbsp} operation is allowed.

 ** In State _Hash_Absorb_, ``ace.exec`` instructions are expected to be of Form B. +
 ŌĆ£```ace.exec Kn|K(Xn), INPUT```,ŌĆØ absorbs the data block `INPUT` into the hash as follows:
+
--
   . `hash <- enc_blk(key, hash xor INPUT)`.
--
+
If `ACELEN` > `b`, then the above operations are applied to each `b`-bit block of `INPUT`.

 ** Upon issuing a Form B ŌĆ£```ace.setst Kn|K(Xn), #ace_state_hash_last_block, Xs```ŌĆØ where `Xs` contains the bit length of the last block, the following happens:
   . if `last_block_len` != 0, then the CR is *invalidated*. (The previous block is not complete.)
   . if `Xs > b` then the CR is *invalidated*.
   . `last_block_len <- Xs`.

 ** In State _Hash_Last_Block_, only a single ``ace.exec`` instruction of Form B may be issued, i.e., ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ, to absorb the data block `INPUT`. If `ACELEN` > `b`, only the least significant `b` bits of `INPUT` are considered.
+
--
  . `(K1, K2) <- gen_subkeys(key)`.
  . if `last_block_len` == `b`, then {
    .. `tmp <- hash xor INPUT xor K1`
  . } else {
    .. `tmp <- INPUT`
    .. Remove the `b` - `last_block_len` most significant bits of `tmp` and pad the resulting value with a `1` and sufficiently many `0` bits to make it `b` bits long.
    .. `tmp <- hash xor tmp xor K2` }
  . `hash <- enc_blk(key, tmp)`
  . The state is changed to _Hash_Output_.
--
+

** In State _Hash_Output_, we can issue one ``ace.exec`` instruction of Form C, i.e., ŌĆ£```ace.exec OUTPUT, Kn|K(Xn)```ŌĆØ, to output the hash into `OUTPUT`.
   If `ACELEN` > `b`, only the bits of `OUTPUT` beyond the `b`-th are cleared.
   Upon issuing that instruction, the CC transitions to State _Success_ with no error.

//

Pseudocode is given in <<ACE-CMAC-mode-example>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-hash-functions]]
===== Hash and MAC Functions, and XOFs

{empty}
(((ACE, algorithm, general hashing)))
(((ACE, algorithm, MAC functions)))
(((ACE, algorithm, XOF)))
This section defines an interface for hash and MAC functions. A completely
general interface cannot be defined because of the variety of constructions.
However, the one given here is sufficiently general to allow describing most
common functions, such as, for instance, the SHA2 cite:[nist-fips-180-4], SHA3
and SHAKE cite:[nist-fips-202], as well as HMAC cite:[nist-fips-198-1].

Parameters:::

* `b` = block size (8|`b`). This is the size of an absorbed block and may be
  different from the size of the internal state that is kept by the function.
  For a sponge function, this value is the _rate_.
* `t` = tag len (8|`t`). This is the size of the digest, or of the block that
  is output each time in a XOF. The present description assumes `t` {le} `b`.
* `n` = size of the internal state that is kept by the function (8|`n`).  For a
  sponge function, `n-b` is the _capacity_ of the function. Either the block
  size is an integer multiple of the vector length or the vector length is an
  integer multiple of the block size.
* `k` = key size (8|`k`). Present only if keyed, i.e., a MAC.

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)             | Field
|   i  | If keyed: `k`, else 64  | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`: `k` bits. Present only if keyed, i.e., a MAC.
 ** `state`: `n` bits.
 ** `last_block_len`: int. Present only if this Hash/MAC provides special
    treatment for a last block that goes beyond padding and appending the
    length. The latter must be handled by user software instead.
 ** `input_base`: int. Offset within input/output to read from/write to.
 ** `block_base`: int. Length of absorbed data so far for the current block.
    Only if needed by the algorithm.
 ** `cumul_len`: int. Cumulative length of data absorbed so far (if the
    algorithm must process and incorporate it in the hash on its own).
 ** `block`: `b` bits.  Included only if a partial block must be maintainedŌĆöfor
    instance when the inputs are not directly absorbed into `state`.


* *Serialized Content*:
+
--
[cols="^6%,<21%,<18%,<55%",options="header"]
|===
|  Pos.| Size (Bits)            | Field                       | Notes
.2+| i | If keyed: `k` or 64      | `key` or SKID               | --
<|        If unkeyed: 0           | none                        | --
|   ii | `n`                      | `state`                     | --
|  iii | 16                       | `last_block_len`            | Present only if this Hash/MAC has special internal treatment for a fractional last block that goes beyond padding and appending the length, which are handled by user software.
|   iv | 16                       | `block_base`                | Amount of data stored so far into `block`.  Only if used by the algorithm, else zero padding.
|    v | 32                       | `cumul_len`                 | Cumulative length of all data absorbed so far. Only if the algorithm must process and incorporate it in the hash on its own, else zero padding.
|   vi | 64{interpunct}{lceil}``block_base``/64{rceil} | `block` | Only if `block_base` is defined and != 0 and the block must be stored separately from the `state`.
|  vii | 0 or 64                  | Padding                     | To reach a multiple of 128 bits.
|===
--
+

//

NOTE: Regarding the `last_block_len`/`block_base`/`cumul_len` group: if any of
these fields is not used, it is replaced by a corresponding padding block. If
all three are not used by the hashing algorithm, then the 64-bit block is
omitted, and `block` is clearly also

Algorithm-Specific Functions:::

* `absorb()`: Process `block` into the hash or MAC.
* `absorb_last_block()`: Process `block` into the hash or MAC, using a function
  for the last block.
* `finalize()`: Process the `state` into the digest value. We assume this
  either re-uses `block` (the entire digest, or a unit of XOF output should not
  be bigger than that) or the digest will be part of `state`.
* `update()`: Updates the `state` during the digest output stage.

State Machine:::

* *States:* _Initial_, _Hash_Absorb_, _Hash_Last_Block_, _Hash_Output_ and _Success_.

 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Absorb data into the hash function.
 ** _Hash_Last_Block_: Set the length of the last block to absorb, then absorb it.
 ** _Hash_Output_: Output the hash.
 ** _Success_: The CC has completed the operation (XOFs do not have this state).

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Last_Block_ -> _Hash_Output_ -> _Success_.
 ** From any valid state to State _Initial_.

* *Behavior:*
 ** In State _Initial_:
  *** `last_block_len`, `block_base` and `block` are set to zero.
  *** `state`: the initial value is set as specified by the algorithm.
  *** Any `ace.exec` will result in the CR being *invalidated*.

 ** In State _Hash_Absorb_, only ``ace.exec`` instructions of Form B may be issued, i.e., +
 ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ, to absorb the data block `INPUT` into the hash as follows.
+
--
  . `input_base <- 0` // or `acestart` upon resumption
  . while `(input_base < ACELEN)` do { // as long as we have input to process
  .. `amount <- min(ACELEN-input_base, b-block_base)`
  .. ``block[block_base + amount - 1 : block_base] <-`` +
      ``{nbsp}{nbsp}{nbsp}{nbsp} <- INPUT[input_base + amount - 1 : input_base]`` +
        ``{nbsp}{nbsp}``(If there is no `block` field, could also be something like +
        ``{fournbsp}state[block_base + amount - 1 : block_base] <- `` +
        ``{fournbsp}{fournbsp}{nbsp}<- state[block_base + amount - 1 : block_base] + `` +
        ``{fournbsp}{fournbsp}{nbsp}+ INPUT[input_base + amount - 1 : input_base]`` , +
        ``{nbsp}{nbsp}{nbsp}``it could directly replace part of `state`, or some other function.)
  .. `input_base <- input_base + amount`
  .. `block_base <- block_base + amount`
  .. if (`block_base` == `b`) then { // it's time to absorb the block
  ... `absorb()`
  ... `block_base <- 0`
  ... *Here* the instruction may be interrupted, with `acestart <- input_base`.

[none]
  . }``{nbsp}{nbsp}`` }
--
+

//
 ** Upon issuing a Form B ŌĆ£`ace.setst Kn|K(Xn), #ace_state_hash_last_block,
    Xs`ŌĆØ where `Xs` contains the length of the last block, the following
    happens:
+
--
 . if `block_base` != 0, then the CR is *invalidated*. (The previous block is not complete.)
 . if `Xs > b`, then the CR is *invalidated*.
 . if `Xs == 0`, then the CR is *invalidated*.
 . `last_block_len <- Xs`.
--
+
Then, state transitions to _Hash_Last_Block_ as expected.

 ** State _Hash_Last_Block_ is very similar to _Hash_Absorb_, the differences
    being:
  *** `last_block_len` is used in place of `b` throughout.
  *** `absorb_last_block()` is called instead of `absorb()` in Step 3.d.i.
  *** The instruction is terminated after `absorb_last_block()`ŌĆöonly one block
      is absorbedŌĆöand the state transitions to _Hash_Output_.

 ** In State _Hash_Output_, the cases where the current function is a hash
    function or a XOF behave differently.
  *** Upon entering the state, the following operations are first performed:
  . `block[t - 1 : 0] <- finalize()`
  . `block_base <- 0`
 *** For each Form C `ace.exec` instruction ŌĆ£`ace.exec OUTPUT, Kn|K(Xn)`ŌĆØ, the
     following operations are performed:
+
--
    * `amount : int`, `{nbsp}` amount of data to copy from `block` to `OUTPUT`
    * `#define output_base input_base`

[]
   . `output_base <- 0` // or `acestart` upon resumption
    . while (`output_base` < `ACELEN`) do { // as long as there is room in the OUTPUT
     .. `amount <- min(ACELEN - output_base, t - block_base)`
     .. ``OUTPUT[output_base + amount - 1 : output_base] <- `` +
           ``{fournbsp}{fournbsp}<- block[block_base + amount - 1 : block_base + amount]``
     .. `output_base <- output_base + amount`
     .. `block_base <- block_base + amount`
     .. if (`block_base` == `t`) then {
      ... if we are in a Hash function, transition to State _Success_, and return.
      ... `update()`
      ... `block_base <- 0`
      ... *Here* the instruction can be interrupted, with `acestart <- output_base`.

[none]
      . }``{nbsp}{nbsp}`` }
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-HMAC]]
===== HMAC

Hash function acceleration is sufficient to compute HMACs, and no dedicated
algorithms are needed for either performance or security reasons.

// ////////////////////////////////////////////////////////////////////

[[ACE-SHA-3]]
===== SHA-3 Family Specific Rules

{empty}
(((ACE, algorithm, SHA-3)))
We describe here the algorithms for the primitives in the SHA-3 family, which
currently includes SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128 and
SHAKE256. These primitives are designed around a special parameter choice of
KECCAK cite:[DBLP-conf-eurocrypt-BertoniDPA13] standardized by NIST
cite:[nist-fips-202]. These are instantiations of the algorithm specified in
<<ACE-hash-functions>>, and we need to describe only the differences with
respect to the behavior described there.

//

Parameters:::

* `b` = rate (8|`b`). It is `b` = 1600 - `c`, where `c` = 448, 512, 768, or 1024 is the capacity.
* `n` = 1600
* `t` = `c/2`

Data Structures:::

* *Provisioning Input* (Content): Empty.

* *Internal State* (Content):
 ** `state`: `n` bits.
 ** `last_block_len`: int.
 ** `input_base`: int.
 ** `block_base`: int.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 1600            | `state`
|  ii  | 16              | `last_block_len`
| iii  | 16              | `block_base`
|  iv  | 96              | Padding
|===
--
+

Algorithm-Specific Functions:::

 * `P()`: computes `KECCAK-p[1600, 24]` on `state`.
 * `absorb()`: in this case there is no explicit operation to copy data into
   `state`, as the inputs will be directly XORed into it, however `absorb`
   applies `P()` to the state.
 * `absorb_last_block()`: this is a NOP.
 * `finalize()`: this is a NOP.
 * `update()`: updates the `state` during the digest output stage.  It applies
   `P()` to the state.

State Machine:::
* *States:* _Initial_, _Hash_Absorb_, _Hash_Last_Block_, _Hash_Finalize_,
  _Hash_Output_ and _Success_.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Last_Block_ -> _Hash_Finalize_ ->
    _Hash_Output_ -> _Success_.
 ** From any valid state to State _Initial_.

* *Behavior:*
 ** In State _Initial_, `state` is zeroed.
 ** In State _Hash_Absorb_, the input data is directly XORed to `state`.
 ** In State _Hash_Last_Block_, the input data is directly XORed to `state`.
 ** Upon transitioning to State _Hash_Output_:
  . The suffix and padding string `S` is generated.
  . If the bit length of `S` is `b-block_base`:
   .. `S` is directly XORed to rate part of the state, and
   .. `P()` is applied.
  . If the bit length of `S` is `2b-block_base`:
   .. The first `b-block_base` bits are XORed to the rate part of the state,
   .. `P()` is applied,
   .. the remaining `b` bits are XORed to the rate part of the state, and
   .. `P()` is applied again.

The rest of the algorithm follows <<ACE-hash-functions>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-AEAD128]]
===== Ascon-AEAD128

{empty}
(((ACE, algorithm, Ascon)))
Ascon is a public permutation cite:[DBLP-journals-joc-DobraunigEMS21]
standardized by the NIST cite:[nist-SP-800-232] together with various
cryptographic algorithms designed around it.

[WARNING]
====
In all ASCON algorithms, the ordering of the bits must be verified!
====

Ascon-AEAD128 is an AEAD algorithm. In Ascon-AEAD128, it is the responsibility
of the user to apply proper padding to the AD and plaintext. The inputs are
therefore assumed to be properly padded. Similarly, it is the responsibility of
the user to remove the padding from the decryption of the ciphertext to recover
the original plaintext.

Parameters:::

* `b` = 128. For this algorithm, `ACELEN` must be an integer multiple of `b`.
* `k` = 128.

Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128 or 64     | `key` or System Key Identifier
|===
--
+

* *Internal State* (Content):
 ** `key`: 128 bits, or 64 bits if it is a System Key Identifier.
 ** `state[0 .. 4]`: five 64-bit words, i.e., 320 bits.
 ** `tag_len`: 8 bits as int.
 ** `last_block_len`: 9 bits as int.
 ** `AD_empty`: Boolean;

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|    i | 128 or 64         | `key` or System Key Identifier
|   ii | 64              | `state`[0]
|  iii | 64              | `state`[1]
|   iv | 64              | `state`[2]
|    v | 64              | `state`[3]
|   vi | 64              | `state`[4]
|  vii | 16              | `last_block_len`
| viii | 16              | `tag_len`
|   ix | 32 or 96        | Padding
|===
--
+

Algorithm-Specific Functions:::
* `ASCON(p)` applies `p` rounds of ASCON to the `state`.

State Machine:::

* *States:*
 ** _Initial_: The CC is ready.
 ** _Hash_Absorb_: Set the nonce, and process the AD.

 ** _Encrypt_: Encrypt the plaintext.
 ** _Enc_Last_Block_: Encrypt the last block of the plaintext.
 ** _Hash_Output_: Return the tag.

 ** _Decrypt_: Decrypt the ciphertext.
 ** _Dec_Last_Block_: Decrypt the last block of the ciphertext.
 ** _Hash_Verify_: Compare a user-provided value with the internally computed tag.

 ** _Success_: The algorithm has completed its operation without errors.
 ** _Success_: The algorithm has completed its operation with an authentication failure.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_.
 **  _Hash_Absorb_ -> _Encrypt_, if encryption is allowed.
 **  _Hash_Absorb_ -> _Decrypt_, if decryption is allowed.
 ** _Encrypt_ -> _Enc_Last_Block_ -> _Hash_Output_ -> _Success_.
 ** _Decrypt_ -> _Dec_Last_Block_ -> _Hash_Verify_ -> _Success_ or _Success_.

* *Behavior:*
** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `state[0] <- 0x00001000808c0001`
   . `state[1] <- key[63:0]`
   . `state[2] <- key[127:64]`
   . `state[3] <- zeros(64)`
   . `state[4] <- zeros(64)`
   . `tag_len <- 128`
   . `AD_empty <- true`

** To transition to State _Hash_Absorb_, a Form C ``ace.setst`` is expected,
   whose `INPUT` sets the nonce of the algorithm as follows:
+
--
  . `state[3] <- INPUT[63:0]`
    . `state[4] <- INPUT[127:64]`
    . `ASCON(12)`
    . `state[3] <- state[3] xor key[63:0]`
    . `state[4] <- state[4] xor key[127:64]`
--
+
If `ACELEN` > 128, only the 128 least significant bits of `INPUT` are considered.

** In State _Hash_Absorb_, only  ``ace.exec`` instructions of Form B are expected.
 ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ absorbs a data block into the state, i.e.:
+
--
 . `AD_empty <- false`
 . `ASCON(8)`
 . `state[0] <- state[0] xor INPUT[63:0]`
 . `state[1] <- state[1] xor INPUT[127:64]`
--
+
If `ACELEN` > 128, this sequence of four operations is executed `ACELEN/128`
times, once for each 128-bit block of `INPUT`.
** Upon entering State _Encrypt_ or _Decrypt_, the following domain separation
   operation is performed:
 . `lsb(state[4]) <- lsb(state[4]) xor 1`

** In State _Encrypt_, ``ace.exec`` instructions are expected to be of Form A, whereby
   ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```ŌĆØ encrypts `INPUT` into `OUTPUT`, namely:
+
--
 . `state[0] <- state[0] xor INPUT[63:0]`
 . `state[1] <- state[1] xor INPUT[127:64]`
 . `OUTPUT <- state[1] @ state[0]`
 . `ASCON(8)`
--
+
If `ACELEN` is a multiple of 128, these operations are executed `ACELEN/128`
times, encrypting each 128-bit block of `INPUT` into the corresponding 128-bit
block of `OUTPUT`.

** In State _Enc_Last_Block_, only one ``ace.exec`` instruction of Form A is expected to be issued, to
   encrypt the last block.
ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```ŌĆØ  performs
+
--
 . `state[0] <- state[0] xor INPUT[63:0]`
 . `state[1] <- state[1] xor INPUT[127:64]`
 . `OUTPUT <- state[1] @ state[0]` // only the 128 lsbs of `OUTPUT` are written to.
 .  The state machine then transitions to State _Hash_Output_.
--
+
In this state only one 128-bit block is processed. +
The differences between the operation of `ace.exec` in this state and in State
_Encrypt_ are the absence of the final `ASCON(8)` and the automatic transition
to State _Hash_Output_.

** In State _Hash_Output_, only one ``ace.exec`` instruction of Form C is expected to be issued, to compute the tag.
ŌĆ£```ace.exec OUTPUT, Kn|K(Xn)```ŌĆØ  performs
+
--
 . `state[2] <- state[2] xor key[63:0]`
 . `state[3] <- state[3] xor key[127:64]`
 . `ASCON(12)`
 . `state[3] <- state[3] xor key[63:0]`
 . `state[4] <- state[4] xor key[127:64]`
 . `OUTPUT <- state[4] @ state[3]` // only the 128 lsbs of `OUTPUT` are written to.
 . The state machine then transitions to State _Success_.
--
+
In this state only one 128-bit block is processed.

** In State _Decrypt_, ``ace.exec`` instructions are expected to be of Form A, i.e.,
 `ace.exec OUTPUT,Kn|K(Xn),INPUT`. This operation performs:
+
--
* `tmp : bits(128)`

[]
. `tmp <- (state[0] xor INPUT[63:0]) @ (state[1] xor INPUT[127:64])`
. `state[0] <- INPUT[63:0]`
. `state[1] <- INPUT[127:64]`
. `ASCON(8)`
. `OUTPUT <- tmp`
--
+
If `ACELEN` is a multiple of 128, these operations are executed `ACELEN/128`
times, decrypting each 128-bit block of `INPUT` into the corresponding 128-bit
block of `OUTPUT`.

** In State _Dec_Last_Block_, only a Form A ``ace.exec`` instruction is expected.
ŌĆ£```ace.exec OUTPUT, Kn|K(Xn), INPUT```ŌĆØ performs:
+
--
* `tmp : bits(128)`

[]
. `tmp <- (state[1] xor INPUT[127:64]) @ (state[0] xor INPUT[63:0])`
. `state[0] <- INPUT[63:0]`
. `state[1] <- INPUT[127:64]`
. The state machine transitions to State _Hash_Verify_
. `OUTPUT <- tmp`
--
+

** In State _Dec_Tag_Finalize_, a Form B `ace.setst Kn|K(Xn),
   #ace_state_dec_tag_finalize, Xs` instruction may be executed, setting the
   tag len `tag_len` to the value of `Xs`, provided it is not smaller than 32
   and not larger than 128. If the value is out of bounds, the CR is *invalidated*.

** In State _Hash_Verify_, only one ``ace.exec`` instruction of Form D is
   expected to be issued, to verify the tag.
ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ performs
+
--
. `state[2] <- state[2] xor key[63:0]`
. `state[3] <- state[3] xor key[127:64]`
. `ASCON(12)`
. `state[3] <- state[3] xor key[63:0]`
. `state[4] <- state[4] xor key[127:64]`
. `INPUT[tag_len-1:0]` is compared to `(state[4] @ state[3])[tag_len-1:0]`.
. If the values match, then the State transitions to _Success_,
  else it transitions to _Failure_.
--
+

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-AEAD128-wsn]]
===== Ascon-AEAD128 with set Nonce

Similarly to GCM with Set IV, Ascon-AEAD128 can also be made into a version
with a set nonce. In this case the State _Set_Aux_Value_ is skipped, and the PI
has the following form.

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128 or 64     | `key` or System Key Identifier
|  ii  | 128           | `nonce`
|===
--
+

In State _Initial_, words 3 and 4 of `state` are initialized thus:

. `state[3] <- nonce[63:0]`
. `state[4] <- nonce[127:64]`

Once in State _Success_, the CC cannot be brought back to State _Initial_.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-AEAD128-N-masking]]
===== Ascon-AEAD128 with Nonce Masking

The NIST specification also describes a version of Ascon-AEAD128 with _Nonce
Masking_. This variant is described as follows:

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)   | Field
|   i  | 128 or 64         | `K1` or System Key Identifier
|  ii  | 128 or 0         | `K2` or System Key Identifier in `K1`
|===
--
+

* *Internal State* (Content):
 . `K1`: 128 bits, or 64 bits if it is a System Key Identifier.
 . `K2`: 128 bits, omitted if a System Key is used.
 ** `state[0 .. 4]`: five 64-bit words, i.e., 320 bits.
 ** `tag_len`: 8 bits.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | 128 or 64     | `K1` or System Key Identifier
|   ii  | 128 or 0      | `K2` or System Key Identifier in `K1`
|  iii  | 64            | `state`[0]
|   iv  | 64            | `state`[1]
|    v  | 64            | `state`[2]
|   vi  | 64            | `state`[3]
|  vii  | 64            | `state`[4]
| viii  | 16            | `tag_len`
|   ix  | 48 or 112     | Padding
|===
--
+

The algorithm has the same states as Ascon-AEAD128 as described in
<<ACE-Ascon-AEAD128>>, with the key `key` equal to `K1` and the nonce `N`
replaced throughout by `N xor K2`.

For encryption and decryption with both nonce masking and a set nonce, the
algorithm described in <<ACE-Ascon-AEAD128-wsn>> is used, giving `K1` as the
key `key` and providing `N xor K2` as the nonce value.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-Hash256]]
===== Ascon-Hash256

In this mode it is the responsibility of the user to apply proper padding to
the inputs.

Parameters:::

* `b` = 64. For this algorithm, `ACELEN` must be an integer multiple of `b`.

Data Structures:::

* *Provisioning Input* (Content): Empty.

* *Internal State* (Content):
 ** `state[0 .. 4]`: five 64-bit words, i.e., 320 bits.
 ** `countdown` : integer going from 3 down to 0.

* *Serialized Content*:
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
|  Pos. | Size (Bits)   | Field
|    i  | 64              | `state`[0]
|   ii  | 64              | `state`[1]
|  iii  | 64              | `state`[2]
|   iv  | 64              | `state`[3]
|    v  | 64              | `state`[4]
|   vi  | 8               | `countdown` (from 3 down to 0)
|  vii  | 56              | Padding
|===
--
+

Algorithm-Specific Functions:::

* `ASCON(p)` applies `p` rounds of ASCON to the `state`.

State Machine:::

* *States:* _Initial_, _Hash_Absorb_, _Hash_Finalize_, and _Success_.

* *Allowed State Transitions:*
 ** _Initial_ -> _Hash_Absorb_ -> _Hash_Finalize_ -> _Success_.

* *Behavior:*
 ** In State _Initial_ :
  *** No ``ace.exec`` operation is allowed.
  *** The following initialization operations are performed:
   . `state[0] <- 0x0000080100cc0002`
   . `state[1] <- zeros(64)`
   . `state[2] <- zeros(64)`
   . `state[3] <- zeros(64)`
   . `state[4] <- zeros(64)`
   . `ASCON(12)`

  ** In State _Hash_Absorb_, only  ``ace.exec`` instructions of Form B are expected to be issued.
 ŌĆ£```ace.exec Kn|K(Xn), INPUT```ŌĆØ absorbs a data block into the state, i.e.:
+
--
 . `state[0] <- state[0] xor INPUT`
 . `ASCON(12)`
--
+
If `ACELEN` > `64`, these operations are executed `ACELEN/64` times, once for
each `64`-bit block of `INPUT`.

** Upon entering _Hash_Finalize_, `countdown` is set to 3.

** In State _Hash_Finalize_, at most four ``ace.exec`` instructions of Form C
   are expected to be issued. To compute the tag, "```ace.exec OUTPUT, Kn|K(Xn)```"  performs
+
--
. `ASCON(12)`
. `OUTPUT <- state[0]`
. if `countdown == 0` then transition to State _Success_.
. `countdown <- countdown - 1`
--
+
If `ACELEN` {ge} `128`, these operations are executed `ACELEN/64` times, writing
to `OUTPUT`[63:0] the first time, then `OUTPUT`[127:64], `OUTPUT`[191:128] and
`OUTPUT`[255:192]. If more than one ``ace.exec`` instructions are required,
writing restarts from `OUTPUT`[63:0]. If `countdown` reaches zero before the
entire output registers is written to, the state of the unwritten bits is
undefined: for instance this may occur if `ACELEN` = `192` or `ACELEN` > `256`.
This is usually not a problem, since the output vectors will be usually
configured for 64-bit, 128-bit, or 256-bit blocks, in which case four, two, or
one ``ace.exec`` instructions are required, respectively.

//

NOTE: There is no need to provide ŌĆ£keyedŌĆØ versions of this algorithm. This can
be done by a trusted entity by providing a CC after absorbing some secret
content in it first.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-XOF128]]
===== Ascon-XOF128

The algorithm is the same as Ascon-Hash256 (<<ACE-Ascon-Hash256>>) with the
following differences:

. The IV written to `state[0]` in State _Initial_ is `0x0000080100cc0002`.
. There is no `countdown` field (and therefore also no padding: the last 64
  bits of the serialized content of Ascon-Hash256 are not present).
. As much output as desired can be produced in State _Hash_Finalize_, and the
  algorithm never transitions to State _Success_.

// ////////////////////////////////////////////////////////////////////

[[ACE-Ascon-CXOF128]]
===== Ascon-CXOF128

Ascon-CXOF128 differs from Ascon-XOF128 in that the message is prepended with
the customization string. Except for the initialization of the state,
Ascon-CXOF128 is identical to Ascon-XOF128 with customization string and
message concatenated. The IV for Ascon-CXOF128 is `0x0000080000cc0004` (in
place of `0x0000080000cc0003`), and it is set by the algorithm. The states and
their semantics are otherwise identical to Ascon-XOF128, and the management of
the customization string is left to the user.

// ////////////////////////////////////////////////////////////////////

[[ACE-ECC]]
==== Elliptic Curve Asymmetric Algorithms

Elliptic Curve Asymmetric Algorithms provide following functionality:

. Scalar multiplication with known and unknown base point.
//This can be used to implement Diffie-Hellman key exchange.
. ECDSA/EdDSA signature generation and verification.

Support for Key Encapsulation Mechanisms (KEMs) and Public-Key Encryption (PKE) schemes
is very difficult to implement in full generality, since there
are several options, with multiple choice of KDF, hash function, and input
formats. In most cases, covering all options would be impractical. Only the
Chinese SM2 standards fully specify an integrated encryption scheme
cite:[GMT-0003-4-2012].
We therefore only provide scalar multiplication and the implementation
of specific KEM and PKE schemes is left to the user code.
This implies that the key values derived using these must be
present in the memory of the environment deriving them, albeit shortly if these
are then only used to provision a CR.

////
// [WARNING]
// This section needs finalization.
// ECC based KEMs are missing, or at least instructions on how to implement them with the basic functionality offered.
// For the moment, Integrated Public-Key Encryption (PKE) schemes are sketched: the semantics of `ace.derive` must be fleshed out better, and only when properly standardized.
////

When an elliptic curve is provisioned into a CR, the default base point (ŌĆ£generatorŌĆØ) according to the standards listed is configured as the `Generator` field in the CR.
This field may be overwritten, and when `ace.setst` is issued on the CR with next state _Initial_, the default base point may be restored.

All values (integers, coordinates, etc.) are in little-endian format.

Parameters:::

The parameters that are used in this section are:
+
--
 . The size `b` of the main fields in bits, used for coordinates, signature R and S fields, scalars;
 . The length `h` of the hash used in the signature scheme;
 . The length `j` of the random number used as nonce in signature generation;
 . The number `u` of coordinates used to represent a point (`u` can be 1 or 2); and
 . The number `v` of elements used to represent a signature (`v` can be 1 or 2).
--
+
The parameters for the defined curves are:
+
--
 * NIST cite:[NIST-SP-800-186,nist-fips-186-5]:
  ** secp256r1 (NIST P-256): `b` = `h` = `j` = 256, `u` = `v` = 2.
  ** secp384r1 (NIST P-384): `b` = `h` = `j` = 384, `u` = `v` = 2.
  ** secp521r1 (NIST P-521): `b` = 576 (55 msbs set to zero), `h` = `j` = 512, `u` = `v` = 2.
 * Edwards cite:[RFC7748]:
  ** ed25519:  `b` = `h` = `j` = 256; `u` = `v` = 1.
  ** ed448: `b` = `h` = `j` = 448; `u` = `v` = 1.
 * Brainpool cite:[RFC5639,RFC8734]:
  ** brainpoolP256r1: `b` = `h` = `j` = 256; `u` = `v` = 2.
  ** brainpoolP384r1: `b` = `h` = `j` = 384; `u` = `v` = 2.
  ** brainpoolP512r1: `b` = `h` = `j` = 512; `u` = `v` = 2.
 * SM2 cite:[GMT-0003-1-2012,GMT-0003-2-2012,GMT-0003-3-2012,GMT-0003-4-2012]: `b` = `h` = `j` = 256; `u` = `v` = 2.

Depending on the specifications of the algorithms, non-compressed or compressed points may be used.

All curves currently used are defined over fields of odd characteristic.
Since the all-ones strings do not represent any valid field value, these are used as coordinate(s) values of a point to represent the point at infinity.
--
+

//

Data Structures:::
* *Provisioning Input* (Content): Empty.
+
NOTE: _AlgorithmPolicy_ enables signature generation (_AlgorithmPolicy_[0]) and verification (_AlgorithmPolicy_[1]), where all four combinations are admissible.
+
* *Internal State* (Content):
 ** `HasSecondPt`: Bool.
 ** `HasScalar`: Bool.
 ** `HasSignature`: Bool.
 ** `HasHash`: Bool.
 ** `HasRndNum`: Bool.
 ** `OutputType`: Bool.
 ** `Progress`: integer.
 ** `block_base`: integer.
 ** `Generator` (X, {Y}): one or two `b`-bit strings representing the X {and Y} coordinate{s}.
 ** `SecondPt` (X, {Y}): one or two `b`-bit strings representing the X {and Y} coordinate{s}.
 ** `Scalar`: `b`-bit string.
 ** If signature generation or verification is allowed:
  *** `PublicKey` (X, {Y}): one or two `b`-bit strings representing the X {and Y} coordinate{s}}.
  *** `Signature` (R,S): two `b`-bit strings representing the `R` and `S` components.
  *** `Hash`: a `h`-bit string representing the hash.
 ** If signature generation or a public-key encryption mechanism are allowed:
  *** `RndNum`: a `h`-bit string representing the random number.
 ** Additional data, for instance precomputed multiples of the Generator.

* *Serialized Content*:
+
--
[cols="^7%,<33%,<30,<30",width="100%",options="header"]
|===
|   Pos.  | Size (Bits)  2+| Field
.3+| i .3+| 16 (Bits 6-15 are reserved) | Bit 0: `HasScalar`     | Bit 1: `HasSecondPt`
                                       <| Bit 2: `HasSignature` <| Bit 3: `HasHash`
                                       <| Bit 4: `HasRndNum`    <| Bit 5: `OutputType`
|    ii   | 16                        2+| `Progress`
|   iii   | 32                        2+| Padding
|    iv   | `ub`                      2+| `Generator`, X coordinate, followed by Y coordinate if `u=2`.
|     v   | `b`                       2+| `Scalar`: `b`-bit string. Can be the Private Key.
|===

`SCC_content_size()` returns only the length of the content from Position i to Position v.

The size of the following fields is included in the _VarDataLen_ field of the Metadata Header.

[cols="^7%,<33%,<60",width="100%",options="header"]
|===
|   Pos.  | Size (Bits)                             | Field
|    vi   | If `HasSecondPt`: `ub`, else: 0         | `SecondPt`, X coordinate, followed by Y coordinate if `u=2`. Can be the Public Key.
|   vii   | If `HasSignature`: `vb`, else: 0        | `Signature`, R value, followed by S coordinate if `v=2`.
|  viii   | If `HasHash`: `h`, else: 0              | `Hash`: a `h`-bit string representing the hash.
|    ix   | If `HasRndNum`: `j`, else: 0            | `RndNum`.
|     x   | (variable)                              | Optional and implementation-specific data from the *Internal State* (Content), starting with `aceunitid := zeros(32) @ aceimpid @ acearchid @ acevendorid` if not empty.
|===

The `HasRndNum` flag is set and the `RndNum` field is used only during signature generation.
`RndNum` is exported only if the signature operation is interrupted.

The size in bits of Fields vi to ix is:

`{fournbsp}{fournbsp}` `varlen` <- 8 + (`HasSecondPt` != 0) {interpunct} ``ub``/8 + (`HasSignature` != 0) {interpunct} ``vb``/8 + +
`{fournbsp}{fournbsp}{fournbsp}{fournbsp}{fournbsp}{fournbsp}{fournbsp}` + (`HasHash` != 0) {interpunct} ``h``/8 + (`HasRndNum` != 0) {interpunct} ``j``/8.

If _VarDataLen_ > `varlen`, Position x contains the microarchitectural dependent part, which starts with
the implementation identifier `aceunitid`.
--
+

State Machine::: {empty}
+
--
* *States:*
Beside
_Initial_ (1),
_Success_ (21),
_Failure_ (22), and the Error States,
ECC algorithms define:
 ** _Set_Generator_ (2)
 ** _Set_Scalar_ (3)
 ** _Gen_Rnd_Scalar_ (4)
 ** _Point_Mul_ (5)
 ** _Sign_Generate_ (6)
 ** _Sign_Verify_ (7)
 ** _Set_Hash_ (8)
 ** _Set_SecondPt_ (9)
 ** _Set_Signature_ (10)
 ** _Output_ (11)
// ** _Absorb_S1_ (12)
--
+

+
--
* *Allowed State Transitions:*

 ** _Initial_ -> _Set_Generator_, _Set_Scalar_, _Set_Hash_, _Set_SecondPt_, _Sign_Generate_, _Set_Signature_.
 ** One can freely transition between _Set_Generator_, _Set_Scalar_, _Set_Hash_, and _Set_SecondPt_.
 ** From any of _Initial_, _Set_Generator_, _Set_Scalar_, _Set_Hash_, _Set_SecondPt_ -> one of the following states:
  *** _Point_Mul_ only if `HasScalar`;
  *** _Sign_Generate_ only if `HasSecondPt`, and `HasHash`;
  *** _Sign_Verify_ only if `HasScalar`, `HasSecondPt`, `HasHash`, and `HasSignature`.
 ** _Point_Mul_ -> _Output_.
 ** _Sign_Generate_ -> _Output_ -> _Success_.
 ** _Sign_Verify_ -> _Success_ or _Failure_.
// ** If `HasSecondPt` -> _Absorb_S1_.

[none]
* In State _Set_Generator_ we can set a group generator, or a default one.
* In State _Set_Scalar_ we can either set a scalar for scalar multiplication or private key.
* For each __Var__ {in} {`Generator`, `Scalar`, `Hash`, `SecondPt`, `Signature`},
the Boolean variable ``Has``__Var__ is set when all operations required in State _set_Var_ have been successfully executed.
--
+

* *Behavior:*

 ** When the CC is created, the `Generator` is set to the default parameter.

 ** All the ŌĆ£setŌĆØ and ŌĆ£outputŌĆØ operations work like the input and output of blocks in the Hash functions, in other words, they use `Progress` (just as the Hash/MAC functions use `block_base`) to track how much information has been read in or written out.

 ** `Progress` can be used by instructions such as Point Multiplication, Signature Generation or Verification, to track the progress of the operations in case they are interrupted.
 In this case, if the CR is exported, the Additional Data Section may contain an implementation-specific section that contain sufficient information to allow resumption, such as certain precomputed multiples of the base point.
 This implementation-specific section starts with the 128-bit value
 `aceunitid = zeros(32) @ aceimpid @ acearchid @ acevendorid`.
 The hardware, after reading `acevendorid`, `acearchid` or  `aceimpid` ,
 decides whether it can retain the additional data and trust the random number generator of the
 originating implementation, in which case it can then resume the computation.
 Otherwise, it will discard the additional data at Position x and `RndNum`
 (Position ix, if present), and restart the operation.

 ** To transition to State _Set_Generator_, a Form A or B `ace.setst` is used.

 *** If no parameter is given, or the value of the GPR used in the Form B `ace.setst` is zero:
  . The default generator of the curve is set.
  . A state change operation can be issued, including to states that require a set `Generator`.

 *** Otherwise:
  . `Progress` <- 0.
  . A value for `Generator` is loaded, using one or more Form B `ace.exec` operations, each one increasing `Progress` by the amount of data provided by `ace.exec`.
  . Once `Progress` has reached the length of the generator point (excess data in the last `ace.exec` is ignored):
   **** No further `ace.exec` instructions may be issued.
   **** A state change operation can be issued, including to states that require a set `Generator`. This state change also clears `Progress`.

 ** To transition to any of the States _Set_Scalar_, _Set_Hash_, _Set_SecondPt_, or _Set_Signature_ a Form A `ace.setst` is used.
 . If there is a current value in the corresponding field _X_ = `Scalar`, `Hash`, `SecondPt`, or `Signature`,
     it is erased, and the Boolean ``Has``_X_ is set to False.
 . `Progress` <- 0, and a value for Field _X_ is loaded, using one or more Form B `ace.exec` operations (similarly to `Generator`).
 . Once the values `Progress` has reached the length of field _X_  (excess data in the last `ace.exec` is ignored):
  *** The corresponding Boolean ``Has``_X_ is set to True.
  *** No further `ace.exec` instructions may be issued.
  *** A state change operation can be issued, including to states that require a value for _X_ to be set. This state change also clears `Progress`.

 ** It is allowed to transition to _Set_Scalar_ also using a Form B `ace.setst` with a non-zero value in the GPR.
    In this case, a random value is set, and `HasScalar` is set to true.

 ** When the operations in states _Point_Mul_ and _Sign_Generate_ are completed:
   . If the output is a point, then `OutputType` <- False, and if the output is a signature, then `OutputType` <- True.
     This allows the ACE implementation to determine not only which output must be written out, but also its length.
     *** If `OutputType` == False, the output is in `SecondPt`.
     *** If `OutputType` == True,  the output is in `Signature`.
   . `Progress` <- 0.
   . One or more Form C `ace.exec` instructions may be issued to export sections of the result to memory, each time increasing `Progress` by the length of the output of `ace.exec`.
     . Data beyond the length of the output is replaced with zeros in the last exported part.
     . Once `Progress` has reached the length of the output, the state automatically transitions to _Success_.

 ** If, after any computation, either `Generator` or `SecondPt` is the point at infinity, then the corresponding field is set to the special value that encodes it.

 ** Upon returning to State _Initial_:
  *** If a Form B `ace.setst` is used, the parameter `Xs` will determine whether the fields
 `Generator`, `Scalar`, and `SecondPt` are reset/erased or kept for further operations.
 This is determined by Bits 0, 1, 2, and 3 of `Xs` as follows:
   **** If Bit 0, 1, 2, resp., 3 is set, then `Generator` is reset to the default value, `SecondPt`, `Scalar`, resp., `SecondPt` is erased, and the corresponding Boolean flags `HasScalar`, resp., `HasSecondPt` is unset as well.
   **** If Bit 4 is set, then `Generator` is copied onto `SecondPt`. If Bit 0 is set, then `Generator` is set to the default value.
   **** If Bit 5 is set, then `SecondPt` is copied onto `Generator`. If Bit 1 is set, then `SecondPt` is erased afterwards and `HasSecondPt` is set to False.
  *** A Form A `ace.setst` does not modify these states.
  *** `Signature` and the corresponding Boolean `HasSignature` are always reset.

// ////////////////////////////////////////////////////////////////////

////
===== Key Derivation Options

[WARNING]
====
This section is WIP.
====

For a sender to perform public-key encryption, the `SecondPt` field must be set
with the _recipient_'s public key, `HasSecondPt` must be True, and the `Scalar`
field must be set with the _sender_'s private key.

For a recipient to decrypt a public-key encrypted message, the `SecondPt` field
must be set with the _sender_'s public key, `HasSecondPt` must be True, and the
`Scalar` field must be set with the _recipient_'s private key.

For ECIES: Before invoking `ace.derive`, it is allowed to transition to State
_Absorb_S1_ where the bit length of the optional S1 must be given as a
parameter to the `ace.setst` transition call through a GPR, and this value is
set in `Progress`. Then, one or more Form B `ace.exec` calls can be made to
absorb consecutive parts of S1 into the state, and the amount of absorbed data
so far is subtracted from `Progress` until it is zero. Excess data is ignored.
S2 must be handled by the user using the MAC function (for NIST curves, an
HMAC, with S2 appended to the ciphertext). `ace.derive` must be of Form B,
where the optional parameter contains (the first 32-bits of) a Metadata Header,
that defines either an encryption algorithm, or a MAC algorithm, or an
authenticated encryption algorithm. The _KeyType_ field must be 0, as well as
_Locality_ and _UsagePolicy_. The latter two will be copied from the source CR
to the destination CR. For KDF use cite:[NIST-SP-800-56Cr2].

The computation of a derived context starts either with the transition to
_Absorb_S1_ or with the issuing of the `ace.derive` instruction.

For SM2 public-key encryption, see cite:[GMT-0003-4-2012].

[WARNING]
====
We need to determine the states/modes for:

. Selection of the KDF (the NIST recommended methods and the chinese one).
 * We assume that the KDF takes first the entire point (X and Y coordinates) or
   the only coordinate in case of Edwards curves.
 * The KDF can then absorb additional data into the state.
. Finalize and seed one or more keys.
. We choose to define auxiliary symmetric algorithms with hidden keys as
  outputs of `ace.derive`.
. For instance, AES/SM2-CTR followed by some MAC function that can absorb an
  additional string after the plaintext. These strings are different from the
  associated data because they are provided _after_ the ciphertext.
====

===== KDF

This family of algorithms will work in two modes: generating L bits of output,
or generated two keys of size L1, L2, with prescribed Metadata Headers M1, M2.

We need to support: NIST SP 800-56C Rev. 2

Parameters:::

* `b` = block size (8|`b`). Similarly to Hash functions, this is the size of an
  absorbed block and may be different from the size of the internal state that
  is kept by the function.
* `t` = tag len (8|`t`). This is the size of the a block that is output each
  time by the function. The present description assumes `t` {le} `b`.
* `h` = The length of the output of a single invocation of the PRF in bits.
* `r` = The length of the counter `i`.
* `j` = The length of the encoding of the output size `L`.
* `k` = key size, if a key is used.
* `l` = The length of the `label`.
* `s` = The length of the ŌĆ£S1ŌĆØ (`context`) string.


Data Structures:::

* *Provisioning Input* (Content):
+
--
[%autowidth,cols="^,<,<",options="header"]
|===
| Pos. | Size (Bits)            | Field
|   i  | If keyed: `k`  , else 64  | `key`
|===
--
+

* *Internal State* (Content):
 ** `key`: `k` bits. Present only if keyed, i.e., a MAC.


* *Serialized Content*:
+
--
[cols="^6%,<21%,<18%,<55%",options="header"]
|===
|  Pos.| Size (Bits)            | Field                       | Notes
.2+| i | If keyed: `k` or 64      | `key` or SKID          | --
<|        If unkeyed: 0            | none                        | --
|===
--
+

//

State Machine:::

* *States:*

. _Initial_
. _Set_KIN_
. _Absorb_Label_
. _Absorb_Context_
. _Output_
. _Completed_

* *Allowed State Transitions:*

TBD.


Parameters:::


Input: KIN, Label, Context, and L

Process:::

. `n` <- {lceil} `L/h` {rceil}
. If `n` > 2^`r`^-1 then output an error indicator and stop
. `i`  <- 1
. foreach Form C ``ace.exec`` while in state _Output_
.. if `i` > `n` then
.. {kappa} := `PRF`(`KIN`, `bin(i,r) || Label || 0x00 || Context || bin(L,j)`)
.. `bits` <- min(`h`, `L` - ``i`` * ``h``)
.. `i <- i` + 1
.. `OUTPUT <- zeros`(`h`-`bits`) @ {kappa}[bits-1:0]
.. if `i` > `n` then transition to state _completed_


===== ECIES Encryption

Inputs{empty}:::

* Random scalar `r` = `RndNum`.
* `PublicKey` = `SecondPt`: The recipient's public key.
* Message: The plaintext message to be encrypted.
* `S1`: Shared information for key derivation.
* `S2`: Shared information for MAC.

Output:::

* The ciphertext

Algorithm:::

. Generate or use a random scalar `r`.
. Compute the public key on chosen curve `R` = `r` {interpunct} `G`, where `G` = `Generator` is the base point of that elliptic curve.
. Derive the symmetric encryption key (Ke) and MAC key (Km):
   `(Ke, Km) = KDF(S || s1)`
   Where KDF is a key derivation function (e.g., HKDF with SHA-256)
. Encrypt the message:
   `c = SymmetricEncrypt(Ke, message)`
   Where SymmetricEncrypt is a symmetric encryption algorithm (e.g., AES-CTR)
. Compute the MAC:
   `t = HMAC(Km, c || s2)`
   Where HMAC is implemented as described in the specification
. Construct the ciphertext:
   `ciphertext = R || c || t`
. Return the ciphertext

////
