[[ACE-unpriv]]
== Book 1: Unprivileged Architecture, Instructions and Architectural States

// Good judgment comes from experience.
// Experience comes from bad judgment.
// —MULLAH NASRUDIN, 1200s AD

=== Introduction

ACE relies on certain fundamental concepts, which are introduced here.
While this leads to some repetitions, it also brings better clarity to the presentation.

[[ACE-concepts]]
==== Fundamental Concepts and Definitions

Cryptographic Context:::
(((Cryptographic Context)))
The *Cryptographic Context* (CC) is the foundation of ACE. A CC is an indivisible structure consisting of a *Metadata Header* (MDH) and *Content*; all cryptographic operations performed by ACE execute within the constraints defined by a CC.
The MDH has a fixed format and specifies the cryptographic algorithm and various optional policies associated with the CC.
(((Cryptographic Context, Metadata Header)))
The Content has an algorithm-specific format and holds sensitive material such as keys and algorithm state.
(((Cryptographic Context, Content)))
The Metadata requires integrity; the Content requires both integrity and confidentiality.
These requirements are architecturally enforced by ACE and by the cryptographic algorithms it implements.

Context Register:::
(((Context Register)))
To create CCs, ACE uses *Context Registers* (CRs), per-hart architectural containers that safeguard their contents.
A CR is *provisioned* by writing Metadata and Content into it; this operation binds the latter to form a CC.
There is no store-like instruction to extract the Content of the CR in a manner that compromises its confidentiality.
A CC may be used for cryptographic operations only while resident in a CR.
Only the ACE unit may access or modify a CC residing in a CR, in accordance with the rules set by the architecture and by the algorithm bound to the CC.

Sealed Cryptographic Context:::
(((Cryptographic Context, sealed)))
To support context switching while protecting CCs outside architectural state, a CC may be *exported* from a CR as a *Sealed Cryptographic Context* (SCC)—an encrypted and authenticated representation of a CC that can later be *imported* into a CR. Export and import use a _Context Sealing Key_ (CSK), which may be programmable by M-mode. An SCC sealed under one CSK cannot be imported under a different CSK, providing cryptographic domain separation across spatial and temporal domains.

Object-Orientation:::
(((Cryptographic Context, object-oriented)))
CCs act as *objects* exposing a uniform interface across algorithms.
A CC encapsulates algorithm-specific behavior, enabling interchangeable use of different primitives (e.g., AES-128, AES-256, SM4) in identical modes (e.g., ECB, GCM-SIV, XTS) without requiring changes to compiled code.
Side-channel attack (SCA) resistant variants are supported transparently.

Usage Control Policy:::
(((Cryptographic Context, usage control)))
(((Cryptographic Context, management operations)))
(((Cryptographic Context, usage operations)))
ACE distinguishes between CC/CR *management* and *usage* operations.
(((Cryptographic Context, export)))
Management operations include *configuration* (e.g., CR provisioning, SCC import, and cloning) and *export* of a CR as an SCC. Usage operations include cryptographic operations and state changes.
To prevent denial-of-service scenarios, management operations, in particular configuration operations, are far less restricted than usage operations. _Usage Control_ policies restrict only certain CC/CR usage operations.

Localities:::
(((Cryptographic Context, Locality)))
ACE can bind CCs to a *Localities*, i.e., restrict usage to specific devices or device classes, hardware configurations, physical or virtual boot cycles, and process domains at various privilege modes. This binding is achieved by using the Localities as _tweaks_ in the encryption and decryption of SCCs.

// ////////////////////////////////////////////////////////////////////

[[ACE-architectural-model]]
==== Architectural Model

[NOTE]
====
ACE is architected as an _attached_ unit, meaning that ACE instructions act as messages across a tightly coupled coprocessor interface.
The ACE unit receives the operations from the hart, executes them independently of the issuing hart, and returns results.

Beside implementations of ACE within a CPU core, this model also allows a single hardware instance of the ACE unit to be shared by multiple cores, with separate architectural states for each client hart.  The specification mandates only behavior, not implementation.

The ACE unit may lock certain architectural states—e.g., Vector Registers, CRs, and CSRs.
The hart stalls when attempting to read them until the ACE operation using those resources completes.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-extensions-overview-unpriv]]
=== Extensions Overview

[%header,cols="15%,47%,18%,10%,10%"]
|===
| Extension       | Features                                                                                                            | Defined in:                                    | Minimum version | Lifecycle state
| `Zlv`           | ACE with support for vector registers.^1^                                                                           | <<ACE-instructions-detailed>>                  | v0.0.0          | --
| `Zlio`          | ACE with support for `ace.input` and `ace.output`.^2^                                                               | <<ACE-usage-input-output>>                     | v0.0.0          | --
| `Zlm`           | ACE with dedicated memory instructions.                                                                             | <<ACE-memory>>                                 | v0.0.0          | --
| `Zlmv`          | ACE with dedicated move instructions.                                                                               | <<ACE-move>>                                   | v0.0.0          | --
| `Zlexpire`      | ACE with support for the _ExpirationDate_ metadata field.                                                           | <<ACE-Metadata-expiration-date>>               | v0.0.0          | --
| `Zlaes128p`     | AES-128 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes192p`     | AES-192 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlaes256p`     | AES-256 encryption/decryption.^3^                                                                                   | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlsm4p`        | ShangMi 4 encryption/decryption.^3^                                                                                 | <<ACE-ECB-mode>>                               | v0.0.0          | --
| `Zlctrm`        | CTR and CTR with set initial counter.^4^                                                                            | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxctrm`       | XCTR and XCTR with set initial counter.^4^                                                                          | <<ACE-keystream-modes>>                        | v0.0.0          | --
| `Zlxexm`        | XEX construction.^5^                                                                                                | <<ACE-XEX-XTS-modes>>                          | v0.0.0          | --
| `Zlgcmm`        | GCM and GCM with set IV.^4^                                                                                         | <<ACE-GCM-mode>>                               | v0.0.0          | --
| `Zlgcmsivm`     | GCM-SIV.^4^                                                                                                         | <<ACE-GCM-SIV-mode>>                           | v0.0.0          | --
| `Zlocbm`        | OCB3 and OCB3 with set IV.^5^                                                                                       | <<ACE-OCB-mode>>                               | v0.0.0          | --
| `Zlcmacm`       | CMAC.^4^                                                                                                            | <<ACE-CMAC-mode>>                              | v0.0.0          | --
| `Zlesha2h`      | SHA-224, SHA-256, SHA-384, SHA-512, SHA-512/224, and SHA-512/256.                                                   | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlesha3h`      | SHA3-224, SHA3-256, SHA3-384, SHA3-512, SHAKE128, and SHAKE256.                                                     | <<ACE-SHA-3>>                                  | v0.0.0          | --
| `Zlsm3h`        | ShangMi 3 (SM3) hash function.                                                                                      | <<ACE-hash-functions>>                         | v0.0.0          | --
| `Zlhmacm`       | HMAC function with hidden key (with SHA2 when `Zlesha2h` is supported, and with SHA3 when `Zlesha3h` is supported). | TBD                                            | v0.0.0          | --
| `Zlkmacm`       | KMAC function with hidden key. Depends on `Zlesha3h`, since KMAC is only defined with SHA3.                         | TBD                                            | v0.0.0          | --
| `Zlascon`       | Ascon-AEAD128 (base, with set Nonce, or with Nonce Masking), Ascon-Hash256, Ascon-XOF128 and Ascon-CXOF128.         | <<ACE-Ascon-AEAD128>> to <<ACE-Ascon-CXOF128>> | v0.0.0          | --
4+| _Point arithmetic and signature generation and verification algorithms for curves in various standards:_                      | {empty}
| `Zlsecp256r1c`  | -- NIST curve secp256r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp384r1c`  | -- NIST curve secp384r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zlsecp521r1c`  | -- NIST curve secp521r1.                                                                                            | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled25519c`    | -- Edwards curve ed25519.                                                                                           | <<ACE-ECC>>                                    | v0.0.0          | --
| `Zled448c`      | -- Edwards curve ed448.                                                                                             | <<ACE-ECC>>                                    | v0.0.0          | --
| `ZlbpP256r1c`   | -- Brainpool curve brainpoolP256r1.                                                                                 | <<ACE-ECC>>                                    | v0.0.0          | --
| `ZlbpP384r1c`   | -- Brainpool curve brainpoolP384r1.                                                                                 | <<ACE-ECC>>                                    | v0.0.0          | --
| `ZlbpP512r1c`   | -- Brainpool curve brainpoolP512r1.                                                                                 | <<ACE-ECC>>                                    | v0.0.0          | --
| `ZlSM2c`        | -- Chinese 256-bit SM2 curve.                                                                                       | <<ACE-ECC>>                                    | v0.0.0          | --
4+| _Post-Quantum Cryptography:_                                                                                                        | {empty}
| `Zlmlkem512k`   | -- `ML-KEM-512`                                                                                                     | <<ACE-PQC-ML-KEM>>                             | v0.0.0          | --
| `Zlmlkem768k`   | -- `ML-KEM-768`                                                                                                     | <<ACE-PQC-ML-KEM>>                             | v0.0.0          | --
| `Zlmlkem1024k`  | -- `ML-KEM-1024`                                                                                                    | <<ACE-PQC-ML-KEM>>                             | v0.0.0          | --
| `Zlmldsa44s`    | -- `ML-DSA-44`/`ML-DSA-44-PH`                                                                                       | <<ACE-PQC-ML-DSA>>                             | v0.0.0          | --
| `Zlmldsa65s`    | -- `ML-DSA-65`/`ML-DSA-65-PH`                                                                                       | <<ACE-PQC-ML-DSA>>                             | v0.0.0          | --
| `Zlmldsa87s`    | -- `ML-DSA-87`/`ML-DSA-87-PH`                                                                                       | <<ACE-PQC-ML-DSA>>                             | v0.0.0          | --
| `Zlkn`        2+| NIST Symmetric Suite. Depends on `Zlaes128`, `Zlaes256`, `Zlesha2`, `Zlgcmm`, `Zlxexm`, and `Zlgcmsivm`.            | v0.0.0                                         | --
5+| ^1^ Requires V (or a suitable subset thereof). Must support the following CSRs: `acestart` (this is a dependency for Zicsr); must support the following instructions: `ace.prov`, all four forms of `ace.exec`, all Forms of `ace.setst`,
`ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size`/`ace.avail`, `ace.getmd{l,h}`, and `ace.restrict{l,h}`; must support `Zlkn`.
5+| ^2^ Must support the following CSRs: `acestart` (this is a dependency for Zicsr), `aceiobuflen` and `aceiobuftop`; must support the following instructions: `ace.prov`, Form D of `ace.exec`, Forms A and B of `ace.setst`, `ace.input` and `ace.output`, `ace.clear`, `ace.export`, `ace.import`, `ace.clone`, `ace.size`/`ace.avail`, `ace.getmd{l,h}`, and `ace.restrict{l,h}`; must support `Zlkn`.
5+| ^3^ Beside defining the basic encryption and decryption operations, these extensions also select which ciphers can be used with the various modes of operations that follow.
5+| ^4^ The mode is applicable to all versions of AES and to SM4.
5+| ^5^ The mode is applicable to all versions of AES.
|===

At least one of `Zlv` or `Zlio` must be implemented.

// ////////////////////////////////////////////////////////////////////

=== Programmer-Visible Architectural State

[[ACE-cryptographic-registers]]
==== Context Registers

{empty}
(((Cryptographic Context)))
ACE defines 32 Context Registers (CRs), numbered 0 to 31 and denoted `K0`–`K31`.

CRs are per-hart architectural state, like GPRs or vector registers.

CRs are not separated by privilege Mode: when a hart changes Mode, it sees the same set of CRs.

Unlike a conventional register, a CR can be _unconfigured_meaning it does not contain a CC.

A CR is addressed either directly, via a 5-bit immediate, or indirectly, via a GPR value.
An additional instruction-encoding bit selects the addressing mode.
Accessing a CR with an indirect index outside [0..31] raises an illegal instruction exception.

An implementation must wait before performing any operation on a CR that is still being written to asynchronously by the ACE unit.

[NOTE]
====
Indirect CR addressing implies that CR renaming, while still possible, would significantly increase microarchitectural complexity.
We posit that CR renaming is not expected to be necessary, and may even be detrimental, for ACE, for the reasons outlined below.

. CRs are redefined far less frequently than GPRs or FP registers (excluding implicit internal state changes); and
. Speculating on the results of cryptographic operations usually leads to security issues.
====

We list the most important operations on CRs below, to refer to them before they are fully defined.

* Provisioning (<<ACE-management-operations>>) loads metadata and plaintext Content into a CR, binding them together.
* Exporting (<<ACE-management-operations>>) exports a CR to memory as an SCC.
* Importing (<<ACE-management-operations>>) imports a SCC into a CR.
* `ace.clear` (<<ACE-instruction-clear>>) unconfigures and clears a CR.
* `ace.exec` (<<ACE-instruction-exec>>) performs cryptographic operations as specified by the algorithm configured in a CR and according to the state of the CR.
* `ace.setst` (<<ACE-instruction-setst>>) transitions a CR between states of a cryptographic algorithm or states of CR management lifecycle.
* `ace.clone` (<<ACE-instruction-clone>>) creates a copy of a CR into a second CR.

===== Representation of Cryptographic Registers for Accessing their Contents

A CR can be viewed as a register of variable and discoverable length (more details in <<ACE-CR-representation>>).
While an ACE implementation may work with an internal representation of a CR's content,
ACE provides a way to access a CR as if it were a register into which a Provisioning Input (PI) or Sealed Cryptographic Context (SCC), as defined in <<ACE-external-formats>> can be loaded.
To this purpose, ACE defines:

* Instructions `ace.load`, to load serialized data into CRs from memory (see <<ACE-instruction-load>>), and `ace.store` (see <<ACE-instruction-store>>) to export a CR's serialized content back to memory; and
* Instructions to make this information available to the ACE unit and to convert the internal representation of CRs to a SCC (by using `ace.setst`, see <<ACE-instruction-setst>>).

===== The Context Register File

CRs reside in a dedicated, per-hart _CR file_ (CRF), a memory accessible only to the ACE implementation.
(((Context Register File)))

The CRF shall guarantee confidentiality and integrity of its contents, including the inability for an attacker to roll back the latter to a previous state.
We do not require that accesses to this memory are hardened against physical side-channel attacks at the hardware level.
However, the implementation of side-channel-protected algorithms in the ACE unit shall provide resistance to such attacks as well.

The amount of CRF capacity consumed by each CR depends on the algorithm encoded in the MDH, and it may differ from one CR to another.

Insufficient residual CRF capacity may prevent execution of a configuration instruction.
Capacity is freed by unconfiguring other CRs.

The CRF capacity is implementation-defined.
Implementations shall provide sufficient capacity for all supported operations.
At a minimum, the CRF must hold the largest possible single CR, or the largest CR pair used in cloning operations, and a small amount of additional authentication and identification information.
This small amount of additional storage space is not replicated per CR but is shared across all CRs per hart and it is used only when importing and exporting SCCs.

Any corruption of the CRF associated with a hart shall cause an unrecoverable error condition.
The entire architectural state of the ACE unit associated with the hart is reset, and exception `ace_guru_meditation` is raised (cf. <<ACE-exceptions>>).

// ////////////////////////////////////////////////////////////////////

==== Providing Inputs and Outputs

===== RVV/RVV-mini

ACE inputs and outputs may use vector registers or an architectural input/output buffer (ACEIOBUF)
that can be loaded from and stored to external memory. Both mechanisms may be supported simultaneously.

When vector registers are used, the full V extension is not required. ACE depends only on a minimal subset, termed _RVV-mini_.
(((RVV-mini)))
RVV-mini must be fully opcode-compatible with RVV: code written for RVV-mini must execute with identical behavior under RVV.
The current set of features is:

* Vector registers (or groups) wide enough to support the inputs and outputs of the implemented algorithms, that is, currently, 128 bits.
* Configuration-setting instructions (`vsetvli`/`vsetivli`/`vsetvl`):
 ** Since all ACE operations ignore masks while accessing vector registers, RVV-mini only needs tail and mask agnostic configurations;
 ** Since ACE operations do not depend on a concept of element (from a logical point of view, they are not performed in the vector unit),
    they view a vector (group) as a bit string of length `VL` * `SEW` with `VL` = min(`AVL`,`VLMAX`),
    processing in each operation `VL` * `SEW` bits.
 ** Support for `LMUL` integer values of 1, 2, 4, and 8;
 ** Unsupported configurations shall raise an illegal instruction exception.
* Unit-strided vector loads and stores; and
* Vector bitwise logical operations: `vxor`, `vand`, and `vor`.

ACE instructions do not use vector masking and do not define masked versions of `ace.exec`.
Therefore, RVV-mini does not need support for masked operations.
We are not using bit 25 of the instruction encodings, though, for potential future adoption of masked operations, should a compelling use case arise.

Floating-point, fixed-point, and general arithmetic vector operations are not required.
Complex operations for certain cryptographic algorithms may be performed in GPRs, with data inserted into vector registers and result extracted from them via `vins`/`vext`.

[WARNING]
[.red]#RVV-mini need not be finalized before ACE ratification begins; it
may be defined later, and the ACE specification amended accordingly.
This allows additional requirements to be collected, for example, whether to mandate
`vclmul.v[vx]` and `vclmulh.v[vx]` from `Zvbc`.#

When vector registers are used, ACE determines the lengths of its operands from `VL*SEW`.
The specific choice of `VL` and `SEW` is irrelevant; for example, `VL`=2, `SEW`=64 and `VL`=4, `SEW`=32 both define a 128-bit input.
The CPU instruction-decoding side of ACE uses `VL` and `SEW` to determine how much data to send to the ACE unit proper, but the ACE unit itself requires only the product `VL*SEW` (or `aceiobuftop`).

===== ACEIOBUF

ACEIOBUF is an optional architectural input/output buffer that may be used in place of vector registers.
It is not part of the CRF.

The `ace.input` instruction loads data from memory into the ACEIOBUF to supply inputs to other ACE operations, which will write their outputs to the ACEIOBUF.
The `ace.output` instruction is used to store these outputs to memory.
When the ACEIOBUF is used in place of vector registers, the `ace.exec`, `ace.setst`, and `ace.derive` instructions that would otherwise use vector registers for their inputs and outputs are replaced by instruction sequences that combine the no-input/no-output versions of the same operations with `ace.input` and `ace.output`.
These sequences are described in <<ACE-usage-input-output>>.

When the ACEIOBUF is used, the length of the input is given in CSR `aceiobuflen` (<<ACE-CSR-aceiobuflen>>).

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata]]
==== Metadata Formats

The ACE architecture recognizes two types of metadata that may be contained in a CC or associated with it.

. A 128-bit _MDH_ that determines the algorithm, the type of key, and various usage policies associated with the key.
 This information is always present in a CC.
 The fields are arranged so that the first 64 bits suffice to determine the length of a PI or SCC.

. An optional 128-bit _Implementation Metadata_ block that contains copies of the values of three architectural registers which are the ACE analogues
of `mvendorid`, `marchid`, and `mimpid` CSRs for the hart implementation (see <<ACE-CSR-impl-ids>>).
 The latter may be only present in an SCC and only if the SCC has been extended by the implementation with an implementation-specific content block.
 This block is used by an implementation to determine whether it can be use the aforementioned implementation-specific content block, even if generated by another implementation.

In this section we only deal with the 128-bit MDH.
Its fields are summarized in <<ACE-metadata-header>>.
// Of its 128 bits, 97 are currently defined and 31 are reserved for future use.
// Most algorithms use only 77 bits, as _StateExtension_ and _AlgorithmUse_ are currently used only by the Elliptic Curve Algorithms (<<ACE-ECC>>).
All _Reserved_ bits, as well as bits unused by a given algorithm, must be zero.

[[ACE-metadata-header]]
.Format of the 128-bit Metadata Header
[width="100%",cols="^9%,^6%,14%,71%",options="header"]
|===
|    Field  | Size | Name              | Description
|    [11:0] |  12  | _Algorithm_       | This field encodes the cryptographic algorithm (primitive, mode, or protocol) that is bound to the key material. See <<ACE-Algorithm-field>>.
|   [13:12] |   2  | _AlgorithmPolicy_ | Allowed algorithm variants(s), such as, for a symmetric cipher, whether it can be used for encryption, decryption, or both.
See <<ACE-Algorithm-field>>.
|   [15:14] |   2  | Reserved          | Reserved for future expansion of _AlgorithmPolicy_ field.
|   [18:16] |   3  | _SCProtection_    | Side-channel protection level. The levels of side-channel protection are defined in <<ACE-SCProtection-field>>.
|   [20:19] |   2  | _KeyType_         | This field determines whether they key is given by value, is a system-defined key, or randomly generated.
See <<ACE-KeyType-field>> for more details.
|   [25:21] |   5  | _State_           | Current state of the CR/algorithm, encoded as an integer. For instance, whether the CR/algorithm is _Off_ (unconfigured), encrypting or decrypting data, absorbing data in a hash/mac/tag, computing elliptic curve point multiples, generating or verifying signatures, or in an error state. It can be modified by the user to advance through various phases of an algorithm. See <<ACE-State-field>>.
|   [29:26] |   4  | _StateExtension_  | May be used by the algorithm to extend the _State_ field with additional information. See <<ACE-State-field>>.
|   [31:30] |   2  | _ConfigStatus_    | Used to indicate whether the CR is fully configured and ready to operate, or is being provisioned, imported, or exported. See <<ACE-ConfigStatus>>.
|   [45:32] |  14  | _ImpDataLen_      | If non-zero, indicates that an additional, variable-length, implementation-dependent data section appended to Content. The length of this additional data section is _ImpDataLen_ * 128 bits (up to 256 KiB).
|   [61:46] |  16  | _AuxInfo_         | Currently used only by ML-DSA to encode an auxiliary hashing algorithm. This field has the same format as bits [15:0].
|   [62:62] |   1  | _Reserved_        | Reserved for future use.
|   [63:63] |   1  | _SystemFormat_    | Value is 0 if an input is in the ACE architected format 1 if it is in a system-defined Format.
|   [68:64] |   5  | _UsagePolicy_     | Usage (Control) Policy. Bits 0, 1, 2, 4 and 4 of the field, when set, disallow CC usage in U-mode, (V)S-mode, HS-mode, M-Mode, and Debug mode, respectively. Any bit of this field is ignored if the corresponding mode is not supported or not enabled.
|   [77:69] |   9  | _Locality_        | Zero, or a value determining one or more Locality Secrets, used in the export/import encryption and decryption algorithm to bind the CR to specific environments. See <<ACE-Localities>>.
|   [79:78] |   2  | Reserved          | Reserved for expansion of the _Locality_ field.
|   [95:80] |  16  | _AlgorithmUse_    | Reserved for algorithms and implementations to store additional state information.
|  [115:96] |  20  | _ExpirationDate_  | If non-zero, the expiration date of this CC. See <<ACE-Metadata-expiration-date>>. Expressed in hours since 00:00, January 1, 2027 (about 119 years and 7 months).
| [127:116] |  12  | Reserved          | Reserved for future use.
|===

The fields as described in detail in the following subsections.

// ////////////////////////////////////////////////////////////////////

[[ACE-system-format-field]]
===== _SystemFormat_ Bit

The use of a system-defined format is signalled by the _SystemFormat_ bit MDH[63:0].
The format of the other 63 bits of MDH[63:0], as well as of the part of the input that would otherwise contain MDH[127:64], is entirely system specific, as is the rest of the input.

// ////////////////////////////////////////////////////////////////////

[[ACE-Algorithm-field]]
===== _Algorithm_ and _AlgorithmPolicy_ Fields

Algorithms are encoded in a 12-bit field.
Values 0–3071 and 4095 are architecture-defined.
The list of encodings is maintained by RVI (see <<ACE-algorithms>>).
The remaining values are available for custom algorithms.

For encryption/decryption primitives and modes, the _AlgorithmPolicy_ field indicates whether the CC may be used for encryption (lower bit set), decryption (upper bit set), or both. At least one of the bits must be set.

For asymmetric primitives supporting signatures, the lower bit permits signature generation and the upper bit permits verification.
Such an asymmetric primitive can be configured to support primitives such as key agreement or key encapsulation but _not_ signatures, and in this case both bits are zero.

For other primitives, the _AlgorithmPolicy_ field may encode additional algorithm identifiers to expand the effective encoding space of the _Algorithm_ field.

The information contained in the _Algorithm_ field may affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-SCProtection-field]]
===== _SCProtection_ Field

The architecture defines the following side-channel protection levels.

[[ACE-SC-protection-levels]]
.Encoding of Side-Channel Protection levels
[%autowidth,float="center",align="center",cols="^1,<7",options="header"]
|===
| Value  | Description
|   0    | Data-independent execution latency (DIEL) for cryptographic operations.
|   1    | First-order threshold implementation.
|   2    | DIEL; first-order threshold, fault-tolerant implementation.
| {ge} 3 | Reserved/Currently not defined.
|===

Implementations offering additional levels of protection may set _SCProtection_ to a value greater than 2:

* Values 3-5 are reserved for future use by the architecture.
* Values 6-7 are reserved for implementation-custom protection levels.
  In this case, the generating environment must use localities that prevent the use of the SCC on different architectures.

The information contained in this field may affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-KeyType-field]]
===== _KeyType_ Field

This field takes the value 0 if the key is given by an explicit value, and 1 if the key is given by a system-specific, 64-bit System Key Identifier (SKID).
Values 2 and 3 are currently reserved. See <<ACE-system-keys>>.

If the value is 0, keys are provisioned, exported, and imported by value.

If the value is 1, keys are provisioned, exported, and imported as a System Key Identifier (SKID), except for the all-ones (i.e., `ones(64)`) SKID value.

If the SKID is the all-ones value, the key material is generated randomly upon provisioning, and then exported by value with _KeyType_ set to 0.
Random generation applies to all keys at once in an algorithm, unless otherwise specified.

The information contained in this field may affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-State-field]]
===== _State_ and _StateExtension_ Fields

The _State_ field is used to track the currently state of an algorithm, including certain types of errors.

The architected values of _State_ common to all algorithms are defined in the following three tables.

[[ACE-state-off]]
.Global CC State Numbers: Off State
[float="center",align="center",width="100%",cols="^7%,<27%,<15%,<51%",options="header"]
|===
| Value | Mnemonic                  | State Name     | Description
|   0   | `ace_state_off`           | _Off_          | The CR is not configured.
|===

[[ACE-states-valid]]
.Global CC State Numbers: Valid States
[float="center",align="center",width="100%",cols="^7%,<27%,<15%,<51%",options="header"]
|===
| Value | Mnemonic                  | State Name     | Description
|   1   | `ace_state_initial`       | _Initial_      | The state of a just provisioned CC; ready for operation.
| 2-21  3+| Defined by the specification of the Algorithm encoded in the _Algorithm_ field.
|  22   | `ace_state_success`       | _Success_      | Algorithm completed successfully. No further cryptographic operations may be performed until the CR is reconfigured or transitioned to _Initial_.
|  23   | `ace_state_failure`       | _Failure_      | Failure in an algorithm, usually an authentication failure in AE(AD) algorithms or a signature verification failure. No further cryptographic operations may be performed until the CR is reconfigured or transitioned to _Initial_.
|===

[[ACE-states-error]]
.Global CC State Numbers: Error States
[float="center",align="center",width="100%",cols="^7%,<27%,<15%,<51%"]
|===
|  24    | `ace_state_not_impl`        | _Not_Impl_        | Not implemented algorithm. It is set by the hardware upon an attempt to provision or import a CR that is not supported by the implementation.
|  25    | `ace_state_invalid`         | _Invalid_         | Invalid/invalidated state, for instance because of the use of an invalid value (argument, state, or metadata).
|  26    | `ace_state_out_of_mem`      | _Out_of_Memory_   | Insufficient CRF memory for configuration instruction. This may be set by privileged code in case they do not handle the CR allocation.
|  27    | `ace_state_ace_CR_import_auth`     | _Auth_Failed_     | Authentication failure with `ace.import`.
|  28    | `ace_state_priv_viol`       | _Priv_Viol_       | Violation of Usage Control policies.
|  29    | `ace_state_expired`         | _Expired_         | The CR has expired.  This is set by the hardware even if the condition also raises an exception.
| 30, 31 | (Reserved)                  |                   | Reserved for future use.
|===

State 0 is the _Off_ state.  It denotes that the CR is unconfigured.

All states in the range 1-23 are termed _valid_. This includes both _Success_ and _Failure_ states, which must be used for
normal termination of an algorithm in the cases of its successful completion or failure.

The immediate in the `ace.setst` instruction (<<ACE-instruction-setst>>) is a 7-bit value, whereas the _State_ field is only 5 bits long.
This allows to encode additional operations related to state changes (such as stages of import, export, or provisioning code) as `ace.setst` with the two high bits of the immediate taking non-zero values.

(((ACE, algorithm, error states)))
States 24-31 are termed _Error States_, and are used to report certain specific ACE errors.
(((ACE, algorithm, invalid state)))
(((Context Register, invalidation)))
In particular, if the State is `ace_state_invalid`, we say that the CR is _invalidated_.

The Error States are currently listed in decreasing severity order, with Error State 24 being the most severe and Error State 29 the least severe.
Error States 30 and 31, if defined, will not necessarily have a lower priority than Error State 29, and may be therefore not in order.

Error conditions that lead to exceptions are treated in <<ACE-exceptions>>.

If an algorithm defines 23 or fewer valid states (including _Initial_, _Success_, and _Failure_), the current state is stored in the _State_ field.
For algorithms with more than 23 valid states, additional state information resides in the Content section.

The following rules are generic and apply to all algorithms:

. The MDHs's _State_ field must reflect the current state whenever the CC is in _Initial_, _Success_, _Failure_, or any Error State.
This ensures that these states can be unambiguously determined from the _State_ field alone, without inspecting the Content.

. In States _Success_ and _Failed_, only the following ACE instructions are permitted: `ace.prov`, `ace.import`, `ace.export`, `ace.clear`, `ace.size`, `ace.setst`, and `ace.getst` (cf. <<ACE-instructions-detailed>> for the descriptions of the instructions).

. In States _Success_ and _Failed_, `ace.setst` can only be used permitted to transition to _Initial_ or _Off_.

. A transition from any valid state to _Initial_ using instruction `ace.setst` is always permitted.
While an algorithm may want an initial state to be used only once to avoid certain cryptographic attacks, a CR can always be restored from a backup SCC, so preventing transitions to _Initial_ are not effective mitigations.

. Any transition may be caused by an performing an explicit `ace.setst` operation performed while in a given state, or may be induced by certain conditions specified in the algorithm's specification.

. The State after `ace.setst` is issued may differ from the State specified by the instruction.
Beside error reporting through an Error State, a common example is given by MAC verification: after `ace.setst` is issued with an `ace_state_hash_verify` immediate as the next state and the value to be verified as the additional parameter, the algorithm transitions to either _Success_ or _Failure_. This is done to prevent the manipulation of a CR's state and to reduce code size.
An `ace.exec` instruction may also trigger a state change.

. Upon transitioning to an Error State, the Content of a CR is invalidated and emptied.
Internal resources associated with the Content may also be released. In that case, any additional variable-length data is released as well and the _ImpDataLen_ field is set to 0.
The CR then retains only the MDH.

. The transitions from _Off_ to any Error State are a result of configuration instructions, whereas the corresponding transitions from these Error States to _Off_ are a result of explicitly clearing the CR.

. Exporting a CR in an Error State exports only the MDH and the authentication tag(s).
  Requesting the SCC's size (`ace.size` <<ACE-instruction-size>>) will return 32 (bytes).
  The resulting SCC can be reimported, allowing software to take appropriate actions even after a context switch.

. If a CR is in any Error State, it can still be reconfigured, cloned, or cleared. `ace.setst` can only be used to change the Error State (for instance by an exception handler) or transition the CR to _Off_.

. Bits [63:0] of the MDH of a CR in an Error State can be read (using `ace.getmdl`: <<ACE-instruction-getmd>>).

. Bits [63:0] of the MDH of a CR in the _Off_ State can be read (using `ace.getmdl`: <<ACE-instruction-getmd>>), returning all zero values.

. Attempts to _use_ a CR in any Error State will not perform any operation, and in particular they leave the _State_ field unchanged.

. Any _usage_ instruction that would violate the Usage Control policies will not perform its operation, and will set _State_ to `ace_state_priv_viol` instead.

In <<ACE-states-graph>> we display the default possible state transitions.


// //
[[ACE-states-graph]]
.Default State Transitions
[float="center",align="center"]
image::images/statestikz-3.svg[]
// //

////
[[ACE-states-graph]]
.Default State Transitions
[tikz,,svg,float="center",align="center",preamble=true,command=lualatex]
....
\usetikzlibrary{calc,trees,matrix,positioning,chains,fit,intersections}
\usetikzlibrary{arrows,shapes.arrows,shapes.geometric,shapes.multipart,shapes.symbols}
\tikzset{
   state/.style={ rectangle, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
   partial state/.style={trapezium, draw=black, thick, minimum height=1.66em, text centered, rounded corners=3pt},
   error state/.style={ rectangle, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
   off state/.style={ circle, double, draw=black, semithick, minimum height=1.66em, text centered, rounded corners=3pt},
   branch/.style={ fill, shape=circle, minimum size=3pt, inner sep=0pt},
   cross line/.style={preaction={draw=white, -, shorten >=3pt, shorten <=3pt, line width=2pt}},
   >=latex
}
\usepackage{fontspec}
\setmainfont[UprightFont={Petrona-Light.ttf},
             BoldFont={Petrona-Medium.ttf},
             ItalicFont={Petrona-LightItalic.ttf},
             BoldItalicFont={Petrona-MediumItalic.ttf},
            ]{Petrona-Light.ttf}
~~~~
\begin{tikzpicture}[scale=1.1]

  \node[off state]   at (-1.75,0)    (off)            {Off\,\vphantom{g}};

  \node[error state, text width=1.3cm] at (2,-2)    (invalid)        {Invalid\vphantom{g}};
  \node[error state] at (2,2)                       (various errors) {\scriptsize\begin{tabular}{@{}c@{}}Privilege Violation,\\Not Implemented,\\Out of Memory\end{tabular}};
  \node[error state] at (2,3.5)                     (authfail)       {\footnotesize\begin{tabular}{@{}c@{}}Authentication\\Failure\end{tabular}};
  \node[error state, text width=1.3cm] at (2,-3.5)  (expired)        {Expired};

  \node[circle,thick,draw=black] at (4.75,2.75) (configuration hub) {};
  \node[coordinate] at ($(expired.east)+(0.5,0)$) (before expired) {};

  \node[state, thick, text width=1.3cm] at (5.5,0)    (initial)           {Initial\vphantom{g}};
  \node[state, thick, text width=2.9cm] at (8.5,-1.5) (algorithm defined) {Algorithm-Defined};
  \node[state, thick, text width=2.9cm] at (8.5,1.5)  (success failure)   {Success / Failure};

  %%%%%%%%%%%

  \node[above=0mm  of configuration hub,xshift=5mm] (ignore) {\small\textit{Configuration}};
  \node[below right=0mm and -4mm of before expired] (ignore) {\small\textit{Expiration}};

  %%%%%%%%%%%

  \draw[-,densely dashed]   (before expired) to[out=9,in=270,looseness=0.8] (initial);
  \draw[-,densely dashed]   (before expired) to[out=7,in=225,looseness=0.8] (algorithm defined);
  \draw[-,densely dashed]   (before expired) to[out=3,in=225,looseness=0.8] (success failure);
  \draw[->,densely dashed]  ($(before expired)+(-0.1,0)$) -- (expired);

  \draw[<->,densely dotted] (configuration hub) to[out=-40,in=90,looseness=0.8] (initial);
  \draw[<->,densely dotted] (configuration hub) to[out=-20,in=125] ($(algorithm defined.north)+(-0.333,0)$);
  \draw[<->,densely dotted] (configuration hub) to[out=0,in=140] ($(success failure.north)!0.5!(success failure.north west)$);
  \draw[<->,densely dotted] (configuration hub) to[out=160,in=0] (authfail);
  \draw[<->,densely dotted] (configuration hub) to[out=190,in=10] (various errors);
  \draw[<->,densely dotted] (configuration hub) -- (invalid.north east);
  \draw[<->,densely dotted] (configuration hub) to[out=270,in=10,looseness=0.6] ($(expired.east)+(0,0.1)$);

  \draw[<->] (off) to[out=-66,in=180] (invalid);
  \draw[<->] (off) to[out=78,in=180,looseness=0.7] (authfail);
  \draw[<->] (off) to[out=66,in=180] (various errors);
  \draw[<->] (off) to[out=-78,in=180,looseness=0.7] (expired);

  \draw[->] (algorithm defined) to[out=250,in=180] ($(algorithm defined)+(0,-1)$) to[out=0,in=290] (algorithm defined);
  \draw[->, cross line] (algorithm defined) -- (invalid);
  \draw[->,cross line] ($(algorithm defined.north)+(-0.667,0)$) to[out=130,in=0] (various errors);

  \draw[<->,cross line] (off) -- (initial);
  \draw[<->,cross line] (off) to[out=-33,in=180,looseness=0.3] (algorithm defined);
  \draw[<->,cross line] (off) to[out=33,in=180,looseness=0.3] (success failure);

  \draw[->,cross line]  ($(success failure.south)+(-1,0)$)   to[out=225,in=10,looseness=0.8] node[near start, above, yshift=-3pt] () {*} ($(initial.east)!0.5!(initial.north east)$);
  \draw[<->,cross line] ($(algorithm defined.north)+(-1,0)$) to[out=135,in=-10,looseness=0.8] ($(initial.east)!0.5!(initial.south east)$);
  \draw[->,cross line] (algorithm defined) -- (success failure);

\end{tikzpicture}
....
////

The legend for the graph is:

* The double circled state is the _Off_ State.
* Valid States have single rounded rectangular borders.
* Error States have double rounded rectangular borders.
* The continuous edges represent state transitions induced by both configuration and usage instructions.
* The dashed edges represent state transitions induced by reaching the expiration date.
* The dotted edges represent state transitions induced by configuration operations.
  Completing a provisioning operation can only lead to the _Initial_ state.
  Completing an import can lead to any state.
* The round _Configuration_ “hub” simplifies the graph by expressing that any Error State is always reachable—even from another Error State—through configuration operations (or via `ace.setst`).

The _StateExtension_ field can be used by an Algorithm to store additional state information.

The information contained in this field may affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-ConfigStatus]]
===== _ConfigStatus_ Field

The admissible values of this field are given in the table below.

[[ACE-SC-sealing-status]]
.Encoding of _ConfigStatus_ field
[float="center",align="center",cols="^7%,<21%,<72%",options="header"]
|===
| Value | Mnemonic             | Description
|   0   | _CfgStComplete_      | The CR is fully configured and ready to operate.
|   1   | _CfgStProvisioning_  | The CR is partially configured as a result of an interrupted provisioning operation.
|   2   | _CfgStImporting_     | The CR is partially configured as a result of an interrupted import operation.
|   3   | _CfgStExporting_     | The CR has been placed in exporting mode, i.e., its contents have been encrypted and authenticated for export..
|===

Usage and cloning of a CR whose _ConfigStatus_ is not _CfgStComplete_ are not allowed.

The information contained in this field shall _not_ affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-extra-content]]
===== _ImpDataLen_ Field

The _ImpDataLen_ MDH field records the length of the _Additional Data Section_ of the content, which is a variable-size additional part that depends on the implementation.

The format of the _Additional Data Section_ is described in <<ACE-data-formats>>.

If _ImpDataLen_ is nonzero, the first 128-bit block of this additional section contains
a copy of the implementation qualifier

``{fournbsp}{fournbsp}IMPQUAL := zeros(32) @ aceimpid @ acearchid @ acevendorid``

(cf. <<ACE-CSR-impl-ids>>) from the originating machine. Its 16 bytes are counted within the length recorded by the _ImpDataLen_ field.
The importing implementation uses this value to determine whether any information in the Implementation-Specific Data Section can be used.

// ////////////////////////////////////////////////////////////////////

[[ACE-Localities]]
===== _Locality_ Field

The Locality Secrets Table (LST) contains 128-bit Locality Secrets (LS).
Some entries are fixed or only configurable through an implementation-specific authenticated hardware process.
These are shared across all ACE units within the same SoC.
Other entries are SW-programmable per-hart architectural state.

<<ACE-locality-indexes>> lists the architected Localities.
Twelve LST entries are defined: the first six form the _HW Binding Group_, which binds SCCs to the hardware;
entries 6–7 form the _Boot Session Group_; and
entries 8–11 form the _SW Filter Group_.
For each Locality, the table provides: index in the LST; domain (SoC-, device-, VM-wide, or per-process); configurability; bit-field encoding; and value.

[[ACE-locality-indexes]]
.Architected Localities. Bits refer to the _Locality_ field in the MDH.
[width="100%",cols="^5%,15%,50%,^9%,^9%,^6%,^6%",options="header"]
|===
|  Idx  | Locality                  | Description                                                                            | Domain | Config?|  Bits  | Value
2+|    No HW Binding                | Independent of Chip, OEM, Device                                                      ^|  --   ^|   --   | [3:0]  |  0
|   0   | _SiPScrt_                 | Identifies the designer of the SoC. Permanent.                                         |  SoC   |   No   | [1:0]  |  1
|   1   | _ChipFamScrt_             | Identifies specific chip/SoC model/family. Permanent.                                  |  SoC   |   No   | [1:0]  |  2
|   2   | _ChipScrt_                | Unique for each SoC. Permanent.                                                        |  SoC   |   No   | [1:0]  |  3
|   3   | _OEMScrt_                 | Provisioned by OEM to differentiate their products from the competition.
{empty}                               Permanent, or reconfigurable via a custom hardware authenticated mechanism.            | Device |   HW   | [3:2]  |  1
|   4   | _ProdScrt_                | Identifies device/system type/model (product).
{empty}                               Permanent or reconfigurable like OEMScrt.                                              | Device |   HW   | [3:2]  |  2
|   5   | _DevScrt_                 | Unique device (entire system) secret. Shared across all harts in a SoC and shareable
{empty}                               across multiple SoCs in a single device using an implementation-defined mechanism.
{empty}                               Reconfigurable like OEMScrt.                                                           | Device |   HW   | [3:2]  |  3
2+|   No Boot Binding               | Independent of Physical or Virtual Boot Session                                       ^|  --   ^|   --   | [5:4]  |  0
|   6   | _PhysBootScrt_            | Unique per the boot session of the host hardware and its firmware stack.
{empty}                     Configured by M-mode during the boot process of the host (see <<ACE-CSR-macePhysBootScrt>>).     | Device |   M    | [5:4]  |  1
|   7   | _VirtBootScrt_            | Unique per the boot session of the virtual hardware and its software stack.
Regenerated by H or higher at each virtual boot of a VM (see <<ACE-CSR-haceVirtBootScrt>>).                                  |   VM   |  H/M   | [5:4]  |  2
2+| No Binding to Modes             | Independent of M-, S-, or any VS-mode Localities                                      ^|  --   ^|   --   | [7:6]  |  0
|   8   | _MLocality_               | Configurable at M.  Useful to separate Supervisor Domains/Security States.             |  < M   |   M    | [7:6]  |  1
|   9   | _HLocality_               | Configurable at HS.                                                                    |  < HS  |   HS   | [7:6]  |  2
|  10   | _SLocality_               | Configurable at (V)S.                                                                  | < (V)S |  (V)S  | [7:6]  |  3
|  11   | _Nonce_                   | Always re-configurable (out-of-band peer-to-peer nonce). Only bits [95:0] are defined. |  hart  |   U    | [8:8]  | 0/1
|===

Implementations are not required to populate every entry in the HW Binding Group, except for _ChipFamScrt_ and _DevScrt_.
If an entry is unconfigured, it is transparently replaced by the next defined entry in its chain: _SiPScrt_ {rightarrow} _ChipFamScrt_ {rightarrow} _ChipScrt_, and _OEMScrt_ {rightarrow} _ProdScrt_ {rightarrow} _DevScrt_.
If no entry is configured in these chain but one Locality is requested, the implementation must raise an authentication failure error.

_HLocality_ is active only when the H extension is enabled and V=1; otherwise, it mirrors _MLocality_.

NOTE: A system key identifier may refer to keys with unrelated purposes on different devices, leading to unspecified behavior.
Implementations shall assign usage policies at least as restrictive as the key's own native policies, and supply an appropriate _Locality_ during CR provisioning.

Up to five architected Localities may be active concurrently: two from the HW Binding Group, one of either _PhysBootScrt_ or _VirtBootScrt_, one from the SW Filter Group, and the _Nonce_.  The SCC generation and import algorithms described in <<ACE-export-import-algorithms>> enforce the policies associated with these Localities.

The information contained in the _Locality_ field shall _not_ affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-Metadata-expiration-date]]
===== _ExpirationDate_ Field

This field is only in effect of extension _Zlexpire_ is supported.

If _Zlexpire_ is supported, the ACE implementation must have access to a secure clock.

If _Zlexpire_ is not supported, the implementation shall reject PIs and SCCs with a non-zero _ExpirationDate_ field.

If non-zero, the 20-bit _ExpirationDate_ field specifies the CC's expiration time as hours elapsed since the base date of January 1, 2027. The maximum representable time span is approximately 119 years and 7 months.

Checking the _ExpirationDate_ is the first step performed by any _usage_ operation.  When a usage instruction executes on a CR whose _ExpirationDate_ has passed, the hardware immediately sets the MDH's _State_ field to `ace_state_expired` and performs all actions prescribed for Error States, including implementation-specific tasks such as releasing the CRF capacity held by the Content. If the ACE privileged architecture is implemented, an `ace_exc_invalid` exception is raised (see <<ACE-exceptions>>).

This check is _not_ performed by management operations (such as exporting, cloning, or configuring), and in particular it is not performed if the _ConfigStatus_ is not _CfgStComplete_. This implies that an `ace_exc_invalid` exception is raised only when the expired CR is first used.

The information contained in this field shall _not_ affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-AlgorithmUse]]
===== _AlgorithmUse_ Field

The _AlgorithmUse_ field can be used by an Algorithm to store additional information.

If not used by the Algorithm, the implementation may use this field.

The information contained in this field shall _not_ affect the size of an SCC.

// ////////////////////////////////////////////////////////////////////

[[ACE-Memory-Alignment]]
==== Memory Alignment Constraints

If the address accessed by an ACE memory instruction is not naturally aligned
to the effective XLEN, the context is transferred successfully or an
address-misaligned exception is raised on that address.

There are no atomicity requirements for any ACE memory instruction.

[[ACE-Memory-Model]]
==== Memory Model

ACE memory instructions appear to execute in program order on the local hart.

ACE memory instructions follow RVWMO at the instruction level. If the `Ztso` extension is implemented, ACE memory instructions additionally follow RVTSO at the instruction level.

ACE memory instructions may be decomposed into a set of component memory operations of any granularity.
The ordering of these memory operations within the instructions is not specified, and it depends on the chosen memory model and implementation of the issuing hart, as long as the the semantics of the configuration and export instruction and `ace.exec` are respected.

NOTE: `Ztso` only imposes RVTSO at the instruction level; intra-instruction ordering follows RVWMO regardless of whether `Ztso` is implemented.

[WARNING]
====
. More formal definitions required.
. Discuss whether the ACE Unit may issue XLEN-sized memory operations to the LSU in a prescribed order, to allow proper resumption.
====

[[ACE-CSR-unpriv]]
==== CSRs

ACE provides a number of unprivileged CSRs.
// The privileged CSRs are documented in <<ACE-priv>>.

[[ACE-CSRs-unpriv]]
.ACE Unprivileged CSRs.
[cols="^10%,^10%,<18%,<62%"]
[float="center",options="header"]
|===
|  Address   | Privilege | Field                    | Description
|  0xXXX     |     RO    | `acevendorid`            | Manufacturer of the ACE unit. See <<ACE-CSR-impl-ids>>.
|  0xXXX     |     RO    | `acearchid`              | Architecture version, per vendor, of the ACE unit. See <<ACE-CSR-impl-ids>>.
|  0xXXX     |     RO    | `aceimpid`               | Implementation, per vendor, of the ACE unit. See <<ACE-CSR-impl-ids>>.
| `vstart`   |    URW    | `acestart`               | ACE start bit index.
|  0xXXX     |    URW    | `aceiobuflen`            | ACE input/output buffer length in bits.
|  0xXXX     |     RO    | `acemaxiobuflen`         | ACE maximum input/output buffer length in bits. Read only.
|  0xXXX     |    URW    | `aceiobuftop`            | ACE input/output buffer limit for current transfers in bits.
|  0xXXX-XXX |    URW    | `acenonce0`, `acenonce1` | Nonce to be used in export and import operations (see <<ACE-export-import-algorithms>>).
|===

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-impl-ids]]
===== `acevendorid`, `acearchid`, and `aceimpid`

{empty}
(((CSR, `acemvendorid`)))
(((CSR, `acemarchid`)))
(((CSR, `acemimpid`)))
`acevendorid`, `acearchid`, and `aceimpid` identify the version of the ACE unit, analogously to `mvendorid`, `marchid`, `mimpid` CSRs for the hart.

The `acemvendorid` CSR is a 32-bit read-only register providing the JEDEC manufacturer ID of the provider of the ACE unit (or 0 it is not commercial).

The `acemarchid` CSR is a 32-bit read-only register encoding the base microarchitecture of the ACE unit. Non-commercial IDs are allocated globally by RVI, while commercial IDs are specific to the acemvendorid`

The `acemimpid` CSR is a 32-bit read-only register that provides a unique encoding of the version of the ACE unit implementation. This register must be readable in any implementation, but a value of 0 can be returned to indicate that the field is not implemented. The Implementation value should reflect the design of the ACE unit itself and not any surrounding system.

These three CSRs, together, form the _Implementation Qualifier_ (see <<ACE-extra-content>>).

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acestart]]
===== `acestart`

{empty}
(((CSR, `acestart`)))
`acestart` is an alias for `vstart`. Therefore, it is an XLEN-bit RW CSR.
ACE defines it also when the V extension is not enabled.

`acestart` tracks the progress of resumable ACE instructions, such as `ace.load`, `ace.store`, `ace.input` and `ace.output`.

Progress tracking by `acestart` also applies to `ace.exec` when iteratively processing a multi-block operand, as `ace.exec` may be interrupted between blocks.
Only these instructions honor a nonzero `acestart`; all other instructions ignore it and are restarted, with `acestart` also being cleared.

Since ACE does not have an _intrinsic_ concept of element length, `acestart` counts the number of _bits_ processed so far nu `ace.exec`, not the number of elements, or read/written by `ace.input`/`ace.output` and `ace.prov`/`ace.import`/`ace.export` or `ace.store`/`ace.load`.

Hardware writes this register on interruption.
Software may save and restore the register across context switches.
For certain algorithms, writing zero to `acestart` to force a full restart of `ace.exec` may lead to inconsistent or unpredictable results.
Writing an invalid or non-supported nonzero value raises an illegal instruction exception.

When a vector instruction is interrupted, the CSR follows `vstart` semantics as expected, i.e., it counts the number of processed elements.
When an ACE instruction is interrupted, the CSR follows the `acestart` semantics described here.

[NOTE]
====
The reason `vstart` can be reused as `acestart` comes from the fact that the Risc-V ISA exposes a computation model in which the observable results are the same as if the instructions were executed in order.
If an implementation has executed instructions past the PC when an interrupt occurs, those instructions are discarded and must be re‑executed upon return from the handler. Only the instruction at the PC may be interrupted in a way that it saves temporary state that allows it to be resumed later.
There is no situation in which the microarchitecture of a hart can simultaneously interrupt multiple instructions allowing them to resume at the same time.
Hence, `vstart` can safely be reused by ACE as `acestart`.
====

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acemaxiobuflen]]
===== `acemaxiobuflen`

{empty}
(((CSR, `acemaxiobuflen`)))
`acemaxiobuflen` is an XLEN-bit RO CSR that reports the maximum configurable length of the ACEIOBUF.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuflen]]
===== `aceiobuflen`

{empty}
(((CSR, `aceiobuflen`)))
`aceiobuflen` is an XLEN-bit URW CSR that programs the ACEIOBUF length in bits for use by `ace.input` and `ace.output`.
Writing this register-even when re-writing the current value-also zeroes the buffer and sets `aceiobuftop` to the same length and `acestart` to zero.

When `aceiobuflen` is zero, the ACEIOBUF is _unconfigured_.
Attempting to execute an operation that expects an input or an output in the ACEIOBUF while the latter is unconfigured raises exception `ace_exc_buf_unconf`.

Writing a value larger than `acemaxiobuflen` raises exception `ace_exc_out_of_mem`.

[NOTE]
====
As per the Privileged Architecture, the dirtiness of the ACEIOBUF is not tracked except as part of the entire ACE state in `*status`.
Context switching code is expected to save and restore the contents of the ACEIOBUF up to `aceiobuflen`.
We recommend software to set `aceiobuflen` to zero once the contents of the ACEIOBUF are no longer needed.
Context switching code can use this information to avoid unnecessary save and restore of ACEIOBUF contents.
====

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-aceiobuftop]]
===== `aceiobuftop`

{empty}
(((CSR, `aceiobuftop`)))
`aceiobuftop` is an XLEN-bit URW CSR that marks the upper bound in bits of the buffer range used by `ace.input` and `ace.output`.
Together with `acestart`, it defines the active transfer window.

The constraints `acestart` {le} `aceiobuftop` {le} `aceiobuflen` must hold.
Violating either bound raises an illegal instruction exception.
Modifying `aceiobuftop` does not modify buffer contents.

NOTE: `aceiobuftop` enables per-operation length adjustments without the need to reconfigure the ACEIOBUF using `aceiobuflen`, which can be expensive due to the fact that it clears the buffer and may lead to internal garbage collection.
This can be used similarly to the reconfiguration of `VL*SEW` to provide an partial “last block” or to supply a short IV/nonce to cryptographic algorithms.

Using a alternative sequence for `ace.exec` or `ace.setst` for any Form with an input or output
when `aceiobuftop` − `acestart` is zero (and `aceiobuflen` nonzero) will result in no operation being performed.

Using ACEIOBUF when `aceiobuftop` − `acestart` is an invalid length raises an illegal instruction exception.

Since context switching code saves and restores the contents of the ACEIOBUF up to `aceiobuflen`, the contents between `aceiobuftop` and `aceiobuflen` are preserved.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-CSR-acenonce]]
===== `acenonce0` and `acenonce1`

{empty}
(((CSR, `acenonce`)))
`acenonce0` and `acenonce1` are XLEN-bit URW CSR that define the nonce to be used in `ace.import` and `ace.export` (see <<ACE-export-import-algorithms>>).
`acenonce0` contains bits [63:0] of the nonce, and `acenonce1` contains bits [95:64] of the nonce.
The most significant 32 bits of `acenonce1` are fixed to zero.

On RV32, 32-bit CSR `acenonce0h` shadows bits [63:32] of `acenonce0`, allowing these bits to be accessed.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instructions-detailed]]
=== Instructions

[WARNING]
====
The encodings presented here are preliminary.
====

ACE provides a number of unprivileged instructions.
This section specifies their semantics and encodings.

The notation `K{Xd}` denotes the CR whose index is held in GPR `Xd`.
`Kn|K{Xn}` indicates two alternative encodings: a 5-bit immediate CR index (`Kn`) or a CR number supplied by GPR `Xn`. Use of the zero register `X0` as a CR index register raises an illegal instruction exception unless explicitly indicated otherwise.

// NOTE: Trappability refers solely to the CPU-side implementation—for example, to enable decomposition of certain ACE instructions into smaller custom operations.
// This is distinct from custom algorithm implementations within the ACE unit itself (e.g., via a secure embedded CPU with updatable firmware), which are outside the scope of this specification.

[NOTE]
====
ACE does not have concepts similar to the vector crypto extension's Element Group Width (EGW), Effective Element Width (EEW), and Element Group Size (EGS).
Since the architecture decouples instructions like `ace.exec` from the actual operations, the high-level design of ACE needs only the total input and output size, denoted `ACELEN`. This is equal to either `VL * SEW` or the `aceiobuftop` length of the ACEIOBUF, as defined in <<ACE-notation>>.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-management-operations]]
==== Provisioning, Import, and Export

_This subsection is informative._

Broadly speaking, and removing error handling, *Provisioning* is performed by the following three steps:

. Use `ace.setst` (<<ACE-instruction-setst>>) to prepare a CR to be provisioned, check the validity of MDH[63:0] and load it in the CR.
. Use `ace.load` (<<ACE-instruction-load>>) to load the rest of the provisioning information into the CR.
. Use `ace.setst` to make the CR available to software.

*Importing* a SCC into a CR is similar:

. Use `ace.setst` to prepare a CR to accept a SCC, store MDH[63:0] in it, check its validity.
. Use `ace.load` to load the rest of the SCC information into the CR.
. Use `ace.setst` to authenticate and decrypt the SCC, and make the CR available to software.

*Exporting* a CR as an SCC consists of the following steps:

. Use `ace.getmdl` (<<ACE-instruction-getmd>>) to get MDH[63:0] of the CR to be exported to be able to determine its size and allocate resources.
. Store MDH[63:0] into memory.
. Use `ace.setst` to prepare a CR to produce a SCC. This includes encrypting its contents and computing the authentication tag(s).
. Use `ace.store` (<<ACE-instruction-store>>) to store MDH[127:64] and the rest of the SCC to memory.
. Use `ace.setst` to restore the CR in a form available to software.

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-load]]
==== ace.load

_Encoding_::
`ace.load` is an I-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x0b, attr: ['custom-0'] },
    { bits:  5, name: 'context', attr: ['Kd','K{Xd}'] },
    { bits:  3, name: 'ace.load', attr: ['0    0    0','0    0    1'] },
    { bits:  5, name: 'Xs1' },
    { bits: 12, name: 'immed12' },
]}
....

_Mnemonics_::
`ace.load{fournbsp}{nbsp}{nbsp}{nbsp}Kd|K{Xd}, %offset(Xs1)` +
`ace.sysimport{nbsp}Kd|K{Xd}, %offset(Xs1)`

_Description_::
+
--
`ace.load` imports a PI or a SCC into the CR `Kd` or `K{Xd}`, starting with the 8th byte of the MDH.
The memory address of the latter is given in `%offset(Xs1)`.

This instruction requires that the CR is ready to import information and that the first 8 bytes of the MDH have already been loaded by passing them as a parameter in a GPR (pair for RV32) to the `ace.setst` instruction used to open the CR for provisioning or import.

If the _ConfigStatus_ field equals _CfgStComplete_, an invalid instruction exception is raised.

`ace.load` can load data larger than the effective XLEN.
`acestart` tracks the number of loaded bytes. If `ace.load` is interrupted,
`acestart` contains the offset to the next byte to load upon resumption.

// NOTE: Modifying the CR being used by an interrupted `ace.load` always forces
// the load to restart. Software that aims to optimize this case must
// inspect `ConfigStatus` in each CR's metadata to detect an incomplete load
// and prevent the restart.

The implementation first determines the size of the input to be loaded from the first 8 bytes of the MDH.
The _ConfigStatus_ field determines the input type (PI or SCC), and
the fields _Algorithm_, _AlgorithmPolicy_, and _KeyType_ determine its length.
`ace.load` then requests the LSU to read the memory contents starting at `%offset(Xs1)`, in XLEN-bit sized loads,
and copies them into the CR starting with the 8th byte (i.e., bits [127:64] of the MDH).
The order in which the LSU issues these transactions is implementation dependent.
See <<ACE-resumability-management>>, <<ACE-resumability-memory-model>> and <<ACE-export-import-algorithms>> for further details.

When the key is in a system-defined format, the semantics of `ace.load`
are entirely implementation dependent and do not assume that the CR has been readied to import information or
that some metadata has already been loaded. System-defined format is signaled by the _SystemFormat_ bit of MDH[63:0], which in this case may have a system-defined length.

The instruction may possibly modify state.

The instruction is not usage-controlled.
--
+

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-store]]
==== ace.store

_Encoding_::
`ace.store` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 'ace.store', attr: [0x0,0x1] },
    { bits:  5, name: 'Xs1' },
    { bits:  5, name: 'context', attr: ['Ks2','K{Xs2}'] },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Mnemonic_::
`ace.store %offset(Xs1), Ks2|K{Xs2}`
(((ACE, instruction, ace.export)))

_Description_::
+
--
Exports raw data from the CR `Ks2` or `K{Xs2}`, starting with the 8th byte of the MDH, to memory at address `%offset(Xs1)`.

The first 8 bytes of the MDH must be read from the CR using `ace.getmdl` and saved to memory by the software.

`ace.store` can store data that may be larger than the effective XLEN.
`acestart` keeps track of the number of stored bytes. If `ace.store` is
interrupted, `acestart` contains the offset to the next byte to store upon
resumption.

NOTE: Modifying the CR being used by the interrupted `ace.store` always forces
the store to restart. Software that aims to optimize this case will have to
inspect `ConfigStatus` in the the metadata of each CR and detect if the store
hasn't completed to impede the restart.

If the _ConfigStatus_ field is equal to _CfgStComplete_, then an invalid instruction exception is raised.

If the _ConfigStatus_ field is not equal to _CfgStComplete_
the implementation first determines the size of the output to be generated from first 8 bytes of the MDH.
The type of the output, i.e. whether it is a PI or a SCC, is determined by the _ConfigStatus_ field, and
its length by _Algorithm_, _AlgorithmPolicy_, and _KeyType_.
Then, `ace.store` requests the LSU to store the CR to memory, beginning with the 8th byte (i.e. bits [127:64] of the MDH),
in XLEN-bit sized stores, in the memory region starting at address `%offset(Xs1)`.
The order in which the LSU issues these transactions is implementation dependent.
See <<ACE-resumability-management>>, <<ACE-resumability-memory-model>> and <<ACE-export-import-algorithms>> for further details.

NOTE: We allow to store a PI because it may be possible that a provisioning operation be interrupted, and this allows
resuming.

The instruction does not modify state.

The instruction is not usage-controlled.
--
+

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-exec]]
==== ace.exec

_Synopsis_::
Perform a cryptographic operation in the ACE unit.

_Mnemonic_::
+
--
The `ace.exec` instruction admits four Forms, namely
(((ACE, instruction, ace.exec)))

[upperalpha]
. `ace.exec  Vd, Kn|K{Xn}, Vs2` {nbsp} takes an input vector and writes to an output vector.
. `ace.exec  {fournbsp} Kn|K{Xn}, Vs2` {nbsp} takes an input vector but does not write to an output vector.
. `ace.exec  Vd, Kn|K{Xn} {fournbsp}{nbsp}` {nbsp} does not take an input but writes to an output vector.
. `ace.exec  {fournbsp} Kn|K{Xn} {fournbsp}{nbsp}` {nbsp} does not take an input vector and does not write to an output vector.
--

_Encoding_::
`ace.exec` is an R-type instruction.
+
--
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'rd', attr: ['Vd','—','Vd','—'] },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Ks1|K{Xs1}'] },
    { bits:  5, name: 'rs2', attr: ['Vs2','Vs2','—','—'] },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x0 },
    { bits:  2, name: 'Form', attr: ['0    0','0    1','1    0','1    1'] },
    { bits:  2, name: 0x0, attr: ['func2'] },
]}
....

Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an immediate, and it takes the value 1 if a GPR (scalar integer value) is used to
reference it.
For the four Forms A–D above, the encodings are:

[upperalpha]
. `Form` = `0b00`.
. `Form` = `0b01` and `rs1` = `0b00000`.
. `Form` = `0b10` and `rs2` = `0b00000`.
. `Form` = `0b11` and `rs2` = `rs1` = `0b00000`.

// To make indent in next line correct
--

_Description_::
+
--
Performs a cryptographic operation as defined by the algorithm in CR `Ks1` or `K{Xs1}`.
The instruction may take an input and produce an output.

If the V extension register file is not implemented, only Form D `ace.exec`
is supported and `ace.input`, `ace.output` are used to provide inputs and
extract outputs from `ace.exec`, as described in <<ACE-usage-input-output>>.

The instruction may possibly modify state.

The instruction is usage-controlled.
--

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv` (Forms A-D)    | v0.0.0          | --
| `Zlio` (Form D)      | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-move]]
==== `Zlmv`: ACE Move Instructions

The `Zlmv` adds dedicated move instructions from/to scalar/vector registers to
a CR. `Zlmv` is mutually exclusive with `Zlio` and `Zlm`. The extension adds
new forms to `ace.exec` and new behavior to `ace.setst`.

===== `ace.move`

The hart adds the following encodings to forms B and C of `ace.exec`:

[upperalpha]
. `Form` = `0b01` and `rs1` = `0b00001`. (Move to CR.)
. `Form` = `0b10` and `rs2` = `0b00001`. (Move from CR.)

In the `Form` = `0b10` and `rs2` = `0b00001`, `vl` elements in `Vs1` are moved
to CR starting at offset `acestart`. `acestart` is updated with `vl * (EEW/8) +
acestart`. The instruction is only valid if the `Ks`'s metada has
`ConfigStatus` set to `CfgStProvisioning` or `CfgStImporting`. Otherwise, an
illegal instruction exception is raised.

In the `Form` = `0b01` and `rs1` = `0b00001`, `vl` elements in CR at offset
`acestart` are moved to `Vs2`. `acestart` is updated with `vl * (EEW/8) +
acestart`. The instruction is only valid if the `Ks`'s metada has
`ConfigStatus` set to `CfgStExporting`. Otherwise, an illegal instruction
exception is raised.

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-setst]]
==== ace.setst

_Synopsis_::
Change the state of the algorithm encoded in the CC in a CR.

_Mnemonic_::
The `ace.setst` instruction admits three Forms, namely
(((ACE, instruction, ace.setst)))
+
[upperalpha]
. `ace.setst Kd|K{Xd}, #immed7{fournbsp}{nbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.setst Kd|K{Xd}, #immed7, Xs{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.setst Kd|K{Xd}, #immed7, Vs{nbsp}{nbsp}` with an auxiliary input in a vector register.

//

_Encoding_::
`ace.setst` is an R-type instruction.
+
--
[wavedrom, ,svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K{Xd}' },
    { bits:  3, name: 'ace.setst', attr: ['0    0    1','0    1    0','0    1    1'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'rs1', attr: ['—','Xs','Vs'] },
    { bits:  7, name: 'immed7' },
]}
....

The encodings of the three Forms are:
[upperalpha]
. `ace.setst` = `0b001`.
. `ace.setst` = `0b010`.
. `ace.setst` = `0b011`.
--

// ////////////////////////////////////////////////////////////////////

_Description_::
+
--
The instruction changes the _State_, _StateExtension_ and _ConfigStatus_ fields of the MDH of `Kd` or `K{Xd}`.

It is primarily used for three purposes:

[loweralpha]
. Advance from one stage of an algorithm to another (for instance, from initialization of a hash function to data absorption and then to digest finalization);
. Set specific state information of an algorithm (such as configure elliptic curve points or private/public keys);
. Initiate and complete provisioning or export/import operations

`#immed7` is a constant from a set of admissible values.
These values include both general values, which apply to all Algorithms, as well as values specific to the Algorithm encoded in a CR.

Certain state values may require an auxiliary input, which may be passed in a GPR `Xs` (a GPR pair in RV32)
or a vector (group) `Vs`. The vector (group) may be replaced by ACEIOBUF is `Zlio` is implemented.

Normally, `#immed7` contains the _State_ value to be set. In most cases, after the instruction has been issues, the _State_ field takes the value specified in `#immed7`.  Some states may transition to a different state automatically after completing `ace.setst`.

The allowed state transitions are described in <<ACE-State-field>> and in the algorithms.
Note that:

* It is allowed to issue `ace.setst` instructions to the current state.
When the algorithm needs to prevent this, it will automatically transition to a different state after completing `ace.setst`.
* If `#immed7` is zero, i.e., the value corresponding to the _Off_ state, the CR is cleared.
* It is always allowed to use an Error State (see <<ACE-states-error>>) for `#immed7`.
This will also invalidate the contents of the CR.  This may trigger a partial or full release of the resources used by the CR.
* Setting an Error State does _not_ trigger an exception, even if reaching that state implicitly would normally do.
Further usage of the same CR–for instance, a later `ace.exec` or `ace.state` to a valid state–will raise exceptions in that case.

Certain values of `#immed7`, depending on the Algorithm, may be used to set change _StateExtension_ instead, so that it can be used as state information that is somewhat orthogonal to the _State_ field.

When used to affect a CR's _ConfigStatus_, `ace.setst` is _not_ considered an usage instruction because it is part of a configuration operation. It is therefore not subject to the limitations on usage instructions, and it will not cause the CR to enter any Error State, including _Expired_.

The special values of `#immed7` to initiate a provisioning, importing, and exporting process, and conclude it afterwards, are listed in the following table:

[[ACE-management-immeds]]
.Values (decimal) of `#immed7` to be used for provisioning, importing, and exporting
[float="center",align="center",width="100%",cols="^7%,<28%,<65%",options="header"]
|===
| Value | Mnemonic                  |  Description
|  96   | `ace_CR_provision_start`  |  Prepare a CR for provisioning keys and metadata into it, set _ConfigStatus_ to _CfgStProvisioning_. Needs an auxiliary input in a GPR (or a GPR pair) with bits [63:0] of MDH.
|  97   | `ace_CR_provision_end`    |  Make the provisioned CR available to software  (“sealing”), set _ConfigStatus_ to _CfgStComplete_. Requires no auxiliary input.
|  98   | `ace_CR_import_start`     |  Prepare a CR for importing a SCC into it, set _ConfigStatus_ to _CfgStimporting_. Needs an auxiliary input in a GPR (or a GPR pair) with bits [63:0] of MDH.
|  99   | `ace_CR_import_end`       |  Decrypt and authenticate the imported SCC, make the CR available to software, set _ConfigStatus_ to a provided value.
| 100   | `ace_CR_export_start`     |  Prepare a CR for exporting it as a SCC (if not yet in the correct format), set _ConfigStatus_ to _CfgExporting_. Requires no auxiliary input.
| 101   | `ace_CR_export_end`       |  Restore the exported CR in the internal clear format (only if already complete) and make it available to software, set _ConfigStatus_ to a provided value. Uses an auxiliary input in a GPR (or a GPR pair) with bits [63:0] of MDH to restore _ConfigStatus_ saved by software.
If the restored value of _ConfigStatus_ is not _CfgStComplete_, the CR is made available to software.
|===

If `ace.setst` is used with one of the immediates in <<ACE-management-immeds>>, the operation has special semantics:

. *`ace.setst` is used to start provisioning, resp., import.*
+
Before issuing `ace.setst`, software must read Bits [63:0] of the MDH from memory first.
Let `ml` be this value.
Software must pass `ml` as the auxiliary input to `ace.setst` in a GPR (or a GPR pair).
+
`ace.setst` then performs following operations:

.. The target CR is cleared.
.. If the combination of _Algorithm_, _AlgorithmPolicy_, and _SCProtection_ in `ml` is not supported, the CR transitions to Error State `ace_state_not_impl`, and exception `ace_exc_invalid` is raised as defined in the Privileged Architecture if the latter is implemented.
.. In other cases here where the Metadata is invalid, such as, for instance, a nonzero _State_ or reserved field: the CR transitions to Error State `ace_state_invalid`, and exception `ace_exc_invalid` is raised as defined in the Privileged Architecture if the latter is implemented.
.. The implementations will try to allocate CRF capacity according to the requirements of the _Algorithm_, _AlgorithmPolicy_, and _SCProtection_ fields of the MDH. No other field shall affect the amount of capacity required.  If capacity allocation is not possible, the CR is transitioned to Error State `ace_state_out_of_mem`, and exception `ace_exc_out_of_mem` is raised as defined in the Privileged Architecture if the latter is implemented.
.. Except for Bits [63:0] of the MDH in the CR, which are set to `ml`, the internal CRF memory corresponding to the target CR is zeroed.
.. _ConfigStatus_ if set to _CfgStProvisioning_, resp., _CfgStace_CR_import_. In the latter case, we assume that software has saved the old value of `ml` in its state.

. *`ace.setst` is used to terminate a provisioning process.*

.. The ACE unit performs any necessary readjustment of the CR's content to turn it into the format internally consumed by the ACE Unit.
..  _ConfigStatus_ is set to _CfgStComplete_.

. *`ace.setst` is used to terminate an import process.*
+
The software must use Form B of `ace.setst` to contextually pass the saved value of `ml`.

.. If `ml`._ConfigStatus_ = _CfgStComplete_ (we are importing the export of a fully configured CR)
... The ACE unit decrypts and authenticates the CR's content.
... If authentication fails, the target CR is transitioned to Error State `ace_state_ace_CR_import_auth`. No exception is raised.
... The ACE unit performs any necessary readjustment of the CR's content to turn it into the format internally consumed by the ACE Unit.
...  _ConfigStatus_ is set to _CfgStComplete_.
.. If `ml`._ConfigStatus_ {ne} _CfgStComplete_  (we are either importing the export of a not fully configured CR or a nested CR export):
+
_ConfigStatus_ is set to `ml`._ConfigStatus_.

. *`ace.setst` is used to start an export process.*
+
Let `ml` <- Bits [63:0] of the MDH of the CR.
Software must save this value in its state to use it when terminating the export process.
+
Then:

.. If `ml`._ConfigStatus_ = _CfgStComplete_:
+
Prepare a CR to produce a SCC. This includes encrypting its contents and computing the authentication tag(s).
.. If `ml`._ConfigStatus_ {ne} _CfgStComplete_ (we are exporting a not fully configured CR or we are initiating a nested CR export):
+
No encryption or authentication occurs, the information in the CR is exported verbatim, in the same order as they appear in the PI in case the SCC is the export of a partially provisioned CR, or the SCC in case the latter is the export of a partially provisioned, resp., imported, CR, or the CR was previously prepared for export and then the export process itself was interrupted.

. *`ace.setst` is used to terminate an export process.*
+
Let `ml` be the value of MDH[63:0] saved by the software upon initiation of the export process.
Software must pass `ml` as the auxiliary parameter to `ace.setst` for export termination.
+
Then:

.. If `ml`._ConfigStatus_ = _CfgStComplete_:
+
The implementation must restore the state of the CR to the state it was in when the export process was initiated.
This may involve decrypting its contents or restoring them from an internal backup.

.. If `ml`._ConfigStatus_ {ne} _CfgStComplete_:
+
No changes to the CR state are made.

Whenever `ace.setst`, used as a configuration instruction, fails for any other reason, the target CR is cleared.

The full provisioning, export, and import operations are described in detail in <<ACE-export-import-algorithms>>.

The instruction may possibly modify state.

The instruction is usage-controlled when used to transition states.
The instruction is not usage-controlled when used to initiate and terminate management processes.
--
+

(`Zlmv` only) When a CR's metadata `ConfigStatus` field is changed from `CfgStImporting` to `CfgStComplete`, the ACE unit verifies the signature of the CR's contents.

(`Zlmv` only) When a CR's metadata `ConfigStatus` field is changed from `CfgStComplete` to `CfgStExporting`, the ACE unit generates the SCC.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
| Extension | Minimum version | Lifecycle state
| `Zlv`     | v0.0.0          | --
| `Zlio`    | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getmd]]
==== ace.getmdl/ace.getmdh

_Synopsis_::
Export the MDH of a CR.

_Mnemonic_::
`ace.getmdl Xd, Ks|K{Xs}` +
`ace.getmdh Xd, Ks|K{Xs}`
(((ACE, instruction, ace.getmd)))

_Encoding_::
+
--
`ace.getmd{l,h}` is an R-type instruction and its encoding shares opcode and `func3` with `ace.exec`, but `func2` is set to `0b11`.

[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'rs1', attr: ['Ks|K{Xs}'] },
    { bits:  5, name: 0x00  },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  2, name: 0x0 },
    { bits:  1, name: 'h' },
    { bits:  2, name: 0x3, attr: ['func2'] },
]}
....

Bit `r` (bit 26) is 0 when the context is an immediate and 1 when it is held in a GPR (scalar integer).

If bit `h` (bit 29) is 0, the instruction is `ace.getmdl`; if `h` is 1, it is `ace.getmdh`.
--

_Description_::
+
--
On RV64:

* `ace.getmdl` copies bits [63:0] of the MDH of CR `Ks` or `K{Xs}` into GPR `Xd`.
* `ace.getmdh` bits [127:64] into GPR `Xd`.

On RV32, `d` must be even, and:

* `ace.getmdl` copies bits  [31:0] of the MDH of CR `Ks` or `K{Xs}` into GPR `Xd` and bits  [63:32] of the same CR into GPR `X[d+1]`, atomically.
* `ace.getmdh` copies bits [95:64] of the MDH of CR `Ks` or `K{Xs}` into GPR `Xd` and bits [127:96] of the same CR into GPR `X[d+1]`, atomically.

The instruction may not modify state.

The instruction is not usage-controlled.
--
+

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-restrict]]
==== ace.restrictl/ace.restricth

_Synopsis_::
Restrict the policies encoded in a CC in a CR.

_Mnemonic_::
`ace.restrictl{nbsp}{nbsp}Kd|K{Xd}, Xs1` +
`ace.restricth{nbsp}{nbsp}Kd|K{Xd}, Xs1`
(((ACE, instruction, ace.restrict)))

_Encoding_::
+
--
`ace.restrict` is an R-type instruction.
The encoding shares opcode and `func3` with `ace.exec`, but `func2` (i.e., the two msbs of `func7`) is `0b01`.
The source register field encodes a GPR and not a vector register.
If bit `h` (bit 29) is 0, the instruction is `ace.restrictl`; if `h` is 1, it is `ace.restricth`.

[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K{Xd}' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 'Xs1' },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  2, name: 0x0 },
    { bits:  1, name: 'h' },
    { bits:  2, name: 0x1, attr: ['func2'] },
]}
....

Bit `r` (i.e., bit 26) takes the value 0 if the context is encoded as an immediate in Bits [11:7], and it takes the value 1 if a GPR (also encoded in [11:7]) is used to reference it.
--

// comment

_Description_::
+
--
`ace.restrictl/ace.restricth` can only be used if the CR's state is _Initial_.
Using the instruction in any other state raises an invalid instruction exception.

`ace.restrictl` modifies the field _AlgorithmPolicy_ in bits [63:0] of the MDH of the CR.

`ace.restricth` modifies fields _Locality_, _UsagePolicy_, _ExpirationDate_, and possibly _AlgorithmUse_ in bits [127:64] of the MDH of the CR.

Modifying the _Locality_ field can be used to add a Locality but also to _replace_ a Locality with a stricter one, such as

 * _SiPScrt_ {rightarrow} _ChipFamScrt_, _ChipScrt_; _ChipFamScrt_ {rightarrow} _ChipScrt_;
 * _OEMScrt_ {rightarrow} _ProdScrt_, _DevScrt_; _ProdScrt_ {rightarrow} _DevScrt_.
 * _MLocality_ {rightarrow} _HLocality_, _SLocality_; and _HLocality_ {rightarrow} _SLocality_.

Generalizing Localities is not permitted: Attempting to do so raises exception `ace_exc_invalid`, but the
State is not automatically set to _ace_state_invalid_ (the exception handler may of course do that).

Once the _Locality_ field has been modified,
when the CR is exported, it will use the new Locality values to tweak the export algorithm.

Let `MDH` be the MDH of the CC in the destination CR.

On RV64, the semantics of the instructions are:

* For `ace.restrictl`, `Xs` follows the format of bits [63:0] of the MDH,
and for `ace.restricth`,  `Xs` follows the format of bits [127:64] of the MDH.
+
Only the fields _AlgorithmPolicy_, _Locality_, _UsagePolicy_, _ExpirationDate_ and _AlgorithmUse_ of `Xs` may be defined.
All other fields must be 0, else exception `ace_exc_invalid` is raised.

* `Xs`._AlgorithmPolicy_ is used to set the value of `MDH`._AlgorithmPolicy_ of the CR.

** If the algorithm configured in the CR does not make use of the field `Xs`._AlgorithmPolicy_, then `Xs`._AlgorithmPolicy_ must be zero,
else exception `ace_exc_invalid` is raised.

** If `Xs`._AlgorithmPolicy_ is used to encode an extension of `Xs`._Algorithm_, then `Xs`._AlgorithmPolicy_ must be zero, else exception `ace_exc_invalid` is raised.

** No currently disabled operation may be (re)enabled.  Any attempt to do so raises
  exception `ace_exc_invalid`. In some cases, a zero value is not permitted, such as
  disabling both encryption and decryption.

** If the CR's current state is _only_ allowed while performing an operation currently
  permitted by `MDH`._AlgorithmPolicy_, a change to _AlgorithmPolicy_ that would
  disable that operation is still possible.
  However, this change will cause exception `ace_exc_invalid` to be raised at the
  next usage operation on the CR.

* If `Xs`._Locality_ is non-zero, then it is the new value of `MDH`._Locality_, subject to the Locality replacement rules above.

* A zero in any of bits `Xs`._UsagePolicy_ means that the corresponding policy is _not_ changed.

* A one in any of the bits `Xs`._UsagePolicy_ means that usage by the corresponding mode is not allowed, and the corresponding bit in the Metadata of the destination CC is set to 1.

* If `Xs`._ExpirationDate_ is zero, the corresponding policy in `MDH`._ExpirationDate_ is _not_ changed.

* A non-zero value in `Xs`._ExpirationDate_ will be copied to
  `MDH`._ExpirationDate_, but only if that policy was not already programmed before
  or the original value of `MDH`._ExpirationDate_ was equal to the new value or larger.
  Otherwise exception `ace_exc_invalid` is raised.

* Any change to `MDH`._AlgorithmUse_ is subject to policies set by the Algorithm in the CR.

On RV32, the only difference is:

* `s` must be even, the register pair `X[s]` and `X[s+1]` is read atomically, and
  `(X[s+1] @ X[s])` replaces `Xs` in the RV64 description.

The instruction may possibly modify state.

The instruction is usage-controlled.
--

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[NOTE]
====
This instruction enables several practical use cases:

*   Enabling side-channel protection when supported by the microarchitecture,
    even if the original CC was not configured with it.
*   Allowing privileged code to give a CC to several processes in a
    fine-grained manner. This can be achieved by cloning the CR and customizing
    the Localities for each clone.
*   Similarly, enabling privileged code to split a CC capable of both
    encryption and decryption into two CCs, one only capable of encryption and
    the other only capable of decryption, thereby creating a one-way channel
    between processes.

The ability to perform such customizations saves both time and computational
resources by avoiding additional round-trips to trusted environments.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clone]]
==== ace.clone

_Synopsis_::
Copy a CR into another CR.

_Mnemonic_::
`ace.clone Kd|K{Xd}, Ks|K{Xs}`
(((ACE, instruction, ace.clone)))

_Encoding_::
The encoding shares opcode and `func3` with `ace.exec`, however `func2` is 2.
The instruction is thus an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K{Xd}' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks|K{Xs}' },
    { bits:  5, name: 0x0 },
    { bits:  2, name: 'R' },
    { bits:  3, name: 0x0 },
    { bits:  2, name: 0x2, attr: ['func2'] },
]}
....
+
Bits [26:25], i.e., field `R`, take the following values depending on how the
CRs are given:
+
[upperalpha]
. `00`{nbsp}{nbsp} if the source and the output CRs are both encoded as
  immediate values.
. `01`{nbsp}{nbsp} if the source CR is encoded as immediate and the output CR
  is selected using a GPR.
. `10`{nbsp}{nbsp} if the source CR is selected using a GPR and the output CR
  is encoded as an immediate value.
. `11`{nbsp}{nbsp} if the source and the output CRs are both selected using the
  values of GPRs.

// Comment to ensure proper indentation in the next Description

_Description_::
Clones source CR `Ks` (or the CR indexed by `Xs`) into destination CR `Kd` (or the CR indexed by `Xd`).
+
A CR whose _ConfigStatus_ is not _CfgStComplete_ cannot be cloned.
+
The instruction may possibly modify state.
+
The instruction is not usage-controlled.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

// //

[[ACE-instruction-derive]]
==== ace.derive

[NOTE]
====
This instruction is not yet used by any algorithm. The encoding is reserved for future use.
====

_Synopsis_::
Derive a CR from a source CR, such as a key derivation.

_Mnemonic_::
The `ace.derive` instruction admits three Forms, namely
(((ACE, instruction, ace.derive)))
[upperalpha]
. `ace.derive Kd|K{Xd}, Ks1|K{Xs1} {fournbsp}{nbsp}{nbsp}{nbsp}` with no auxiliary input.
. `ace.derive Kd|K{Xd}, Ks1|K{Xs1}, Xs2{nbsp}{nbsp}` with an auxiliary input in a GPR.
. `ace.derive Kd|K{Xd}, Ks1|K{Xs1}, Vs2{nbsp}{nbsp}` with an auxiliary input in a vector register.

_Encoding_::
The encoding differs from `ace.clone` in that bit 27 is set to 1.
The instruction is thus an R-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Kd|K{Xd}' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks1|K{Xs1}' },
    { bits:  5, name: 'Xs2|Vs2' },
    { bits:  2, name: 'R' },
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'Form' },
    { bits:  2, name: 0x2, attr: ['func2'] },
]}
....
+
Bits [26:25], i.e., field `R`, are encoded exactly as for `ace.clone` (<<ACE-instruction-clone>>).
+
Bits [29:28], i.e., field `Form`, deals with the optional auxiliary input:
+
[upperalpha]
. `00`{nbsp}{nbsp} the instruction admits no auxiliary input.
. `01`{nbsp}{nbsp} the instruction accepts an auxiliary input in a GPR.
. `10`{nbsp}{nbsp} the instruction accepts an auxiliary input in a vector register.
. `11`{nbsp}{nbsp} is reserved for future use.

_Description_::
+
--
Derive a new context from an existing one, with its own opaque key material, for instance using a key derivation mechanism.
The behavior of the instruction is not expected to be deterministic.
It can be used multiple times, to generate multiple derived contexts.

The instruction may possibly modify state.

The instruction is usage-controlled.
--
+

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// //

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-size]]
==== ace.size

_Synopsis_::
Return the size of a PI or SCC in bytes, or zero in case of error.

_Mnemonics_::
There are two Forms of the `ace.size` instruction:
(((ACE, instruction, ace.size)))

[upperalpha]
. `ace.size Xd, Ks|K{Xs}` - Size from a context.
. `ace.size Xd, Xs` - Size from MDH.

// Without this comment, the next part is not properly formatted...

_Encoding_::
+
--
The encoding shares opcode, `func3`, and `func2` (the two msbs of `func7`) with `ace.exec`, but with bit 27 equal to 1.

[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x5b, attr: ['custom-2'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x0, attr: ['ace.exec'] },
    { bits:  5, name: 'Ks/K{Xs}/Xs' },
    { bits:  5, name: 0x0 },
    { bits:  1, name: 0x0 },
    { bits:  1, name: 'r' },
    { bits:  1, name: 0x1 },
    { bits:  2, name: 'F' },
    { bits:  2, name: 0x0, attr: ['func2'] },
]}
....

The `F` field and the `r` bit may assume the following values:

* `F` = `0b00`, `r` = `0` {implies} Form A: Size from a context given as `Ks`.
* `F` = `0b00`, `r` = `1` {implies} Form A: Size from a context given indirectly as `K{Xs}`.
* `F` = `0b01`, `r` = `0` {implies} Form B: Size from MDH.
--

_Description_:: {empty}
+
--
* Form A `ace.size` returns the total size in bytes of the memory buffer that
  would be necessary to store the exported SCC, including the authentication tag(s) and the additional variable-length data.
  Knowing this size is necessary
  for any feature that relies on `ace.export`, including context switching. The
  instruction returns 0 if the CR is unconfigured.

* On RV64, Form B `ace.size` returns the total size in bytes of an SCC having Bits [63:0]
  of the MDH given in `Xs` into GPR `Xd` including the additional variable-length data,
  and `0` if the if the algorithm is not supported or the Metadata is otherwise invalid.

* On RV32, Form B `ace.size` differs from the RV64 version in that `s` must be even, and
  Bits [63:0] of the MDH are passed in `X[s+1] @ Xs`,

The instruction may not modify state.

The instruction is not usage-controlled.
--
+

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-input]]
==== ace.input

_Synopsis_::
Load data into the ACEIOBUF.

_Mnemonic_::
`ace.input %offset(Xs), Xl`
(((ACE, instruction, ace.input)))

_Encoding_::
`ace.input` is an S-type instruction.
+
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'immed[4:0]' },
    { bits:  3, name: 0x2, attr: ['ace.input'] },
    { bits:  5, name: 'Xl' },
    { bits:  5, name: 'Xs' },
    { bits:  7, name: 'immed[11:5]' },
]}
....

_Description_::
+
--
If the vector registers are not sufficiently long, or not implemented, inputs can be read directly from memory and outputs written directly to memory.
For this reason, the architecture defines `ace.input` and `ace.output` (cf. next section).
`ace.input` loads `Xl` bytes from memory starting at address `%offset(Xs)` and copies them to the ACEIOBUF, starting at offset `acestart`.

If `Xl` = 0, the operation does nothing.

If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.

The intended usage of `ace.input` and `ace.output` is explained in detail in
<<ACE-usage-input-output>>.

`ace.input` may be used only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero.
Otherwise, exception `ace_exc_buf_unconf` is raised.

The instruction may possibly modify state.

The instruction is not usage-controlled.
--
+

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-output]]
==== ace.output

_Synopsis_::
Save the contents of the ACEIOBUF to memory.

_Mnemonic_::
`ace.output %offset(Xd), Xl`
(((ACE, instruction, ace.output)))

_Encoding_::
+
--
`ace.output` is an I-type instruction.

[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0x27, attr: ['custom-1'] },
    { bits:  5, name: 'Xd' },
    { bits:  3, name: 0x3, attr: ['ace.output'] },
    { bits:  5, name: 'Xl' },
    { bits: 12, name: 'immed' },
]}
....
--

_Description_:: {empty}
+
--
This is the output operation corresponding to `ace.input`.
`ace.output` writes the contents of the input buffer, starting at offset `acestart`, to memory starting at address `%offset(Xs)`.

If `Xl` = 0, the operation does nothing.

If `Xl` is greater than `aceiobuftop` - `acestart`, exception `ace_exc_invalid` is raised.

`ace.output` may be used only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero.
Otherwise, exception `ace_exc_buf_unconf` is raised.

The instruction may possibly modify state.

The instruction is not usage-controlled.
--

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-pseudo-instructions-detailed]]
=== Pseudo-Instructions

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-clear]]
==== ace.clear/ace.reset

_Synopsis_::
Clears and unconfigures a CR, or the ACE state.

_Mnemonic_::
`ace.clear Kd|K{Xd}` +
(((ACE, instruction, ace.clear)))
`ace.reset`
(((ACE, instruction, ace.reset)))

_Encoding_::
Pseudo-instructions `ace.clear`/`ace.reset` are implemented as `ace.setst` (see <<ACE-instruction-setst>>) with no auxiliary operands and the immediate for _State_ set to `ace_state_off` (as defined in <<ACE-State-field>>).

_Description_::
+
--
`ace.clear` unconfigures the state of the CR `Kd` or `K{Xd}` and releases its resources in the CRF.

`ace.reset` unconfigures all the CRs and the ACEIOBUF.
It uses the encoding of `ace.setst` described above with indirect CR addressing and `Xd` = `X0`.

Clearing an _Off_ CR does not change dirtiness flags.

The instruction is not usage-controlled.
--
+

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-getst]]
==== ace.getst

_Synopsis_::
Returns the _State_ field of the metadata of the source CR.
This is useful to determine whether a CR is in an Error State, as defined in <<ACE-State-field>>.

_Mnemonic_::
`ace.getst Xd, Ks|K{Xs}`
(((ACE, instruction, ace.getst)))

_Encoding_::
The operations is a pseudo-instruction.

_Description_::
`ace.getst` is implemented as a read of the source CR's metadata using `ace.getmdl`
followed by instructions to extract the _State_ field of the latter.
For instance, on RV64, we can use:

 . `ace.getmdl Xd, Ks` or `K{Xs}`
 . `srli  Xd, Xd, 20`
 . `andi  Xd, Xd, 0x1F`

//

// ////////////////////////////////////////////////////////////////////

[[ACE-instruction-available]]
==== ace.avail

_Synopsis_::
Verify whether an algorithm is supported, or the first 64 bits of a metadata block are valid.

_Mnemonic_::
`ace.avail Xd, Xs`
(((ACE, instruction, ace.avail)))

_Encoding_::
`ace.avail` is an alias to Form B of `ace.size`, as the latter returns 0 in case of error.

_Included in_::
+
--
[%header,cols="4,2,2"]
|===
|Extension | Minimum version | Lifecycle state
| `Zlv`    | v0.0.0          | --
| `Zlio`   | v0.0.0          | --
|===
--

// ////////////////////////////////////////////////////////////////////

[[ACE-usage-input-output]]
=== Using ace.input and  ace.output to Replace Vector Inputs and Outputs

When `Zlio` is available, some instructions that access vector inputs and outputs may be replaced by instruction sequences without vector inputs and outputs as described in <<ACE-replacement-instructions>>.

[[ACE-replacement-instructions]]
.Alternative sequences for `ace.exec`, `ace.setst`, and ```ace.derive``` using `ace.input` and `ace.output`
[float="center",align="center",width="100%",cols="<20%,<41%,<39%",options="header"]
|===
| Instruction and Form | Original Instruction          | Alternative Sequence
| `ace.exec`, Form A   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K{Xn}, Vs` | `1: ace.input{nbsp}{nbsp}Xl, %offset(Xs)` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K{Xn}` +
`3: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.exec`, Form B   | `ace.exec{fournbsp}{nbsp}{nbsp}{nbsp}Kn\|K{Xn}, Vs`     | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K{Xn}` +
| `ace.exec`, Form C   | `ace.exec{nbsp}{nbsp}Vd, Kn\|K{Xn}`     | `1: ace.exec{nbsp}{nbsp}{nbsp}Kn\|K{Xn}` +
`2: ace.output{nbsp}%offset(Xd),  Xl` +
| `ace.setst`, Form C  | `ace.setst{nbsp}Kd\|K{Xd}, #immed, Vs` | `1: ace.input{nbsp}{nbsp}%offset(Xs), Xl` +
`2: ace.setst{nbsp}{nbsp}Kd\|K{Xd}, #immed` +
| `ace.derive`, Form C | `ace.derive Kd\|K{Xd}, Ks1\|K{Xs1}, Vs2` | `1: ace.input{nbsp}{nbsp}%offset(Xs2), Xl` +
`2: ace.derive{nbsp}Kd\|K{Xd}, Ks1\|K{Xs1}` +
|===

The sole functions of `ace.input` and `ace.output` are to supply inputs to cryptographic operations and to read out their outputs. No computation is performed on the data by these instructions. All computations and internal state changes of `ace.exec`, `ace.setst`, and `ace.derive` remain within those operations.

The usage and ordering of the alternative sequences are not enforced architecturally.
Thus, the caller may omit `ace.input` or `ace.output`, meaning that the contents of the ACEIOBUF are reused, or the output is ignored.
This does not expand the attack surface, since the caller always retains full control over the data passed to ACE instructions and their outputs.
Instead, the ACE architecture defines the following rules:

. A Form D `ace.exec` can be used whenever a Form of `ace.exec` with an input and/or an output is instead expected, i.e., any of the Forms A, B, or C `ace.exec`. The implementation shall automatically use the ACEIOBUF if `Zlio` is available, and raise an invalid instruction exception otherwise.

. A Form A `ace.exec` cannot be replaced by a Form B `ace.exec`, where the input is provided by a vector register but an output vector register is not defined, expecting that the output be written to the ACEIOBUF.
Any attempt to do so raises an invalid instruction exception

. A Form A `ace.exec` cannot be replaced by a Form C `ace.exec`, where the output is provided by a vector register but an input vector register is not defined, expecting that the input be read from the ACEIOBUF.
Any attempt to do so raises an invalid instruction exception

. Similarly, for `ace.setst`, if a vector input is expected (Form C `ace.setst`) and it is not provided, the implementation shall automatically use the ACEIOBUF if `Zlio` is available, and raise an invalid instruction exception otherwise. This instruction replacement is not allowed in the case of a Form B `ace.setst`, i.e., when the auxiliary input should come from a GPR, and an invalid instruction exception is raised regardless of whether `Zlio` is available.

. A Form A `ace.derive` can be used whenever a Form C `ace.derive` is expected. The implementation shall automatically use the ACEIOBUF if `Zlio` is available, and raise an invalid instruction exception otherwise.

. Form D `ace.exec` in place of its Forms A-C, Form A `ace.setst` in place of its Form C, and Form A `ace.derive` in place of its Form C
may be issued only if the ACEIOBUF is enabled and `aceiobuflen` is non-zero. Else, exception `ace_exc_buf_unconf` is raised. If `aceiobuflen` is non-zero but the range size `aceiobuftop - acestart` is invalid for the algorithm, exception `ace_exc_invalid` is raised and no cryptographic operation is performed.

NOTE: It is because of these rules that, in the Algorithms, we write that a certain Form of `ace.exec` or `ace.setst` is _expected_ instead of _required_ (or _only [...] allowed_). The above substitutions are implicit in all algorithms and are not restated for each occurrence.

// ////////////////////////////////////////////////////////////////////

[[ACE-resumability]]
=== Interruptibility and Resumability of ACE instructions

`ace.clear`, `ace.reset`, `ace.setst`, `ace.getst`, `ace.restrict`, `ace.clone`, `ace.size` and `ace.avail` are uninterruptible.

Long-running ACE operations may proceed even if the hart is preempted.
In this case, when the context‑switch handler accesses an output of the operation register, different behaviors are allowed:

. The hart may wait for the operation to finish;
. the implementation may adopt a precise exception model, whereby the ACE unit is halted and sets a value in a CSR called `acestart` to allow later resumption;
or
. the system may impose a timeout before halting.

The architecture permits all these approaches: It only specifies the allowed interruption points for its instructions and algorithms.

`ace.input`, `ace.output`, `ace.load` and `ace.store` may be interrupted and resumed.
`acestart` reflects the amount of data read or written before the interrupt.
In this case resumption will start from that point.

The operation of `ace.exec` on a basic processing unit as defined in the algorithm it is performing is uninterruptible, unless explicitly allowed by the algorithm.
Most cryptographic primitives cannot be interrupted; therefore, state information to encode the round number or a round key value is not needed.
For certain very long running operations, such as public key primitives, an algorithm specific interruptibility and resumability behavior is defined.

When processing multiple basic processing unit iteratively, `ace.exec` handles each block atomically, but it may be interrupted between blocks.
On an interrupt during block processing, the implementation may either complete the current block before yielding to the handler, or discard the partial computation and restore the state from before its processing.
`acestart` is updated accordingly to point at the place of resumption, valid values are multiples of the length of the basic processing unit, with the only possible exceptions defined by the algorithm.

While handlers can set `acestart` to zero to force a restart of an `ace.exec` operation, this may lead to unpredictable behavior when the input and output overlap.

[[ACE-resumability-management]]
==== Management Operations

_This section is informative and non-normative._

The rules defined in `ace.setst` for the initiation and termination of management operations are necessary because any management operation may be interrupted, and there may be multiple nested interrupts or exceptions, with or without context switches.
Leaving the burden of saving and restoring _ConfigStatus_ to the interrupted software simplifies the logic and supports arbitrarily many levels of nested virtualization.

These rules also imply that an interrupted import operation may be resumed on a hart attached to a different ACE Unit implementation.
The architecture is designed to ensure interoperability, provided the importing implementation supports the algorithm encoded in the SCC.
However, the implementation must handle cases where the SCC is too large to fit in a CR due to an optional Implementation VDS—or where that VDS is incompatible—by ignoring the optional data.  A different set of optional data mey be created by the importing implementation.  In these cases, _ImpDataLen_ is accordingly updated.

Software must ensure that an interrupted configuration or export operation can be resumed, to support binary compatibility across implementations that provide this feature and implementations that do not.
An implementation is not required to support resumption, and even those that do may ignore the `acestart` value and restart the interrupted operation for any reason.

For this reason, we define specific instruction sequences for the management operations, cf <<ACE-management-code-snippets>>.
The architecture is co-designed with the intended use of the instructions.

A context switch handler can force a restart by clearing partially configured or exported CRs at context save and again at context restore.
This must also be handled by the software.

[[ACE-resumability-memory-model]]
==== Resumption and Memory Model

[WARNING]
====
To be discussed with ARC. We would like to know whether instructions issuing long loads or stores can prescribe whether they can access the memory in a prescribed order, i.e., the ACE unit can send to the LSU sequences of reads or writes in ascending memory address order, as if these were separate instructions.
====

RISC-V implementations may read or write long inputs in an arbitrary order.
Enforcing a strict access ordering for ACE inputs and outputs would be complex on certain microarchitectures.

The ACE unit sends commands to the LSU to read and write memory sequentially—analogously to software looping over an array. The LSU may then issue those reads and writes in any order it chooses.

However, we need that the same code must work across all behaviors.

An implementation always has the option to restart an operation instead of resuming it, for any reason, and may ignore and clear `acestart`. The ACE instructions are designed so that the same instruction sequences work correctly in all such cases and on every ACE implementation.

For example, the instruction that loads or stores a CR's content starting with the 8th byte may always fail, leaving the CR in an _Off_ state. This signals that the import, provisioning, or export operation must be restarted. The software must then prepare the CR for the operation again. For import and provisioning, this entails providing the first 8 bytes of the MDH to the `ace.setst` instruction used to prepare the CR anew.

// ///////////////////////////////////////////////////////////////////

[[ACE-management-code-snippets]]
=== Code for CR Configuration and Export Operations

_Ths subsection is informative._

We show here how the architecture expects the entire configuration and export processes to be coded.

The code fragments presented here only include the main operation logic together with the detection of any error condition, not the actual error management, which would be platform specific.
While these code fragments are obviously much longer than monolithic instructions, they can be made into libraries or OS APIs, so they do not affect code size in any major way. The use of indirect CR addressing proves itself very useful in this case.

In these examples,
GPR `t6` points to the memory location where a PI or SCC is stored,
and GPR `t0` contains the number of the CR to be configured or exported.
The code also uses `t1`, `t2`, and `t3` for temporary storage.

*Provisioning Code*
----
  ld         t1, 0(t6)                  # load MDH bits [63:0] from memory
  li         t3, #23
restart:
  ace.setst  K{t0}, t1, #ace_CR_provision_start
                                        # start provisioning, load MDH[63:0] in CR
  ace.getst  t2, K{t0}                  # get _State_ field from MDH[63:0]
  bltu       t3, t2, handle_errors      # errors (larger than 23, i.e. ≥ 24)
  beqz       t2, handle_errors          # handle error (is _Off_ needed?)
  ace.load   K{t0}, 8(t6)               # load rest of PI starting with MDH[127:64]
  ace.getst  t2, K{t0}                  # get _State_ field from MDH[63:0]
  li         t3, #ace_state_off         # compare to off state
  beq        t2, t3, restart            # CR cleared means force restart
  ace.setst  K{t0}, #ace_CR_provision_end   # terminate provisioning
                                        # and possibly reconstructs data
  ace.getst  t2, K{t0}                  # get _State_ field from MDH[63:0]
  bltu       t3, t2, handle_errors      # handle other errors (> 23, i.e. ≥ 24)
success:
----

*Import Code*
----
  ld         t1, 0(t6)                  # load MDH bits [63:0] from memory
  li         t3, #23
restart:
  ace.setst  K{t0}, t1, #ace_CR_import_start
                                        # prepare CR for import, load MDH[63:0] in it
  ace.getst  t2, K{t0}                  # get _State_ field from CR (after checks!)
  bltu       t3, t2, handle_errors      # errors (larger than 23, i.e., ≥ 24)
  ace.load   K{t0}, 8(t6)               # load all the rest starting with MDH[127:64]
  ace.getst  t2, K{t0}                  # get _State_ field from MDH[63:0]
  li         t3, #ace_state_off         # compare to off state
  beq        t2, t3, restart            # CR cleared means force restart
  ace.setst  K{t0}, #ace_CR_import_end  # decrypt/authenticate CR, possibly complete it
  ace.getst  t2, K{t0}                  # get _State_ field from MDH[63:0]
  bz         t2, handle_errors          # handle _Off_ state (needed ? double check)
  bltu       t3, t2, handle_errors      # handle other errors (> 23, i.e., ≥ 24)
success:
----

During the provisioning and import procedures, the validity of bits [63:0] of the metadata field is checked immediately.
The validity of bits [127:64] is deferred to sealing, which in the case of import includes authentication.
If these bits are invalid, the CR will be invalidated upon executing `ace.setst K{t0}, #ace_CR_provision_end/ace_CR_import_end`, and so the following `ace.getst` will catch this situation.

NOTE: Implementations may interleave decryption and authentication with the load operation.
If an import is interrupted and the partial state exported (assuming we allow that),
the exported data must be the original encrypted data loaded so far, and not a re-encryption
of a partially decrypted payload.  This is required for both correctness and security.

*Export Code*
----
  ace.size   t2, K{t0}                # get size of the data to export
  {...}  # here goes the code that allocates the buffer to store the exported data

  ace.getmd  t1, K{t0}

  # If _ConfigStatus_ is _CfgStcomplete_, the following ace.setst prepares the
  # serialized, encrypted and authenticated internal representation of the CR for
  # export, computes the SIV(s), then changes _ConfigStatus_ to _CfgStExporting_.
  # Otherwise, it does nothing.

  ace.setst  K{t0}, #ace_CR_export_start
  sd  0(t6), t1                       # Export original _ConfigStatus_ to memory

  # The next instruction stores all data starting with the 8th byte of the MDH.
  # In case of interrupt/exception, the handler will decide whether to keep `acestart`
  # or clear it to force restart.
  # The instruction gets the length of the blob to export from the MDH
  # no special handling from the SW is necessary.

  ace.store  8(t6), K{t0}

success:
  # Reset MDH[63:0] to the previously saved value. If the saved _ConfigStatus_ is
  # _CfgStcomplete_, the operation also re-decrypts the state and makes the CR available
  # to software, otherwise it does nothing and leaves the CR state in the serialized and
  # encrypted format.

  ace.setst  K{t0}, t1, #ace_CR_export_end
----

// NOTE: The three instructions are essentially the same as `ace.export`.
// This first splitting is useful if we want to consider splitting also the entire loading.
// NOTE: Maybe we can have multiple export operations open, but only one prov/init.

[NOTE]
====
If we close the operation prematurely, then we get an authentication error.
If we forget to close it, we also get errors because we cannot use the CR unless _ConfigStatus_ is _CfgStcomplete_
====

[NOTE]
====
Longer instruction sequences based on XLEN-wide writes from GPRs into a CR's state are also possible.
However, safely resuming such code after preemption may be more cumbersome.
This is feasible and minimally impacts code size, since provisioning, import, and export routines can be placed in a shared library, with indirect CR addressing allowing the target CR to be passed as a parameter.
Storing some state information in the caller's context also reduces the need for dedicated CSRs.
====

// ////////////////////////////////////////////////////////////////////

[[ACE-external-formats]]
=== External Cryptographic Context Formats

ACE defines two external CC formats:

. The _Provisioning Input_ (PI), loaded into a CR to create a CC; and
. The _Sealed Cryptographic Context_ (SCC), an encrypted and authenticated representation of a CC used when exporting a CR to memory for later import.

{empty}
(((Cryptographic Context,Metadata)))
(((Cryptographic Context,Metadata,Header)))
Both formats begin with the 128-bit MDH described in <<ACE-Metadata>>.

// ////////////////////////////////////////////////////////////////////

[[ACE-data-formats]]
==== Formats of Provisioning Input and Sealed Cryptographic Context

The format of a Provisioning Input (PI) is shown in <<ACE-PI>>.

[[ACE-PI]]
.Format of the Provisioning Input (PI), all Sections in Order
[width="100%",cols="^8%,25%,42%,25%",options="header"]
|===
| Section | Section Name                      | Size     | Description
| 1       | `MDH`, MDH                        | 128 bits | See <<ACE-Metadata>>.
| 2       | `Content[]`, Provisioning Content | Depends only on the _Algorithm_, _AlgorithmPolicy_, and _KeyType_ fields of the MDH. | Contains keys and other algorithm-specific information.
|===

The length of a PI, and thus of `Content[]`, must be a multiple of 128 bits.

A CR can contain significantly more information than the Provisioning Content.
This additional information falls into three categories:

. Information necessary for the algorithm to function that cannot be reconstructed from other information—for example, random values generated in the _Initial_ state.

. Information that can be easily reconstructed from other state data. The *algorithm* may choose to omit this from an SCC.

. Data that optimizes performance on a specific *implementation* and is more expensive to recompute than to encrypt and save to external memory. The implementation may export such data in a custom format within an SCC for efficient reuse. A different receiving implementation may safely ignore this data during import after checking the `IMPQUAL` value. The originating implementation may silently restart a cryptographic operation if the additional data is corrupted.

The format of a Sealed Cryptographic Context (SCC) is shown in <<ACE-SCC>>.

[[ACE-SCC]]
.Plaintext of the Sealed Cryptographic Context (SCC) Format, all Sections in Order
[width="100%",cols="^8%,25%,32%,35%",options="header"]
|===
| Section | Section Name                            | Size                 | Description
| 1       | `MDH`, MDH                   | 128 bits             | See <<ACE-Metadata>>.
| 2       | `SIV`                                   | 128 bits             | Authentication tag for section 4.
//
| 3
| `Content1`: _Algorithm Data Section_
| If the CR is not in an Error State, the length of the SCC depends only on the _Algorithm_, _AlgorithmPolicy_, _KeyType_ and _StateExtension_ fields of the MDH.
| Contains keys and other algorithm-specific information. Encrypted in memory and during partial import.
 The data in this section is necessary for the correct functioning of the algorithm.
//
| 4       | `IMPQUAL`, Implementation Qualifier     | 128 bits, if present | Used to identify the implementation of the ACE Unit
| 5       | `SIV2`                                  | 128 bits, if present | Authentication tag for sections 4 and 6.
| 6
| `Content2`: _Implementation (Specific) Variable-Length Data Section_ (Implementation VDS)
| Implementation-Specific
| The data in this section is _not_ necessary for the correct functioning of the algorithm.
  Encrypted in memory and during partial import.
|===

The length of each section must be a multiple of 128 bits.

If the context is exported while in an Error State, Sections 3–6 are empty; that is, the SCC consists only of a plaintext MDH and of `SIV`.

The MDH's _ImpDataLen_ field specifies the total size of the Variable-Length Section (`SIV2`, `IMPQUAL`, and `Content2[]`).

// ////////////////////////////////////////////////////////////////////

[[ACE-rules-threshold-implementations]]
==== Single-Share Key Export Rule for Threshold implementations

Any CC with its algorithm implemented as a threshold implementation will always
provision, import and export _all_ its keys and secrets as reconstructed values.
(((ACE, algorithm, threshold variants)))
The PI and SCC Formats will be the same for non-threshold and threshold implementation
variants of the same algorithm, with the only difference being the value of the
_SCProtection_ in the MDH.

NOTE: These rules assume that reconstructing or re-randomizing a key is an inexpensive operation—for example, XORing with values generated by a PRNG internal to the ACE unit. This approach keeps SCCs compact and guarantees interoperability across architectures that implement side-channel protection differently.

To accelerate key share reconstruction in a threshold variant of an algorithm,
some shares of a system key can be included in the content's Additional Data.

For the purposes of the architectural specification, all values are represented as a single share. Side-channel analysis (SCA) protected algorithms are defined as implementation variants of the same unprotected algorithm and are not specified separately. The only difference between a protected and an unprotected algorithm is the value of the _SCProtection_ field in the MDH.

// ////////////////////////////////////////////////////////////////////

[[ACE-system-keys]]
==== System Keys and Randomly Generated Key Values

In a PI or SCC, System Keys are encoded as a 64-bit SKID used to retrieve the key from the a system-specific SKS.
This replaces the key value itself with an usually smaller field, and may reduce the size of the PI or SCC.

For threshold implementations of system keys, ACE may copy key material from the SKS into the CR and expand it into multiple shares.
The key must still be exported as a SKID.
Rule 3 of <<ACE-rules-threshold-implementations>> can be applied to system keys as well, as long as the system key's value cannot be recovered from the included shares.

// //////////////////////////////////////////////////////////////////

[[ACE-CR-representation]]
==== Notation and Representation of CR Internals

The information contained in a CR comprises at least as many bits as the SCC (see <<ACE-SCC>>), excluding `SIV`, `IMPQUAL`, and `SIV2`.
Additional storage may be required for information reconstructed upon successful import.

The _i_-th CR is denoted by ``K(i)``.
When ``K(i)`` is being provisioned, resp., imported, it behaves like a contiguous structure,
whose length equals that of the PI, resp., the SCC plus an additional 128 bits for the `SIV`, or 384 bits if also `IMPQUAL` and `SIV2` are required.

The additional capacity of 128 or 384 bits is per hart, not per CR,
since allocating an additional 128 bits per CR (or 384 bits if at least one algorithm supports implementation-specific data) would be costly.
The implementation must transparently manage this capacity as though it belongs to the CR.
In principle, this limits the ability to perform concurrent management operations within the same piece of code:
If a second operation is started that may overwrite the storage for `SIV`, `IMPQUAL`, and `SIV2`, the old values of `SIV` and `SIV2` may be irreversibly overwritten.
However, this does not affect any conceivable use case.

The format of this structure follows <<ACE-PI>> for provisioning and <<ACE-SCC>> for export and import.
// For provisioning, the structure consists of
// ``K(i)``.`MDH`[63:0],
// ``K(i)``.`MDH`[127:64] and
// ``K(i)``.`Content[]`, in this order.
// For import, the structure consists of
// ``K(i)``.`MDH`[63:0],
// ``K(i)``.`MDH`[127:64],
// ``K(i)``.``MDH``,
// ``K(i)``.``SIV``, and
// ``K(i)``.``Content1[]``, followed by
// ``K(i)``.``IMPQUAL``,
// ``K(i)``.``SIV2``,
// and
// ``K(i)``.``Content2[]``
// if the _ImpDataLen_ is non-zero.

// ////////////////////////////////////////////////////////////////////

[[ACE-export-import-algorithms]]
=== Management of Sealed Cryptographic Contexts

We now present the cryptographic algorithms used to generate and read SCCs.
This completes the description of the semantics of the management operations given in <<ACE-management-operations>>,
in the description of `ace.setst`
(<<ACE-instruction-setst>>), and in the code detailing the operations as split by the architecture (<<ACE-management-code-snippets>>).
See also `ace.load` (<<ACE-instruction-load>>), `ace.store` (<<ACE-instruction-store>>), and `ace.getmdl` (<<ACE-instruction-getmd>>).

// ////////////////////////////////////////////////////////////////////

[[ACE-SCC-AEAD]]
==== AES-GCM-SIV Key Derivation and POLYVAL

AES-GCM-SIV cite:[DBLP-journals-iacr-GueronLL17,RFC8452] is used to export and
import CRs.

// NOTE: AES-GCM-SIV has been chosen because it only required single passes of data in
// main memory, reducing the number of external memory accesses. GCM uses also a
// single pass but requires separate nonce and tag values, increasing the size of
// the exported data by one block.

We define the Key Derivation (<<ACE-SCC-RFC8452-derivation>>) and POLYVAL
(<<ACE-SCC-POLYVAL>>) functions first. The generation of an SCC from a CR
(<<ACE-SCC-export>>) and the import of an SCC into a CR (<<ACE-SCC-import>>)
are defined next. Then, we define AES-GCM-SIV encryption and decryption.

[[ACE-SCC-RFC8452-derivation]]
.RFC8452 Key Derivation
[]
----
function RFC8452_KeyDeriv(key : bits(256))
    → struct{enc_key : bits(256), auth_key : bits(128)} =
{
  return struct {
    AESE256(key, (zeros(125) @ 0b101))[63:0] @ AESE256(key, (zeros(125) @ 0b100))[63:0] @
    AESE256(key, (zeros(125) @ 0b011))[63:0] @ AESE256(key, (zeros(125) @ 0b010))[63:0],
    AESE256(key, (zeros(125) @ 0b001))[63:0] @ AESE256(key, (zeros(125) @ 0b000))[63:0]
  }
}
----

NOTE: Due to the computational cost of the derivation functions,
implementations may cache recently used derived keys.

The SIV (“Synthetic IV”), which also serves as the authentication tag in GCM-SIV,
is computed by encrypting the `POLYVAL` hash of the concatenation of the Locality Secrets, the MDH, and the Content of the CR.
In the `POLYVAL` pseudocode below, the digested data is represented as an array of 128-bit blocks.

[[ACE-SCC-POLYVAL]]
.Polyval Hashing Function
[]
----
function POLYVAL(auth_key : bits(128), blocks[0..n-1] : bits(128), n : int)
    → bits(128) =
{
  local tmp : bits(128) ← zeros(128);
  local i : int;
  foreach(i from 0 to n-1) {
    tmp ← tmp xor blocks[i];
    tmp ← Montmul(tmp, auth_key);
  }
  return tmp;
}
----

We now give the notation used for the inputs and outputs of the AES-GCM-SIV encryption and decryption functions,
i.e. <<ACE-SCC-GCM-SIV-enc>> and <<ACE-SCC-GCM-SIV-dec>>:

* `AD[]` denotes the Associated Data as an array of `len_AD` 128-bit blocks;
* `P[]`, resp., `C[]`, denotes a Plaintext, resp., a Ciphertext, as arrays of `len_PC` 128-bit blocks;
* `K` is a 256-bit Key;
* `N` is a 96-bit Nonce; and
* `SIV` is a 128-bit SIV/tag.

[[ACE-SCC-GCM-SIV-enc]]
.AES-GCM-SIV Encryption for SCC Generation
[]
----
function AES_GCM_SIV_Encrypt(AD[] : array of bits(128), N : bits(96),
    P[] : array of bits(128), K : bits(256), len_AD : int, len_PC : int)
  → {SIV : bits(128), C[] : array of bits(128)} =
{
  enc_key, auth_key ← RFC8452_KeyDeriv(K);
  SIV ← POLYVAL(auth_key, AD @ P, len_AD + len_PC);
  SIV[95:0] <- SIV[95:0] xor N[95:0];
  SIV ← AESE(enc_key, 0 @ SIV[126:0]);

  foreach(i from 0 to len_PC - 1)
    C[i] ← P[i] xor AESE(enc_key, 1 @ SIV[126:32] @ (SIV[31:0]+bin(i,32) % 2**32));

  return { SIV, C[] };
}
----

[[ACE-SCC-GCM-SIV-dec]]
.AES-GCM-SIV Decryption for SCC Import
[]
----
function AES_GCM_SIV_Decrypt(AD[] : array of bits(128), N : bits(96), SIV : bits(128),
    C[] : array of bits(128), K : bits(256), len_AD : int, len_PC : int)
  → {correct : bool, P[] : array of bits(128)} =
{
  enc_key, auth_key ← RFC8452_KeyDeriv(K);

  foreach(i from 0 to len_PC - 1)
    P[i] ← C[i] xor AESE(enc_key, 1 @ SIV[126:32] @ (SIV[31:0]+bin(i,32) % 2**32);

  SIV ← POLYVAL(auth_key, AD @ P, len_AD + len_PC);
  tmp[95:0] ← tmp[95:0] xor N[95:0];
  tmp ← AESE(enc_key, 0 @ SIV[126:0]);

  if (tmp != SIV) {
    foreach(i from 0 to len_PC - 1)
      P[i] ← zeros(128);
    return { false, P[i] };
  }

  return { true, P[] };
}
----

[[ACE-SCC-export]]
==== Generation of an SCC from a Fully Configured CR

If the _ConfigStatus_ field is set to _CfgStComplete_, then ``K(i)`` is fully provisioned,
and opening the CR for export (`ace.setst Kd|K{Xd}, #ace_CR_export_start`) performs the following steps
to create the serialized, encrypted and authenticated SCC from the CR.

.Exporting a Fully Configured CR ``K(i)``
[example]
--
. First, the algorithm-dependent data is processed:
.. ``AD[0]`` <- ``K(i)``.``MDH``, ``len_AD`` <- 1
.. foreach(_j_ from 0 to 10) :
... If `MDH`.Locality includes Locality #j, then ``AD[len_AD]`` <-  ``LST[``_j_``]``, ``len_AD`` <- ``len_AD`` + 1
.. If _Nonce_ (Locality #11) is included, then `N` <- `LST[11]`, else `N` <- `zeros(96)`
.. `len_PC` <- lengths of Sections 3.a and 3.b combined.
.. `SIV`, `C[]` <- ``AES_GCM_SIV_Encrypt(AD, N, K``__i__.``Content1[], CSK, len_AD, len_PC)``
. Second, if _VarDataLen_ {ne} 0, the implementation-dependent data is processed:
.. `len_AD` <- 2, ``AD[0]`` <- ``K(i)``.``IMPQUAL``, ``AD[0]`` <- `SIV`.
.. `len_PC` <- length of Section 6.
.. `SIV2`, `C2[]` <- ``AES_GCM_SIV_Encrypt(AD, N, K``__i__.``Content2[], CSK, len_AD, len_PC)``
. Finally, output `MDH`, `SIV`, `Content1[]`, and, if VarDataLen {ne} 0, `IMPQUAL`, `SIV2`, and `Content2[]`.
--

// ////////////////////////////////////////////////////////////////////

[[ACE-SCC-import]]
==== Decryption and Authentication of a complete SCC into a CR

When the import of the SCC of a fully configured CR is completed,
`ace.setst  Kd|K{Xd}, #ace_CR_import_end` decrypts and authenticates the SCC by the following algorithm.

.Importing a Fully Configured CR ``K(i)``
[example]
--
 . Clear ``K(i)``.
 . Load `M`, the MDH, from the SCC, into ``K(i)``.``MDH``.
 . Check correctness of `M`, and whether the Algorithm is supported.
 . Determine the length of the entire SCC.
 . If the length exceeds the implementation's maximum for the given Algorithm, the SCC contains an Implementation VDS that the importing implementation does not support. The SCC length is therefore adjusted by excluding the Implementation VDS.
 . Load the rest of the SCC, up to the determined length.
 . ``AD[0]`` <- ``K(i)``.``MDH``, ``len_AD`` <- 1
 . foreach(_j_ from 0 to 10) :
 .. If `MDH`.Locality includes Locality #j, then ``AD[len_AD]`` <-  ``LST[``__j__``]``, ``len_AD`` <- ``len_AD`` + 1
 . If _Nonce_ (Locality #11) is included, then `N` <- `LST[11]`, else `N` <- `zeros(96)`
 . `len_PC` <- lengths of Section 3.
 . `SIV`, `C[]` <- ``AES_GCM_SIV_Decrypt(AD, N, K``__i__.``Content1[], CSK, len_AD, len_PC)``.
 . Second, if _VarDataLen_ {ne} 0, the Implementation-dependent data is processed:
.. `len_AD` <- 2, ``AD[0]`` <- ``K(i)``.``IMPQUAL``, ``AD[1]`` <- `SIV`.
.. `len_PC` <- length of Section 6.
.. `SIV2`, `C2[]` <- ``AES_GCM_SIV_Encrypt(AD, N, K``__i__.``Content2[], CSK,§ len_AD, len_PC)``
 . Finally, output `MDH`, `SIV`, `Content1[]`, and, if VarDataLen {ne} 0, `IMPQUAL`, `SIV2`, and `Content2[]`.
--

// ////////////////////////////////////////////////////////////////////

[[ACE-import-and-DIEL]]
==== Import and Data-Independent Execution Latency

_This section is informative and non-normative._

In ACE, Data-Independent Execution Latency (DIEL) applies only to the cryptographic operations it performs, including the decryption and authentication of SCC contents.

Loading an SCC into a CR and decrypting-and-authenticating it are performed by separate instructions: `ace.load` is followed by an `ace.setst` instruction that performs no memory accesses. This second instruction is either continued while the requesting hart is preempted or interrupted, or aborted and then resumed. As a result, its timing is unaffected by the data being verified.

There is one dependency, however: an IMPQUAL mismatch. If an SCC contains both architecture-dependent and implementation-dependent parts, whether the latter can be imported on the target machine determines how many AEAD operations are performed, namely, one or two:

. When the import process is opened, ACE checks the total SCC length. If that length exceeds what is supported on the target machine for the given algorithm, the implementation-dependent part is necessarily unsupported: The SCC length to load and process is adjusted to include only the architecture-dependent part, `ace.load` does not load the implementation-dependent part, and only the architecture-dependent part is decrypted (if the resulting _ConfigStatus_ is _CfgStComplete_).

. When the import process is ended, the implementation qualifier is compared. If there is a mismatch, the implementation-dependent part is discarded, the CR length is adjusted, and only the architecture-dependent part is processed (if the resulting _ConfigStatus_ is _CfgStComplete_).

This only allows an attacker to distinguish, in certain cases, between the import of an SCC from a migrated VM and that of a native one. Beyond revealing information that is normally easily obtainable (if not a precondition for other attack types), this is unavoidable and not mitigated by splitting the decryption and authentication of the architecture-dependent and implementation-dependent parts into separate instructions.

// ////////////////////////////////////////////////////////////////////
