[[Assumptions]]
== Assumptions, Definitions, and Goals

=== Assumptions and Definition of the Environment

==== Privilege Levels and Security States

// We assume a generic architecture that implements a hierarchy of Privilege Levels (PL) and, optionally, separate, coexisting Worlds (an example is provided by the Secure and Non-Secure Security States in the ARM Architecture). Its properties are:
// [arabic]
// . There are several PLs, such as: *User*, *OS/VM*, *Supervisor*, and *Machine Mode.*
// . These PLs are abbreviated as UL (as in User Land), OS, SV, and MM.
// . Different architectures may support a different number of levels.
// . There are at least two levels, one of which is MM.
// . MM is always the highest privilege level.
// . There is always one and only one instance of the MM and corresponding Software/Firmware stack.
// . A *world* is a hierarchy of PLs different from MM. Inside a world, a SW hierarchy exists, which may vary in complexity from of a single process to a full stack including a Hypervisor, multiple operating systems managed by the latter, and multiple user processes running under the operating systems.
// . These SW entities correspond to the three PLs that can be implemented inside a World: SV, VM, and UL.
// . There is at least one World.
// . The separation between Worlds correspond to same protection commonly found in Trusted Execution Environments (TEE) or Supervisor Domains.
// . If a world contains more than one PL, the effectiveness of the separation of the PLs and the enforcement of their hierarchy typically depends on how the SL software stack is implemented, on the architectural access control features on memory, and hardware support.
// . Access Control based separation of the Worlds is assumed.
// . Cryptographic RAM protection (i.e., encryption or better) is not assumed.
// . In traditional environments, OL and SL directly manage page tables. However, in Confidential Computing Environments (CCE), the MM may ensure the CCE guarantees by verifying or managing these tables.
// The mapping of our terminology to the various solutions on the market is straightforward.

We assume a generic architecture that implements a hierarchy of Privilege Levels (PL) and, optionally, separate, coexisting Worlds.
There are at least two levels, one of which is MM (Machine).
The current PL (CURRENTPL) and World are discoverable.


==== Processing Elements and Subsystems

The system shall contain one or more processing elements (PE).

These processing elements may have different capabilities, and they may grouped into Subsystems (SS). All the PEs in a SS have the same capabilities: they share the same architecture, functionality, Privilege Levels (PLs), and World separation, varying only in performance and power usage. This allows any thread to run unchanged on any PE within that subsystem. For example, multiple CPU cores can form the Application Processor Subsystem (APSS).

Each PE runs either single-threaded or with Simultaneous Multithreading (SMT). A hardware thread ("hart") represents an independent execution context with its own architectural registers. When SMT is unavailable, a hart refers to a core; with SMT enabled, it refers to a hardware thread.

=== Assumptions, Goals, and Definitions

[[Goals-Regarding-Key-Types]]
==== Goals Regarding Key Types

Support must be provided for opaque keys of three different types:

[arabic]
. *Software Keys*, where its key value is explicitly set by SW. The key may be set by an agent running in a SW environment for use in a different one.
. *Immutable* *System Keys (ISKs)*, i.e. keys which are provided to a SS by the system outside the SS that implements the feature, for instance by a key management engine. There is one table of ISKs per SS. The values of these keys are often not available to any SW environment and must not leak. Such keys are immutable during a boot session and are provided to a SS as a single table only once per boot.
. *System Derived Keys.* These keys resemble system keys in that they are provided by the system. But the similarities end here. They are dynamically generated or derived and can be provided upon request at any time. They are also provided to a SW environment, not to the entire SS.

We have already mentioned that policies are associated with opaque keys to allow their use only with specific cryptographic algorithms. In the case of System or System derived keys, these policies are mandated by the system and cannot be altered by SW.

Opaque keys must support at least five different types of lifecycles:

[arabic]
. _Keys that survive_
[loweralpha]
.. Reboot and process migration to a different machine.
.. Hibernation of a VM to be resumed later, also after a boot of the device.
.. Reboot, but cannot be migrated with a process or a VM.
. _Keys that are tied to the device_, thus are allowed to survive reboot but not process migration. There are two subtypes of lifecycles for such keys:
[loweralpha]
.. Some of these keys are immutable and usually anchored in HW, whereas.
.. Other keys are dynamically generated by some SW or HW environment.
. _Keys that must be regenerated upon boot_, hence are not allowed to survive rebooting the device and cannot be transported by process migration. These can be generated by SW components or provided by HW IP blocks.

Furthermore,

[arabic, start=4]
. It must be possible to separate the keys of different processes and VMs — in other words, if a SCC from a VM is copied into the memory of a different VM, the latter should be from importing it into a CHR if so desired.
. The type and level of side channel hardening shall be discoverable.

==== Debugging non-goal

ACE does not provide ad-hoc debugging support. If HW debug is enabled, it must be accessible to both Key-Generating Software and Hardware components. This lets them provide alternate keys to debugged software environments if normal keys aren’t available. So, we do not think ACE needs debugging-specific features. However, sensitive SW components must be able to detect whether they are running under a debug configuration.

==== Storage of the keys

As mentioned in the introduction, there are architectural registers, the CHRs, where the keys are stored together with their policies.
We recall that "architectural" means that these registers are per hart, like the integer, floating point, and vector registers.
The CHRs are denoted by the letter `c` and an integer number from 0 to 31, and therefore are named `c0`, `c1`, ..., `c31`.
This also means that, like any other registers in the RV architecture, they are encoded in a 5-bit field.
The last CHR, namely `c31` is reserved for system use and is only accessible to Machine mode.

Now, any limited number of CHRs is not sufficient to cover all use cases, and in any case they would not be sufficient to provide keys to all processes.
Therefore, we have defined export and import operations that create and consume the SCCs.

The ISKs are stored in internal RAM, which is architecturally common to all PEs in a single SS.
This table can be copied to internal, non user accessible, RAM common to one or more CPUs or clusters.
Once provisioned, it is write locked and cannot be modified until the next boot.

System-derived keys are provided directly to SW entities and are not stored in the ISK table.
CnThey are provided as bit strings, and the SCC import instructions recognize this format and import them into CHRs.

==== Sealed Cryptographic Contexts, Import and Export

The internal state of a CHR can be _exported_ as a SCC.

A SCC can later be re-_imported_ into a CHR.

Export and import processes must comply with any policies associated with the keys and guarantee that they properly transferred from the CHRs to the SCCs and vice versa.

The distinctions between export/import and normal store/load operations are:

[arabic]
. *Encryption*: Exported data is encrypted, which means its contents are not in a directly useable form, and are different from the actual raw contents of a CHR.
. *Authentication*: An SCC includes an integrity tag, to ensure that the key and associated metadata have not been tampered with. This also means that an SCC is usually larger than the contents of a CHR.

The SW environment of a process domain receiving a SCC is responsible for protecting the latter according to its own security guarantees.

Export operations on a CHR that refer to an ISK will not include the key itself; instead, only its index into the internal ISK Table is exported as well together with all but one of its shares if the key is being used. As a result, a system key is never _actually_ exported, even if encrypted. This is essential to ensure that certain system keys remain confidential and are not exported in any form.

The (Deterministic) Authenticated Encryption used to generate SCCs is 256-bit AES-GCM-SIV as per RFC8452, with the SIV field reduced by 8 bits in order to encode information about key type (cf. <<Goals-Regarding-Key-Types>>) and key lifecycle (cf. <<Key-Management>>). Upon generation of the SIV as per RFC8452, the least significant 8 bits will be replaced by this information and the resulting value used as the actual SIV.

==== Context Transport Keys

*The MM exclusively controls the Context Transport Key (CTK), which is used for wrapping/unwrapping CHR contents to/from SCCs.*

The CTK resides in `c31`, a special 256-bit MM-only read/write register.
While encoded as the 31^rst^ CHR for instruction compatibility, `c31` differs from the other CHRs:
it has fixed usage policies, no metadata storage, and the export/import operations do not apply to it.

*The MM can reconfigure the CTK at any time, enabling various configurations of the system as a whole:*
* System-wide configuration at boot.
* Different keys for each Security State.
* Custom keys for individual VMs or VM groups (upon secure Hypervisor request).

*Remark:* _Clearly the MM may be able to generate SCCs without going through the CHRs, but we discourage MM stack implementers from implementing this._

If support for different CTKs for distinct process spaces or support for migration is implemented by the MM stack (the latter feature requiring the former), then any system software will have to invoke the MM to manage the CTK.

*VM migration is enabled through the reconfigurability of the CTK.*

If the MM stack keeps track of per-VM CTKs on behalf of the Hypervisor, then VM migration and maintains key isolation between different security domains and VMs can be implemented and enforced.

When a VM is migrated, a public key-based Key Encapsulation Mechanism (KEM) can be employed to guarantee that the MM of the target machine can use the same CTK for the migrated machine as the one used on the original device. This method shall use either the target's identity or that of a trusted intermediary, such as a Hardware Security Module (HSM), to transfer the VM's CTK.

This document does not cover the protocols for transferring a CTK to a target machine during VM migration. These shall be defined by the cloud VM provider as part of their own SW and FW stacks. From the point of view of the underlying cryptography, we recommend using a non-interactive hybrid post-quantum KEM for this purpose. A suitable method is X-Wing (see https://datatracker.ietf.org/doc/draft-connolly-cfrg-xwing-kem[X-Wing: general-purpose hybrid post-quantum KEM]).

[[Key-Management]]
==== Key Management and Provisioning Applications

Software environments that implement key management operations for other domains require their own CTK. A system may contain multiple such software environments.

A Key Management Applet (KMA) will

[arabic]
. Generate or retrieve a key matching a request.
. Configure a CHR with this key and its associated metadata.
. Export this CHR to a SCC in memory.
. Relinquish control to the MM.

The MM, which controls the CTK, can the

[arabic, start=5]
. Set the CTK to the KMA’s CTK.
. Re-import the SCC into a CHR
. Change the CTK to match the requester domain's CTK.
. Export the key for the Requester's use.
. Relinquish control to the Requester.

This is the most generic approach and allows each piece of software to use a CHR of choice to generate and import SCCs.
Furthermore, it protects the key from other SW environments that may be crossed while transferring control between the Requester process, the MM, and the Key Management application.

Various optimizations are possible, which can be interesting for embedded environments: Steps 3., 5., and 6. can be omitted if the CHR used for these operations is fixed and the overall SW/FW stack is simple enough.
Similarly, Step 8. can be omitted.
These are choices of the ABI architect of a specific SW/FW stack.

[[Context-Binding]]
==== Binding of Contexts to Lifecycles and Domains, Derived CTKs

[CAUTION]
====
We need to define the Domain as a concatenation of domain strings for each of the levels.
For instance, if we are not using the Hypervisor extension, then we have strings for User and Supervisor modes.
If we are using the Hypervisor extension, then we have strings for Virtual User, Virtual Supervisor, and Supervisor (Hypervisor) modes.
Let us call these values the Domain Unique Values.
They are set by the local software environment, they are 32 (or 64? 128?) bit values, and are set by the immediately superior environment.
They are not required to be secret, so they are just set by programming a register (*is this ok?*)

So, we have DUV_U, DUV_S, set by S and M, without the Hypervisor extension, and
DUV_VU, DUV_VS, DUV_VS, set by VS, S, and M, if the the Hypervisor extension is set.
They are meant to be an alternative to reprogramming the CTK for each SW environment in order to make switching domains faster.
Reprogramming the CTK is still useful for VM migration or to more strongly isolate Worlds.

If there DUV_xx values are not set by the system, they have a default value of zero.
If the hardware does not support them, then they are not writeable and they are always read as zero, but are otherwise unused.
If the hardware supports them, then there must be a register to lock them, so that they they become WARZ even to the hardware.
====

As noted in <<Goals-Regarding-Key-Types>>, different keys may require distinct lifecycles based on specific requirements (e.g., DRM-protected content limited to certain devices).
The same mechanism is used to bind keys to specific domains.

The system manages these lifecycles through:
* Lifecycle and Domain information stored in CHR metadata
* Lifecycle/Domain Specific Context Transport Keys (LSCTKs) for key export/import

LSCTKs are derived by combining the original CTK with a Lifecycle Type Secret (LTS) and a Domain Secret (DOS)
that matches the desired Lifecycle/Domain encoded in the CHR metadata.

When an LTS expires and therefore it is erased, or is changed, all associated LSCTK-exported SCCs become invalid because they can not be reimported. However, any value in a CHR remains usable and can be exported under a new key associated with the LTS. This is not a concern since LTSs are not expected to be dynamically invalidated or changed during SW execution, but only between boot sessions.

This CTK dependency also enables lifecycles within migration: if a VM is migrated together with its CTK, keys only relying on the CTK will be able to be imported from memory on the target device. However, if they need to use a lifecycle restricted key, this will only be possible if the LTS is the same.

This allows a VM to continue functioning on the target device with restricted functionality, instead of preventing its use completely. This enables use cases where DRM protocols detect invalid keys and request credentials according to the content owner’s policies.

The same mechanism is used also to bind keys to SoC types, device types, manufacturers, etc.

A few types of LTSs are defined (nomenclature is our own)

* Boot Unique Secret: regenerated at each boot.
* Device Unique Secret. Permanent device identifier, shareable across multiple SoCs for instance by being stored in separate secure chip on the motherboard, or by allowing one SoC as being the master providing the value to other chips. Such mechanism is not architected.
* SiP Unique Secret: Identifies the manufacturer of the SoC.
* Chip Model Unique Secret: Identifies specific chip model/family.
* Device Type Unique Secret: Identifies device type/model. May be provisioned and accessed like the Device Unique Secret.
* OEM Secret. Provisioned by OEM to differentiate their products from the competition.

These keys are stored in the Lifecycle Secret Table (LST), a subset of the ISK Table, with policies that make them visible only to hardware and never to software. They are provisioned at boot as part of the ISK Table and can be addressed as LTST++[++index++]++.

A Lifecycle Type is configured through metadata by having a field with the same index. This field determines how a key is exported and reimported.

* If the lifecycle is not restricted, then the CTK in `c31` is used directly.
* Otherwise, a LSCTK will be computed using a special function (TBD) +
`Derived_CTK = Uniquify(CTK,LTST[index])`, +
`Derived_CTK = Uniquify(CTK,LTST[index] || DUV_S })`, +
`Derived_CTK = Uniquify(CTK,LTST[index] || DUV_S || DUV_U })`, +
`Derived_CTK = Uniquify(CTK,LTST[index] || DUV_S || DUV_VS)`, or +
`Derived_CTK = Uniquify(CTK,LTST[index] || DUV_S || DUV_VS || DUV_VU})` +
and the `Derived_CTK` is value used to encrypt and authenticate the SCC.

[CAUTION]
====
This function must be as fast as possible. We cannot use a cryptographic hash or too many chained AES invocations.
However, a CMAC-like construction can be used, where the derivation using the LTS, as well as the current value at each higher PL can be cached,
so each change at one level only requires one extra encryption.
The key (which is `c31`) can be slightly masked at each level to make extension attacks impossible, for instance
by XORing its least significant byte with fixed values associated to the S, U, VS, VU PLs (use four different values).
====

[CAUTION]
====
Do we actually need to use a derived key thought? And how to allow, say, an OS running in S mode to properly export and import keys for a process?
====

[[Support-dynamically-generated-system-keys]]
==== Support for dynamically generated system keys

Systems can dynamically generate keys for various purposes. If generated by SW, the key is placed in a CHR and exported. However, HW can also generate keys, especially in complex SoCs with third-party or legacy components that may not produce a format that is compatible with ACE’s SCC formats.

As an example, we consider here an architecture where these keys are delivered using a system defined mechanism. The latter may vary, and it does not necessarily offer the same flexibility as the methods architected in this document, therefore we cannot assume that the system defined mechanism can be used in its place.

At this point, there are two options:
[arabic]
. SoC designers modify the key-providing component to output ACE’s SCC format.
. ACE supports the foreign format by passing a bit-field to the import instruction.

Support for the latter case is provided by a bit-field passed to the import instruction.

After import from the foreign format, the CHR contents can be exported and re-imported exclusively in ACE’s SCC format. If the key is unique or uniquely provided per device or boot, this must be reflected in the metadata, and ACE must enforce this policy.

Other mechanisms, like a pure HW interface, raise significant synchronicity issues and are discouraged for non-constrained embedded environments unless blocking operations are acceptable.
