"""SHA-2 family as instantiated by <<ACE-SHA-2>>.

REF is Python's hashlib. ACE implements the section's model literally: the message is an
octet string absorbed in b-bit blocks under the ACE value model; the j-th message word of
a block is int(bswap(block[(j+1)w-1 : jw])); the digest is emitted with the i-th chaining
variable at octet offset i*w/8 as bswap(bin(H_i, w)), truncated to t bits overall.
Initial hash values follow FIPS 180-4 5.3, with the SHA-512/224 and SHA-512/256 IVs
generated by the 5.3.6 procedure; round constants are computed from the fractional parts
of the cube roots of the first primes. Padding is applied caller-side, per the section.

A negative control absorbs the words without the bswap (little-endian) and must fail.
"""
import os, sys, hashlib
d = os.path.dirname(os.path.abspath(__file__)); sys.path.insert(0, d)
exec(open(os.path.join(d, 'ocb-kat.py')).read()
     .split('# ------------------------------------------------------------------ vectors')[0])

from decimal import Decimal, getcontext
getcontext().prec = 90

def primes(k):
    ps, n = [], 2
    while len(ps) < k:
        if all(n % p for p in ps): ps.append(n)
        n += 1
    return ps

def frac_root(p, e, w):                 # first w bits of the fractional part of p^(1/e)
    r = Decimal(p) ** (Decimal(1) / Decimal(e))
    return int((r - int(r)) * (1 << w))

PR80 = primes(80)
K256 = [frac_root(p, 3, 32) for p in PR80[:64]]
K512 = [frac_root(p, 3, 64) for p in PR80]
H256 = [frac_root(p, 2, 32) for p in PR80[:8]]
H224 = [frac_root(p, 2, 64) & 0xffffffff for p in PR80[8:16]]   # second 32 bits (5.3.2)
H512 = [frac_root(p, 2, 64) for p in PR80[:8]]
H384 = [frac_root(p, 2, 64) for p in PR80[8:16]]                # first 64 bits (5.3.4)

def rotr(x, r, w): return ((x >> r) | (x << (w - r))) & ((1 << w) - 1)

def compress(H, W0, w, K, rounds):      # FIPS 180-4 6.2/6.4, both word sizes
    if w == 32: s0, s1, S0, S1 = (7,18,3), (17,19,10), (2,13,22), (6,11,25)
    else:       s0, s1, S0, S1 = (1,8,7),  (19,61,6),  (28,34,39), (14,18,41)
    M = (1 << w) - 1
    W = list(W0)
    for t in range(16, rounds):
        x, y = W[t-15], W[t-2]
        W.append((W[t-16] + (rotr(x,s0[0],w) ^ rotr(x,s0[1],w) ^ (x >> s0[2]))
                  + W[t-7] + (rotr(y,s1[0],w) ^ rotr(y,s1[1],w) ^ (y >> s1[2]))) & M)
    a,b,c,dd,e,f,g,h = H
    for t in range(rounds):
        T1 = (h + (rotr(e,S1[0],w) ^ rotr(e,S1[1],w) ^ rotr(e,S1[2],w))
              + ((e & f) ^ (~e & g)) + K[t] + W[t]) & M
        T2 = ((rotr(a,S0[0],w) ^ rotr(a,S0[1],w) ^ rotr(a,S0[2],w))
              + ((a & b) ^ (a & c) ^ (b & c))) & M
        a,b,c,dd,e,f,g,h = (T1+T2) & M, a, b, c, (dd+T1) & M, e, f, g
    return [(x + y) & M for x, y in zip(H, [a,b,c,dd,e,f,g,h])]

def sha512_iv_gen(name):                # FIPS 180-4 5.3.6: SHA-512/t IV generation
    H = [h ^ 0xa5a5a5a5a5a5a5a5 for h in H512]
    msg = name.encode()
    m = msg + b'\x80' + bytes((-(len(msg) + 1 + 16)) % 128) + (len(msg)*8).to_bytes(16,'big')
    for i in range(0, len(m), 128):
        W = [int.from_bytes(m[i+8*j:i+8*j+8], 'big') for j in range(16)]
        H = compress(H, W, 64, K512, 80)
    return H

H512_224 = sha512_iv_gen("SHA-512/224")
H512_256 = sha512_iv_gen("SHA-512/256")

def ace_sha2(msg, w, H0, t_bits, be_words=True):
    """State machine of <<ACE-SHA-2>> in the ACE value model (padding caller-side)."""
    b = 512 if w == 32 else 1024
    K, rounds = (K256, 64) if w == 32 else (K512, 80)
    L = len(msg) * 8
    msg = msg + b'\x80' + bytes((-(len(msg) + 1 + 2*w//8)) % (b//8)) \
              + L.to_bytes(2*w//8, 'big')
    H = list(H0)
    for i in range(0, len(msg), b // 8):
        block_v = b2v(msg[i:i + b//8])
        W = [(bswap(sl(block_v, (j+1)*w - 1, j*w), w) if be_words
              else sl(block_v, (j+1)*w - 1, j*w)) for j in range(16)]
        H = compress(H, W, w, K, rounds)
    dig_v, pos = 0, 0                   # digest emission per the Endianness paragraph
    for hi in H:
        dig_v |= bswap(hi, w) << pos; pos += w
    return v2b(sl(dig_v, t_bits - 1, 0), t_bits // 8)

FN = {  # name: (w, H0, t, hashlib name)
    'SHA-224':     (32, H224,     224, 'sha224'),
    'SHA-256':     (32, H256,     256, 'sha256'),
    'SHA-384':     (64, H384,     384, 'sha384'),
    'SHA-512':     (64, H512,     512, 'sha512'),
    'SHA-512/224': (64, H512_224, 224, 'sha512_224'),
    'SHA-512/256': (64, H512_256, 256, 'sha512_256'),
}
# Fallback vectors if hashlib lacks the SHA-512/t names (FIPS 180-4 examples, "abc")
FIXED = {
    'SHA-512/224': {b'abc': '4634270f707b6a54daae7530460842e20e37ed265ceee9a43e8924aa'},
    'SHA-512/256': {b'abc': '53048e2681941ef99b2e29b76b4c7dabe4c2d0c634fc6d46e0e2f13107e7af23'},
}

msgs = [b'', b'abc', b'a'*55, b'a'*56, b'a'*63, b'a'*64, b'a'*111, b'a'*112,
        bytes(range(200)), b'x'*1000]
ok = True
print(f"{'function':13} {'vs REF':7} {'cases'}")
for name, (w, H0, t, hname) in FN.items():
    try:
        ref = lambda m, hn=hname: hashlib.new(hn, m).digest()
        cases = msgs
    except Exception:
        ref = None
    good, n = True, 0
    for m in msgs:
        a = ace_sha2(m, w, H0, t)
        try:
            r = hashlib.new(hname, m).digest()
        except Exception:
            r = bytes.fromhex(FIXED[name][m]) if (name in FIXED and m in FIXED[name]) else None
        if r is None: continue
        good &= a == r; n += 1
    ok &= good and n > 0
    print(f"{name:13} {'PASS' if good else 'FAIL':7} {n}")

neg = ace_sha2(b'abc', 32, H256, 256, be_words=False) != hashlib.sha256(b'abc').digest()
print(f"negative control (words absorbed without bswap) is caught: "
      f"{'PASS' if neg else 'FAIL'}")
ok &= neg
print(f"\nKAT-RESULT: {'PASS' if ok else 'FAIL'}")
